### ISSUE TITLE
Bump releases for Windows operations file in CI

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/cf-deployment#103]
We want to keep getting mileage out of the Windows operations file and it would really help if the releases it includes (garden-windows and the hwc buildpack) were bumped automatically in CI. This would enable all of the consumers of cf-deployment that use windows cells (diego, loggregator, infrastructure, potentially capi and others) to deploy our new BOSH releases.

These releases are on bosh.io here:
- garden-windows: http://bosh.io/releases/github.com/cloudfoundry-incubator/garden-windows-bosh-release?all=1
- hwc-buildpack: http://bosh.io/releases/github.com/cloudfoundry-incubator/hwc-buildpack-release?all=1

**Comment by dsabeti** [comment]
@sunjayBhatia. Yeah, feedback received. I've prioritized two stories here:
https://www.pivotaltracker.com/story/show/138166203
https://www.pivotaltracker.com/story/show/142637199

According to tracker, we'll get to these stories next week.

**Comment by sunjayBhatia** [comment]
@dsabeti sweet thanks! thats great news, ill close this out
