### ISSUE TITLE
Unable to resolve *.nats.service.cf.internal on a broker machine in different deployment

### ISSUE THREAD

**Issue by cagric0** [cloudfoundry/cf-deployment#1035]
### What is this issue about?

After updating the Ubuntu stemcell version to the Jammy on our setup, Our route_registrar couldn't resolve nats.service.cf.internal

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v20.3.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

bosh -d hz-mc deploy manifest.yaml

manifest.yaml:

```
name: hz-mc
releases:
  - name: hazelcast-boshrelease
    version: 5.2.1
  - name: routing
    version: 0.248.0
  - name:  bosh-dns-aliases
    version: 0.0.4
  - name: bpm  
    version: 1.1.19
stemcells:
  - alias: only-stemcell
    os: "ubuntu-jammy"
    version: "1.49"
instance_groups:
  - name: management-center
    instances: 1
    jobs:
      - name: management-center
        release: hazelcast-boshrelease
        properties:
          config_json:
            hazelcast:
              license-key:  <hazelcast-license-key>
            hazelcast-pcf:
              debug: true
              instanceCount: 1
              management-center:
                appName: mancenter
                enabled: true
      - name: route_registrar
        release: routing
        consumes:
          nats-tls:
            deployment: cf
            from: nats-tls
        properties:
          nats:
            machines:
              - nats.service.cf.internal
            password: nkhd2oa69oab0bgwnwzz
            port: 4224
            tls:
              enabled: true
              client_cert: |
                -----BEGIN CERTIFICATE-----
                <cert>
                -----END CERTIFICATE-----
              client_key: |
                -----BEGIN RSA PRIVATE KEY-----
                <key>
                -----END RSA PRIVATE KEY-----
            user: nats
          route_registrar:
            routes:
              - name: mancenter
                port: 8080
                tags: {}
                uris:
                  - mancenter.apps.demo.cf.hazelcast.com
                route_service_url: ""
                registration_interval: 20s
    vm_type: default
    stemcell: only-stemcell
    persistent_disk_type: 1GB
    azs:
      - z1
      - z2
    networks:
      - name: default
  - name: hazelcast
    instances: 1
    jobs:
      - name: hazelcast
        release: hazelcast-boshrelease
        properties:
          config_json:
            hazelcast:
              license-key: <hazelcast-license-key>
            hazelcast-pcf:
              debug: true
              instanceCount: 1
              management-center:
                appName: mancenter
                enabled: true
          network: default
    vm_type: default
    stemcell: only-stemcell
    persistent_disk_type: 1GB
    azs:
      - z1
      - z2
    networks:
      - name: default
update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-240000
  max_in_flight: 1
  serial: false

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-xenial
    - os: ubuntu-bionic
    - os: ubuntu-jammy
  jobs:
  - name: bpm
    release: bpm
- name: bosh-dns-aliases
  include:
    stemcell:
    - os: ubuntu-jammy  
  jobs:
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: nats.service.cf.internal
        targets:
        - query: '*'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
      - domain: _.nats.service.cf.internal
        targets:
        - query: '_'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
```

### Please provide output that helps describe the issue:

Output of the deploy command:
`                       L Error: 'management-center/651776a5-97b6-4482-b861-7bfb99131ac7 (0)' is not running after update. Review logs for failed jobs: route_registrar
`

Error log on the route_registrar:
`goroutine 1 [running]: code.cloudfoundry.org/lager.(*logger).Fatal(0xc0000ae360, {0x74c1e3, 0x12}, {0x7d5720?, 0xc000196140}, {0x0, 0x0, 0x0?}) /var/vcap/data/compile/route_registrar/src/code.cloudfoundry.org/vendor/code.cloudfoundry.org/lager/logger.go:162 +0x5dc
main.main()
/var/vcap/data/compile/route_registrar/src/code.cloudfoundry.org/route-registrar/main.go:138 +0x111a
panic: dial tcp: lookup nats.service.cf.internal on 10.0.0.2:53: no such host`

`{"timestamp":"2023-01-11T11:00:53.289166840Z","level":"error","source":"Route Registrar","message":"Route Registrar.nats-connection-failed","data":{"error":"dial tcp: lookup nats.service.cf.internal on 10.0.0.2:53: no such host","nats-hosts":["nats.service.cf.internal:4224"]}}
`

### What IaaS is this issue occurring on?

Amazon

### Is there anything else unique or special about your setup?

These setup was working properly with old stemcell versions. When we upgrade our stemcell to the Ubuntu Jammy we get this error.

### Tag your pair, your PM, and/or team!

**Comment by ctlong** [comment]
Hi @cagric0, can you please create a similar issue in https://github.com/cloudfoundry/routing-release so that the folks maintaining the project can help you resolve this.

You can also reach out to them in [#cf-for-vms-networking in CFF Slack](https://cloudfoundry.slack.com/archives/C01ABMVNE9E).
