### ISSUE TITLE
cflinuxfs4 Rollout - Step 1: Make cflinuxfs4 the default stack

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cf-deployment#1047]
### What is this issue about?

Details out https://github.com/cloudfoundry/cf-deployment/issues/989.

In step 1 of the rollout, we want to make cflinuxfs4 the default stack, but keep cflinuxfs3. Prerequisite is that all buildpacks are available for cflinuxfs4.

This would be a breaking change, so we would ship this as a major release.

Technically we would integrate these ops files into [cf-deployment.yml](https://github.com/cloudfoundry/cf-deployment/blob/main/cf-deployment.yml):
[operations/experimental/add-cflinuxfs4.yml](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/experimental/add-cflinuxfs4.yml)
[operations/experimental/set-cflinuxfs4-default-stack.yml](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/set-cflinuxfs4-default-stack.yml)

This ops file:
[operations/experimental/use-trusted-ca-cert-for-apps-cflinuxfs4.yml](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/experimental/use-trusted-ca-cert-for-apps-cflinuxfs4.yml)
would be integrated into:
[operations/use-trusted-ca-cert-for-apps.yml](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/use-trusted-ca-cert-for-apps.yml)

**Comment by ctlong** [comment]
In the WG meeting today we discussed also adding an ops file to make cflinuxfs3 the default once again. Could we add that to the to-do list as well?

**Comment by jochenehret** [comment]
Released in cf-deployment v28.0.0: https://github.com/cloudfoundry/cf-deployment/releases/tag/v28.0.0

Ops file to keep "cflinuxfs3" as default stack has been provided:
[operations/set-cflinuxfs3-default-stack.yml](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/set-cflinuxfs3-default-stack.yml)
