### ISSUE TITLE
Cloud foundry Api downtime

### ISSUE THREAD

**Issue by Manu2516789** [cloudfoundry/cf-deployment#1060]
Hi all,
Suddenly my cloud foundry login api is showing downtime for a min or 2 recently thrice in last 6 days
which all vms logs or process logs I have to check to find the root cause ?

Earlier one of the scheduler vms process had restarted when the downtime had occurred but today again the downtime occurred but no process got restarted.

Please let us know.

**Comment by ctlong** [comment]
Hi @Manu2516789!

I would check the logs for the `cloud_controller_ng` job in the `api` VM.

Additionally, the [troubleshooting docs](https://docs.cloudfoundry.org/running/troubleshooting.html) may provide some direction.

**Comment by ctlong** [comment]
I'm not sure that I follow your specific problem... In any case, unless you're able to provide logs/metrics indicating where the failure state occurs, or concrete reproduction steps, there's not much I can do to help you.

**Comment by ctlong** [comment]
I'm going to close this as stale. Pls feel free to reopen if new information comes up.
