### ISSUE TITLE
Multiple instances of mysql

### ISSUE THREAD

**Issue by yatzek** [cloudfoundry/cf-deployment#108]
Currently there is only one mysql instance, is it possible to have 3 instances replicated with galera?

**Comment by dsabeti** [comment]
Hey @yatzek. Yeah, I suspect that it's possible -- the nodes run Galera (for replication) and a MySQL proxy (for failover), so you could probably scale to 3 nodes. **We've never tested it, so give this a try in a test environment first.**

Long term, we'll probably get around to making sure that it works and testing it in our CI pipeline. It just wasn't the highest priority thing for us to get to.

**Comment by dsabeti** [comment]
Hey @yatzek. Did you ever give this a try? Any other questions? Otherwise, I'd like to close this issue. In the meantime, you can follow this [Pivotal Tracker story](https://www.pivotaltracker.com/story/show/135805021).

**Comment by yatzek** [comment]
Hi,

I did not have a chance to do it yet, I will close the issue.
