### ISSUE TITLE
Links in Readme to cloud foundry docs are wrong

### ISSUE THREAD

**Issue by valenbb** [cloudfoundry/cf-deployment#11]
Hyperlinks are incorrect for the following:

vSphere (not currently supported by this tool)
vCloud (not currently supported by this tool)
OpenStack (not currently supported by this tool)

Clicking on the link leads to:

Page not Found
Visit the homepage.

**Comment by Amit-PivotalLabs** [comment]
Thanks @valenbb 

FYI, work on this repo is on pause, but I've updated the links on the `develop` branch, this will eventually make it to `master`.
