### ISSUE TITLE
Remove erroneous cf CLI bosh release

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-deployment#1100]
The retracted [cf CLI bosh release](https://github.com/bosh-packages/cf-cli-release) v1.46.0 went through our pipelines successfully, updating develop and maybe release-candidate to use that version, and now it doesn't exist. CI is not happy.

**Comment by jochenehret** [comment]
The version has been automatically reverted to v1.45.0 on "develop":
https://github.com/cloudfoundry/cf-deployment/commit/7c565af11ea2b7f6436f4c331ea548efe52101c6
CI should pass. We should create a release soon with the fixed version.

**Comment by jochenehret** [comment]
Raised issue on cf-cli-release for an RCA: https://github.com/bosh-packages/cf-cli-release/issues/13

**Comment by jochenehret** [comment]
Released https://github.com/cloudfoundry/cf-deployment/releases/tag/v30.9.0 which reverts cf-cli-release to v1.45.0.

**Comment by ctlong** [comment]
Closing this issue since:
* CF-D release notes have been updated to note that some versions won't work
* New CF-D release is cut
* CI is green once again

Thanks Jochen!

Please refer to the https://github.com/cloudfoundry/bosh-package-cf-cli-release/issues/13 for the RCA.
