### ISSUE TITLE
Remove Windows2012R2 stack option?

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-deployment#1116]
There's a few references to the Windows2012R2 stack in this repo, and I think that stack is deprecated & removed. Can we remove those references?

https://github.com/cloudfoundry/cf-deployment/blob/3c61b371e6f8d79ae3e6f0013113996257483eeb/cf-deployment.yml#L923

**Comment by jochenehret** [comment]
Yes I think this can be removed. We can release this as a major version. We could also remove the "Bionic" leftovers.

**Comment by ctlong** [comment]
I think we can also remove the windows2016 stack.

**Comment by jochenehret** [comment]
Released in https://github.com/cloudfoundry/cf-deployment/releases/tag/v33.0.0
