### ISSUE TITLE
Problem on changing system domain after deployment

### ISSUE THREAD

**Issue by gristest** [cloudfoundry/cf-deployment#1128]
Hi team,

I've deployed a cf with a system domain for a development enviroment by following commands:
```
...
bbl plan --lb-type cf --lb-domain *.dev.mydomain.com --lb-cert cert.pem --lb-key key.pem 
...
bosh -e bosh-formal -d cf deploy cf-deployment/cf-deployment.yml -v system_domain=dev.mydomain.com
```
It works fine. I can use cf console to login and upload my apps to cf. Now I want to use it in a production enviroment, and the domain for production enviroment should be changed to [prod.mydomain.com](http://prod.mydomain.com/). I prepared new certification file for the production domain and issued commands like following:
```
...
bbl plan --lb-type cf --lb-domain *.prod.mydomain.com --lb-cert cert_prod.pem --lb-key key_prod.pem 
...
bosh -e bosh-formal -d cf deploy cf-deployment/cf-deployment.yml -v system_domain=prod.mydomain.com
```
The deployment was succesful without any error. Command "bosh vms" showed all virtual machines worked properly. But the CF could not be accessed by the production domain. Calling api by https://api/..[prod.mydomain.com](http://prod.mydomain.com/) in a browser would return an error message "503 Service Unavailable: Requested route [api.prod.mydomain.com](http://api.prod.mydomain.com/) has no available endpoints". cf login also returned same error.

I redeployed it with the development enviroment domain [dev.mydomain.com](http://dev.mydomain.com/) and it worked fine again.

I am now wondering If I can change the system domain for cloud foundry after deployment. If yes, how to implement it?

Thanks a lot.

**Comment by ctlong** [comment]
Hi @gristest there was a near identical question asked [in Cloud Foundry Slack](https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1698736750959829).

Let's continue the conversation there.
