### ISSUE TITLE
FIPS validation for cf-deployment

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cf-deployment#1140]
We want to validate cf-deployment on a FIPS compliant stemcell. The validation pipeline has been set up here:
https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/fips-stemcell. PR for validation pipeline is https://github.com/cloudfoundry/cf-deployment/pull/1135.

The pipeline uploads the stemcell to be validated and then deploys cf-deployment. Next, it runs the CF smoke-tests and the CF acceptance tests. The pipeline is triggered for each cf-deployment release candidate and for each new stemcell version.

This parent issue will be used to track child issues that are raised for the involved BOSH releases.

```[tasklist]
### Issues
- [ ] https://github.com/cloudfoundry/uaa-release/issues/722
- [ ] https://github.com/cloudfoundry/uaa/issues/2230
- [ ] https://github.com/pivotal/credhub-release/issues/174
- [ ] https://github.com/pivotal/credhub-release/pull/177
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3541
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3555
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/issues/3542
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/issues/3544
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3557
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3558
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/issues/3561
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3562
- [ ] https://github.com/cloudfoundry/buildpackapplifecycle/pull/65
- [ ] https://github.com/cloudfoundry/diego-release/issues/896
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3609
- [ ] https://github.com/cloudfoundry/cf-acceptance-tests/pull/1046
- [ ] https://github.com/cloudfoundry/cf-acceptance-tests/pull/1047
```

**Comment by Gerg** [comment]
Is there an ops file somewhere to enable FIPS compatibility (for example, configuring the CAPI property introduced here: https://github.com/cloudfoundry/capi-release/pull/370)

**Comment by jochenehret** [comment]
We don't have an ops file for FIPS compatibility. It's not yet clear which properties need to be set.

**Comment by jochenehret** [comment]
The latest FIPS validation runs are now green, e.g.: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/fips-stemcell/jobs/fips-cats/builds/66
CATs and CF smoke tests are both passing. We are still using the [fips-compliance.yml](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/experimental/fips-compliance.yml) ops file, however.
