### ISSUE TITLE
Remove operations/experimental/disable-interpolate-service-bindings.yml?

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-deployment#1170]
Does anyone still [disable service binding interpolation in CAPI](https://github.com/cloudfoundry/cf-deployment/blob/develop/operations/experimental/disable-interpolate-service-bindings.yml)? I'm wondering whether the ops file and relevant CATs tests could be removed.

**Comment by ctlong** [comment]
Started a discussion in Slack: https://cloudfoundry.slack.com/archives/C07C04W4Q/p1712361317157729

**Comment by jochenehret** [comment]
Proposed PR: https://github.com/cloudfoundry/cf-deployment/pull/1179

**Comment by jochenehret** [comment]
Small fix: https://github.com/cloudfoundry/cf-deployment/pull/1189

**Comment by jochenehret** [comment]
PRs are merged and the disable CredHub scenario is tested in the "experimental" environment.
