### ISSUE TITLE
Small Footprint Cloud Foundry Deployment

### ISSUE THREAD

**Issue by andy-a-d-nguyen** [cloudfoundry/cf-deployment#1192]
### What is this issue about?

This issue https://github.com/cloudfoundry/cf-deployment/issues/315 regarding work to create Small Footprint Cloud Foundry Deployment was closed some time ago with no resolution. With that, I am opening this issue to ask whether this work can be prioritized again. I think that a Small Footprint CF-D can help test new changes to Cloud Foundry components during CI/CD as well as locally (assuming the machine is sufficiently powerful) without needing a full CF-D infrastructure that can be costly and time-consuming to spin up.

Is this something that can be done?

Respectfully,
Andy

**Comment by ctlong** [comment]
I tend to think that BOSH Lite deployments of CF satisfy this requirement already.

Have you tried that yet? If so, why doesn't it work for this use-case?

**Comment by andy-a-d-nguyen** [comment]
I didn't know such a thing existed. I'll take a look at it and see if it satisfies the use case. Thanks for letting me know!

**Comment by ctlong** [comment]
ARD WG's CI deploys CF-D on BOSH Lite using [bosh-bootloader](https://github.com/cloudfoundry/bosh-bootloader) with a [BOSH Lite plan patch](https://github.com/cloudfoundry/bosh-bootloader/tree/main/plan-patches/bosh-lite-gcp).

Please note that we only test that deployment on GCP at the moment.

**Comment by andy-a-d-nguyen** [comment]
@ctlong Are there docs for BOSH Lite that outlines its architecture similarly to docs for [Small Footprint TAS](https://docs.vmware.com/en/VMware-Tanzu-Application-Service/5.0/tas-for-vms/small-footprint.html)

**Comment by ctlong** [comment]
There are no such docs that I'm aware of. BOSH Lite and SF-TAS are very different conceptually:
- BOSH Lite: the BOSH deployment is setup to deploy BOSH instances as containers instead of VMs, so the CF deployment conceptually is the same but in reality is all deployed in one VM.
- SF-TAS: the BOSH deployment is setup the same, but the CF deployment is purposefully collapsed into less VMs resulting in a smaller footprint.

**Comment by andy-a-d-nguyen** [comment]
Sounds good. I will close this issue and look into whether BOSH Lite can be used for end-to-end tests. Thank you for the explanation!
