### ISSUE TITLE
It also deploys diego?

### ISSUE THREAD

**Issue by vfonsecapv** [cloudfoundry/cf-deployment#12]

**Comment by Amit-PivotalLabs** [comment]
Hi @vfonsecapv 

We have pivoted away from this approach, and are instead focusing on simplifying manifest generation for CF by leveraging features in BOSH 2.0.  The BOSH-2.0-style manifests for CF will "come with" Diego, so you can look forward to that.  This particular project is no longer under active development, and I will udpate the README to reflect this.

Thanks,
Amit
