### ISSUE TITLE
Singleton blobstore denies access on 240.0.0.0/8

### ISSUE THREAD

**Issue by a2geek** [cloudfoundry/cf-deployment#1216]
### What is this issue about?

I am seeing 403 Forbidden when deploying Cloud Foundry to a cluster using 240.0.0.0 (via the [Ubuntu fan](https://wiki.ubuntu.com/FanNetworking)).

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment-44.11.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

```
cf_deployment=~/Documents/Source/cf-deployment-44.11.0

bosh -n -d cf deploy $cf_deployment/cf-deployment.yml \
    -o $cf_deployment/operations/use-compiled-releases.yml \
    -o $cf_deployment/operations/use-latest-stemcell.yml \
    -o $cf_deployment/operations/override-app-domains.yml \
    -o $cf_deployment/operations/use-haproxy.yml \
    -o cf-scale-to-one-multi-az.yml \
    -l cloudfoundry-vars.yml \
    --vars-store=creds/cf.yml
```

The custom scale ops file is just try to more evenly distribute the VMs across a 2 node cluster.

### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

From deploy:

```
Task 37 | 18:12:32 | Updating instance api: api/0f20b72b-0093-43a5-b26a-79caeac30e5c (0) (canary)
Task 37 | 18:12:32 | L starting jobs: api/0f20b72b-0093-43a5-b26a-79caeac30e5c (0) (canary)
Task 37 | 18:13:18 | L executing post-start: api/0f20b72b-0093-43a5-b26a-79caeac30e5c (0) (canary) (00:11:41)
                   L Error: Action Failed get_task: Task 1bf9d21a-7018-4dd1-4686-77c337baaea0 result: 1 of 4 post-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: bosh-dns, policy-server-internal, policy-server.
```

From `api/0`:

```
[2024-11-25 18:13:18+0000] + chpst -u vcap:vcap bundle exec rake buildpacks:install
[2024-11-25 18:13:23+0000] rake aborted!
 (CloudController::Blobstore::BlobstoreError)lobstore::BlobstoreError: Could not create object, 403/<html>
[2024-11-25 18:13:23+0000] <head><title>403 Forbidden</title></head>
[2024-11-25 18:13:23+0000] <body>
[2024-11-25 18:13:23+0000] <center><h1>403 Forbidden</h1></center>
[2024-11-25 18:13:23+0000] 
[2024-11-25 18:13:23+0000] </body>
[2024-11-25 18:13:23+0000] </html>
[2024-11-25 18:13:23+0000] /var/vcap/data/packages/cloud_controller_ng/179007f906b641dd5de0e736b4d913b43270dda4/cloud_controller_ng/lib/cloud_controller/blobstore/webdav/dav_client.rb:207:in `raise_blobstore_error'
```

From `singleton-blobstore/0`:

> 2024/11/25 18:13:23 [error] 11#0: *5 access forbidden by rule, client: 240.5.0.21, server: blobstore.service.cf.internal, request: "PUT /admin/cc-buildpacks/36/ce/36ce47ce-c3de-4ec8-bda7-abe5f09ff7e8_8f6510b62424936a81ab5dc38dba67b0117f25d8d76ffc60e8afd0cc7475dc6c HTTP/1.1", host: "blobstore.service.cf.internal:4443"

I also noticed that allowed internal IP ranges do not include `240.0.0.0/8` which is what the [Ubuntu fan](https://wiki.ubuntu.com/FanNetworking) defaults to: 

```
  allow 10.0.0.0/8;
  allow 172.16.0.0/12;
  allow 192.168.0.0/16;
  deny all;
```
(from `/var/vcap/jobs/blobstore/config/sites/blobstore.conf`)

See: 
* https://github.com/cloudfoundry/capi-release/blob/develop/jobs/blobstore/spec#L40
* https://bosh.io/jobs/blobstore?source=github.com/cloudfoundry/capi-release&version=1.196.0#p%3dblobstore.internal_access_rules

### What IaaS is this issue occurring on?

[LXD](https://github.com/a2geek/bosh-lxd-cpi-release)

### Is there anything else unique or special about your setup?

No.

I added this patch file to my deployment to add that `240/8` block (and had a successful deployment):

```
---
- type: replace
  path: /instance_groups/name=singleton-blobstore/jobs/name=blobstore/properties/blobstore/internal_access_rules?
  value:
  - "allow 10.0.0.0/8;"
  - "allow 172.16.0.0/12;"
  - "allow 192.168.0.0/16;"
  - "allow 240.0.0.0/8;"
```

Uncertain what/if anything should be done in the `cf-deployment` project:
1) Leave as-is. Only crazy people use `240.0.0.0/8`.
2) Add a patch file under community.
3) Update the defaults in the blobstore `spec` to include `240.0.0.0/8`.

Thoughts? 

Thanks!
-Rob

**Comment by jochenehret** [comment]
Hi Rob,
thanks for this detailed explanation of your issue.

The default blobstore access rules defined here:
https://github.com/cloudfoundry/capi-release/blob/6d85f1b93dc72a366b0b92094131dc15d6e68e95/jobs/blobstore/spec#L40
really just include the private networks as defined in RFC 1918. So I wouldn't change that. A community ops file that adds new networks to the allow rules seems to be a reasonable solution. If someone needs yet another network, the ops file can be used as template.

Can you open a PR?

Best Regards,

  Jochen.

**Comment by a2geek** [comment]
Submitted #1217. Please let me know if there is any (likely naming suggestions). I'm traveling so am trying to get something out for comment while I'm gone. :-)
