### ISSUE TITLE
cf-deployment.yml not compliant with YAML spec

### ISSUE THREAD

**Issue by amitoj** [cloudfoundry/cf-deployment#124]
Hi,

I'm developing a tool, for my own educational use, to parse cf-deployment yaml file and visualise the components and dependencies. My tool was parsing the yaml file correctly until Dec 2016. Coming back to the project after few months I've noticed following error message with the latest clone of cf-deployment,
>Exception in thread "main" found undefined alias diego_bbs_client_properties
>            bbs: *diego_bbs_client_properties
> in 'reader', line 727, column 16:
>                 ^

With some analysis I found that the yaml alias is being referenced before it's declaration, which is not compliant with YAML spec - according to various YAML parsers and lint tools available online.

Alias in
`Line 727:           bbs: *diego_bbs_client_properties`
whereas the declaration is in
`Line 800:           bbs: &diego_bbs_client_properties
 Line 801:            ca_cert: "((diego_bbs_client.ca))"
 Line 802:            client_cert: "((diego_bbs_client.certificate))"
 Line 803:            client_key: "((diego_bbs_client.private_key))"
`
Switching the declaration above Line 727 fixes the problem. I'm looking for alternative YAML parsers (written in Java) that can overlook the issue of declaration order, if not then I hope the cf-deployment team can comment on this issue.

**Comment by dsabeti** [comment]
Hey @amitoj, thanks for noticing this! Would you be willing to give a PR for the fix that you made?

**Comment by dsabeti** [comment]
Actually, @amitoj, I think this PR will solve this problem: https://github.com/cloudfoundry/cf-deployment/pull/121

**Comment by amitoj** [comment]
Thanks @dsabeti 
I was really looking forward for a chance to contribute to the project but maybe next time.

**Comment by dsabeti** [comment]
@amitoj, we look forward to your contributions in the future!
