### ISSUE TITLE
3 AZ requirement

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/cf-deployment#13]
Is there any specific reason why there is a requirement on 3 AZs?
- https://github.com/cloudfoundry/cf-deployment/blob/1a599ccc0ef35828a1eca83cee69b8dd37adb590/cf-deployment.yml#L38
- https://github.com/cloudfoundry/cf-deployment/blob/1a599ccc0ef35828a1eca83cee69b8dd37adb590/cf-deployment.yml#L108

I just bbl up'd an environment in us-west-1 and it only gave me 2 AZs, which caused this deployment to fail.

**Comment by dsabeti** [comment]
@zankich I'm pretty sure that the idea was to create an "HA" consul and etcd. If two nodes of a three-node cluster share an AZ, then you'd end up with a split brain should that AZ go down or get its network partitioned.

Granted, that's based on a super cursory understanding of consul and etcd and how they behave under things like a network partition and how they handle split-brain. Is that not the right way to think about high availability for those clusters?

**Comment by zankich** [comment]
@dsabeti yeah from an HA point of view that is correct, but from a bbl up'd deployment experience it was a little unfortunate that I needed to modify the deployment to get it to work. 

If this manifest is supposed to provide an HA manifest, then it makes sense to have a 3 AZ deployment, but what about some of the single instance jobs like `mysql`, `cc_clock` and `blobstore`? Shouldn't those be more than one instance?

I don't mean to be pedantic, I'm just trying to figure out if this manifest is intended to be the de facto open source HA deployment manifest for cloud foundry, or is it supposed to be mostly HA used for test/dev environments.

**Comment by dsabeti** [comment]
Good question, honestly. I think for now it's a "mostly HA" used for test/dev, with the intention that it's going to evolve into the canonical manifest that we point everyone to. That means that eventually it should be properly HA, especially for `mysql` and probably `blobstore` (`cc_clock`, although a singleton, doesn't actually contain any important data, so it could probably remain a single instance).

**Comment by dsabeti** [comment]
Hey, I've added a story to document the requirement of 3 AZs: https://www.pivotaltracker.com/story/show/135450163

There's also a story to add an ops file for deploying to a single AZ:
https://www.pivotaltracker.com/story/show/136291119

I'm going to close the issue in the meantime, but feel free to re-open if you have any more questions ore concerns about this.
