### ISSUE TITLE
Long MariaDB compilation

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/cf-deployment#137]
I am observing two packages compilation takes about 1 hour on `c3.large` machines:

```
11:54:47 | Compiling packages: mariadb/563c214c66c68a3558312fee44c22c30085a663a (00:25:17)
12:20:04 | Compiling packages: xtrabackup/44b8b474086ddbc45a7797c191449da8806ee9d1 (00:27:36)
```

It is too long - for other packages it takes only several minutes to compile.

What is the reason for such long timing and can we make it shorter?

Possible ideas:

1. Make compilation parallel inside single package
2. Start compilation of these two packages first thing in the deployment - now they are the last ones.
3. Run compilation of these two packages in parallel - currently they are compiling sequentially though I have 6 compilation vms.

**Comment by dsabeti** [comment]
Hey @lexsys27. Have you seen our [ops file for using pre-compiled releases](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-compiled-releases.yml)? It uses a version of the release where those packages have already been compiled, so it will skip those steps when you run `bosh deploy`.

It currently only skips the MariaDB-related packages (mariadb, galera, and xtrabackup), but we intend to populate it with compiled versions of the other releases as well.

**Comment by lexsys27** [comment]
Hi @dsabeti . I guess this is not an option for me as I deploy to AWS. And as far as I know pre-compiled release is stemcell specific.

**Comment by dsabeti** [comment]
You can actually use it. The compiled releases are specific to the stemcell _OS_, not the IaaS. We use it on our AWS environments as well.

**Comment by lexsys27** [comment]
Thank you, @dsabeti ! I will try compiled releases
