### ISSUE TITLE
blobstore job should not run consul_agent in server mode

### ISSUE THREAD

**Issue by luan** [cloudfoundry/cf-deployment#14]
This looks like a mistake: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L638-L674

**Comment by Amit-PivotalLabs** [comment]
Thanks again @luan 

Fix LGTM. https://github.com/cloudfoundry/cf-deployment/commit/f8f7bf83580fd6ed3626410f0d6355184f7ac127
