### ISSUE TITLE
Migration from cf-release

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry/cf-deployment#146]
Is there a plan for people using cf-release to migrate to cf-deployment

**Comment by dsabeti** [comment]
Hey @lnguyen. Yeah absolutely. We're still working on it, but you can follow along in the Release Integration tracker: https://www.pivotaltracker.com/n/projects/1382120. We're currently working on the [first milestone](https://www.pivotaltracker.com/story/show/141893473).

**Comment by dsabeti** [comment]
Hey @lnguyen, I wanted to update you briefly on this work.

We've passed that milestone that I linked to, and our second one. The last one [is to validate the migration doesn't incur app downtime](https://www.pivotaltracker.com/story/show/143199685).

Also, if you're interested in poking around, you can take a look [at our transition tooling](https://github.com/cloudfoundry/cf-deployment-transition). **We're not recommending its use just yet**, but I figured you might be interested in seeing what we're working on.

**Comment by dsabeti** [comment]
In the meantime, I'm going to close this issue. Feel free to re-open this issue if you have other questions.
