### ISSUE TITLE
metron_agent has an implicit dependency on consul_agent that isn't satisfied in all instance groups

### ISSUE THREAD

**Issue by luan** [cloudfoundry/cf-deployment#15]
Because of the properties defined here: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L19-L26 that use `etcd.service.cf.internal` the `metron_agent` job ends up having a dependency on the `consul_agent` job.

We found that the following `instance_groups` don't satisfy that dependency:
 - `nats`: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L70-L103
 - `mysql`: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L70-L103
 - `cc_clock`: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L70-L103

**Comment by jaresty** [comment]
Good catch, Luan. Here's the commit to fix it: https://github.com/cloudfoundry/cf-deployment/commit/e324ad4d922f9eae690bc2b750f0633c13a92695

**Comment by Amit-PivotalLabs** [comment]
Thanks @luan!

Fix LGTM.

Closing.
