### ISSUE TITLE
Configuration for mysql should be multi-zone by default

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/cf-deployment#152]
So it is not a single-point-of-failure anymore.

See https://github.com/cloudfoundry/cf-deployment/blob/171fede2351726a520286ab89986946da100be2a/cf-deployment.yml#L175

**Comment by heyjcollins** [comment]
Hey Marco,

I'm just reviewing old issues and doing some cleanup and wanted to respond to here.

We decided to go with a single AZ by default and provide an [ops file](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/scale-database-cluster.yml) to deploy a clustered db.

I'm going to go ahead and close with this issue comment and you can go ahead and reopen if you would like to continue this dialogue.

Cheers,

Josh
