### ISSUE TITLE
bbl create-lbs with valid cert fails

### ISSUE THREAD

**Issue by magnetnoc** [cloudfoundry/cf-deployment#166]
Performing Step 1.5 from instructions https://github.com/cloudfoundry/cf-deployment#readiness

bbl create-lbs --type cf --cert star.crt --key star.key --chain chain.crt

there was 1 error with 'create-lbs':
    * failed to parse private key: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5

The cert is valid - not only used in production, but also verified using the instructions from here:

https://support.asperasoft.com/hc/en-us/articles/216128468-OpenSSL-commands-to-check-and-verify-your-SSL-certificate-key-and-CSR

Possibly related to https://github.com/cloudfoundry/cf-deployment/issues/72  - honestly I'm not sure why this bug was closed, as the user had to perform non-standard workarounds to get by the issue that was reported

**Comment by dsabeti** [comment]
Hi @magnetnoc. The team that maintains bbl [has a story](https://www.pivotaltracker.com/story/show/143960601) to address the issue.

It looks like the issue isn't the validity of the cert, but the format. Different versions of OpenSSL produce different key formats. `bbl` assumed one of the formats (PKCS#1), but it seems likely that your key is PKCS#8. The plan is for `bbl` to support more key formats.

**Comment by magnetnoc** [comment]
Is there a work around for using a valid (not self generated) certificate?   If not, then this is an installation blocker for bbl (and also for Cloud Foundry) on AWS.  Unless setting up the Load Balancers is not needed?

Also I don't think it is the format of the key I provided, as it is exactly the same format AWS requires when uploading a key for use with their load balancers.  It must be some kind of extra transformation the code does, incorrectly.

Can you mark this bug as a blocker?  Highly critical?  P1 ?

**Comment by dsabeti** [comment]
Let me rope in the team that actually builds `bbl`.

@nmahoney-pivotal @christianang: Any thoughts on prioritizing this story? Also, any ideas how someone can work around the issue for now?

**Comment by nmahoney-pivotal** [comment]
Hi @magnetnoc. Still looking into this, but which format are you referring to when you say "it is exactly the same format AWS requires when uploading a key for use with their load balancers"? Do you have a link to docs that discuss this?

**Comment by magnetnoc** [comment]
AWS documentation found via google:  http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/ssl-server-cert.html

I am no expert if certificates or encryption, but I guess I am talking about an SSL certificate for securing HTTPS traffic.  The above doc link calls them X.509 certs.

The "bbl create-lbs" has 3 switches : "--cert" for the public certificate, "--key" for the private cert, and "--chain" for the intermediate cert.

bbl create-lbs --type cf --cert star.crt --key star.key --chain chain.crt

These are identical to the input areas for uploading a SSL certificate into the AWS certificate manager, and for using a SSL certicate for Apache, NGINX etc.

**Comment by nmahoney-pivotal** [comment]
@magnetnoc: Cool. I think the word "format" is a little overloaded when it comes to certs. The issue in `bbl` is that we expect the X.509 cert to adhere to the PKCS#1 standard. We'll change the key parsing code to handle different "formats" now.

**Comment by magnetnoc** [comment]
Ok that sounds great - how can i convert my X.509 certs into PKCS#1 standard ?  I spent an hour last night looking into this, but only ended up more confused than when I started.

**Comment by magnetnoc** [comment]
Also, perhaps a note in the docs, or in the help for bbl, as to what types of certificates it accepts would be helpful

**Comment by nmahoney-pivotal** [comment]
Yeah... I know the feeling. There's a lot hidden behind crypto abstractions. Peeking behind the curtain gets a little crazy.

I'm not sure how to convert keys between these formats, but you shouldn't need to once we cut a release with this change in it. I think we can squeeze another one in this week. I'll report back here when that's done.

**Comment by paulsorensenmagnet** [comment]
Any news of a release with this certificate bug fix?  Just checking in ...

**Comment by dsabeti** [comment]
Hey @paulsorensenmagnet, it looks like there was a commit a few days ago: https://github.com/cloudfoundry/bosh-bootloader/commit/2a92303eefc08aabe1b297186af61e2ba2b5e95b

It hasn't made it into a release yet, but I imagine the next one will include the fix. I'll check back in a few days.

**Comment by nmahoney-pivotal** [comment]
@magnetnoc @paulsorensenmagnet Just cut a new release with these changes: https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v3.2.6.

**Comment by dsabeti** [comment]
@magnetnoc, has the new release of `bbl` solved this issue for you?

**Comment by paulsorensenmagnet** [comment]
I just had a moment to test, and the "bbl command" completed correctly   Thanks for all your help !

**Comment by magnetnoc** [comment]
closing issue as fixed
