### ISSUE TITLE
Step 2 fails with "certificate signed by unknown authority"

### ISSUE THREAD

**Issue by magnetnoc** [cloudfoundry/cf-deployment#170]
After finally getting past Step 1.5 because of a certificate issue (https://github.com/cloudfoundry/cf-deployment/issues/166, "bbl create-lbs with valid cert fails") , I've run into another certificate issue on Step 2.

```
$ bosh -e MYDIRECTORIPADDRESS -d cf deploy cf-deployment/cf-deployment.yml --vars-store env-repo/deployment-vars.yml -v system_domain=$SYSTEM_DOMAIN -o cf-deployment/operations/aws.yml -o cf-deployment/operations/change-logging-port-for-aws-elb.yml -o cf-deployment/operations/disable-router-tls-termination.yml -o cf-deployment/operations/scale-to-one-az.yml
Fetching info:
  Performing request GET 'https://MYDIRECTORIPADDRESS:25555/info':
    Performing GET request:
      Retry: Get https://MYDIRECTORIPADDRESS:25555/info: x509: certificate signed by unknown authority

Exit code 1
```

**Comment by dsabeti** [comment]
Hey @magnetnoc. It looks like you need to provide the CA certificate. If you used `bbl` to create the director, you can run do it one of two ways:
1. With a flag:
```
bosh -e MYDIRECTORIPADDRESS --ca-cert <(bbl director-ca-cert) deploy ...
```
2. With environment variables:
```
export BOSH_CA_CERT="$(bbl director-ca-cert)"
bosh -e MYDIRECTORIPADDRESS deploy ...
```

I just updated the README to include an explanation of this: https://github.com/cloudfoundry/cf-deployment/commit/5cd8332c6e8f4d436390feb085184fad7a4acd2e

**Comment by magnetnoc** [comment]
Actually I did include the CA - in my case this is DigiCert:

Here is the command I ran for step 1.5, for setting up the AWS load balancers:
```
$ bbl create-lbs --type cf --cert star_com.crt --key star_com.key --chain DigiCertCA.crt
step: uploading certificate
step: generating cloudformation template
step: updating cloudformation stack
•••••••••••
step: finished applying cloudformation template
step: generating cloud config
step: applying cloud config
```

Please note that this command was indicated in the bug I referenced : https://github.com/cloudfoundry/cf-deployment/issues/166 and had the same CA being uploaded

That bug had the developers update what certificates types could be processed - perhaps this new style of certificates are not yet compatible with Bosh?

**Comment by magnetnoc** [comment]
Oh wait - now I see what you mean.  I tried that and it did work - or at least it got me to the next issue.

Thanks for updating the documentation!
