### ISSUE TITLE
Deployment using cf-deployment.yml fails due to stemcell version mismatch

### ISSUE THREAD

**Issue by joaompinto** [cloudfoundry/cf-deployment#172]
When running:
bosh -e vbox -d cf deploy cf-deployment.yml   -o operations/bosh-lite.yml   --vars-store deployment-vars.yml   -v system_domain=bosh-lite.com

We get:
06:55:25 | Error: Stemcell version '3421.9' for OS 'ubuntu-trusty' doesn't exist

The default stemcell version was updated to .11, this change needs to be reflected into cf-deployment.yml   .

✔ ~/work bosh -e vbox ss 
Using environment '192.168.50.6' as client 'admin'

Name                                         Version  OS             CPI  CID                                   
bosh-warden-boshlite-ubuntu-trusty-go_agent  3421.11  ubuntu-trusty  -    60b1df3d-9e83-4f4b-4121-2b846c61c326

**Comment by dsabeti** [comment]
Hi @joaompinto. Thanks for raising this issue. Let me explain how the the stemcell version gets updated in cf-deployment.

We have a Concourse job [that automatically updates the stemcell version](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/update-release-stemcell) in `cf-deployment.yml`. When there's a new stemcell published on bosh.io, the job updates the [version in the manifest](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1739-L1742) and commits it to the `develop` branch. Then, the commit with the stemcell updates [gets tested pretty thoroughly](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment?groups=cf-deployment) and, assuming the tests pass, gets promoted to the `release-candidate` branch.

If you look at the `release-candidate` branch, [it actually has version 3421.11](https://github.com/cloudfoundry/cf-deployment/blob/release-candidate/cf-deployment.yml#L1725-L1728).

Periodically -- about twice a week -- we [create a new version of cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases), which also promotes `release-candidate` to `master`. I'll probably do that at some time today.

That necessarily means that the `master` branch of cf-deployment will lag behind the latest stemcell on bosh.io from time to time. The good news is that this includes a bunch of important testing and validation of the integration between the stemcell and the releases in cf-deployment.

Let me know if you have any other questions about cf-deployment or how the releases and stemcells are updated.

**Comment by joaompinto** [comment]
David, thanks for the detailed explanation. 

Meanwhile I have found that I can avoid the issue by explicitly selecting the stemcell version that is set at the deployment manifest:
```
export STEMCELL_VERSION=$(bosh int ~/workspace/cf-deployment/cf-deployment.yml --path /stemcells/alias=default/version)
bosh upload-stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=$STEMCELL_VERSION

```
Thanks
