### ISSUE TITLE
Compiled releases ops file does not work with bosh-lite

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/cf-deployment#174]
I tried to use the `use-compiled-releases.yml` ops file with bosh-lite, but the manifest failed to interpolate:

```
$ bosh int cf-deployment.yml -o operations/bosh-lite.yml -o operations/use-compiled-releases.yml --vars-store vars-store.yml -v system_domain=example.com
Expected to find exactly one matching array item for path '/releases/name=cf-mysql' but found 0

Exit code 1
```

It would be super helpful if compiled releases were compatible with bosh-lite.

**Comment by dsabeti** [comment]
Hey @zankich, it seems like we could easily add `?` to each `replace` action. But, I also you think could solve this by switching the order that you apply the ops-files in. Could you try that and let me know how it goes?

**Comment by zankich** [comment]
@dsabeti yes the manifest does interpolate if I switch the order, but then `postgres-release` is not imported as a compiled release.

**Comment by zankich** [comment]
@dsabeti it might be enough to put a `?` on the replace for `postgres` and `mysql` since those are the only two jobs that can be swapped around.

**Comment by dsabeti** [comment]
Hey @zankich, I think we're going to solve this by replacing cf-mysql-release with postgres-release everywhere. I'll link to the story when it's ready.

**Comment by dsabeti** [comment]
Story is here: https://www.pivotaltracker.com/story/show/148853947

**Comment by dsabeti** [comment]
I left out that we think we're still going to allow cf-mysql-release as a possible backing datastore, but we're going to recommend that deployers set it up as a separate bosh deployment, and use [`use-external-dbs.yml`](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-external-dbs.yml) as the way to access it.

**Comment by zankich** [comment]
If you do that, can you please link to https://github.com/cloudfoundry/cf-mysql-deployment in your documentation

**Comment by dsabeti** [comment]
Yeah definitely. Probably, we'll provide the link, and then some ops-files for seeding the cluster with the databases necessary for CF.

**Comment by dsabeti** [comment]
Hey @zankich. I'm going to close out this issue. We're no longer swapping out mysql for postgres in bosh-lite, so the compiled-releases ops-file should be totally compatible.
