### ISSUE TITLE
The cf client is missing necessary scopes

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cf-deployment#186]
The cf client should have these scopes :
cloud_controller.admin_read_only
cloud_controller.global_auditor

See: https://github.com/cloudfoundry/cf-release/blob/master/templates/cf.yml#L991

**Comment by dsabeti** [comment]
Hey @zrob, thanks for pointing this out. There's no test that fails as a result of these scopes being missing, so my understanding is that no _feature_ is broken as a result of this, but a user who has those scopes wouldn't be able to use them via the CLI. Am I understanding that correctly?

**Comment by zrob** [comment]
I guess we could mince what a feature is.  But the ability to have a user log in as either a read only admin or global auditor would be broken.  This would potentially lock users out of the ability to perform their tasks on CF.

**Comment by dsabeti** [comment]
Sounds good, I just wanted to make sure I understood the effect of missing those scopes.

**Comment by ishustava** [comment]
These scopes were added in [this commit](https://github.com/cloudfoundry/cf-deployment/commit/b658bb76114b12c3b5bfd570922837b17ecc6ea0)
