### ISSUE TITLE
Remove unused loggregator route in route-registrar

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/cf-deployment#187]
The configuration [here](https://github.com/cloudfoundry/cf-deployment/blob/61cb51cc1fcd5c0db17e47c80d65ffd12745ad33/cf-deployment.yml#L1275-L1279) is unused as far as I can tell. Can we delete these lines?

/cc @jasonkeene

**Comment by dsabeti** [comment]
@enocom I'm pretty sure we can get rid of it as well. Do you want to try removing it and see if LATs and CATs still pass?

**Comment by enocom** [comment]
@dsabeti Sure. I'll do that and send you a PR if all works out.

**Comment by dsabeti** [comment]
Hey @enocom, any update on this?

**Comment by enocom** [comment]
@dsabeti It's still on my list of things to do. I'll close the issue and send a PR when I've got around to making the change.
