### ISSUE TITLE
Stop registering TrafficController with consul agent

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/cf-deployment#188]
As far as I know, nothing connects to Traffic Controller though consul DNS. So I think we can remove the lines [here](https://github.com/cloudfoundry/cf-deployment/blob/61cb51cc1fcd5c0db17e47c80d65ffd12745ad33/cf-deployment.yml#L1240-L1243).

Note, we **do** need a consul agent on the VM, though, for Traffic Controller to communicate with Cloud Controller.

/cc @WesleyJeanette @jasonkeene

**Comment by ematpl** [comment]
@enocom the tps-listener still uses it: https://github.com/cloudfoundry/capi-release/blob/1.36.0/jobs/tps/spec#L38-L40:

```
  capi.tps.traffic_controller_url:
    description: URL of Traffic controller
    default: "ws://loggregator-trafficcontroller.service.cf.internal:8081"
```

**Comment by dsabeti** [comment]
Thanks for that, @ematpl. @enocom, should we close the issue?

**Comment by enocom** [comment]
@ematpl Nice! Part of improving Loggregator is understanding our downstream consumers. This is very helpful. Closing. /cc @dsabeti
