### ISSUE TITLE
db address property

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry/cf-deployment#195]
Hi all.
With default cf deployment manifest, uaadb and ccdb is not using the address property and releated app is not using the sql-db domain.
Is it intended configuration?

**Comment by dsabeti** [comment]
Hi @marcus-sds. Good question!

The Cloud Controller and UAA find the database using [BOSH Links](https://bosh.io/docs/links). Specifically, the database proxy in cf-mysql-release [provides a link of type `database`](https://github.com/cloudfoundry/cf-mysql-release/blob/5523b5581a499f60f0114d0077ad6631aa10e1e5/jobs/proxy/spec#L30-L31), which UAA, for example, [consumes](https://github.com/cloudfoundry/uaa-release/blob/059a34b420e9c20f65d1be6d79aef5935f34caf5/jobs/uaa/spec#L33-L35). The UAA templates [are able to use the link to discover the address of the database job.](https://github.com/cloudfoundry/uaa-release/blob/059a34b420e9c20f65d1be6d79aef5935f34caf5/jobs/uaa/templates/uaa.yml.erb#L76-L77) The Cloud Controller does precisely the same thing.

**Comment by dsabeti** [comment]
Hi @marcus-sds, I'm going to close the PR due to inactivity, but feel free to re-open it if you need.
