### ISSUE TITLE
cf-release need to be checked out with `git submodule update --init --recursive` when using an absolute filepath

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/cf-deployment#2]
A hint that your cf-release needs to have all recursive submodules would be appreciated. Maybe just referencing https://github.com/cloudfoundry/cf-release/blob/master/scripts/update as this is what your internal scripting calls when using `integration-latest` would be a good idea?

**Comment by Amit-PivotalLabs** [comment]
Done: https://github.com/cloudfoundry/cf-deployment/commit/b26555201721d9a5291a466265af70ecec179fd7
