### ISSUE TITLE
use-external-dbs.yml does not work with postgres

### ISSUE THREAD

**Issue by jsievers** [cloudfoundry/cf-deployment#202]
if we use ops file 

https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-external-dbs.yml

with variable `db_type=postgres`, the UAA job won't start with error message 

```No bean named 'platformProperties' is defined```

it turns out that the UAA job (spring) requires "postgresql" (note the trailing "ql") as uaa.db_scheme 

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/uaa.yml.erb#L188

nevertheless the other jobs using the diego and ccdb databases work with `db_type=postgres`.

One way to fix this would be to add a UAA specific db_type variable.

**Comment by dsabeti** [comment]
Good catch @jsievers.

I think the approach you suggested would work, but it would require a big warning that told operators to provide the scheme twice, each time in a different format (`postgresql` for UAA, and `postgres` for everything else).

@sreetummidi, could we add some logic to the UAA templates to unify this interface?

**Comment by jhamon** [comment]
@sreetummidi Yeah, we should be able to do that pretty easily if needed.

**Comment by dsabeti** [comment]
Yeah, it would make the deployment interface much simpler if everyone could supply the same string for the db_scheme. Thanks for the quick response, UAA team.

**Comment by dsabeti** [comment]
Hey @sreetummidi, any update on this? Is there a link to a story that we can follow?

**Comment by philippthun** [comment]
We've applied cf-deployment v1.3.1 and could remove our internal workaround that patched the db type - so this is working fine now.

**Comment by dsabeti** [comment]
Thanks for the update @philippthun. I'll go ahead and close this issue now.
