### ISSUE TITLE
ops file `disable-router-tls-termination.yml` is broken

### ISSUE THREAD

**Issue by astrieanna** [cloudfoundry/cf-deployment#211]
The PR changed the structure of the manifest: https://github.com/cloudfoundry/cf-deployment/pull/171

But this file https://github.com/cloudfoundry/cf-deployment/blob/master/operations/disable-router-tls-termination.yml still expects the old keys.

This breaks deployments (or even interpolating the manifest) with this ops-file.

**Comment by dsabeti** [comment]
@astrieanna As I mentioned in your PR, we have a change to fix this in the testing pipeline. I'm going to go ahead and close this issue.
