### ISSUE TITLE
cc-clock scale down in operations/scale-to-one-az.yml

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry/cf-deployment#216]
Hi
The cc-clock is not updated in the file operations/scale-to-one-az.yml. 
Best regards

**Comment by dsabeti** [comment]
Hey @rauizab, good catch! We've already merged a PR that fixes this: https://github.com/cloudfoundry/cf-deployment/pull/210.

We're hoping to cut a release of cf-deployment later today with this fix.
