### ISSUE TITLE
How to insert new instance_group *before* another one

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/cf-deployment#223]
For the bits-service, which is currently in experimental (on branch develop), we need it to be inserted **before** the `api` instance_group, otherwise the cloud_controller will fail to start up.

Our understanding is that ops files cannot do that, they always **append**. What is the recommended approach to solve this problem?

Thanks,
Peter

/cc @egurnov @smoser-ibm

**Comment by dsabeti** [comment]
Hey @petergtz. There's not an easy way to do this currently. I'm going to chat with @cppforlife about adding something to the BOSH CLI to allow for this.

In the meantime, would it make sense to colocate the bits service on an instance_group like `api`?

**Comment by petergtz** [comment]
@dsabeti 

> I'm going to chat with @cppforlife about adding something to the BOSH CLI to allow for this.

That would definitely be helpful. Thanks.

> In the meantime, would it make sense to colocate the bits service on an instance_group like `api`?

@egurnov and I will try and see if that works and if so open a new PR with the changes.

**FYI**, for our [own pipeline](flintstone.ci.cf-app.com) we'll keep them in separate jobs. The reason why it works in our pipeline is that on the first deployment we tell CC not to use bits-service. So bits-service is just lying around there. Only on the second deploy we tell CC to use it. Since bits-service is already there, CC deploys fine.

**Comment by petergtz** [comment]
@dsabeti 

> In the meantime, would it make sense to colocate the bits service on an instance_group like `api`?

We tested to colocate this and it actually works. We didn't colocate it on `api` though, but on `blobstore`. The reason is that BOSH does not allow the same package name from two different jobs on the same VM. bits-service and cloud-controller both use a `nginx` package. Hence, we decided to colocate it on the `blobstore` VM instead.

Now that this works, do you recommend to provide the ops files for colocation instead? That would help early adopters to get a working manifest, but requires us to update the ops files again once BOSH provides this feature, and also uses a configuration which is against the idea of the bits-service. What's your recommendation?

/cc @egurnov @smoser-ibm

**Comment by dsabeti** [comment]
@petergtz, I'm going to pair with @cppforlife on Friday to address some of these issues. I'd say wait until these BOSH features come through, and the we can just get the whole thing right.

Also, it seems very unfortunate that you can't colocate it with the `api` due to a simple naming collision. If that weren't an issue, do you think it would make sense to colocate it with the `api` VM? I'm asking because we've gotten feedback about the VM footprint of cf-deployment, so I'm trying to find reasonable colocation opportunities. If not, that's totally fine, we can add it as a separate instance_group.

**Comment by petergtz** [comment]
@dsabeti 

> it seems very unfortunate that you can't colocate it with the api due to a simple naming collision. If that weren't an issue, do you think it would make sense to colocate it with the api VM? 

We'll rename the package in the bits-service to give us max flexibility.

We'll also open new PR for co-location on `api` to get us off the ground for the time being. We can reconsider things when BOSH provides new features.

**Note though**: The motivation for extracting the bits-service from CC was to be able to scale it independently from CC. It's one of its main reasons for existence. Co-location is fine for test environments, but for production environments we wouldn't recommend this.

Anyway, long-term the bits-service will be part of the default template and there we can decide to co-locate it or have it as extra `resource_group` and then we can provide a separate ops-file to change this to the operators liking. What do you think?

/cc @smoser-ibm

**Comment by dsabeti** [comment]
@petergtz That sounds like a great plan -- it gives us a path forward in the short-term while we try to get the feature that we need from BOSH.

Also, this
> The motivation for extracting the bits-service from CC was to be able to scale it independently from CC.

seems like a sufficiently good reason to have the bits service as a separate instance_group in the long-term.

**Comment by petergtz** [comment]
For reference, co-location on `api` is now in https://github.com/cloudfoundry/cf-deployment/pull/252.

**Comment by dsabeti** [comment]
Hi @petergtz, I'm not sure if you've seen, but the BOSH CLI supports this now. [This ops-file has a good a example](https://github.com/cloudfoundry/cf-deployment-transition/blob/master/keep-etcd-for-transition.yml#L22-L23).

I'm going to close the issue, but feel free to reopen.
