### ISSUE TITLE
deploy failed when there are iptables rules&nats on the host machine

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-deployment#231]
I tried to deploy cf use cf-deployment on my machine. And when there are some iptables rules&nats, the deploy will fail with following error msg. And when I delete all the iptables rules, the deployment can be successfully.
error:
```
Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{20aa3189-6f59-491c-82b6-3827ee51e14a}}': Forwarding host ports: Forwarding host port(s) '{%!s(int=80) %!s(int=80)}': Running command: 'iptables -w -t nat -A PREROUTING -p tcp ! -i w+ --dport 80 -j DNAT --to 10.244.0.34:80 -m comment --comment bosh-warden-cpi-be38f243-0181-445f-4793-2369d2924a34', stdout: '', stderr: 'iptables: Resource temporarily unavailable.
': exit status 4' in 'create_vm' CPI method
```

**Comment by dsabeti** [comment]
Hi @qibobo, I'm very familiar with this error. It looks like the issue is with BOSH trying to use `iptables`. Are you running this on bosh-lite? If so, how you setting it up -- specifically, did you follow [these instructions](http://bosh.io/docs/bosh-lite.html)?

A quick google of the error message ("iptables: Resource temporarily unavailable") suggests resource constraints? What kind of resources are available to your bosh-lite?

**Comment by qibobo** [comment]
@dsabeti yes, it is on a bosh-lite and I followed the instructions. What this issue comes is that I deploy a bosh-lite on my machineA, and I want to access the bosh-lite on other remote machines. So I added some iptables nats that will forward the request access port 25555 of machineA to the bosh-lite. Is it conflicted with bosh?

**Comment by dsabeti** [comment]
@qibobo, I don't think I've heard of someone trying to do this. Let's first get a bunch of information about your setup. Could you provide every command you ran, and which machine you ran it on? Please provide as much detail as possible.

In the meantime, I'm going to pull in @cppforlife and @dpb587 from the BOSH team to see if they can help you to debug your bosh-lite setup.

**Comment by qibobo** [comment]
Below is all the steps. Not every time of my deployments will occur this error but sometimes.
====================
git clone https://github.com/cloudfoundry/bosh-deployment
cd bosh-deployment
cat >external_ip.yml <<-EOF
- type: replace
  path: /variables/name=director_ssl/options/alternative_names/-
  value: 10.121.94.103
EOF

bosh2 create-env bosh.yml \
  --state ./state.json \
  -o virtualbox/cpi.yml \
  -o virtualbox/outbound-network.yml \
  -o bosh-lite.yml \
  -o bosh-lite-runc.yml \
  -o jumpbox-user.yml \
  -o external_ip.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork \
  -v admin_password=admin 

bosh2 -e 192.168.50.6 --ca-cert <(bosh2 int ./creds.yml --path /director_ssl/ca) alias-env vbox

export BOSH_CLIENT=admin \
&& export BOSH_CLIENT_SECRET=admin 

cd ..
git clone https://github.com/cloudfoundry/cf-deployment.git
cd cf-deployment
bosh2 -n -e vbox upload-stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent \
&& bosh2 -n -e vbox update-cloud-config bosh-lite/cloud-config.yml \
&& bosh2 -n -e vbox -d cf deploy  cf-deployment.yml \
 -o operations/bosh-lite.yml \
 --vars-store deployment-vars.yml \
 -v system_domain=bosh-lite.com \
 -v cf_admin_password=admin \
 -v uaa_admin_client_secret=admin-secret
====================
And the iptables rules:
iptables -A FORWARD -i bond0 -o vboxnet0 -j ACCEPT \
&& iptables -A FORWARD -o bond0 -i vboxnet0 -j ACCEPT \
&& iptables -A FORWARD -i bond0 -o vboxnet0 -m state --state ESTABLISHED,RELATED -j ACCEPT \
&& iptables -A FORWARD -o bond0 -i vboxnet0 -m state --state ESTABLISHED,RELATED -j ACCEPT \
&& iptables -t nat -A PREROUTING -p tcp -i bond0 -d 10.121.94.103 --dport 25555 -j DNAT --to 192.168.50.6:25555 \
&& iptables -t nat -A POSTROUTING -o bond0 -j MASQUERADE \
&& iptables -t nat -A POSTROUTING -o vboxnet0 -j MASQUERADE \
&& iptables -t nat -A PREROUTING -p tcp -i bond0 -d 10.121.94.103 --dport 443 -j DNAT --to 10.244.0.34:443 \
&& iptables -I INPUT -p tcp --dport 25555 -j ACCEPT && sudo iptables -I OUTPUT -p tcp --dport 25555 -j ACCEPT \
&& iptables -I INPUT -p tcp --dport 443 -j ACCEPT && sudo iptables -I OUTPUT -p tcp --dport 443 -j ACCEPT \
&& iptables -t nat -A OUTPUT -p tcp -d 10.121.94.103 --dport 25555 -j DNAT --to-destination 192.168.50.6:25555

**Comment by dsabeti** [comment]
Ok. Could you try an experiment? While you're deploying, could you ssh into the VirtualBox VM and run `htop` to see if any resources like CPU or memory become overly constrained?

**Comment by xoebus** [comment]
I'm seeing the same error with vanilla iptables rules.

**Comment by dsabeti** [comment]
@xoebus, also on a local bosh-lite?

**Comment by xoebus** [comment]
Yep.

**Comment by xoebus** [comment]
I upgraded to the latest version of VirtualBox and the deploy succeeded. I'm not sure whether or not this was a coincidence.

**Comment by dsabeti** [comment]
@qibobo, could you try upgrading your VirtualBox?

**Comment by qibobo** [comment]
@dsabeti  In the latest 2 deployments, the error does not occur. Not sure whether it will occur in the future or not.

**Comment by dsabeti** [comment]
Ok. Let's leave this issue open for a week or so, and if the error occurs again, let us know. Like I said, any information about resource usage in the bosh-lite vm would be very helpful to debug if you continue to see it.

**Comment by dsabeti** [comment]
I'm going to close this issue since we haven't heard any news. Feel free to reopen the issue if needed.
