### ISSUE TITLE
the latest stemcell 3445.11  is not supported 

### ISSUE THREAD

**Issue by cdlliuy** [cloudfoundry/cf-deployment#241]
I have 3445.11 deployed, but cf-deployment only support 3445.7 only

$ bosh -e vbox stemcells
Using environment '192.168.50.6' as client 'admin'

Name                                         Version  OS             CPI  CID
bosh-warden-boshlite-ubuntu-trusty-go_agent  3445.11  ubuntu-trusty  -    e1dd642d-e671-4817-675d-4a6e75ae219a

(*) Currently deployed

1 stemcells

Error when deploy CF:
....
+ variables: []
Task 36

Task 36 | 09:18:33 | Preparing deployment: Preparing deployment (00:00:01)
                   L **Error: Stemcell version '3445.7' for OS 'ubuntu-trusty' doesn't exist**
Task 36 | 09:18:34 | **Error: Stemcell version '3445.7' for OS 'ubuntu-trusty' doesn't exist**

Task 36 Started  Wed Sep 20 09:18:33 UTC 2017
Task 36 Finished Wed Sep 20 09:18:34 UTC 2017
Task 36 Duration 00:00:01
Task 36 error

Updating deployment:
  Expected task '36' to succeed but state is 'error'

Exit code 1

**Comment by Infra-Red** [comment]
@cdlliuy Develop branch of cf-deployment was already updated to use `3445.11` stemcell version, please see
https://github.com/cloudfoundry/cf-deployment/blob/develop/cf-deployment.yml#L1769-L1772

If you prefer to use `master` branch or latest tag you should upload stemcell `3445.7` to your bosh director.
https://bosh.io/docs/uploading-stemcells.html

**Comment by dsabeti** [comment]
Yup @Infra-Red, is correct. @cdlliuy, I'm going to try to cut a new cf-deployment some time today, at which point you'll get the latest stemcell.

**Comment by cdlliuy** [comment]
thank you for you all !  I already workaround it with 3445.7, but anyway just want to use this issue to require your attention for the mismatch. Glad to see it is addressed already. thanks
