### ISSUE TITLE
Redeploy cf-deployment to bosh-lite failed

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-deployment#249]
I do the cf-deployment by **concourse**. I first deploy bosh-deployment to my bosh-lite and then begin to deploy cf-deployment.
When concourse do the deployment the first time , the cf-deployment will always succeed. But  when deploy again, it always fail, with consul, api and diego-api vms failed.

Deployment 'cf'
```
Instance                                          Process State  AZ  IPs           VM CID                                VM Type
api/8657e77e-52a2-45ce-a679-7eeebaa4e456          failing        z1  10.244.0.136  2d080210-1232-41b1-6b93-7f3fe9ad5acc  small
blobstore/3820bfb8-0910-498c-b370-ab042cc6ee1c    running        z1  10.244.0.135  f975282b-ac42-462e-7fe8-c3808858610f  small
cc-bridge/feb1c282-0723-421f-bdcf-2e38a115abe7    running        z1  10.244.0.141  3ba0c3f3-7506-45b5-47b0-911006cb932b  minimal
cc-clock/3f223ee4-d0e7-411b-be5f-7452cad3df38     running        z1  10.244.0.140  ce1583a5-e44f-4737-7d9f-66f1720d3cec  small
cc-worker/cfad2c54-a819-453a-bcc3-ccab3fc4a3ed    running        z1  10.244.0.137  ce33dbf5-e48b-4f75-5a35-33f6ee23f892  minimal
consul/e91daddb-9f30-41b6-a415-60cdc91c9e0c       failing        z1  10.244.0.128  bfb4d331-41ae-471b-778d-446c98412f7a  minimal
diego-api/66d74455-4983-4abc-acbe-a888d24335f0    failing        z1  10.244.0.133  d0424f3a-5e15-4ae6-57c9-1101ff46a7bf  small
diego-brain/c61d47f9-8e9a-4eff-93f4-dca956507ad8  running        z1  10.244.0.138  687a85c5-4491-4e3e-53e5-e2a90f7ac752  minimal
diego-cell/750d2718-7717-42d5-8565-83a2fcfeaf91   running        z1  10.244.0.139  bba43af4-2225-4619-5b3e-3f0f5664c3c3  small-highmem
doppler/47686bd1-7b22-4236-9fd7-b491fbbaf64c      running        z1  10.244.0.131  291f0d25-6542-4632-7cfc-3c0519dcb53f  minimal
etcd/0cb578b0-b48f-41e8-b991-42723b71e292         running        z1  10.244.0.130  6f19e66f-e908-4c43-4cd3-5a56f5c23d37  minimal
log-api/5030127f-3e56-4d17-9e84-259116568bce      running        z1  10.244.0.142  0f7e0137-9835-4837-5380-4bbf18f3c2e6  sharedcpu
nats/4f66731c-222d-42f7-a26d-20706c5d92ca         running        z1  10.244.0.129  f520deee-d7c7-4444-4a95-377e50ab367b  minimal
postgres/6dffe19b-f75b-4b4c-9b66-cc5adf6b6f02     running        z1  10.244.0.132  97952538-4ba5-42bd-68cb-332925bef4fd  small
router/8468b6a9-3c39-4367-9169-7cc7ec3a15d1       running        z1  10.244.0.34   2f830290-bbef-4e7a-4e29-206adfd07532  minimal
uaa/6ef6fa2b-170c-40d9-b0cb-f69aca0a1d18          running        z1  10.244.0.134  3c7524f7-9b52-4c02-5f5a-ca45ae72bdfd  minimal
```

**Comment by qibobo** [comment]
consul-agent log fragment:

2017/09/21 08:18:37 [INFO] serf: Received remove-key query
    2017/09/21 08:18:37 [ERR] serf: Failed to remove key: Removing the primary key is not allowed
    2017/09/21 08:18:37 [INFO] serf: Received remove-key query
    2017/09/21 08:18:37 [ERR] serf: Failed to remove key: Removing the primary key is not allowed
    2017/09/21 08:18:38 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.139:57124: read: connection reset by peer from=10.244.0.139:57124
    2017/09/21 08:18:38 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.139:57140: read: connection reset by peer from=10.244.0.139:57140
    2017/09/21 08:18:38 [ERR] http: Request DELETE /v1/operator/keyring, error: 2 error(s) occurred:

* 1/1 nodes reported failure
* 24/24 nodes reported failure from=127.0.0.1:47846
{"timestamp":"1505981918.318831921","source":"confab","message":"confab.agent-client.set-keys.remove-key.request.failed","log_level":2,"data":{"error":"Unexpected response code: 500 (2 error(s) occurred:\n\n* 1/1 nodes reported failure\n* 24/24 nodes reported failure)","key":"QqD439itjRZnBiY405ZsPQ=="}}
    2017/09/21 08:18:38 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.139:57144: read: connection reset by peer from=10.244.0.139:57144
    2017/09/21 08:18:38 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.141:46232: read: connection reset by peer from=10.244.0.141:46232
    2017/09/21 08:18:38 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.135:50372: read: connection reset by peer from=10.244.0.135:50372
    2017/09/21 08:18:39 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.138:33138: read: connection reset by peer from=10.244.0.138:33138
{"timestamp":"1505981919.319208145","source":"confab","message":"confab.agent-client.set-keys.list-keys.request","log_level":1,"data":{}}
    2017/09/21 08:18:39 [INFO] serf: Received list-keys query
    2017/09/21 08:18:39 [INFO] serf: Received list-keys query
    2017/09/21 08:18:39 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.139:57184: read: connection reset by peer from=10.244.0.139:57184
{"timestamp":"1505981919.753839016","source":"confab","message":"confab.agent-client.set-keys.list-keys.response","log_level":1,"data":{"keys":["QqD439itjRZnBiY405ZsPQ=="]}}
{"timestamp":"1505981919.753888845","source":"confab","message":"confab.agent-client.set-keys.remove-key.request","log_level":1,"data":{"key":"QqD439itjRZnBiY405ZsPQ=="}}
    2017/09/21 08:18:39 [INFO] serf: Received remove-key query
    2017/09/21 08:18:39 [ERR] serf: Failed to remove key: Removing the primary key is not allowed
    2017/09/21 08:18:39 [INFO] serf: Received remove-key query
    2017/09/21 08:18:39 [ERR] serf: Failed to remove key: Removing the primary key is not allowed
    2017/09/21 08:18:40 [ERR] http: Request DELETE /v1/operator/keyring, error: 2 error(s) occurred:

* 1/1 nodes reported failure
* 24/24 nodes reported failure from=127.0.0.1:47846
{"timestamp":"1505981920.203001738","source":"confab","message":"confab.agent-client.set-keys.remove-key.request.failed","log_level":2,"data":{"error":"Unexpected response code: 500 (2 error(s) occurred:\n\n* 1/1 nodes reported failure\n* 24/24 nodes reported failure)","key":"QqD439itjRZnBiY405ZsPQ=="}}
    2017/09/21 08:18:40 [ERR] consul.rpc: failed to read byte: read tcp 10.244.0.128:8300->10.244.0.129:39616: read: connection reset by peer from=10.244.0.129:39616

**Comment by dsabeti** [comment]
Hi @qibobo. Can you show me your full deploy command? `bosh deploy cf-deployment -d cf -o ... `. I'd like to know which ops-files your providing, and how you're passing variables to the deployment.

**Comment by qibobo** [comment]
@dsabeti 
bosh2 -n -e vbox upload-stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent \
&& bosh2 -n -e vbox update-cloud-config bosh-lite/cloud-config.yml \
&& bosh2 -n -e vbox -d cf deploy  cf-deployment.yml \
 -o operations/bosh-lite.yml \
 --vars-store deployment-vars.yml \
 -v system_domain=bosh-lite.com \
 -v cf_admin_password=admin \
 -v uaa_admin_client_secret=admin-secret

**Comment by evanfarrar** [comment]
Hi @qibobo is it possible that deployment-vars.yml is not being persisted between the first and the second deploy? If you generate the variables again, consul will attempt to rotate the keys and produce errors like the above.

**Comment by qibobo** [comment]
@evanfarrar thanks for your response. In the cf-deployment.yml I found there are several keys, should I persist all of them or just one ?
- name: consul
  azs:
  - z1
  - z2
  - z3
  instances: 3
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  update:
    max_in_flight: 1
    serial: true
  networks:
  - name: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link}
      consul_server: {from: consul_server_link}
      consul_client: {from: consul_client_link}
    provides:
      consul_common: {as: consul_common_link, shared: true}
      consul_server: {as: consul_server_link, shared: true}
      consul_client: {as: consul_client_link, shared: true}
    properties:
      consul:
        agent:
          mode: server
          domain: cf.internal
        **encrypt_keys:
        - "((consul_encrypt_key))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_agent.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"**

**Comment by dsabeti** [comment]
@qibobo You should persist the whole file `deployment-vars.yml`. 

That file contains all of the credentials -- including passwords and certificates -- that get used in the deployment. If you don't provide the same file in your subsequent deploys, the bosh CLI will regenerate them, and it regenerating the consul certificates is what's causing your failed deploy.

**Comment by dsabeti** [comment]
Hi @qibobo, did persisting `deployment-vars.yml` help?

**Comment by qibobo** [comment]
@dsabeti  For manual deployment, I can persist the yml, but in concourse, the deploy will be done on the jobs' containers. And the yml can not be shared between the containers.

**Comment by dsabeti** [comment]
@qibobo, you can persist the file using a [Concourse resource](http://concourse.ci/concepts.html#resources). The [s3 resource](https://github.com/concourse/s3-resource) and the [git resource](https://github.com/concourse/git-resource) are good places to start. If you want a good example for how we use Concourse resources on the CF teams, you can look in our [nats pipeline configuration](https://github.com/cloudfoundry/runtime-ci/blob/master/pipelines/nats-release.yml#L255-L259)_

**Comment by dsabeti** [comment]
Hi @qibobo, I'm going to close this issue due to inactivity, but feel free to reopen it if you need more help.
