### ISSUE TITLE
use-external-dbs.yml uses different variable names for DB passwords than cf-deployment.yml

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/cf-deployment#250]
Hi,
if you run `bosh interpolate  --var-errs  --var-errs-unused` with `use-external-dbs.yml` ops file you get the following errors:
```
- Expected to find variables:
    - cc_database_password
    - diego_database_password
    - uaa_database_password
    .....
```
This is because `use-external-dbs.yml` is using different variables for the db passwords than cf-deployment but doesn't remove the corresponding variable declarations in the manifest (e.g. `cc_database_password` opposed to `cc_db_password`).

One could either use the same variable names as in `cf-deployment.yml` and keep the variable declarations or remove the variable declarations, like

```
- type: remove
  path: /variables/name=cc_database_password
- type: remove
  path: /variables/name=diego_database_password
- type: remove
  path: /variables/name=uaa_database_password
....
```

**Comment by dsabeti** [comment]
Hi @achawki. Good catch. I think it makes more sense to have `use-external-dbs.yml` remove the variable declarations in the bosh manifest. Having distinct names for the variables that ship as part of cf-deployment.yml vs variables used by the ops-file will be helpful for BOSH directors that have a CredHub deployed with them.

**Comment by achawki** [comment]
Seems to be fixed with https://github.com/cloudfoundry/cf-deployment/commit/567657102cd1e231e482883fc5b6ac9a9e04023f
