### ISSUE TITLE
GCP networking issue

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/cf-deployment#27]
We are creating this issue as a place for conversation about GCP networking issues.

We are seeing requests to the cloud controller fail intermittently. The issue primarily shows up while running CATs. The cf cli does not have a timeout value set on its HTTP client, so it just hangs until the test fails. We can reproduce the issue outside of CATs from anywhere on the internet using the cf cli. Here is the test:

```bash
cf login # log into the cf deployment
export CF_TRACE=true
while true; do
    echo "--------------------------------------------------"
    date
    time cf create-org foo
    date
    time cf delete-org -f foo
done
```

Eventually the cf cli will hang. We then track down the vcap-request-id and when we look at the cloud controller's app and nginx logs we see that a 200 response is written out.

### Here are the details of our environment that is showing the issue:

- CF deployed on GCP using the manifest from this repo.
- Static IP assigned to a local forwarding rule that has a target pool for the gorouter instances.

### Stuff we've tried to help CATs pass:

- We set the MTU for garden containers to 1460 to prevent packet fragmentation coming from the container running CATs. This turned out to be a red herring since running the cf cli from anywhere on the internet also exposes the issue.
- We [patched](https://github.com/cloudfoundry/cli/compare/cloudfoundry:269814d...jasonkeene:fd334a0) the cf cli to have a timeout and a new transport for each request. Since the cf cli has a retry loop this helps CATs still pass when we see these failures. This just masks the underlying issue but helps get us green.

### Steps we are taking to fix the problem:

- We are verifying this problem exists against a newly deployed GCP environment.
- If we see the issue crop up again we will continue to trace the failed requests. Then next thing we need to look at are gorouter logs and try to find what (if anything) is between the gorouter and the cf cli that might be causing these failures.

### Loggregator team members who have context on this issue:

- @jasonkeene
- @enocom
- @nelsam

**Comment by genevievelesperance** [comment]
container-networking has seen a similar issue. Our own integration tests were failing in an environment that is deployed to AWS by a concourse running on GCP.

We mitigated the issue with this commit:
https://github.com/cloudfoundry-incubator/netman-release/commit/f89da4b843d0b242b71169e484decb7dd20afb87

We wrap our cli commands in timeouts as opposed to patching the cli. We actually did this in order to better identify the failures we were seeing but the timeout actually resolved them.

cc @mcwumbly

**Comment by wfernandes** [comment]
The problem still exists in our newly deployed GCP environment. We'll continue to troubleshoot the issue.

**Comment by jasonkeene** [comment]
We added [another patch](https://github.com/jasonkeene/cli/commit/22d233b76573909929806d561418c4207079cf3e) to the cli to not retry requests.

Related issue: https://github.com/cloudfoundry/cli/issues/1015

**Comment by RochesterinNYC** [comment]
Is there a way to patch the CLI to still have overall retry logic without causing the errors related to resetting the request body? Maybe using retry mechanisms at a lower level (like the HTTP Client library itself)?

**Comment by RochesterinNYC** [comment]
Noting that this affects the Buildpacks team pretty severely as not only do we run CATS in three pipelines in our CI, each of our buildpack test suites (9 of them) rely on the CF CLI for pushing a lot of fixture apps during the integration testing portions.

**Comment by rosenhouse** [comment]
An update here from the Container Networking team: this became so painful for us that we moved our Concourse back to AWS (where our CF environments live).  Once we did that, CATS immediately began passing again.

**Comment by jaresty** [comment]
An update from the release integration team:

# We are not able to reproduce a "hang" using the shell loop provided

I've tried running the example create/delete org loop against our GCP environment and after 10 minutes of looping I haven't seen the CLI hang, where I'm defining hang to mean "hang forever and never come back". We are seeing it occasionally stop for a moment before continuing.
Details about the test I'm doing:

# We are using version 6.22.1 of the CF CLI on our dev iMacs to run the test
```
cf version
> cf version 6.22.1+6b7af9c-2016-09-24
```
# We terraformed and deployed to GCP using the setup described in our gcp-cf-deployment repository

Our GCP environment was deployed using cf-deployment.yml and the opsfiles/gcp.yml opsfile against a GCP project that was setup using the terraform files in the [gcp-cf-deployment](https://github.com/cloudfoundry-incubator/cf-gcp-infrastructure) repository and the terraform concourse resource [defined in our runtime-ci pipeline](https://github.com/cloudfoundry/runtime-ci/blob/e79f1cfcfa2cdf7a4fbb592bc48944d8cad40628/pipelines/cf-deployment.yml#L36-L54).

# The terraform files we are using setup our GCP using multiple load balancers, target proxies, and instance groups as follows:


* global forwarding rule "cf-lb-http":
  -> httpproxy and httpsproxy which are target proxies that point to the cf-http load balancer
![screen shot 2016-12-14 at 10 24 29 am](https://cloud.githubusercontent.com/assets/1313844/21195513/eff8f3e0-c1e8-11e6-9b18-aed1d5b33b48.png)
  -> a backend httpslb service that points to two regional instance groups each containing one cf-router
![image](https://cloud.githubusercontent.com/assets/1313844/21195533/0917e07a-c1e9-11e6-8257-af0f5956e0e8.png)
![image](https://cloud.githubusercontent.com/assets/1313844/21195542/12c858fc-c1e9-11e6-9a44-7552be451445.png)
* load balancer "cf-http" accepts http and https and points to two instance groups (one per region, each containing a single cf router with a health check)
![image](https://cloud.githubusercontent.com/assets/1313844/21195556/1cdd5248-c1e9-11e6-8417-911362d92905.png)
* load balancer "cf-ws" accepts http and https and points directly to router instances
![image](https://cloud.githubusercontent.com/assets/1313844/21195572/311913fa-c1e9-11e6-8cb8-6270ee5f8f1c.png)
* health checks access the path /health from port 8080 on each router
![image](https://cloud.githubusercontent.com/assets/1313844/21195589/4274633e-c1e9-11e6-8c85-1ad9e6505100.png)

**Comment by flavorjones** [comment]
@jaresty Thanks for working on this. Are you able to reliably get CATS to pass in your environment?

**Comment by ChunyiLyu** [comment]
@flavorjones Yes -- it works at least as reliably as our AWS environment.

**Comment by dsabeti** [comment]
/cc @jasonkeene @enocom @rosenhouse @RochesterinNYC @jtarchie @genevievelesperance @ahevenor 

Just wanted to point everyone to this update.

**Comment by rosenhouse** [comment]
One more data point from the garden team (cc @williammartin): https://www.pivotaltracker.com/n/projects/1158420/stories/136177031

**Comment by nelsam** [comment]
I wonder if it isn't working for us because we're using `Forwarding Rule` for *everything*, instead of just for websocket.  We should update our stack to use a `Global Forwarding Rule` for the non-websocket connections and see if that helps.

**Comment by JesseTAlford** [comment]
The recent Concourse release notes mentioned that the default MTU limit in their containers was too high for GCP, and that they've fixed that now.

Has anyone who was having this problem tried updating to the latest Concourse? If I'm understanding reports correctly, everyone who's had an issue was experiencing it from inside Concourse containers?

**Comment by RochesterinNYC** [comment]
Is that in regards to the Concourse `2.5.1` release? In the release notes, the only reference to MTU fixes/changes is specifically for the Docker image concourse resource and not really Concourse itself.

**Comment by JesseTAlford** [comment]
You're right, @RochesterinNYC. I misread the note; the MTU change they mention is only relevant for fetching docker images.

Still, GCP's recommended MTU settings being 1450 might be relevant. Packets over the MTU can result in dropped packets and thus hanging calls. I'm researching the exact situation and its implications now.

**Comment by JesseTAlford** [comment]
# Investigation Update

It sounds like we have discussed four potential factors:

1. Concourse being deployed to GCP.
2. The target deployment being deployed to GCP.
3. The particulars of the load-balancing/traffic forwarding used to get traffic into the router.

## The MTU Thing
Concourse has [recently](http://concourse.ci/downloads.html#v251) had to make [some fixes](https://github.com/concourse/docker-image-resource/issues/67) to how MTU settings are propagated through containers to allow for Google's recommended settings. While their fixes are specific to fetching docker containers, it's interesting to note that the reason it was necessary appears to be that PMTUD (Path MTU Discovery) wasn't working for those fetches from inside the containers, and the default MTU is 1500.

This seems potentially relevant, especially to the extent that the problems are concentrated in tasks running inside garden containers in Concourse. This doesn't cover all our issues, but it covers many.

## Other Factors
The [story](https://www.pivotaltracker.com/n/projects/1158420/stories/136177031) @rosenhouse liked to discussed mass storage performance on GCP, and how SSD performance improves with greater size, but I don't understand how this might cause hung connections with the CLI, so I'm just mentioning it as another thing we're aware of.

## Current Investigation Plan

1. RelInt will deploy a Concourse worker to GCP and attempt to replicate the problem with the create/destroy loop Jason provided, targeting instances of `cf-deployment` running on both AWS and GCP.
  1. We'll also check what the MTU is in practice for Concourse tasks running in this configuration.

We'll see what we learn, and plot out further investigation from there.

**Comment by jtarchie** [comment]
@JesseTAlford, with @jaresty plan, we deployed using the `cf-gcp-infrastructure` and now have CATs passing consistently. Thanks! This solved our issues.

**Comment by JesseTAlford** [comment]
Just to get some end of thread clarity on this: what particular change was it that fixed your problem, if you know? What were you doing before that was different from Josh's description of our setup? A crisp answer may prove useful in the future.

**Comment by jasonkeene** [comment]
@JesseTAlford We were using forwarding rules for http, websockets, and ssh. We did this because websockets are not supported by global forwarding rules. It appears that switching regular http to use a global forwarding rule solved our issue.
