### ISSUE TITLE
How to create load balancer for Openstack

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/cf-deployment#273]
How to configure software load balancer for Openstack environment in case Openstack does not provide it's own load balancing service. "cf-release" based deployment uses "haproxy" for this. How to configure it for Openstack environment?

I have tried to include "https://github.com/cloudfoundry/cf-deployment/blob/master/operations/community/use-haproxy.yml" file during deployment but no luck.

Keepalive job under HAProxy instance gives me following error message for floating IP address.
   Could not autodetect interface to use for 10.xx.xx.xx. Cannot continue.

I have passed "haproxy_static_vip=10.xx.xx.xx as a floating IP address for "cf-deployment" deployment script.

It there any other alternative for HAProxy?

Thanks,
Prashant

**Comment by dsabeti** [comment]
Hi @prashantgnet, did you see [this part of the documentation](https://github.com/cloudfoundry/cf-deployment/tree/master/iaas-support/openstack#prepare-openstack-resources-for-bosh-and-cloud-foundry-via-terraform) for Openstack? It points to a [terraform module](https://github.com/cloudfoundry-incubator/bosh-openstack-environment-templates/tree/master/cf-deployment-tf) for creating IaaS load balancers. You should be able to use that.

I'll also cc @rkoster and @geofffranks, who help to maintain the haproxy ops-file, in case he wants to chime in with some help.

**Comment by prashantgnet** [comment]
Hi David,

I really need to create haproxy based load balancer, IaaS based LB is not possible to due to permissions.

It will be great if someone help me to create haproxy ops file, right now I am referring following file which gives me error message (Could not autodetect interface to use for 10.xx.xx.xx. Cannot continue) for floating IP address 

"https://github.com/cloudfoundry/cf-deployment/blob/master/operations/community/use-haproxy.yml"

Thanks,
Prashant

**Comment by geofffranks** [comment]
That error indicates the startup script was unable to find a network interface on a network corresponding for the VIP address. 

If there is an interface on that network, you can override it with the keepalived.interface property. If there isn't, you will either need to add a network to the instance group that contains the VIP, or pick a new VIP from the existing networks.

The Keepalived feature has not been tested on openstack, and has some networking requirements that may or may not be supported, which are discussed here:
https://github.com/cloudfoundry-incubator/haproxy-boshrelease/blob/master/docs/keepalived.md

**Comment by prashantgnet** [comment]
Thanks a lot Geoff for the updates, I will try it.

**Comment by prashantgnet** [comment]
It seems that keepalived property is applicable for multiple HAProxy instances. I am really looking for assigning floating IP address to single HAProxy instance which route traffic to multiple routers (default is 2 in cf-deployment), same like "cf-release" based environment.

Thanks,
Prashant

**Comment by geofffranks** [comment]
Ah, if you're just using one haproxy node, then I would just remove the keepalived process altogether, since  it isn't providing value in that situation.

**Comment by dsabeti** [comment]
Hi @prashantgnet. Do you still need help setting up your load balancer?

**Comment by prashantgnet** [comment]
Please close this.

Thanks a lot!
