### ISSUE TITLE
deploy-error with the latest cf-deployment

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-deployment#277]
With the cmd to deploy the latest cf-deployment:
bosh2 -n -e vbox upload-stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent \
&& bosh2 -n -e vbox update-cloud-config iaas-support/bosh-lite/cloud-config.yml \
&& bosh2 -n -e vbox -d cf deploy  cf-deployment.yml \
 -o operations/bosh-lite.yml \
 --vars-store deployment-vars.yml \
 -v system_domain=bosh-lite.com \
 -v cf_admin_password=admin \
 -v uaa_admin_client_secret=admin-secret

And got error as below:

Task 10 | 02:58:38 | Downloading remote release: Downloading remote release
Task 11 | 02:58:39 | Downloading remote release: Downloading remote release
Task 10 | 02:59:03 | Downloading remote release: Downloading remote release (00:00:25)
Task 10 | 02:59:03 | Verifying remote release: Verifying remote release (00:00:01)
                   L Error: Expected stream to have digest '7b99ebed8fcbf556e633452848002212ce707abb' but was '76a0794effdf5da82d067856721378c8475e6a6b'

Task 10 | 02:59:04 | Error: Expected stream to have digest '7b99ebed8fcbf556e633452848002212ce707abb' but was '76a0794effdf5da82d067856721378c8475e6a6b'

Task 10 Started  Fri Oct 13 02:58:38 UTC 2017
Task 10 Finished Fri Oct 13 02:59:04 UTC 2017
Task 10 Duration 00:00:26
Task 10 error

Task 12 | 02:59:04 | Downloading remote release: Downloading remote release
Task 11 | 03:00:08 | Downloading remote release: Downloading remote release (00:01:29)
Task 11 | 03:00:08 | Verifying remote release: Verifying remote release (00:00:01)
Task 11 | 03:00:09 | Extracting release: Extracting release (00:00:01)
Task 11 | 03:00:10 | Verifying manifest: Verifying manifest (00:00:00)
Task 11 | 03:00:10 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 11 | 03:00:10 | Creating new packages: acceptance-tests/189ff778417fad1d88a4fe7d3feb23443a12827995a03babf6e5ee1c6564f5ab (00:00:00)
Task 11 | 03:00:10 | Creating new packages: acceptance-tests-windows/e52fe9336690e5dd180d8d0ffba91aa39e233ee49ed06a3ebec89d7d75d68afb (00:00:01)
Task 11 | 03:00:11 | Creating new packages: confab/c03774794de30c7f51b51fb1059fd420f91870b30bfb6dfca4218bca376446a0 (00:00:00)
Task 11 | 03:00:11 | Creating new packages: confab-windows/63d0c11f6c71d97f448c5a04685bcfeef568a69634e5264492d0cdae2561d232 (00:00:00)
Task 11 | 03:00:11 | Creating new packages: consul/aa267a2e570e051b5b24b0029f8dc9ee3bccc443e4e6c8db7a90bbde04586054 (00:00:00)
Task 11 | 03:00:11 | Creating new packages: consul-windows/ed50fbfcfef13de31c13e68048861dd8b28b9eb7f55309745703704abb68ce7f (00:00:00)
Task 11 | 03:00:11 | Creating new packages: golang1.8/194ab685f34fa814e323815bc2397c93eb0c35df79150155f1f3f539ffc888f7 (00:00:02)
Task 11 | 03:00:13 | Creating new packages: golang1.8-windows/555eedb14aa9778e38101e67144a0f8c4d291e1038c56f0719bb7e9c021f9e4c (00:00:01)
Task 11 | 03:00:14 | Creating new jobs: acceptance-tests/70aca5b8a7f9890a33ccc66fe8576d090f5419cc02a4231c39e4ad99e3138da8 (00:00:00)
Task 11 | 03:00:14 | Creating new jobs: consul-test-consumer/683fd76e52f413cb97f759f8333baf7809a17afa340941b1ca7681de2566bbca (00:00:00)
Task 11 | 03:00:14 | Creating new jobs: consul-test-consumer-windows/21ba1939056dde71518892b518ad8ad3b4aeb082f882d46a09b9ec06f74a7b2b (00:00:00)
Task 11 | 03:00:14 | Creating new jobs: consul_agent/af671ae5b3f382da6b4d0087185526fe9140153a4b5c6521194e3da9d0693b97 (00:00:00)
Task 11 | 03:00:14 | Creating new jobs: consul_agent_windows/2b0d42fd447af40007d62fee6ee32736e291a73be4bc0473a17c5e1c43e06620 (00:00:00)
Task 11 | 03:00:14 | Creating new jobs: fake-dns-server/66c04aa3958499f7f3abe8455286e13a1e7e9818057f32494e61cd8e510991f7 (00:00:00)
Task 11 | 03:00:14 | Release has been created: consul/181 (00:00:00)
Task 13 timeout

Task 11 Started  Fri Oct 13 02:58:39 UTC 2017
Task 11 Finished Fri Oct 13 03:00:14 UTC 2017
Task 11 Duration 00:01:35
Task 11 done

Task 14 | 03:00:14 | Downloading remote release: Downloading remote release (00:00:02)
Task 14 | 03:00:16 | Verifying remote release: Verifying remote release (00:00:00)
Task 14 | 03:00:16 | Extracting release: Extracting release (00:00:00)
Task 14 | 03:00:16 | Verifying manifest: Verifying manifest (00:00:00)
Task 14 | 03:00:16 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 14 | 03:00:16 | Creating new packages: dotnet-core-buildpack/c4b3d60370734ef05bb03cc396f40ebde5477dff (00:00:00)
Task 14 | 03:00:16 | Creating new jobs: dotnet-core-buildpack/1ef120904474b6048cb9737fe6c2526ecb9f6ebf (00:00:00)
Task 14 | 03:00:16 | Release has been created: dotnet-core-buildpack/1.0.27 (00:00:00)

Task 14 Started  Fri Oct 13 03:00:14 UTC 2017
Task 14 Finished Fri Oct 13 03:00:16 UTC 2017
Task 14 Duration 00:00:02
Task 14 done

Task 12 | 03:00:47 | Downloading remote release: Downloading remote release (00:01:43)
Task 12 | 03:00:47 | Verifying remote release: Verifying remote release (00:00:01)
Task 12 | 03:00:48 | Extracting release: Extracting release (00:00:01)
Task 12 | 03:00:49 | Verifying manifest: Verifying manifest (00:00:00)
Task 12 | 03:00:49 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 12 | 03:00:49 | Creating new packages: cflinuxfs2/bf75b5c31c3bdb9d3fed45710c691c41ec99d61f (00:00:04)
Task 12 | 03:00:53 | Creating new jobs: cflinuxfs2-rootfs-setup/6007d0ebcf196c78fd2041c823e8c878e0347495 (00:00:00)
Task 12 | 03:00:53 | Creating new jobs: cflinuxfs2-smoke-test/c80072f7e26e5c8b3c184060ffc27e502c6be06b (00:00:00)
Task 12 | 03:00:53 | Release has been created: cflinuxfs2/1.160.0 (00:00:00)

Task 12 Started  Fri Oct 13 02:59:04 UTC 2017
Task 12 Finished Fri Oct 13 03:00:53 UTC 2017
Task 12 Duration 00:01:49
Task 12 done

Creating and uploading releases:
  Uploading release 'diego/1.27.0': Uploading remote release 'https://bosh.io/d/github.com/cloudfoundry/diego-release?v=1.27.0': Expected task '13' to succeed but state is 'timeout':
    Uploading release 'cf-networking/1.8.0':
      Uploading remote release 'https://bosh.io/d/github.com/cloudfoundry/cf-networking-release?v=1.8.0':
        Expected task '10' to succeed but state is 'error'

Exit code 1

**Comment by dsabeti** [comment]
Hey @qibobo. Try the latest version (0.32.1) -- that should fix this issue.
