### ISSUE TITLE
deploy cf error with xtrabackup compilation timeout.

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-deployment#281]
Task 114 | 09:04:15 | Preparing deployment: Preparing deployment (00:00:02)
Task 114 | 09:04:20 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 114 | 09:04:21 | Compiling packages: xtrabackup/fcf33355eec22b871179cf31e7e096723c9d3354

Task 114 Started  Tue Oct 17 09:04:15 UTC 2017
Task 114 Finished Tue Oct 17 09:04:21 UTC 2017
Task 114 Duration 00:00:06
Task 114 timeout

Updating deployment:
  Expected task '114' to succeed but state is 'timeout'

Exit code 1

**Comment by dsabeti** [comment]
Hey @qibobo. Try running `bosh task 114 --debug` for more information.

**Comment by qibobo** [comment]
@dsabeti  Recreate my bosh-lite and it deployed successfully now.
