### ISSUE TITLE
name change for "cf-internet-required" and "cf-internet-not-required"

### ISSUE THREAD

**Issue by christianang** [cloudfoundry/cf-deployment#30]
We are thinking of adding these two vm_extensions to the cloud config that bbl generates however, we would like to make them non-cf specific. We'd like to propose the name change to "internet-required" and "internet-not-required".

-Christian and @kkallday

**Comment by dsabeti** [comment]
@christianang Sounds reasonable. Thanks for the heads up. Would you mind pinging me once you guys make the change so we can make the according changes in cf-deployment?

**Comment by christianang** [comment]
@dsabeti the current release of bosh-bootloader now generates a cloud config with both `internet-{not,}-required` and `cf-internet-{not,}-required`.

Whenever you update cf-deployment to use `internet-{not,}-required` we will remove the `cf` prefixed vm extensions from bbl.

Thanks,
Christian

**Comment by dsabeti** [comment]
@christianang We've updated cf-deployment to use the new vm_extension names.
