### ISSUE TITLE
bosh-dns breaks when you change vm names

### ISSUE THREAD

**Issue by charleshansen** [cloudfoundry/cf-deployment#302]
I know the bosh-dns ops file is experimental, but I wanted to file the issue in case other people are using it.

Whenever you change a vm name (like renaming `mysql` to `singleton-database`), the bosh-dns aliases need to be updated, or everything breaks. In the `singleton-database` example, I added a line in my bosh-dns aliases:
```yml
sql-db.service.cf.internal:
   - '*.mysql.default.cf.bosh'
   - '*.postgres.default.cf.bosh'
   - '*.singleton-database.default.cf.bosh'  #this is the new line
```
This fixed my deployment (after I added a similar line for `singleton-blobstore`).

**Comment by dsabeti** [comment]
Thanks for raising this @charleshansen. It was already reported to us on Slack and we wrote this bug to capture the problem: https://www.pivotaltracker.com/story/show/152285466

I'll leave a note for myself to close this issue when I accept that story.

**Comment by dsabeti** [comment]
Hey @charleshansen This should be fix on release-candidate now. We're going to try to cut a master very soon.
