### ISSUE TITLE
Diego Rep uses metron's TLS properties

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/cf-deployment#310]
Looking at how Diego's rep configures itself to speak with Loggregator's metron, it looks like diego is using metron's cert/key instead of their own.

https://github.com/cloudfoundry/cf-deployment/blob/b21cdc72b659f85a007d1f18f801ede6c42aa39c/cf-deployment.yml#L302-L304

**Comment by dsabeti** [comment]
Hey @apoydence, it depends on the implementation,  I think. If this is **mutual** TLS, then it seems like there should be dedicated client and server certificates -- `metron_servier_cert` and metron_client_cert`, for example.

If, however, the TLS is "one way" -- only the server has a certificate and the client need not authenticate -- then it seems reasonable that the rep would want to know which certificate and CA to validate. However, it does seem weird in that case that the rep would be configured with the metron private key.

@ematpl, do you have any thoughts on this?

**Comment by bradylove** [comment]
@dsabeti This is mutual TLS from the rep to metron.

**Comment by emalm** [comment]
@dsabeti That's fine with me if there's a separate client cert for the reps to use for the sake of propriety, so long as everything still works.

**Comment by apoydence** [comment]
@dsabeti It looks like most teams provide their certs via bosh links.

Loggregator had an issue where a user was requesting we do so as well (cloudfoundry/loggregator-release#334) where @cppforlife weighed in.

I realize this is a different approach, but it might be worth doing it that way instead of shaking things up multiple times.

**Comment by dsabeti** [comment]
It sounds like we're not feeling this change anymore, so I'll just close the issue.
