### ISSUE TITLE
update to bosh-dns 0.0.11

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cf-deployment#317]
@dsabeti rolled out to pws today and saw large improvement in cpu usage.

**Comment by dsabeti** [comment]
It's already on RC: https://github.com/cloudfoundry/cf-deployment/blob/release-candidate/operations/experimental/use-bosh-dns.yml#L210

I'll probably cut another cf-deployment tomorrow.

**Comment by cppforlife** [comment]
oh great.
