### ISSUE TITLE
Incompatible version of loggregator and cf-syslog-drain in v0.35.0

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/cf-deployment#321]
Version 3 of `cf-syslog-drain-release` is not compatible with `loggregator` v99.

The simple fix is to set `cf-syslog-drain-release` to v2.

https://github.com/cloudfoundry/cf-deployment/blob/v0.35.0/cf-deployment.yml#L1612-L1614

Note `cf-syslog-drain-release` v3 depends on `loggregator` v101 or higher.

/cc @bradylove

**Comment by dsabeti** [comment]
Thanks @enocom. I just cut v0.36.0, which uses cf-syslog-drain-release v2.

**Comment by JohannaSmith** [comment]
@dsabeti we'd going to verify v0.36.0 with syslog v2 today and get back to you.

/cc @apoydence

**Comment by JohannaSmith** [comment]
@dsabeti confirmed that the combination of releases in v0.36.0 is safe.

**Comment by dsabeti** [comment]
Thanks all. I'll go ahead and close this issue.
