### ISSUE TITLE
L Error: Stemcell version '3468.1' for OS 'ubuntu-trusty' doesn't exist

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/cf-deployment#323]

**Comment by dsabeti** [comment]
@qibobo Have you uploaded the appropriate stemcell to your director?

https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md#upload-a-stemcell

**Comment by qibobo** [comment]
@dsabeti  I can upload the the stemcell. But shouldn't it use the latest stemcell?

**Comment by dsabeti** [comment]
Not until it's been tested in our pipelines. If you look at the [develop branch](https://github.com/cloudfoundry/cf-deployment/blob/develop/cf-deployment.yml#L1677-L1680), you'll see that it does include the latest stemcell version. Once it goes through our testing pipelines, it gets promoted to `release-candidate`, and then roughly twice a week I promote it manually to `master`.

If you want to jump ahead of what's tested, you can always use [this ops-file](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-latest-stemcell.yml).
