### ISSUE TITLE
Failed to deploy cf with powerdns due to the order of haproxy

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/cf-deployment#327]
I used to deploy cf but it returned an error during updating haproxy vm and monit log like below:
```
[ALERT] 315/130818 (15864) : parsing [/var/vcap/jobs/haproxy/config/haproxy.config:96] : 'server node0' : invalid address: '0d33eed1-ccfa-4ea1-9602-fc76a181ce88.router.default.automation-cf.bosh' in '0d33eed1-ccfa-4ea1-9602-fc76a181ce88.router.default.automation-cf.bosh:80'

[ALERT] 315/130818 (15864) : parsing [/var/vcap/jobs/haproxy/config/haproxy.config:117] : 'server node0' : invalid address: 'e8e0c16e-8cfc-4bec-ab9e-615dd476576d.diego-brain.default.automation-cf.bosh' in 'e8e0c16e-8cfc-4bec-ab9e-615dd476576d.diego-brain.default.automation-cf.bosh:2222'

[ALERT] 315/130818 (15864) : Error(s) found in configuration file : /var/vcap/jobs/haproxy/config/haproxy.config
[WARNING] 315/130818 (15864) : parsing [/var/vcap/jobs/haproxy/config/haproxy.config:23] : 'option httplog' not usable with frontend 'tcp-frontend_diego-brain' (needs 'mode http'). Falling back to 'option tcplog'.
[WARNING] 315/130818 (15864) : config : 'option forwardfor' ignored for frontend 'tcp-frontend_diego-brain' as it requires HTTP mode.
[WARNING] 315/130818 (15864) : config : 'option forwardfor' ignored for backend 'tcp-diego-brain' as it requires HTTP mode.
[ALERT] 315/130818 (15864) : Fatal errors found in configuration.
+ RETVAL=1
```

In my deployment, CF use powerdns to resolve DNS record. So these address like `*.router.default.automation-cf.bosh` did not work before relative VM finish updating jobs.

And I read `operations/community/use-haproxy.yml` operation file(https://github.com/cloudfoundry/cf-deployment/blob/master/operations/community/use-haproxy.yml#L9-L12), we replaced the first VM of `smoke-test` by `haproxy`'s. So I had to modify the file by placing haproxy as the last VM and it worked.

That is my question, Why we should place haproxy as the first VM? It could not work well with powerdns.

**Comment by dsabeti** [comment]
Hi @EdwardStudy. Let's get some help from @geofffranks and @rkoster, who help to maintain the [haproxy-boshrelease](https://github.com/cloudfoundry-incubator/haproxy-boshrelease).

**Comment by geofffranks** [comment]
IIRC, placing haproxy at the end of the instance groups list will break initial deploys of CF, as haproxy is supposed to be the incoming endpoint of traffic before it hits gorouters. If those servers aren't deployed until the end, anything trying to hit cloud controller, or other components will fail to start up properly.

Seems like haproxy needs to be started after powerdns is configured, but before as many other components as possible, right?

**Comment by EdwardStudy** [comment]
@geofffranks Should I place haproxy after these VMs(router, diego-brain)? Could you please tell the correct order?

Thank you.

**Comment by geofffranks** [comment]
I would guess a serial job after the routers would work, if powerdns is the bosh DNS system requiring the vms to be alive to resolve. @dsabeti might have a better idea of where to place them after the router but before other deps.

**Comment by dsabeti** [comment]
I think it makes sense to deploy the HAProxy immediately after the router. Clearly, the HAProxy has a dependency on the router, so router needs to come up first. However, as @geofffranks suggested, waiting too long (for example, at the end of the deployment) may cause problems where the HAProxy doesn't get the new configuration quickly enough, which could result in route unavailability.

I'd say try to deploy the HAProxy immediately after the router and see how it goes. 

You can update the ops-file like this:
```
- type: replace
  path: /instance_groups/name=router:after
  value:
    ...
```
Notice the `:after` keyword, which tells BOSH to place the new instance group after the instance group called `router`.

**Comment by dsabeti** [comment]
Hey @EdwardStudy, sorry not to follow up in some time. Did you try out the solution above? Any luck?

**Comment by EdwardStudy** [comment]
@dsabeti Sorry. I did not try it. I thought your suggestion may work. I will try it.

**Comment by dsabeti** [comment]
Hi @edwardstudy. I'm going to closet his issue due to inactivity, but feel free to reopen it if you need more help.
