### ISSUE TITLE
CF deployment on BOSH-Lite should not create privileged containers

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/cf-deployment#329]
The configuration at https://github.com/cloudfoundry/cf-deployment/blob/v0.37.0/operations/bosh-lite.yml#L9-L19 was introduced in https://www.pivotaltracker.com/story/show/145314731, but the evidence in support of it is circumstantial at best. This configuration is currently strongly discouraged from a security point of view. It is also a significant difference in configuration from non-BOSH-Lite deployments, which can be confusing when conducting integration tests or explorations such as https://www.pivotaltracker.com/story/show/152645865 on BOSH-Lite. (See https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1510604497000237 and https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1506618248000216 for additional context from the cf-deployment Slack channel.)

/cc @jvshahid

**Comment by dsabeti** [comment]
@emalm, we've addressed this issue in this commit:
https://github.com/cloudfoundry/cf-deployment/commit/e9bda06bc9f47b3fd996c60494a7502d3811a4ee
