### ISSUE TITLE
certificate error on bosh-lite deployment 

### ISSUE THREAD

**Issue by amitoj** [cloudfoundry/cf-deployment#33]
Hi,

So I tried following command with bosh v2, as mentioned in README
`AH-MacBook-Pro:cf-deployment$ bosh -e lite update-cloud-config bosh-lite/cloud-config.yml`

I'm get the following error message

> Updating cloud config:
>   Performing request POST 'https://lite:25555/cloud_configs':
>     Performing POST request:
>       Post https://lite:25555/cloud_configs: x509: certificate is valid for *.sslip.io, not lite
> 
> Exit code 1

Somewhere I read that I should be using www-192-168-50-4.sslip.io instead of lite (which is mapped to 192.168.50.4 in my /etc/hosts), but then i get

> Updating cloud config:
>   Performing request POST 'https://www-192-168-50-4.sslip.io:25555/cloud_configs':
>     Performing POST request:
>       Post https://www-192-168-50-4.sslip.io:25555/cloud_configs: x509: certificate signed by unknown authority
> 
> Exit code 1

Help appreciated.

Best Regards

**Comment by JesseTAlford** [comment]
Hey @amitoj, I have a couple of questions to help me get you up and running. First, what's the result of `bosh envs`?

Second, where did your bosh-lite come from? Is it the result of a vagrant up with the standard bosh-lite box, or did you do something else?

**Comment by amitoj** [comment]
Hi @JesseTAlford

The output of  `bosh envs`
> URL  Alias
> 
> 0 environments 
> 
> Succeeded

And bosh-lite is downloaded from `https://github.com/cloudfoundry/bosh-lite`
It's a simple `vagrant up` box.

Versions
> bosh-lite 9000.131.0
> vagrant 1.9.0
> Virtualbox 5.1.10
> OS X El Capitan
> bosh 0.0.139-40f043d-2016-12-17T02:38:50Z

**Comment by jaresty** [comment]
Hi @amitoj,

You uncovered a problem with our README -- thank you!  We have added to and updated the steps for targeting your bosh-lite to address the problems you ran into.  Please see [this changeset](https://github.com/cloudfoundry/cf-deployment/commit/287e5adcf30c42f4dfe069b5dadb87663e5d84e0) and I expect you will be able to get it working.  Let us know if you still run into problems.

Thanks,
@jaresty && @staylor14

**Comment by amitoj** [comment]
Hi @jaresty, @staylor14 & @JesseTAlford 

It's working ok now, managed to create a bosh-lite cf-deployment environment to understand the diego environment.

Thanks and Happy New Year
