### ISSUE TITLE
create_vm CPI method not supported

### ISSUE THREAD

**Issue by varun7447** [cloudfoundry/cf-deployment#338]
For some reason when i try to run the 

`bosh -d cf deploy`     

i see below error with the latest cf-deployment package              

` L Error: Unknown CPI error 'Unknown' with message 'The requested configuration is currently not supported. Please check the documentation for supported configurations.' in 'create_vm' CPI method
`

**Comment by ishustava** [comment]
@varun7447 

This issue feels more appropriate in the corresponding BOSH CPI repository (AWS CPI can be found [here](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release)). CF deployment only references instance type names from cloud config, so there is not much we can do to help with the issue you are seeing.

Is it ok to close this for now?

**Comment by varun7447** [comment]
Sure, we can close this for now..
