### ISSUE TITLE
Deploy on OpenStack without Iaas load balancer

### ISSUE THREAD

**Issue by fluppirt** [cloudfoundry/cf-deployment#339]
Hello everybody,

i'm trying to deploy CF on OpenStack and ran into an error:

`Creating missing vms: router/54555613-bdc7-438b-97e6-b855ba1c1270 (0) (00:00:23)
Error: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API service not found error: Expected(200) <=> Actual(404 Not Found)
excon.error.response
  :body          => "404 Not Found\n\nThe resource could not be found.\n\n   "
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "52"
    "Content-Type"           => "text/plain; charset=UTF-8"
    "Date"                   => "Wed, 22 Nov 2017 20:52:28 GMT"
    "X-Openstack-Request-Id" => "req-6b5871e8-bcc4-4a0e-a231-49c31931ea1b"
  }
  :host          => "134.103.195.11"
  :local_address => "192.168.1.6"
  :local_port    => 60534
  :path          => "/v2.0/lbaas/pools"
  :port          => 9696
  :reason_phrase => "Not Found"
  :remote_ip     => "134.103.195.11"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"

Check task debug log for details.' in 'create_vm' CPI method`

I guess this happens due to the fact that my openstack environment is not configured with a load balancer.
I've tried the to add the ops-file "use-haproxy.yml", but this didn't help.

Since i'm completely new to CF, i'm not sure how to solve this problem. 
Has anyone a hint how to handle this?

**Comment by dsabeti** [comment]
Hey @fluppirt. [This vm_extension](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L886-L887) is the part of the deployment manifest that tells BOSH to connect the `rotuer` VMs to a load balancer. If you remove it, BOSH should probably be able to create the VM. You'll probably also want to remove the [vm_extension for connecting the ssh proxy](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L966-L967) to a load balancer as well.

However, you still need to connect the router to a load balancer. Let's pull in the maintainers of that ops-file to see if they can help us get haproxy hooked up right. @geofffranks, should `use-haproxy.yml` remove that vm_extension of the routers?

**Comment by dsabeti** [comment]
Hey everyone, the [newer ops-file for deploying HAProxy](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-haproxy.yml#L8-L13) removes those vm_extensions, so I'm going to go ahead and close out this issue.
