### ISSUE TITLE
Inconsistent use of hyphens and underscores in instance-group names

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry/cf-deployment#34]
The names of the instance groups in the cf-deployment.yml manifest are not using separators consistently. Some jobs use hyphens (`diego-bbs`, `diego-brain`,`diego-cell`, `route-emitter`, `tcp-router`) while some use underscores (`cc_bridge`, `cc_clock`, `log_controller`). My own preference is for the hyphen to be the separator, but underscore is used more frequently (but not universally) in the job template names and properties.

Thanks,
Eric

**Comment by JesseTAlford** [comment]
Yeah, it's inconsistent and that's irritating. We should fix it, and then have a style-guide.

The dash-vs_underscore thing is painful throughout our yaml-ruled world. As far as I know, we've achieved no alignment on any heuristics around this.

**Comment by dsabeti** [comment]
Hey @ematpl I think you're totally right and we should go with hyphens over underscores. I think there are only three uses of underscores for instance group names: `cc_bridge`, `cc_clock`, and `log_controller`. There a plan for each of these:
- `log_controller`. This will be renamed to `log-api` in this story https://www.pivotaltracker.com/story/show/133871155
- `cc_clock`. We can rename this, but it looks like there's a change to make cc_clock HA: https://www.pivotaltracker.com/n/projects/966314/stories/136621261. As a result, we can just colocate the job with the `api` job and lose a VM in the process. Here's a story for that: https://www.pivotaltracker.com/story/show/137050345
- `cc_bridge`. Also, we could rename this to `cc-bridge`, but I wonder if maybe it's better to just start putting in the work to remove the bridge entirely now the CC supports talking to BBS directly. I'll try to write up some stories soon and link to them here.

**Comment by ematpl** [comment]
Thanks, @dsabeti, sounds good! I'm not sure if the de-bridging work is completely ready yet, but I too would like to see us eliminate that VM soon.

**Comment by ematpl** [comment]
With those existing stories and the assumption that we'll be totally de-bridged at some point, I'll close this issue.
