### ISSUE TITLE
aws deployment error grpc: addrConn.resetTransport failed to create client transport

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/cf-deployment#340]
hi is any one deploy cf-deployment on aws, i am trying to deploy but i encounter this rep error in diego cell. 
I created cloud-config for aws deployment 
[cloud-config.txt](https://github.com/cloudfoundry/cf-deployment/files/1500369/cloud-config.txt)

i enclosed log files and security screenshorts for your reference. 
<img width="1137" alt="inbond-rules" src="https://user-images.githubusercontent.com/10971841/33191485-0c32ddfe-d0fd-11e7-96ee-8846e65880de.png">
<img width="1151" alt="outbond-rules" src="https://user-images.githubusercontent.com/10971841/33191486-0de3325c-d0fd-11e7-8456-841833a3d6d1.png">
[rep.stdout.log](https://github.com/cloudfoundry/cf-deployment/files/1500376/rep.stdout.log)
[rep.stderr.log](https://github.com/cloudfoundry/cf-deployment/files/1500377/rep.stderr.log)

thanks in advance

**Comment by selzoc** [comment]
Hello,

Looking at your cloud config, I notice it doesn't have all of the required `vm_extension`s as listed https://github.com/cloudfoundry/cf-deployment/blob/master/texts/on-cloud-configs.md#vm-extensions.  The error you see in `rep.stderr.log` is unrelated.

We generally recommend the use of [bbl](https://github.com/cloudfoundry/bosh-bootloader) for IaaS setup, which will generate the correct cloud config.  Here is our [deployment guide](https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md).

Please let us know if you have any further questions!

**Comment by abhilash07** [comment]
Hello @selzoc 
thanks for your information and quick response i will test and let you know. 

Thanks

**Comment by selzoc** [comment]
Great! going to close this issue, please feel free to re-open if you have further problems.  Also don't hesitate to reach out to us on [slack](https://cloudfoundry.slack.com) in the `#cf-deployment` channel for more interactive troubleshooting help.
