### ISSUE TITLE
hwc_buildpack not automatically updated

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/cf-deployment#343]
The `hwc-buildpack-release` seems to not be getting auto bumped in the `windows-cell.yml` opsfile.

The current version is [`v2.3.11`](https://github.com/cloudfoundry/hwc-buildpack/releases/tag/v2.3.11) and the version in the opsfile is [`v2.3.9`](https://github.com/cloudfoundry/cf-deployment/blob/dae9a7dc732872febb5f40178ae5feaffa4b2d8d/operations/windows-cell.yml#L146-L152)

**Comment by dsabeti** [comment]
Hey @sunjayBhatia, good catch. It looks like there's a bug in our pipeline. We have a resource for the `hwc-buildpack-release`, and it even has version v2.3.11. However, the job that updates the ops-file seems to be holding it to v2.3.9.

I'll prioritize this issue as a bug to address the problem.

**Comment by sunjayBhatia** [comment]
@dsabeti thanks!

**Comment by selzoc** [comment]
@sunjayBhatia thanks!  this is fixed and the latest release of the buildpack is now wending its way through our pipeline on the way to master.

**Comment by ishustava** [comment]
Closing this issue because we now bump hwc-buildpack automatically.
