### ISSUE TITLE
BOSH LITE cloud foundry deployment fails during compiling packages

### ISSUE THREAD

**Issue by dawg2k** [cloudfoundry/cf-deployment#345]
Updating deployment:
     Expected task '38' to succeed but state is 'timeout'
Exit code 1

bosh task 38 --debug
Expected non-empty Director URL
Exit Code 1

bosh -e vbox env
Using environment '192.168.50.6' as client 'admin'

Name        Bosh Lite Director
UUID         xxx

**Comment by dsabeti** [comment]
Hi @dawg2k. 

You can circumvent this problem by using pre-compiled releases. Deploy with the following command:
```
bosh -e vbox deploy cf-deployment.yml -o operations/use-compiled-releases.yml ...
```

It will skip the entire compilation stage and make your deployment go much more quickly.

And, for future reference, this error
```
Expected non-empty Director URL
Exit Code 1
```
indicates that your CLI isn't configured to target your BOSH director. To run any command, you'll either need to provide the `-e vbox` flag, or set the `BOSH_ENVIRONMENT` variable.

**Comment by dawg2k** [comment]
Thanks..I will try pre-compiled release.

The BOSH Director was targetgeted. I had posted earlier that when I use following command
bosh -e vbox env

It shows the Director targeted.

Not sure why it keeps complaining about not seeing Director.

**Comment by dsabeti** [comment]
@dawg2k. The reason `bosh -e vbox env` shows a targeted director is because you provided `-e vbox` in the command. Without the `-e` flag, the BOSH CLI doesn't target a director.  When you ran `bosh task 38 --debug`, you did not provide the `-e` flag, so the CLI wasn't targeting a director during that command.

**Comment by dawg2k** [comment]
Thanks. Now I can see the error. The task failed again. Below is what I see in debug logs.

D, [2017-11-30T18:33:01 #333291] [task:49] DEBUG -- DirectorJobRunner: (0.000268s) SELECT * FROM "tasks" WHERE ("id" = 49) LIMIT 1
D, [2017-11-30T18:33:01 #333291] [task:49] DEBUG -- DirectorJobRunner: (0.000102s) BEGIN
D, [2017-11-30T18:33:01 #333291] [task:49] DEBUG -- DirectorJobRunner: (0.000304s) UPDATE "tasks" SET "state" = 'cancelled', "timestamp" = '2017-11-30 18:33:01.267657+0000', "description" = 'create deployment', "result" = 'task cancelled', "output" = '/var/vcap/store/director/tasks/49', "checkpoint_time" = '2017-11-30 18:29:53.095228+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'cf', "started_at" = '2017-11-30 18:20:47.709410+0000', "event_output" = '{"time":1512066047,"stage":"Preparing deployment","tags":[],"total":1,"task":"Preparing deployment","index":1,"state":"started","progress":0}
{"time":1512066053,"stage":"Preparing deployment","tags":[],"total":1,"task":"Preparing deployment","index":1,"state":"finished","progress":100}
{"time":1512066057,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Finding packages to compile","index":1,"state":"started","progress":0}
{"time":1512066057,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Finding packages to compile","index":1,"state":"finished","progress":100}
{"time":1512066057,"stage":"Compiling packages","tags":[],"total":4,"task":"cloud_controller_ng/21328ea17ab95d15edefc67a8d533766ea408e9b31cecbd881cd0246df5f3e66","index":1,"state":"started","progress":0}
{"time":1512066057,"stage":"Compiling packages","tags":[],"total":4,"task":"galera/d531f7bb00dd53ab1ebc2e1a42b7db8c7a14ef03","index":2,"state":"started","progress":0}
{"time":1512066464,"stage":"Compiling packages","tags":[],"total":4,"task":"cloud_controller_ng/21328ea17ab95d15edefc67a8d533766ea408e9b31cecbd881cd0246df5f3e66","index":1,"state":"finished","progress":100}
{"time":1512066573,"stage":"Compiling packages","tags":[],"total":4,"task":"galera/d531f7bb00dd53ab1ebc2e1a42b7db8c7a14ef03","index":2,"state":"finished","progress":100}
{"time":1512066573,"stage":"Compiling packages","tags":[],"total":4,"task":"mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23","index":3,"state":"started","progress":0}
{"time":1512066780,"stage":"Compiling packages","tags":[],"total":4,"task":"mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23","index":3,"state":"failed","progress":100,"data":{"error":"Task 49 cancelled"}}
{"time":1512066781,"error":{"code":10001,"message":"Task 49 cancelled"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 49)
D, [2017-11-30T18:33:01 #333291] [task:49] DEBUG -- DirectorJobRunner: (0.000800s) COMMIT
I, [2017-11-30T18:33:01 #333291] []  INFO -- DirectorJobRunner: Task took 12 minutes 13.563174447000051 seconds to process.

Task 49 cancelled

Capturing task '49' output:
  Expected task '49' to succeed but state is 'cancelled'

Exit code 1

**Comment by dsabeti** [comment]
@dawg2k, the output seems to suggest that you cancelled the task. Did you run `bosh cancel-task`?

**Comment by dawg2k** [comment]
No. It cancelled or timed out on it's own.

**Comment by dawg2k** [comment]
it's doing the same (timing out on compilation) if I restart my deployment by running the deployment command again below. 

bosh -e vbox -d cf deploy cf-deployment.yml   -o operations/bosh-lite.yml   --vars-store deployment-vars.yml   -v system_domain=bosh-lite.com

Can I increase the timeout value for compilation?.

If not, I will try the compiled packages option you suggested earlier.

D, [2017-11-30T18:59:54 #354010] [] DEBUG -- DirectorJobRunner: RECEIVED: director.54b4be23-a86f-4843-99f9-7b7269964894.f28544fc-83bc-4200-ba26-93497f0ec624.dc3c0e55-967f-4407-885c-81b21f4d6c1b {"value":{"agent_task_id":"0c163ed2-fe6a-498e-6cb8-6627d2f193f9","state":"running"}}
D, [2017-11-30T19:00:02 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000629s) SELECT * FROM "tasks" WHERE "id" = 50
D, [2017-11-30T19:00:03 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: SENT: agent.f28544fc-83bc-4200-ba26-93497f0ec624 {"protocol":3,"method":"get_task","arguments":["0c163ed2-fe6a-498e-6cb8-6627d2f193f9"],"reply_to":"director.54b4be23-a86f-4843-99f9-7b7269964894.f28544fc-83bc-4200-ba26-93497f0ec624.0e4d8b28-48f2-44ca-9144-c562ff1329e4"}
D, [2017-11-30T19:00:08 #354010] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
D, [2017-11-30T19:00:13 #354010] [task:50-checkpoint] DEBUG -- DirectorJobRunner: (0.000441s) BEGIN
D, [2017-11-30T19:08:08 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: SENT: agent.f28544fc-83bc-4200-ba26-93497f0ec624 {"protocol":3,"method":"get_task","arguments":["0c163ed2-fe6a-498e-6cb8-6627d2f193f9"],"reply_to":"director.54b4be23-a86f-4843-99f9-7b7269964894.f28544fc-83bc-4200-ba26-93497f0ec624.e47e4b86-3eac-4e11-ba47-c8ba0e63ba0e"}
D, [2017-11-30T19:08:08 #354010] [] DEBUG -- DirectorJobRunner: RECEIVED: director.54b4be23-a86f-4843-99f9-7b7269964894.f28544fc-83bc-4200-ba26-93497f0ec624.e47e4b86-3eac-4e11-ba47-c8ba0e63ba0e {"value":{"agent_task_id":"0c163ed2-fe6a-498e-6cb8-6627d2f193f9","state":"running"}}
D, [2017-11-30T19:08:08 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000531s) SELECT * FROM "tasks" WHERE "id" = 50
D, [2017-11-30T19:08:09 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: SENT: agent.f28544fc-83bc-4200-ba26-93497f0ec624 {"protocol":3,"method":"get_task","arguments":["0c163ed2-fe6a-498e-6cb8-6627d2f193f9"],"reply_to":"director.54b4be23-a86f-4843-99f9-7b7269964894.f28544fc-83bc-4200-ba26-93497f0ec624.d4e6addd-ee6a-4d45-bec3-5ca2b5353efb"}
D, [2017-11-30T19:08:14 #354010] [task:50-checkpoint] DEBUG -- DirectorJobRunner: (5.382384s) UPDATE "tasks" SET "checkpoint_time" = '2017-11-30 19:00:13.029252+0000' WHERE ("id" = 50)
D, [2017-11-30T19:08:15 #354010] [] DEBUG -- DirectorJobRunner: RECEIVED: director.54b4be23-a86f-4843-99f9-7b7269964894.f28544fc-83bc-4200-ba26-93497f0ec624.d4e6addd-ee6a-4d45-bec3-5ca2b5353efb {"value":{"agent_task_id":"0c163ed2-fe6a-498e-6cb8-6627d2f193f9","state":"running"}}
D, [2017-11-30T19:08:15 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000657s) SELECT * FROM "tasks" WHERE "id" = 50
D, [2017-11-30T19:08:15 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000438s) BEGIN
D, [2017-11-30T19:08:15 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000612s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2017-11-30 19:08:15.335392+0000', 'admin', 'delete', 'instance', 'compilation-cab71888-e7e8-4135-bf27-b4f338605895/a159a552-94c9-48d5-806f-6ab802dc20ec', NULL, '50', 'cf', 'compilation-cab71888-e7e8-4135-bf27-b4f338605895/a159a552-94c9-48d5-806f-6ab802dc20ec', '{}') RETURNING *
D, [2017-11-30T19:08:15 #354010] [] DEBUG -- DirectorJobRunner: (6.707954s) UPDATE "locks" SET "expired_at" = '2017-11-30 19:12:09.698087+0000' WHERE (("name" = 'lock:deployment:cf') AND ("uid" = '6c8e5ff1-c05e-438e-904b-5c0350193146'))
D, [2017-11-30T19:08:16 #354010] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:compile:51:ubuntu-trusty/3468.11
D, [2017-11-30T19:08:28 #354010] [task:50-checkpoint] DEBUG -- DirectorJobRunner: (13.278078s) COMMIT
D, [2017-11-30T19:08:28 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (13.268643s) COMMIT
D, [2017-11-30T19:08:29 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000521s) SELECT * FROM "vms" WHERE (("instance_id" = 61) AND ("active" IS TRUE)) LIMIT 1
D, [2017-11-30T19:08:29 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000544s) SELECT * FROM "vms" WHERE (("instance_id" = 61) AND ("active" IS TRUE)) LIMIT 1
D, [2017-11-30T19:08:29 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000110s) BEGIN
D, [2017-11-30T19:08:29 #354010] [compile_package(mariadb/7ceb7566bb515253a73bade5df4b1aa2d16a1e23, bosh-warden-boshlite-ubuntu-trusty-go_agent/3468.11)] DEBUG -- DirectorJobRunner: (0.000363s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2017-11-30 19:08:29.329767+0000', 'admin', 'delete', 'vm', '5778990b-ad9c-43ea-6baf-ab840d205d49', NULL, '50', 'cf', 'compilation-cab71888-e7e8-4135-bf27-b4f338605895/a159a552-94c9-48d5-806f-6ab802dc20ec', '{}') RETURNING *

Task 50 timeout

Capturing task '50' output:
  Expected task '50' to succeed but state is 'timeout'

Exit code 1

**Comment by dsabeti** [comment]
@dawg2k The latest logs don't include any information about there error. I'm not sure we actually need the debug logs, though. Could you just provide the full stdout/stderr output of the `bosh deploy` command? That should give us a starting to point to debug.

**Comment by dsabeti** [comment]
Hey @dawg2k, I'm going to close this issue due to inactivity, but feel free to re-open if you need more help.
