### ISSUE TITLE
Why is the adapter being advertised as doppler.service.cf.internal?

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/cf-deployment#347]
I think this might be a copy/paste issue, I can't think of why the adapter instances would be advertised as doppler:

https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L130-L134

**Comment by dsabeti** [comment]
@amhuber, that does indeed look like a copy/paste issue.

@ahevenor @JohannaSmith, does the adapter need consul on it at all?

**Comment by bradylove** [comment]
@amhuber @dsabeti 

That looks like a copy paste failure. The adapter's consul should not advertise as it only consumes DNS from consul.

**Comment by selzoc** [comment]
@amhuber thanks for pointing this out!  This is now fixed in https://github.com/cloudfoundry/cf-deployment/commit/aa195c59c55e53c464bf17b2f5215cdb529fa06e and will be in a release shortly.
