### ISSUE TITLE
Unnecessary duplication of vm_extensions in gcp.yml override 

### ISSUE THREAD

**Issue by drich10** [cloudfoundry/cf-deployment#36]
Currently there is duplication in the `gcp.yml` override file for vm_extensions (one example here https://github.com/cloudfoundry/cf-deployment/blob/08eb7683daa66b350e1b9a43ebc833e77ef2c476/opsfiles/gcp.yml#L20). This could instead take the form of an append function. It would make the file smaller and reduce the chance for error if the list of shared extension names were to change.

-Derek

**Comment by dsabeti** [comment]
Thanks @drich10, I've prioritized the story.

**Comment by dsabeti** [comment]
This story was accepted so I'm closing the story.
