### ISSUE TITLE
Help pkıx path bulding failed sun security provider cert path sun cert  path builder

### ISSUE THREAD

**Issue by hickimse** [cloudfoundry/cf-deployment#360]
Hi I am getting such an error what is the solution. N
![tmbot](https://user-images.githubusercontent.com/34642575/34094280-9589e230-e3dd-11e7-8bfd-85a6589b747c.jpg)
o connection to web sun security validator validator exception pkıx path bulding failed sun security provider cert path sun cert  path builder exception unable to find valid certification path to requested target

**Comment by dsabeti** [comment]
Hi @hickimse, this request looks like it's for the wrong repo. I'm going to close the issue, but feel free to open a new issue if you have a question about deploying Cloud Foundry using cf-deployment and BOSH.
