### ISSUE TITLE
Please, add adapter to rename-network.yml ops file

### ISSUE THREAD

**Issue by Ykisialiou** [cloudfoundry/cf-deployment#365]
We are using rename-network.yml ops-file as our network name differs from default. As the adapter is a separate job now, I beleive is should be added to rename-network.yml ops-file.

**Comment by ishustava** [comment]
Done in [this commit](https://github.com/cloudfoundry/cf-deployment/commit/cf48d7ed4ee3c14ee29fc7232c8a7efba184bf47)
