### ISSUE TITLE
README does not use new terminology "application runtime" 

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/cf-deployment#366]
With the advent of Cloud Foundry container run time, cf-deployment should limit use of the word "cloud foundry" to describe Application Runtime.

**Comment by dsabeti** [comment]
Hey @ahevenor, good point. I see your PR to start using the phrase "application runtime." We'll try to keep an eye and be more specific. Eventually, we may want to rename this repo to reflect that this is for the CF Application Runtime specifically.
