### ISSUE TITLE
cf login password for bosh-lite + cf-deployment 

### ISSUE THREAD

**Issue by amitoj** [cloudfoundry/cf-deployment#37]
Hi,

The default cf login credential for cf-release on bosh-lite (admin / admin) is not working with cf-deployment. I understand that there no default credentials and secrets are loaded from `deployment-vars.yml` file.

Which key inside the `deployment-vars.yml` file holds the password for `cf login -a api.bosh-lite.com --skip-ssl-validation` command?

Regards,
Amitoj

**Comment by dsabeti** [comment]
The key is called `uaa_scim_users_admin_password`. I'm pretty sure that in any deployment where UAA is your OAuth server, the place to look in the manifest for the admin password will look similar to this: https://github.com/cloudfoundry/cf-deployment/blob/6637e89e4715671063bf9d1a2a85282b6d8f25ad/cf-deployment.yml#L344-L347

Hope that helps!

**Comment by amitoj** [comment]
@dsabeti Thanks
