### ISSUE TITLE
Error while deploying cf-deployment on bosh-lite

### ISSUE THREAD

**Issue by akskap** [cloudfoundry/cf-deployment#376]
I had setup a bosh-lite VM on Openstack and now trying to deploy cf using cf-deployment:

Deployment fails with the following errors:

```
$ bosh -e boshlite -d cf deploy ./cf-deployment.yml -o ./operations/bosh-lite.yml --vars-store cf-deployment-vars.yml -v system_domain="sf-bosh-lite.com"

Task 28 | 06:16:17 | Creating missing vms: router/96e38261-9287-4a69-b526-eb361eb36d84 (0) (00:00:01)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{0d5412ff-4140-4c10-9bcc-b82f8b8595ca}}': Unmarshaling VM properties: json: cannot unmarshal object into Go value of type string' in 'create_vm' CPI method
Task 28 | 06:16:17 | Creating missing vms: tcp-router/0a492310-b1d7-4092-9f12-7bbdaeafa51f (0) (00:00:01)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{e2c6f33e-46b6-4600-a32e-8d113d327dd7}}': Unmarshaling VM properties: json: cannot unmarshal object into Go value of type string' in 'create_vm' CPI method
Task 28 | 06:16:25 | Creating missing vms: database/eb7319a4-83af-4463-8cb9-455c2f3689c9 (0) (00:00:09)
```

**Comment by dsabeti** [comment]
Hi @akskap. The CPI error isn't giving us a lot to work with. Let's try two things to get more information:
1. What does your cloud-config look like? You can fetch it using `bosh cloud-config`.
2. Could you try getting the debug logs by running `bosh task 28 --debug`?

**Comment by akskap** [comment]
Hi @dsabeti .. Thanks for helping out.

Cloud Config looks like :

azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: minimal
  workers: 6
disk_types:
- disk_size: 1024
  name: 1GB
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB
networks:
- name: default
  subnets:
  - azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: random
    gateway: 10.244.0.1
    range: 10.244.0.0/20
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2 - 10.244.0.127
    - 10.244.1.0 - 10.244.1.127
    - 10.244.2.0 - 10.244.2.127
    - 10.244.3.0 - 10.244.3.127
vm_extensions:
- name: 5GB_ephemeral_disk
- name: 10GB_ephemeral_disk
- name: 50GB_ephemeral_disk
- name: 100GB_ephemeral_disk
- name: 500GB_ephemeral_disk
- name: 1TB_ephemeral_disk
- cloud_properties:
    ports:
    - host: 80
    - host: 443
    - host: 2222
  name: ssh-proxy-and-router-lb
- cloud_properties:
    ports:
    - host: 1024-1123
  name: cf-tcp-router-network-properties
- cloud_properties:
    ports:
    - host: 8845
  name: credhub-lb
vm_types:
- name: minimal
- name: small
- name: small-highmem

Succeeded

(Also attached bosh debug log for your reference)

[bosh-error.txt](https://github.com/cloudfoundry/cf-deployment/files/1627229/bosh-error.txt)

**Comment by akskap** [comment]
@dsabeti 

With the --cpi flag also, I see a similar error:

{"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Creating VM with agent ID '{{520ca5e2-1618-4678-99a3-cddc2219a0aa}}': Unmarshaling VM properties: json: cannot unmarshal object into Go value of type string","ok_to_retry":false},"log":""}

**Comment by dsabeti** [comment]
@akskap How did you bootstrap the bosh director? What was your full `bosh create-env` command?

**Comment by akskap** [comment]
@dsabeti 

Full command was:


```
#! /bin/bash

set -eu

echo "- Openstack with BOSH Lite on Docker"

bosh create-env ~/Documents/workspace/bosh-deployment/bosh.yml \
  -o ~/Documents/workspace/bosh-deployment/openstack/cpi.yml \
  -o ~/Documents/workspace/bosh-deployment/bosh-lite-docker.yml \
  -o ~/Documents/workspace/bosh-deployment/external-ip-with-registry-not-recommended.yml \
  --state ./state.json \
  --vars-store ./bosh-lite-setup-vars \
  -v auth_url="XXX" \
  -v az="XXX" \
  -v default_key_name="XXX" \
  -v default_security_groups="[AAA,BBB]" \
  -v director_name="Bosh Lite Director OpenStack" \
  -v internal_cidr="192.168.0.0/24" \
  -v internal_gw="192.168.0.1" \
  -v internal_ip="192.168.0.30" \
  -v net_id="XXX" \
  -v openstack_domain="XXX" \
  -v openstack_password="XXX" \
  -v openstack_project="XXX" \
  -v openstack_username="XXX" \
  -v private_key="~/Documents/workspace/bosh_lite_ssh_files/bosh-lite-rsa" \
  -v region="XXX" \
  -v external_ip="172.18.105.228"
```

**Comment by akskap** [comment]
@dsabeti We don't have any strict dependencies on Docker CPI as such. Would you mind sharing a snippet of your bosh create-env command (that uses runc)?

When I use `bosh-lite-runc.yml`, I get the following error:

```
Parsing release set manifest '/Users/xxxx/Documents/workspace/bosh-deployment/bosh.yml':
  Evaluating manifest:
    Expected to find exactly one matching array item for path '/releases/name=garden-linux' but found 0

Exit code 1 
```

**Comment by dsabeti** [comment]
Hi @akskap. [Here's a script](https://github.com/cloudfoundry/bosh-bootloader/blob/master/plan-patches/bosh-lite-gcp/create-director-override.sh) for deploying bosh-lite to GCP. Our team doesn't test Openstack ourselves (cc @voelzmo, whose team supports BOSH and CF on Openstack), but I think you could achieve bosh-lite on Openstack by changing the following things:
1. Update [GCP specific info](https://github.com/cloudfoundry/bosh-bootloader/blob/master/plan-patches/bosh-lite-gcp/create-director-override.sh#L7-L9) like regions and creds to Openstack specific data. You can look in the [Openstack CPI ops-file](https://github.com/cloudfoundry/bosh-deployment/blob/master/openstack/cpi.yml) for the variables you need to provide.
2. Replace the [GCP CPI ops-file with the Openstack CPI ops-file](https://github.com/cloudfoundry/bosh-bootloader/blob/master/plan-patches/bosh-lite-gcp/create-director-override.sh#L10).
3. Drop [these ops-files that GCP-specific](https://github.com/cloudfoundry/bosh-bootloader/blob/master/plan-patches/bosh-lite-gcp/create-director-override.sh#L16-L17).

**Comment by akskap** [comment]
Thanks a lot @dsabeti 

I was missing some relevant ops file, however there is another issue now.

I can list the cf-deployment VMs from another machine (say X, which has access to external IP of the bosh-lite VM), but, I am unable to target the CF API endpoint using `cf api https://10.244.0.34 --skip-ssl-validation` on machine X - I have setup static routing on machine X using `sudo route add -net 10.244.0.0/24 gw 172.18.105.228` - Are the above commands correct ?

While debugging this, I went through various other docs and it seems that it is mandatory to use a [particular pattern of system-domain](https://github.com/cloudfoundry/diego-release/issues/94#issuecomment-154456883) while deploying cf. Is this understanding correct ?

While deploying cf, I had used the following command:

`bosh -e boshlite -d cf deploy ./cf-deployment.yml -o ./operations/bosh-lite.yml --vars-store cf-deployment-vars.yml -v system_domain="sf-bosh-lite.com"`

Not sure about the relevance of system_domain property here, because sf-bosh-lite.com won't resolve to anything.

**Comment by dsabeti** [comment]
Hi @akskap. Running `sudo route add ...` is only useful if you're running a bosh-lite on your local machine. Since you're running it on a VM on Openstack, you don't need to add that route.

Instead, you need to set up your system domain properly. By default, all Cloud Foundry VMs get deployed to private IPs that are not accessible outside of their network. To reach the important components like the CF API, we use the CF Routing tier -- specifically, `api.$(SYSTEM_DOMAIN)`. You'll need to ensure the following things:
1. Your system domain resolves to the IP address of your bosh-lite VM.
2. The IP of the bosh-lite VM should be accessible to the machine where you'll run the CF CLI. That is, if you want to use the CF CLI from outside the private network, the bosh-lite VM should have a public IP. If you're in the same private network as your bosh-lite VM, it's ok to use a private IP for bosh-lite.
3. The bosh-lite VM should have ports 80, 443, and 2222 open -- that is, firewall rules must allow traffic to those ports, so that the CF CLI can make the necessary requests to the system.

**Comment by akskap** [comment]
@dsabeti Thanks a lot for the suggestions. Your inputs helped setting up a cf-deployment successfully on bosh-lite. If this setup in addition to CI requirements (Jenkins validations etc.), is also needed for broker development on a local machine (which has access to the Openstack public IP), I guess we would need to enable some sort of reverse tunnelling, correct ? Or would you have some other suggestions ?

Anyways, since this is another discussion, I'll also resolve this open issue.

Thanks again.

**Comment by dsabeti** [comment]
Great! I'm glad that helped.

As for the other discussion regarding a broker that has access to an OpenStack public IP, I would say that it warrants a different Github issue (although I don't think we've ever tried to do what you're describing). I'll close this issue for now, and you can open a new one if you want to discuss it further.
