### ISSUE TITLE
`?` in ops files carry over to the right

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cf-deployment#38]
`/instance_groups/name=api/jobs/name=cloud_controller_ng/properties/doppler?/port?` [1]

is same as

`/instance_groups/name=api/jobs/name=cloud_controller_ng/properties/doppler?/port`

because once something is optionally present everything to the right of it by definition may or may not be present when it's being created.

[1] https://github.com/cloudfoundry/cf-deployment/blob/develop/opsfiles/change-logging-port-for-aws-elb.yml#L3

**Comment by dsabeti** [comment]
@cppforlife Good to know. Thanks for pointing this out. We'll clean this all up pretty soon.

**Comment by heyjcollins** [comment]
Hey @cppforlife, 

Just audited cf-d and cleaned up all instances of redundant '?'s.
I'm going to close this issue.

Cheers,

Josh
