### ISSUE TITLE
Make bosh-dns-windows addon names unique

### ISSUE THREAD

**Issue by chendrix** [cloudfoundry/cf-deployment#380]
Currently, the [use-bosh-dns](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/use-bosh-dns.yml) operation adds three addons, one named `bosh-dns`, and *two* named `bosh-dns-windows`, with different stemcells.

Because they have the same name, we cannot use the name as a unique key to match when making later operations. Their names should be unique.

**Comment by dsabeti** [comment]
Hey @chendrix, seems like a reasonable request. I'll probably just plan to rename the windows2016 one to `bosh-dns-windows2016`.  Let me know if there's more to it than that.

**Comment by chendrix** [comment]
Sounds good to me

**Comment by vChrisR** [comment]
I did this change as part of PR #389. Without it it was impossible to solve issue #388.
So When that PR gets accepted this issue can be closed as well :)

**Comment by dsabeti** [comment]
I think this has been addressed as of https://github.com/cloudfoundry/cf-deployment/commit/fcd9b4959adf98cdb59c26545b5d61845c8bd8f0. I'm going to close out the issue now.
