### ISSUE TITLE
cf-deployment: bosh-lite :: dial tcp i/o error after system restart 

### ISSUE THREAD

**Issue by Deekshit51** [cloudfoundry/cf-deployment#403]
Hi Team,

We are doing cf-deployment on my personal machine using bosh - lite to know the capabilities of Cloudfoundry . 

**Steps to reproduce :** 

1. Install Bosh
2. Deploy cloud foundry on a bosh vm
3. start the vm , cloud foundry is up & running
4. stop the vm 
5. restart the machine

**Actual result :** 
                  Able to start the VM, but unable to login to cloudfoundry.. getting dial tcp i/o error

**As a workaround i am uninstalling and deleting the files related to bosh and cloudfoundry, again restarting the machine and starting the cf-deployment process again. this is a bit annoying thing and won't help us in production. 

Kindly help me in resolving this.. do i need to clear cache anywhere ?** 

Thanks,
Deekshit.D

**Comment by dsabeti** [comment]
Hey @Deekshit51. When you stop the VM, the bosh-lite "VMs" (they're really containers) all get shut down and need to be brought back up. The easiest way to do that is to run `bosh cck` and then choose `Recreate VM` as your option for each VM.

**Comment by Deekshit51** [comment]
Hi , 

I have tried running bosh cck command .. but it is telling " Pointing to an empty director" 

do i need to do anything else before running cck ?

Thanks in advance,
Deekshit

**Comment by dsabeti** [comment]
@Deekshit51 You need to be targeting your BOSH director in order to run `bosh cck`. Either you set the `BOSH_ENVIRONMENT` to the IP address of your director, or provide it via `bosh -e IP_ADDRESS cck`.

**Comment by Deekshit51** [comment]
Hi @dsabeti ,

Now i am targeting to the environment, but facing the below error.. any other configurations required ? 

emp-user@A932QD:~$ bosh -e vbox cck
Fetching info:
  Performing request GET 'https://192.168.50.6:25555/info':
    Performing GET request:
      Retry: Get https://192.168.50.6:25555/info: dial tcp 192.168.50.6:25555: getsockopt: connection refused

Exit code 1

Thanks,
Deekshit

**Comment by dsabeti** [comment]
Hey @Deekshit51, I just got word from the BOSH team that bosh-lite no longer supports restarts. I'm afraid you'll need to delete the deployment and start from scratch. You should also consider deploying bosh-lite to an IaaS. We have an example for GCP here: https://github.com/cloudfoundry/cf-deployment/blob/master/iaas-support/bosh-lite/README.md

**Comment by Deekshit51** [comment]
Hi @dsabeti, 

Thanks for your confirmation, will try this on GCP or AWS and let you know if we face any issues.. thanks once again

**Comment by Deekshit51** [comment]
Hi @dsabeti, May i know one additional information?

will we face this restart problem even if we restart the instance in AWS or GCP as well ? or this issue will occur only for VM?

Kindly clarify on this.

Thanks,
Deekshit.

**Comment by dsabeti** [comment]
@Deekshit51 It will likely occur if you restart the VM instance on GCP or AWS.
