### ISSUE TITLE
cf-deployment occasionally fails to allocate a port for MySQL server

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/cf-deployment#413]
Today, @ishustava from the RelInt team reported that the mysql job was unable to claim 33306.

It turns out that many linux kernels reserve the range 32768+ for ephemeral ports. That means that using 33306 as a non-ephemeral port for a server is opening cf-deployment for the occasional collision if Linux assigns that port to another process before MySQL has the chance to allocate it.

cf-deployment should use a port number under 32768 for the MySQL server. We (cf-mysql team) will come back with a recommendation / PR to address this problem.

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by dsabeti** [comment]
Thanks for the heads up, @menicosia. Let us know what port makes the most sense. IIRC, we chose 33306 so we could colocate the proxies with the mysql nodes.

**Comment by menicosia** [comment]
@dsabeti @zankich I propose `13306` as the internal MySQL server listening port.

It doesn't show up on an [IANA search](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=13306) as already allocated/commonly-used.

Thoughts?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by dsabeti** [comment]
`13306` sounds good to me. I can re-purpose this issue as a story to change the port.

**Comment by ishustava** [comment]
Closing this issue because [the port is now changed](https://github.com/cloudfoundry/cf-deployment/blob/73904941fd0dd5842da7371e1cc3e630ba2719e4/cf-deployment.yml#L371).
