### ISSUE TITLE
How to configuration extends db and deploy a app in deploy cf-deployment?

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-deployment#418]
Hi team:
    I look [using extend db](https://github.com/cloudfoundry/cf-mysql-deployment#prerequisites),When deploy cf-deployment  can using cf-mysql-deployment. But I look [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment#prerequisites),deploy it must install  Cloud Foundry.How can using cf-mysql-release when deploy cf-deployment?
    And when i deploy cf-deployment , i want to deploy a app .How can deploy this app and register a router in go-router compoent , such as [nfs-volume-release](https://github.com/cloudfoundry/nfs-volume-release),can you give a guide？

**Comment by dsabeti** [comment]
Hi @geekyzk.
- cf-deployment already includes a mysql cluster. If you want to scale it into a 3-node cluster, you can use [this ops-file](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/scale-database-cluster.yml) for cf-deployment. What are you hoping to do with cf-mysql-deployment?
- I'm not sure I understand this question. When you push an app, the gorouter will automatically create an route for you. How are you trying to use nfs-volume-release?

**Comment by geekyzk** [comment]
Hi @dsabeti 

- I  am sorry,  I understand the mistake for mysql cluster.
- I mean the same as uaa or use [enable-nfs-volumn-service](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/enable-nfs-volume-service.yml), when i deploy use  [enable-nfs-volumn-service](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/enable-nfs-volume-service.yml),the http://nfs-broker.YOUR.DOMAIN.com will register in gorouter 。The effect I want is to deploy an application through ops-file while deploying cf and register a default route.

**Comment by dsabeti** [comment]
@geekyzk I see. When I saw "deploy an app," in your first comment, I assumed you meant using `cf push`. It sounds like that isn't what you want to do. Instead, it sounds like you want to add another component to the platform using an ops-file.

Assuming that's correct, you want to colocate the `route_registrar` job with your new component. You can find an example for this [here](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L466-L483)

**Comment by geekyzk** [comment]
@dsabeti Thanks a lot.
