### ISSUE TITLE
Upgrading from v0.34.0 to v0.36.0 can initialize the database.

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry/cf-deployment#428]
When I upgraded from cf-deployment v0.34.0 to v0.36.0, all data was initialized.

I was using the postgres database with operations/use-postgresql.yml instead of mysql, which seems to be the reason migrated_from was not recognized correctly when v0.36.0 was deployed.

In my opinion, the operations/use-postgresql.yml in v0.36.0 should be modified as follows.

```
diff --git a/operations/use-postgres.yml b/operations/use-postgres.yml
index 25a8e7d..117cb52 100644
--- a/operations/use-postgres.yml
+++ b/operations/use-postgres.yml
@@ -9,13 +9,14 @@
   path: /instance_groups/name=singleton-database/jobs/name=mysql
 - type: remove
   path: /instance_groups/name=singleton-database/jobs/name=proxy
+- type: replace
+  path: /instance_groups/name=singleton-database/migrated_from/-
+  value:
+    name: postgres
 - type: replace
   path: /instance_groups/name=singleton-database/jobs/-
   value:
     name: postgres
-    migrated_from:
-    - name: postgres
     properties:
       databases:
         databases:
```

**Comment by dsabeti** [comment]
Hi @kukgini. Overall, I think you're right -- if this change had been made after officially release cf-deployment 1.0.0, we would have certainly included the `migrated_from` or bumped the major version to denote a backwards-incompatible change. At the time, cf-deployment was still in beta, so we decided merely to mark cf-deployment 0.35.0 as a "pre-release," as a signal to operators not to deploy it.

Anyway, since both versions in question are pre-1.0, I'm not sure there's anything to be done about the issue now.

**Comment by kukgini** [comment]
I agree with your idea that there is no need to do anything specifically for releases prior to 1.0. 

However, it would not be too bad to help the operators who have been performing the upgrade tests slowly since the previous version to help convince them that the platform upgrade policy is stable.

Since I saw 0.35.0 to be in the "pre-release" state, I expected that the upgrade from 0.34.0 to 0.36.0 would work well. (And if I were using mysql, it probably worked.) However, the problems described were retained for release versions up to 0.36.0 and 0.37.0 before 1.0.0.

I would like to describe the upgrade between these versions as a possible issue, in the release notes, and let them know what changes are needed to avoid them.

**Comment by dsabeti** [comment]
Yeah, I think that's reasonable. I was thinking of adding the following to release notes:
- v0.34.0:
  A note on changes to instance group names:
  This version of cf-deployment is the last one to use certain names for datastores. Between this version and v1.0.0, there are some changes that were made to the names of instance groups. Operators using `mysql` should not have any issues upgrading to future versions.
  
  **However, for operators using postgres**, you'll need to add another ops-file to leverage [the `migrated_from` keyword in BOSH](http://bosh.io/docs/migrated-from.html) to rename your instance group. Failing to do this could lead to data loss. Your ops-file will look something like this:
  ```
  - type: replace
    path: /instance_groups/name=NEW_JOB_NAME/migrated_from/-
    value:
      name: postgres
  ```
  You can use this table to discover `NEW_JOB_NAME`, based on the version of cf-deployment you're migrating to:

  | cf-deployment version | postgres job name |
  | ----------------------- | ---------- |
  | v0.34.0                            | `postgres`    |
  | v0.35.0 - v0.37.0             | `singleton-database`    |
  | v1.0.0 and greater           | `database`    |
  
- v0.35.0, 0.36.0, and 0.37.0:
  A note on changes to instance group names:
  As part of cf-deployment v1.0.0, the `singleton-database` gets renamed to `database`. Operators using `mysql` should not have any issues upgrading to future versions, but **operators using postgres** will need to add another ops-file to leverage [the `migrated_from` keyword in BOSH](http://bosh.io/docs/migrated-from.html) to rename your instance group. Failing to do this could lead to data loss. Your ops-file will look something like this:
  ```
  - type: replace
    path: /instance_groups/name=database/migrated_from/-
    value:
      name: singleton-database
  ```

**Comment by kukgini** [comment]
That seems to be enough. You can close this issue when you're done. Thank you. :-)

**Comment by dsabeti** [comment]
Ok, release notes are updated. Thanks so much for your feedback!
