### ISSUE TITLE
cf-deployment ci appears to  be inserting new lines every time releases change

### ISSUE THREAD

**Issue by APShirley** [cloudfoundry/cf-deployment#43]
Observe: https://github.com/cloudfoundry/cf-deployment/blame/develop/cf-deployment.yml#L1434-L1477

**Comment by dsabeti** [comment]
Hey @APShirley! We found this recently ourselves, but just haven't gotten around to fixing it. I just prioritized the story so we should get to this soon.

**Comment by jaresty** [comment]
Hey @APShirley,

Thanks for the feedback!  This issue was fixed when we [re-wrote the manifest update section in go](https://github.com/cloudfoundry/runtime-ci/commit/8976d2a94d3449fb6941700ff42b04a968d0340f#diff-4860533d9f1c7f0ad07a94c60806695f).  Cheers!

Josh
