### ISSUE TITLE
Diego-API : Do we need to do Horizontal or vertical scaling

### ISSUE THREAD

**Issue by K7king** [cloudfoundry/cf-deployment#434]
Since many of  the CF components are replaced, we are unable to make a sizing for the vms. We were facing issues with diego-api to handle too many applications. Can someone provide  on diego-api to scale horizontally or vertically ?

A guide or architecture for new CF deployment would be great enough to work around.

**Comment by dsabeti** [comment]
Hi @K7king. I'm pretty sure that Diego is structures so that only one Diego API is ever active, and the other Diego API nodes are available for failover in case the active one fails. As such, I'd recommend vertical scaling. I'll loop in the Diego team so they can give their advice: cc @emalm @jvshahid.

**Comment by emalm** [comment]
That's correct: in particular, the Diego BBS service operates that way, so it is appropriate to scale it horizontally only for failover redundancy and then to scale it vertically to meet environmental load. Conversely, the Diego Locket service has all of its instances active simultaneously, so it can scale horizontally.

The CF docs have some recommendations for horizontal vs vertical scaling at https://docs.cloudfoundry.org/concepts/high-availability.html#processes, so it likely makes sense to revise those guidelines to match to the cf-deployment instance-group names and compositions now that cf-release and the associated manifest-generation systems are no longer supported. Individual CF subsystem releases such as Diego could also provide better guidance about these scaling recommendations for their BOSH jobs, for those operators modifying cf-deployment or constructing their own deployment topologies. /cc @seviet 

Thanks,
Eric

**Comment by dsabeti** [comment]
I'm going to close this issue due to inactivity, but feel free to re-open if you have more questions on the subject.

**Comment by emalm** [comment]
Oh, the Diego team also recently added some more specific scaling guidelines for individual components in the diego-release docs, at https://github.com/cloudfoundry/diego-release/blob/develop/docs/scaling-and-performance-tuning.md.
