### ISSUE TITLE
No Services available in Cloudfoundry marketplace

### ISSUE THREAD

**Issue by Deekshit51** [cloudfoundry/cf-deployment#437]
Hi Team,

We have done the installation of cloudfoundry using bosh lite on an ubuntu machine.

When we are trying get the list of available services in cf marketplace, we are not getting any services listed.

**Installation procedure followed :** https://banck.net/2017/03/deploying-cloud-foundry-virtualbox-using-bosh-cli-v2/

Can you kindly help us to get the services listed.
![screenshot from 2018-03-12 16-37-22](https://user-images.githubusercontent.com/28754526/37280417-b55e9fce-2613-11e8-9324-a4f598432427.png)

Thanks in advance,
Deekshit

**Comment by dsabeti** [comment]
Hi @Deekshit51. By default, the platform doesn't include any services. Operators need to include them by setting up service brokers. You should probably take a look at the [service overview docs](http://docs.cloudfoundry.org/services/overview.html), as well as the article on [managing service brokers](http://docs.cloudfoundry.org/services/managing-service-brokers.html)

**Comment by Deekshit51** [comment]
Hey @dsabeti ,

Thanks for the quick response, went through those 2 articles, able to understand about the things.

but is it possible to send me any additional URL's which includes some commands and helps me to add the services quickly.

Sorry for inconvinience.

Thanks in advance,
Deekshit

**Comment by dsabeti** [comment]
The article about managing service brokers includes the CLI commands for creating service brokers and making plans public. For example, to create a service broker, you'll need to run `cf create-service-broker`.

**Comment by Deekshit51** [comment]
Thank you @dsabeti ,

Need one more clarification ,

i could see the below command in the "Manage Service Brokers" page for registering the broker..

cf create-service-broker mybrokername someuser somethingsecure https://mybroker.example.com/

in the above command, i am giving my "cf admin" username & password instead of "someuser" & "somethingsecure" respecctively...

but what could be the URL for that ? 

Let say i want to create a service broker with mysql instance what could be the url for that? 

kindly explain , Thank you.

**Comment by dsabeti** [comment]
@Deekshit51, the docs I've provided explain this, but I can try to summarize again.

Services in Cloud Foundry are always provided by third-parties. The service brokers act as the interface between Cloud Foundry and the third-party service provider. That means that if you want to use services, you have to set up a service and a service broker yourself. 

For example, you could use [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment) to deploy a MySQL cluster and then use this [ops-file to deploy a broker](https://github.com/cloudfoundry/cf-mysql-deployment/blob/develop/operations/add-broker.yml). Once the cluster and the broker are set up, you can run `cf create-service-broker mysql $MYSQL_BROKER_USERNAME $MYSQL_BROKER_PASSWORD $URL_OR_IP_OF_MYSQL_BROKER`.

**Comment by Deekshit51** [comment]
Thanks @dsabeti , we were able to list down the services in the marketplace now,

Thanks for your support.
