### ISSUE TITLE
rename-network doesn't work when used with use-external-dns.yaml

### ISSUE THREAD

**Issue by jyriok** [cloudfoundry/cf-deployment#444]
i use ops file use-external-dbs.yml  and now i want use rename-network.yml too because our network name is not default

but i have error on deploy because database component don't exist anymore on the deployment:

`Could not interpolate: Expected to find exactly one matching array item for path '/instance_groups/name=database' but found 0`

this ops-file must be adapted 
can i do a ops-file for a ops-file ? :p

**Comment by jyriok** [comment]
and same for /use-s3-blobstore.yml :)

**Comment by dsabeti** [comment]
@heyjcollins

**Comment by jyriok** [comment]
thanks for the tips, i will try this ;)

**Comment by dsabeti** [comment]
Hi @jyriok, I'm going to close out this issue, but go ahead and re-open if you need more help.
