### ISSUE TITLE
deployment issue using cf-deployment, unable to update vm_type for instances

### ISSUE THREAD

**Issue by apsraps** [cloudfoundry/cf-deployment#445]
Hi,

I am deploying CF using BBL, BOSH 2.0 and cf-deployment on AWS.
Following all steps from
https://docs.cloudfoundry.org/deploying/cf-deployment/index.html

Using bbl 6.4.7 (linux/amd64)

Doing a BBL up using
bbl up 
--iaas aws 
--aws-access-key-id YOUR-ACCESS-KEY-ID 
--aws-secret-access-key YOUR-SECRET-ACCESS-KEY 
--aws-region YOUR-AWS-REGION 
--lb-type cf 
--lb-cert YOUR-CERT.crt 
--lb-key YOUR-KEY.key 
--lb-domain YOUR-SYSTEM-DOMAIN

After Deploying Bosh
$bbl print-env shows the output correctly, able to login to bosh using bosh log-in
AWS console shows the jumpbox/0, bosh/0 and bbl nat instance as running

This creates cloud-config.yml and ops.yml and after uploading the stemcell, we try to deploy CF using
bosh -e cloudconfig-env -d cf deploy cf-deployment/cf-deployment.yml --vars-store vars/cloud-config-vars.yml -v system_domain=test.com

This works partially OK and creates the CF components on AWS with vm_type as m4.large (as that is the default in ops.yml) Some instances are not created as we run out of AWS quota for m4.large

We wanted to change the m4.large to another value during the deployment to manage quota on AWS and have changed the ops.yml file for the same. Change vm_type minimal and vm_type small to other values

repeated the steps for bosh deploy but it doesnt pick up the updated ops.yml. We tried bosh update cloud-config cloud-config.yml. But this messes up the bosh deploy as the cloud-config.yml generated by bbl is still the template and doesnt have the aws specific replacements from ops.yml

If we try to change the instance type from AWS EC2 console and restart, the VMs go into unresponsive state

Can you please suggest what options we have to update the vm_type for instances when doing a bosh-deploy?

Thanks,

**Comment by dsabeti** [comment]
Hi @apsraps. Can you post the exact command you're using to deploy with the ops-file? It should look something like this:
```
bosh deploy cf-deployment/cf-deployment.yml \
  -v system_domain=test.com \
  --vars-store env-repo/cf-vars.yml \
  -o path/to/my-ops-file.yml
```

Also, what are the contents of your ops-file?

**Comment by dsabeti** [comment]
Hi @apsraps, any updates on this issue?

**Comment by heyjcollins** [comment]
Since there's been no response on this issue, I'm going to close it. If you'd like to see it re-opened, please comment on the issue and reopen.
