### ISSUE TITLE
cloud_controller.admins can't app ssh without also being SpaceDevelopers

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cf-deployment#452]
The UAA client for the `ssh-proxy` doesn't contain the `cloud_controller.admin` scope. As a result, users who are CF admins can't app ssh into apps, unless they are space developers for the app.  Can that get added back?

**Comment by dsabeti** [comment]
Hey @geofffranks. I haven't thought this through completely, but there might be an issue with that approach on multi-tenant environments. On an environment where users are from a different org than the admin running the platform, you may want to ensure that admin users can't `ssh` onto an arbitrary user's app (even if that same admin can stop or even delete an app).

**Comment by dsabeti** [comment]
Ok, after conferring with the Diego team, it seems that
- This functionality used to work this way in cf-release
- If you're an admin, you can just give yourself space dev permissions anyway, so this is, at best, Security By Being Annoying :tm:.

I'll prioritize this.

**Comment by cdutra** [comment]
The story has been accepted. I'm closing this issue, feel free to reopen if necessary. Thanks
