### ISSUE TITLE
Should container trusted ca certs be configured in rep properties?

### ISSUE THREAD

**Issue by Ykisialiou** [cloudfoundry/cf-deployment#456]
Hello. I'm going to use 
https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-trusted-ca-cert-for-apps.yml
to add my ca cert as trusted for applications. 
And I'm not sure should I also configure my cert for rep job, like
https://github.com/cloudfoundry/diego-release/blob/develop/jobs/rep/spec#L248 and why it's not included in ops file.

**Comment by dsabeti** [comment]
Hi @Ykisialiou. Good catch. The difference between those properties is very subtle, but worth explaining.

- The [cflinuxfs2 property](https://github.com/cloudfoundry/cflinuxfs2-release/blob/master/jobs/cflinuxfs2-rootfs-setup/spec#L12) (the property we set in the ops-file) 
  - only configures apps that use the **cflinuxfs2** container filesystem to trust the given CA certificate. Specifically, that excludes apps pushed using the docker lifecycle, and all windows apps.
  - stores the certificate in the container trust store, so it is automatically trusted by the app running in the container.
- The [diego rep property](https://github.com/cloudfoundry/diego-release/blob/develop/jobs/rep/spec#L248) (the property you're inquiring about) 
  - configures **all apps** to trust the given CA.
  - save the CA in a canonical location (`/etc/cf-system-certificates`), but requires that the app know to look there for the certs and install those certificates into their trust store. This creates some extra work for the app developer.

I think the right solution here is configure both properties as you suggest, and improve documentation of the ops-file to reflect the subtle differences between the two properties.

**Comment by Ykisialiou** [comment]
Thanks a lot @dsabeti for quick and detailed explanation. Looks like it's working on my test env, so I'll create a PR, probably it will be usefull.

**Comment by cdutra** [comment]
The story has been accepted. I'm closing this issue, feel free to reopen if necessary. Thanks
