### ISSUE TITLE
Cloud Controller API Endpoint in AWS

### ISSUE THREAD

**Issue by apsraps** [cloudfoundry/cf-deployment#460]
Hi,

New to CF and have setup CF using BBL, cf-deployment on AWS. Now trying to set the API endpoint using cf api https://api.<domain given during AWS setup>

This somehow doesnt seem to work and looks like we have to point api.<domain> to something from Route53 in AWS. Instructions are not very clear and it says "Find your Cloud Controller API endpoint by consulting your cloud operator"

Can someone please help with the right API endpoint setup on AWS.

Thanks.

**Comment by dsabeti** [comment]
Hi @apsraps. I'm going to closet his issue due to inactivity, but feel free to reopen it if you need more help.
