### ISSUE TITLE
How to config use-haproxy when your deploy cloudfoundry using bosh

### ISSUE THREAD

**Issue by zhongjun2** [cloudfoundry/cf-deployment#463]
bosh -e bosh-1 -d cf deploy cf-deployment/cf-deployment.yml \
--vars-store cf-vars.yml \
-v system_domain=cloudfoundry.com \
-v  haproxy_public_ip=xxx.xxx.xxx.xxx  \
-v haproxy_public_network_name= bosh \
-v haproxy_ssl.private_key=./bosh.pem \
-o cf-deployment/operations/openstack.yml \
-o cf-deployment/operations/use-haproxy.yml \
-o cf-deployment/operations/use-haproxy-public-network.yml \

I am a new guy to deploy the cf.
When I run the above command, I got error about  "cf-haproxy-network-properties" doesn't config.

1. Do you know how to config the cf-haproxy-network-properties in 

use-haproxy-public-network.yml. Is there an example?

2.  Do we have a simplest yml file to deploy the cf in openstack. I don't want to support loadbalancer or something else. I just want to deploy a simplest cloudfoundry in openstack and this cloudfoundry just need to push a simplest application.

Thanks!!!!

**Comment by dsabeti** [comment]
Hi @zhongjun2. You've stumbled onto an ops-file that we've forgotten about. If you look [at the release that first introduced `use-haproxy-public-network.yml`](https://github.com/cloudfoundry/cf-deployment/releases/tag/v1.11.0), I said:
> Do not use warning: use-haproxy-public-network.yml is still under development and should not be used.

After that, our team got caught up in other work and we failed to complete work on this ops-file. I'm happy to explain how to avoid the error you're receiving, but I'm concerned that you'll just find a different error afterward.

Instead, it might be better to deploy without `use-haproxy-public-network.yml`. If you decided not to use the ops-file, your HAProxy would be deployed only to a private IP address. You'd still be able to push an application, but the app would only be reachable by machines in the same private network. For example, to curl your app, you'd first need to ssh onto a VM in your Openstack private network. Does your app need to be publicly addressable? Or is it sufficient to use this process I just described?

If your app needs to be publicly addressable, then our best is to ask for help from the team that supports cf-deployment on Openstack. cc @voelzmo

**Comment by dsabeti** [comment]
Hi @zhongjun2. Sorry for the delay in responding. We've got `use-haproxy-public-network.yml` working on one of our environments, so I'm happy to walk you through how to make it work for you deployment.

The `cf-haproxy-network-properties` is a kind of placeholder for whatever you need to do in your IaaS to configure your HAProxy. 

For example, on GCP, we need to configure firewall rules to allow HAProxy to receive traffic on certain ports. The way we do that is to update our [cloud-config](https://bosh.io/docs/cloud-config), with a [vm_extension](https://bosh.io/docs/cloud-config/#vm-extensions) called `cf-haproxy-network-properties`:
```
    name: cf-haproxy-network-properties
    cloud_properties:
      tags:
      - cf-ha-proxy
```
This simple vm_extension adds a tag called `cf-ha-proxy` to the VM. Then, we configure our GCP firewall rules to allow traffic to various ports (80, 443, 4443, 22, 222 -- to name a few) for any VM with the `cf-ha-proxy` tag.

Now, that was the GCP-specific implementation. You'll need to figure out what additional configuration you'll need to do for your HAProxy on your Openstack environment. Again, maybe @voelzmo can help here. In the case that your HAProxy doesn't need any additional configuration, you can simply implement a no-op vm_extension:
```
    name: cf-haproxy-network-properties
    cloud_properties: {}
```

**Comment by heyjcollins** [comment]
Since there's been no response on this issue since May, I'm going to close it. If you'd like to see it re-opened, please comment on the issue and reopen.
