### ISSUE TITLE
Certificate validity 

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/cf-deployment#472]
Hi everyone i need small information, the certificates created by bosh2 us validity only for 1 year.

Is there any way to extend the validity of certificates more than 1 year. 

For example i want to extend 5 years,  it is possible.

Thanks in advance.

**Comment by dsabeti** [comment]
Hi @abhilash07. I don't think there's a way to specify a different validity period for certs using the BOSH CLI. If I were you, I'd open an issue on the [bosh repo](https://github.com/cloudfoundry/bosh) -- I imagine plenty of people would like to be able to specify a longer validity period.

**Comment by abhilash07** [comment]
@dsabeti thanks for your responce and information.
