### ISSUE TITLE
deployment failed with 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.

### ISSUE THREAD

**Issue by doubleTP** [cloudfoundry/cf-deployment#474]
i'm trying to install cloud foundry on vsphere,but there is some problems.

command:
bosh -e bosh -d cf deploy cf-deployment/cf-deployment.yml --vars-store cf-deployment/env-repo/deployment-vars.yml -v system_domain=test.com -o cf-deployment/operations/scale-to-one-az.yml

result:
Task 229
Task 229 | 06:51:37 | Preparing deployment: Preparing deployment (00:00:04)
Task 229 | 06:51:50 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 229 | 06:51:51 | Updating instance api: api/c7569305-a073-4c92-a941-3d7a2b7411e9 (0) (canary) (00:01:38)
                    L Error: Action Failed get_task: Task e789016d-b853-44a2-64c4-913edb115b87 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.
Task 229 | 06:53:29 | Error: Action Failed get_task: Task e789016d-b853-44a2-64c4-913edb115b87 result: 1 of 1 post-start scripts failed. Failed Jobs: cloud_controller_ng.
Task 229 Started  Wed Apr 25 06:51:37 UTC 2018
Task 229 Finished Wed Apr 25 06:53:29 UTC 2018
Task 229 Duration 00:01:52
Task 229 error
Updating deployment:
  Expected task '229' to succeed but state is 'error'
Exit code 1

[post-start.stderr.log](https://github.com/cloudfoundry/cf-deployment/files/1945844/post-start.stderr.log)

**Comment by dsabeti** [comment]
Hi @doubleTP. You can start to debug by downloading the logs for the Cloud Controller by running `bosh logs api/0`. The logs should have some information about the failure, which you can take to the CAPI team -- either in their channel in the Cloud Foundry slack, or in a Github issue on the capi-release repo.

**Comment by dsabeti** [comment]
Hi @doubleTP. I'm going to close this issue due to inactivity, but feel free to reopen if you need more help.
