### ISSUE TITLE
Azure blobstorage  Error uploading application

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/cf-deployment#479]
Hi did any one tried to configure azure blobstore to CF blobstore ???.

I am encountering below error on . I have attached my bosh-lite cf deployment yaml file for your reference.

<img width="513" alt="screen shot 2018-05-02 at 9 50 11 am" src="https://user-images.githubusercontent.com/10971841/39500265-3d4258d4-4dee-11e8-9777-97d8ec106b1f.png">

[cf.txt](https://github.com/cloudfoundry/cf-deployment/files/1965600/cf.txt)

Thanks In advance.

**Comment by abhilash07** [comment]
@dsabeti, thanks for your responce. here is my api logs 


[cc_uploader.stdout.log](https://github.com/cloudfoundry/cf-deployment/files/1969445/cc_uploader.stdout.log)
[cloud_controller_ng_ctl.err.log](https://github.com/cloudfoundry/cf-deployment/files/1969447/cloud_controller_ng_ctl.err.log)
[cloud_controller_ng_ctl.log](https://github.com/cloudfoundry/cf-deployment/files/1969448/cloud_controller_ng_ctl.log)
[cloud_controller_ng.log](https://github.com/cloudfoundry/cf-deployment/files/1969449/cloud_controller_ng.log)
[cloud_controller_worker_ctl.err.log](https://github.com/cloudfoundry/cf-deployment/files/1969450/cloud_controller_worker_ctl.err.log)
[cloud_controller_worker_ctl.log](https://github.com/cloudfoundry/cf-deployment/files/1969451/cloud_controller_worker_ctl.log)
[post-start.stderr.log](https://github.com/cloudfoundry/cf-deployment/files/1969452/post-start.stderr.log)
[post-start.stdout.log](https://github.com/cloudfoundry/cf-deployment/files/1969453/post-start.stdout.log)
[pre-start.stderr.log](https://github.com/cloudfoundry/cf-deployment/files/1969454/pre-start.stderr.log)
[pre-start.stdout.log](https://github.com/cloudfoundry/cf-deployment/files/1969455/pre-start.stdout.log)

Thanks in advance!!!

**Comment by dsabeti** [comment]
Hi @abhilash07. I couldn't find anything in the logs. Could you try this:
1. Run `CF_TRACE=true cf push ...` to find the request guid
2. Search for the request guid in your logs.

**Comment by abhilash07** [comment]
@dsabeti thanks for your response, same here i can't able to find anything in cc logs and CF_TRACE=true cf push as well.
I will try with micro-bosh if the same error continues i will reopen this error. Now i am closing this error.
