### ISSUE TITLE
Error: Job 'silk-controller' not found in Template table

### ISSUE THREAD

**Issue by xiaozhu36** [cloudfoundry/cf-deployment#480]
Hi ,

When I use the latest cf-deployment v1.28.0  to deploy CF, I happened an error:
```
Task 44

Task 44 | 12:07:53 | Preparing deployment: Preparing deployment (00:00:00)
                   L Error: Job 'silk-controller' not found in Template table
Task 44 | 12:07:53 | Error: Job 'silk-controller' not found in Template table

Task 44 Started  Wed May  2 12:07:53 UTC 2018
Task 44 Finished Wed May  2 12:07:53 UTC 2018
Task 44 Duration 00:00:00
Task 44 error

Updating deployment:
  Expected task '44' to succeed but state is 'error'

Exit code 1
```

My bosh cli is 3.0.1 and bosh release is 265.2.0. 

Can you please suggest something on this.

**Comment by dsabeti** [comment]
Hi @xiaozhu36. Are you including any ops-files when you deploy? What version of cf-networking-release is being used?

**Comment by xiaozhu36** [comment]
HI @dsabeti 

Thanks for your reply.  I did not use any Ops file. Do I need to specify one? If so, which Ops file can be used?
