### ISSUE TITLE
Getting the provided error while deploying cf-deployment.yml

### ISSUE THREAD

**Issue by Murugan4all** [cloudfoundry/cf-deployment#489]
I deployed the bosh bootloader successfully and while deploying cf-deployment.yml i am getting the below error.
Command Executed: bosh -e bbl-bosh -d cf deploy cf-deployment.yml -o operations/aws.yml

Task 29 | 13:22:56 | Error: - Failed to find variable '/bosh-bbl-env-nicaragua-2018-05-08t08-54z/cf/system_domain' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'

Task 29 Started  Tue May  8 13:22:56 UTC 2018
Task 29 Finished Tue May  8 13:22:56 UTC 2018
Task 29 Duration 00:00:00
Task 29 error

**Comment by dsabeti** [comment]
Hi @Murugan4all. You need to add `-v system_domain=...` to your deploy command.

**Comment by dsabeti** [comment]
Hi @Murugan4all. That error message is saying that the `consul` instance group is trying to deploy to some AZ that isn't listed as part of your `default` network. What AZ's do you have listed in your `consul` configuration? What AZ's are part of your `default` network, as defined in your cloud-config?

**Comment by Murugan4all** [comment]
Thanks for the help. Now the deployment successfully completed. When i try to deploy the api using cf command. I am getting 404 domain doesn't exist. 

Please also let me know how i can test after the successful deployment?

**Comment by dsabeti** [comment]
Your system domain should resolve to your load balancer, which should be configured to pass traffic through to your routers. Is that the case?
