### ISSUE TITLE
cf-deployment failing using centos stemcell

### ISSUE THREAD

**Issue by apsraps** [cloudfoundry/cf-deployment#500]
Hi All,

Good Day :)

Currently trying to deploy cloud foundry using Centos.

Following link which i have used for deployment
https://docs.cloudfoundry.org/deploying/cf-deployment/deploy-cf.html

I have uploaded the Centos stemcells and replaced the deployment file but following error occurred during the deployment.

Can you please give any pointers?

Task 25 | 04:27:18 | Compiling packages: apparmor/0133a2288b0f71d05d89bd117c957297ad19cd19c0253236ba0ce4dedeb27186 (00:01:54)
L Error: Action Failed get_task: Task 7c60db3b-4862-4d79-5793-10d8fc45d114 result: Compiling package apparmor: Running packaging script: Running packaging script: Command exited with 1; Stdout: checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for bison... bison -y
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for swig... /bin/swig
checking whether the libapparmor debug output should be enabled... no
checking whether the libapparmor man pages should be generated... yes
checking for podchecker... no
, Stderr: + tar xzf apparmor/apparmor-2.11.1.tar.gz

pushd apparmor-2.11.1/libraries/libapparmor/

./configure
configure: error:
The podchecker program was not found in the default path. podchecker is part of
Perl, which can be retrieved from:

https://www.perl.org

**Comment by dsabeti** [comment]
Hi @apsraps. It looks like the package that's failing to compile is `apparmor` from the garden-runc-release. Let's see if we can get help from @julz or @teddyking can help figure out what's going wrong.

**Comment by apsraps** [comment]
Thanks @dsabeti. 
Some more inputs.
We tried to download the apparmor and execute it outside of CF from command line
tar xzf apparmor/apparmor-2.11.1.tar.gz
pushd apparmor-2.11.1/libraries/libapparmor/
./configure

and this works fine.

When we look at the logs, the only difference is in 
checking for podchecker... no // This happens in cf deployment

checking for podchecker... podchecker // This happens outside of CF deployment
.. and other commands eventually succeeding

We have tried with both the light and full stemcell version of CentOS but no luck. 

Not sure where it is looking for as default path.

**Comment by apsraps** [comment]
Thanks for checking @dsabeti. How can i contact the workspace admin to get me an invitation to join CF Slack?

**Comment by dsabeti** [comment]
You should be able to ask for an invite at https://slack.cloudfoundry.org/

**Comment by bingosummer** [comment]
I also hit the same issue. Besides whether garden supports CentOS or not, it seems this specific issue of compiling apparmor can be fixed in my test. Just FYI.

I ssh into the failed compiling VM and run `sudo yum install perl-Pod-Checker`. Then the following [commands](https://github.com/cloudfoundry/garden-runc-release/blob/develop/packages/apparmor/packaging#L5-L8) can run successfully.
```
pushd apparmor-2.11.1/libraries/libapparmor/
  ./configure
  make
popd
```
Maybe the package `perl-Pod-Checker` can be added into https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/stemcell_builder/stages/base_centos_packages/apply.sh.

**Comment by dsabeti** [comment]
@bingosummer, you'd have to check with @cppforlife and the BOSH team about adding that to the stemcell. However, that would merely get you to successfully compiling apparmor -- it doesn't necessarily mean that garden would function properly on CentOS.

**Comment by cppforlife** [comment]
@bingosummer since it's necessary for that particular release, maintainers of garden can decide to include whatever pkg they want to make it work on centos; however, garden team does not have any plans to support centos stemcells afaik hence this is not somethig that will really move forward.

**Comment by bingosummer** [comment]
Understood, thanks for your kindly explanation and patience. @dsabeti @cppforlife

**Comment by dsabeti** [comment]
I'm going to close the issue since it seems like we're agreed that we don't currently expect cf-deployment to support CentOS stemcells. If you'd like to broach the subject with the garden team, please open an issue on the [Garden repo](https://github.com/cloudfoundry/garden).
