### ISSUE TITLE
Autobump windows-syslog-release

### ISSUE THREAD

**Issue by mhoran** [cloudfoundry/cf-deployment#504]
There's an [experimental opsfile](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/windows-enable-component-syslog.yml) for enabling syslog functionality on Windows, which requires the windows-syslog-release. Currently this release is manually bumped, but there is a [BOSH release](http://bosh.io/releases/github.com/cloudfoundry/windows-syslog-release?all=1) so I presume this can be done automatically.

**Comment by dsabeti** [comment]
Yep, seems like the right thing to do

**Comment by ishustava** [comment]
This [job exists](https://release-integration.ci.cf-app.com/teams/main/pipelines/update-releases/jobs/update-windows-syslog/builds/3)! Closing the issue.
