### ISSUE TITLE
Updating instance api:  Expected stream to have  digest 'sha256:' but was 'sha256:'

### ISSUE THREAD

**Issue by gherasima** [cloudfoundry/cf-deployment#514]
I'm trying to do is to install Cloud Foundry for the very first time, actually I already tried many times. My deploy command is "bosh  -d cf deploy cf-deployment/cf-deployment.yml --vars-store env-repository/deployment-vars.yml  -v system_domain=domain.local" I didn't include any ops-files. My IaaS is vShpere, using one ESXi 6.0 I didn't use and BBL, I'm installing BOSH and CF manually using the docs.

All the VM are up and running expect one API:
```
Task 2530

Task 2530 | 10:38:52 | Preparing deployment: Preparing deployment (00:00:04)
Task 2530 | 10:39:02 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 2530 | 10:39:03 | Updating instance api: api/4449c67a-01da-4fdf-8461-2c7bd62f0656 (0) (canary) (00:00:45)
                     L Error: Action Failed get_task: Task ff94734f-56bc-4333-6a61-047ec92cc29e result: Applying: Applying job consul_agent: Applying package cloud_controller_ng for job consul_agent: Fetching package blob: Getting blob from inner blobstore: Checking downloaded blob '65cbe493-9744-48c4-7a85-d6dc987a2c5a': Expected stream to have digest 'sha256:16eb2a92fe92a0ab07763f65de2c518293e386548e9f1b688d562e0755f2cd5c' but was 'sha256:763212484916f3c3cc0e78614474f7c2b93e8e78ea0745174c3e22ba5fadd76c'
Task 2530 | 10:39:48 | Error: Action Failed get_task: Task ff94734f-56bc-4333-6a61-047ec92cc29e result: Applying: Applying job consul_agent: Applying package cloud_controller_ng for job consul_agent: Fetching package blob: Getting blob from inner blobstore: Checking downloaded blob '65cbe493-9744-48c4-7a85-d6dc987a2c5a': Expected stream to have digest 'sha256:16eb2a92fe92a0ab07763f65de2c518293e386548e9f1b688d562e0755f2cd5c' but was 'sha256:763212484916f3c3cc0e78614474f7c2b93e8e78ea0745174c3e22ba5fadd76c'

Task 2530 Started  Fri Jun  1 10:38:52 UTC 2018
Task 2530 Finished Fri Jun  1 10:39:48 UTC 2018
Task 2530 Duration 00:00:56
Task 2530 error

Updating deployment:
  Expected task '2530' to succeed but state is 'error'

Exit code 1
```

I have tried to delete the vm and re-deploy but without success

**Comment by dsabeti** [comment]
Hey @gherasima. You can run `bosh task 2530 --debug` to pull down the full set of debug logs. Can you try that and take a look through the logs to see if you find a more specific error; sometimes, things like network or disk issues surface as a SHA mismatch because BOSH will compute a SHA on an incomplete file or 404 page that it gets instead of the actual blob.

**Comment by gherasima** [comment]
I already look at that log before I open the issue but I didnt understand where to look:
I'm attaching the  bosh task 2530 --debug output

[debug.txt](https://github.com/cloudfoundry/cf-deployment/files/2063605/debug.txt)

**Comment by gherasima** [comment]
Thanks it worked
