### ISSUE TITLE
log-cache-release sha is incorrect

### ISSUE THREAD

**Issue by dtimm** [cloudfoundry/cf-deployment#520]
https://github.com/cloudfoundry/cf-deployment/blob/8b60a7bbd4e43cb56c4edf3fa2fde92a1295ae28/operations/experimental/use-log-cache.yml#L5

`sha` is referenced instead of the `sha1`. It is also not being updated by the CI process that gets new bosh.io releases.

**Comment by ishustava** [comment]
Closing this issue since #521 is now merged.
