### ISSUE TITLE
Error occurred after DIEGO deployment

### ISSUE THREAD

**Issue by grapematstar** [cloudfoundry/cf-deployment#528]
Hi.
I'm now, BOSH and CloudFoundry were successfully deployed in the Ubuntu environment.
Also, Some of the necessary releases were uploaded to BOSH.
However, during deployment of DIEGO, the following error occurred.
**********************************************************************************************
Task 84

Task 84 | 08:12:05 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
Task 84 | 08:12:06 | Preparing deployment: Preparing deployment (00:00:03)
Task 84 | 08:12:15 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 84 | 08:12:16 | Compiling packages: golang-windows/c82f5401ad36fce9816796bcc9b69d1e6ae3b4b7
Task 84 | 08:12:16 | Compiling packages: mingw/ebc717242616e72aaa85ded74028f9ee97973d308344e8b80d13af489f60fbf5
Task 84 | 08:12:16 | Compiling packages: golang-windows/74d60eca8a8ca634d606bd78d1589f9411e3d328
Task 84 | 08:12:16 | Compiling packages: golang-windows/d73a039da9cf2dd361705b7bf8fd447dbaadc28efbc38840ce85105bf464a64b
Task 84 | 08:12:16 | Compiling packages: cfdot/dcffd9b7f215c239074c1e9d1e0305ce873058e7
Task 84 | 08:12:16 | Compiling packages: certsplitter_windows/eb7a099e80afcf2a0a4835fee317117f31bd09b3
Task 84 | 08:15:38 | Compiling packages: golang-windows/c82f5401ad36fce9816796bcc9b69d1e6ae3b4b7 (00:03:22)
Task 84 | 08:15:38 | Compiling packages: healthcheck_windows/819ff998e9ee98f3ccb1ec55a2794da8e4572e6e
Task 84 | 08:18:45 | Compiling packages: golang-windows/74d60eca8a8ca634d606bd78d1589f9411e3d328 (00:06:29)
Task 84 | 08:18:45 | Compiling packages: rep_windows/ca89063c53f2f00ee635f5a166d51cb798a893fe
Task 84 | 08:22:01 | Compiling packages: certsplitter_windows/eb7a099e80afcf2a0a4835fee317117f31bd09b3 (00:09:45)
Task 84 | 08:22:01 | Compiling packages: golang/2206cd4937e897c2a6639f93db9683a529b73e5c
Task 84 | 08:22:01 | Compiling packages: cfdot/dcffd9b7f215c239074c1e9d1e0305ce873058e7 (00:09:45)
Task 84 | 08:22:01 | Compiling packages: pid_utils/df9c92d8d2daa1806afe7a38d332a6fd59a8abc0
Task 84 | 08:25:20 | Compiling packages: golang-windows/d73a039da9cf2dd361705b7bf8fd447dbaadc28efbc38840ce85105bf464a64b (00:13:04)
                   L Error: Action Failed get_task: Task 27b5c56b-1c32-4574-49ae-64bd296e6d3f result: Compiling package golang-windows: Running packaging script: Running packaging script: Command exited with 1; Stdout: , Stderr: function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
\+ iex (get-content -raw packaging)
\+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [Invoke-Expression], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
 

Task 84 | 08:25:27 | Compiling packages: mingw/ebc717242616e72aaa85ded74028f9ee97973d308344e8b80d13af489f60fbf5 (00:13:11)
                   L Error: Action Failed get_task: Task 51ab5e3b-504e-4efd-6ce7-2dfd771fb625 result: Compiling package mingw: Running packaging script: Running packaging script: Command exited with 1; Stdout: , Stderr: function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
\+ iex (get-content -raw packaging)
\+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [Invoke-Expression], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
 

Task 84 | 08:25:35 | Compiling packages: pid_utils/df9c92d8d2daa1806afe7a38d332a6fd59a8abc0 (00:03:34)
Task 84 | 08:26:56 | Compiling packages: healthcheck_windows/819ff998e9ee98f3ccb1ec55a2794da8e4572e6e (00:11:18)
Task 84 | 08:28:03 | Compiling packages: golang/2206cd4937e897c2a6639f93db9683a529b73e5c (00:06:02)
*************************************************************************************************
I tried to modify the packaging script file and modify the DIEGO manifest file.
But it failed. I want a little hint.
thank you.

**Comment by ishustava** [comment]
Hey @grapematstar,
 
Based on the BOSH output you've included, it looks like you are using deprecated manifest which cf-deployment doesn't support. Most likely, you are deploying `cf-release` (which did not include Diego and required it to be deployed separately). `cf-release` is now deprecated, and operators should use `cf-deployment` (this repo) to deploy Cloud Foundry. Diego is included with `cf-deployment` by default and does not require a separate deployment.

Here are some docs that might help:
1. [Deployment Guide](https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md)
1. [Migrating from cf-release](https://github.com/cloudfoundry/cf-deployment#migrating). If your deployment is a test deployment, then I would recommend deleting your existing deployment and starting fresh with cf-deployment manifest instead of trying to migrate the one you have.

**Comment by grapematstar** [comment]
@ishustava Thank you. Forgive me for being late. There was a lot of help.
