### ISSUE TITLE
cf push fails with "Server error, status code: 404/500, error code 0"

### ISSUE THREAD

**Issue by kal2t** [cloudfoundry/cf-deployment#555]
### What is this issue about?

As part of our tests, we do "cf push" multiple times and occasionally it fails with one of these errors: "Server error, status code: 404, error code: 0, message: " or "Server error, status code: 500, error code: 0, message: ", or " Server error, status code: 500, error code: 10011, message: Database error ". A second cf push of the same application using the same manifest file usually passes successfully.

To make sure that our code is not the reason, we have tested this with a clean cloud foundry deployment, without any custom code, and a simple test project (https://github.com/cloudfoundry-samples/test-app) and it is still happening.

I have found many similar issues and questions posted online, but no solution.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

Latest cf-deployment version from github (it is regularly updated). Currently 2.5.0.

### Please include the `bosh deploy...` command, including all the operations files:

CF_DEPLOYMENT_DEFINITION="${CF_DEPLOYMENT_DIR}/cf-deployment.yml -o ${CF_DEPLOYMENT_DIR}/operations/use-compiled-releases.yml -o ${CF_DEPLOYMENT_DIR}/operations/bosh-lite.yml -o ${CF_DEPLOYMENT_DIR}/operations/experimental/use-grootfs.yml -o ${CF_DEPLOYMENT_DIR}/operations/enable-privileged-container-support.yml -v system_domain=${CF_SYSTEM_DOMAIN} -v network=${DOCKER_CF_NETWORK}"

bosh -e docker -d cf -n deploy ${CF_DEPLOYMENT_DEFINITION} --vars-store cf-vars-store.yml

The yaml files from the cf-deployment repository are not customized - they are used without changes.

### Please provide output that helps describe the issue:

I'm not sure which logs to check since there are so many but here are some from the api vm:

routing-api 
[mysql] 2018/07/09 08:29:20 packets.go:36: unexpected EOF
[mysql] 2018/07/09 08:29:20 packets.go:36: unexpected EOF
[mysql] 2018/07/09 08:29:20 connection.go:363: invalid connection
[mysql] 2018/07/09 08:29:20 connection.go:363: invalid connection

route_registrar
Warning: Transient problem: timeout Will retry in 1 seconds. 1 retries left.

nginx_cc
[error] 8207#0: send() failed (111: Connection refused)

cloud_controller
Unexpected error while processing request: Mysql2::Error: MySQL server has gone away

All these happen multiple times. Please let me know what additional information to provide.

### What IaaS is this issue occurring on?

None - local dev environment.

### Is there anything else unique or special about your setup?

[Description here]

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by ishustava** [comment]
Hey @kal2t,

Since it's a bosh-lite and seems like your deployment is having database problems, it might be because it's running out of disk. Could your machine be running out of disk space?

I'm seeing that cloud controller logs are saying that the mysql server has become unavailable. Do you see any errors on the `database` VM? You'd want to check logs in `/var/vcap/sys/log/mysql` folder. 

If this error is not that frequent, it could be a load problem. Do your tests push apps in parallel or in serial?

**Comment by kal2t** [comment]
Hi @ishustava,

Thank you for the quick response. There is plenty of free disk space on the machine so this doesn't seem to be the problem.
There are many of these warning in mysql.err.log:

[Warning] WSREP: last inactive check more than PT1.5S ago (PT2.37483S), skipping check

I don't see any errors or warnings in the other log files in the folder.

**Comment by ishustava** [comment]
Thanks for that info!

Do these warnings happen at the same time as the push failures? Do you still have logs on the VMs from when the failures happened? 

So far from the logs you've posted, it looks like mysql becomes unavailable. This could explain both the 404s and 500s returned from the API (if API is unhealthy, the router will lose its route and you will get a 404 when trying to `cf api api.<system_domain>`, for example).

It would be good to see if there are any errors in the mysql logs (at the time of push failures). You might also check disk space of the database itself (by running `df -h` on the VM and checking `%` available in the `/var/vcap/store` disk).

**Comment by ytulsiani** [comment]
Hey @kal2t,

From the base `cf-deployment` manifest it looks like the database VM persistent disk is 10GB. Do you mind confirming that this is true for you? You can do this by running `bosh ssh database/0` and then `df -h` and seeing the size for /var/vcap/store. Additionally, can you provide us with the database VM logs? You can either look into the logs on the VM and let us know if you see anything unusual or you can run `bosh logs database/0` and provide us with the generated tarball that we can look at.

**Comment by kal2t** [comment]
Hi @ytulsiani 

This is exactly what I did - "bosh ssh -d cf database", and then "df -h". It seems it shows the size of the test machine, not the database VM. According to the output of  "du -sh *" /var/vcap/store is using 2.6GB.
Like I said earlier, there is nothing interesting in the database logs, just some warnings.

I have uploaded the logs (had to put the tarball in a zip because it was telling me the file type was not supported).


[cf.database-20180716-094025-018899182.zip](https://github.com/cloudfoundry/cf-deployment/files/2196704/cf.database-20180716-094025-018899182.zip)

**Comment by kal2t** [comment]
I'm afraid it didn't help. I got both

Error processing app files: Error uploading application.
Server error, status code: 500, error code: 0, message: 
 
and

Error restarting application: Server error, status code: 404, error code: 0, message: 

The logs look the same (I can send them if you want).

**Comment by kal2t** [comment]
Hi,

Here is an update from this week (testing with version 2.9.0): We still see errors 404 and 500 occasionally but it's very rare now - maybe 3 times the whole week, and before it used to happen several times a day. We saw a couple of new errors - 502 and staging timeout, but these also happen rarely and I cannot provide any additional information at this time.

**Comment by heyjcollins** [comment]
Hey @kal2t,

I'm scrubbing our issues backlog and see this has been languishing for quite some time and I'm going to close it but if this issue continues to persist for y'all, please comment and reopen.
