### ISSUE TITLE
error receiving from doppler via gRPC context canceled

### ISSUE THREAD

**Issue by ashwithahn** [cloudfoundry/cf-deployment#563]
Hi
**cf nozzle --debug** gives the below error

```
WEBSOCKET RESPONSE
HTTP/1.1 400 Bad Request
X-Vcap-Request-Id: ff57d685-c478-4ff5-4d86-b92337e14afd
Content-Length: 12
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Tue, 17 Jul 2018 06:34:41 GMT
Sec-Websocket-Version: 13
X-Content-Type-Options: nosniff
Error dialing trafficcontroller server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.app-cloudfoundry.com:443).
```

Also found that in log-api -> loggregator_trafficcontroller -> trafficcontroller.log
 ```
Startup: Setting up the loggregator traffic controller
2018/07/17 03:10:09 health bound to: 127.0.0.1:14825
2018/07/17 03:10:09 Metrics endpoint is listening on 127.0.0.1:14825
2018/07/17 03:10:09 Event from finder: {GRPCDopplers:[10.0.16.16:8082]}
2018/07/17 03:10:09 adding doppler 10.0.16.16:8082
2018/07/17 03:10:09 pprof bound to: 127.0.0.1:41142
2018/07/17 03:10:09 ws bound to: 0.0.0.0:8081
2018/07/17 04:08:36 Connecting to 1 dopplers
2018/07/17 04:08:36 websocket handler: Not a websocket handshake: websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header
2018/07/17 04:08:36 Disconnecting from stream (10.0.16.16:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2018/07/17 04:08:36 error receiving from doppler via gRPC context canceled
2018/07/17 04:08:37 Connecting to 1 dopplers
2018/07/17 04:08:37 websocket handler: Not a websocket handshake: websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header
2018/07/17 04:08:37 Disconnecting from stream (10.0.16.16:8082) (doppler.disconnect=false) (ctx.disconnect=1)
2018/07/17 04:08:37 error receiving from doppler via gRPC context canceled

```
Please help

**Comment by ishustava** [comment]
Hey @ashwithahn,

Would you mind providing us with some more info about your CF deployment? (I'm taking these questions from the [issue template](https://github.com/cloudfoundry/cf-deployment/blob/master/ISSUE_TEMPLATE.md))

1. Which version of cf-deployment are you using?
1. Which IaaS are you deploying to?
1. Did you use [bosh-bootloader](https://github.com/cloudfoundry/bosh-bootloader) to set up infrastructure prior to deploy?

It looks like the first error is `Not a websocket handshake`, so I'm curious if your load balancer (if you have any) supports websockets.

**Comment by ashwithahn** [comment]
Hi @ishustava , 
1. I am using
```
name: cf
manifest_version: v2.9.0
```
2. Deploying to AWS with CLB as Load balancer
3. No, we did not use bosh-bootloader to set up infrastructure prior to deploy

Please let me know if any further logs/ information needed to resolve this. Thank you.

**Comment by ishustava** [comment]
Thanks @ashwithahn.

Are you using [`aws.yml` ops file](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/aws.yml)? If not, could you apply it and see if error repeats?

**Comment by ashwithahn** [comment]
@ishustava : Thank you. We resolved this by deploying aws.yml file again with cf deployment and it worked. Somehow just cf deployment was not picking up this changes in aws.yml file. I would like to close to issue.
