### ISSUE TITLE
Add nginx buildpack to default buildpacks

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cf-deployment#577]
Now that the nginx buildpack has hit version 1.0 and been listed in the official [system buildpacks](https://docs.cloudfoundry.org/buildpacks/#system-buildpacks), it seems like we should include it in the default `install_buildpacks` here.

Depends on https://github.com/cloudfoundry/nginx-buildpack/issues/7, unless we want to grab the buildpack from a github release instead of a bosh release like the other system buildpacks.

cc @sclevine

**Comment by heyjcollins** [comment]
Hey @jmcarp,

We've now got the [PR for this](https://github.com/cloudfoundry/cf-deployment/pull/687) so I'm going to close this issue.

Happy Holidays!
