### ISSUE TITLE
DNS for SSH Proxy

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cf-deployment#58]
I looked through this repo's README, https://docs.cloudfoundry.org, docs and README for `capi-release`, and docs and README for `bosh-bootloader`, and couldn't find any instructions on how to set up DNS for the load balancer in front of the SSH Proxy instances.

Digging through CC code I found that it makes a [hard-coded assumption](https://github.com/cloudfoundry/cloud_controller_ng/blob/25f6536e5b79b7e7d86762d45142ea83d8ae5798/bosh/jobs/cloud_controller_ng/templates/cloud_controller_api.yml.erb#L146) that you have `ssh.SYSTEM_DOMAIN` DNS setup to point to your SSH Proxy LB (or the SSH Proxies directly if you're skipping the LB).

It would be nice if `cf-deployment` explicitly asked the user for system, app, and SSH domains as the only things the user needs to provide for a basic deployment.  Basically, the user needs to be responsible for DNS and ingress, and `cf-deployment` can do the rest.  So by the same token, `cf-deployment` ideally wouldn't assume how the user has chosen to set up that DNS.

What if:

* `capi-release` made this a required property in the job spec
* `cf-deployment` made it a required input from the user
* docs.cloudfoundry.org explicitly explained the DNS requirements for setting up an environment, and
* `bosh-bootloader` and `cf-deployment` referred user to those official docs

?

/cc @zrob @evanfarrar @wendorf @drich10

**Comment by cppforlife** [comment]
> cf-deployment made it a required input from the user

...or default to something meaningful. silver ideal is to only ask for `system_domain` (ideally not even that). if exposed properly people can always override it if it's necessary.

**Comment by drich10** [comment]
I agree with @cppforlife, I'd still prefer to configure as little as possible as a user. This is assuming we do a better job of explaining the responsibility of DNS management to the user.

**Comment by wendorf** [comment]
:+1: to that. Most (all?) of the *.sys domains are hard-coded. What's the customer value in letting it be configured?

**Comment by Amit-PivotalLabs** [comment]
@cppforlife how would you imagine not asking for system domain?

@wendorf @drich10 I'm not a fan of magic, I'd much rather have an explicit dependency I can understand than magical wiring that I have to have tribal knowledge about.

The customer value in letting it be configured is that customers want to configure it.  Pivotal Web Services manages the `run.pivotal.io` and `cfapps.io` domains differently.  Customers also may wish to have multiple shared app domains.

Perhaps you're asking about the value in *making* users configure it, not about *letting* them configure it.  Making them configure it makes the dependency clear and simple, less magical.

The issue actually conflates two things.  There's less value in configuring the SSH domain, but it's also undocumented.

**Comment by dsabeti** [comment]
Not to pile on, but I definitely don't want to add more required variables for basic OSS consumers of cf-deployment. That doesn't mean we can't make it easy(er) for other deployers/vendors out there in the world to extend cf-deployment to allow for more complex configuration.

With the way that CC "hard-codes" the ssh proxy location, it's impossible to even override this with an ops file. However, I was able to override the `app_domains` with a pretty simple ops file:
```
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/app_domains
  value:
  - ((app_domain))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_worker/properties/app_domains
  value:
    - ((app_domain))
- type: replace
  path: /instance_groups/name=cc_clock/jobs/name=cloud_controller_clock/properties/app_domains
  value:
  - ((app_domain))
```
And manifest generation looked like this:
```
bosh int cf-deployment.yml \
  --var-errs \
  --vars-store ~/workspace/gcp-spike/deployment-vars.yml \
  -o ~/workspace/gcp-spike/override-apps-domain.yml \
  -v system_domain=cf-dsabeti.cf-app.com \
  -v app_domain=apps.cf-dsabeti.cf-app.com
```
which I think is sort of a nice UX -- you only get the new variable if you included the ops file.

If CAPI made the ssh proxy url configurable (but with the same default), vendors could similarly ship an ops file that requires a property called `((ssh_proxy_domain))` variable and override the default value.

**Comment by cppforlife** [comment]
@dsabeti's snippets above are exactly what i was thinking. nice!

**Comment by dsabeti** [comment]
Hey @Amit-PivotalLabs, there hasn't been much activity on this thread for a while, and I want to take action and the close this out.

It looks like capi-release [still computes the ssh-proxy domain from the system domain](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/bosh/jobs/cloud_controller_ng/templates/cloud_controller_api.yml.erb#L154). Do you want to submit a github issue for them to make the ssh-proxy domain configurable?

As for the "app domain," it's actually a slightly more complicated topic than we've implied here. There isn't really such a thing as the "app domain" -- the field simply [seeds the SharedDomains](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/seeds.rb#L69-L78) table. If you change the value of app_domains after the first deploy, I'm not sure that anything gets updated in your Cloud Controller DB. It might make sense to support an ops file for configuring the app_domains on the initial deploy anyway, but we'd have to set expectations that the ops-file is only relevant for a bootstrap deploy.

cc @anEXPer

**Comment by Amit-PivotalLabs** [comment]
I think at minimum the official documentation for deploying Cloud Foundry
should explicitly document the DNS requirements the deployer must fulfill.
It should also recommend some tooling to simplify IaaS paving, and said
tool should either automate the DNS provisioning or reiterate in its
documentation that there's some DNS setup pre-requisites, pointed back to
the official CF docs as the source of truth as to what those pre-requisites
are.

**Comment by anEXPer** [comment]
I suspect (but have not tested) that changing app_domains does affect the DB... but not how users might expect. I suspect it's additive only, which means if you have only one, and you change it, what you will actually get is a second shared domain. CC uses the first shared domain as a default, and the "changed" "app domain" won't be used.

The idea of an "app domain" configuration may have to go away. We'd be adding a concept in manifest tooling that doesn't actually exist in the spec.

**Comment by Amit-PivotalLabs** [comment]
Yes, it's additive, but the second app domain you add will just be a shared
app domain, not *the default* shared app domain.

It's not ideal to have to seed data in the manifest, since it's very
misleading (changing the value in the manifest makes the manifest no longer
an accurate declaration of the expected or desired state).  There's already
a way to add a shared app domain via the cf CLI as an admin.  But I can't
think of a great way in the short-term to offer a simple, packaged CF setup
experience which allows operators to seed the app domain(s) while fixing
this misleading issue.  Even if you take the apps domains out of the
manifest and into some other declaration that's used to create these
resources, how do you prevent that declaration from becoming misleading?

**Comment by dsabeti** [comment]
Howdy folks. Reviving this thread again. I think we can address everything brought up here.

First of all, docs now include an explanation of DNS requirements for deployers: http://docs.cloudfoundry.org/deploying/common/dns_prereqs.html

As for seed value and app domains, we think that this story should prevent stale seed data from living on in deployment manifests, but still allows an out-of-the-box successful deploy:
https://www.pivotaltracker.com/story/show/149282005

How do these sound as solutions?

**Comment by jleavers** [comment]
It would be good if the docs pointed out exactly where an external LB should point SSH traffic to as well. A user moving to `cf-deployment` from an older setup might look for `proxy_z1` & `proxy_z2` and then have to consult the output of `bosh instances --ps` to find out that `ssh_proxy` is with `diego-brain`, for example.

**Comment by dsabeti** [comment]
I think that's good advice, @jsievers. As I look through that doc, there are few other things that look cf-release-specific, so we should make sure they get updated once cf-deployment is GA.

**Comment by jsievers** [comment]
@dsabeti I guess you meant @jleavers :)

**Comment by dsabeti** [comment]
Heh, it seems so. Sorry about that!

**Comment by dsabeti** [comment]
Hi @jleavers, I made a PR (https://github.com/cloudfoundry/docs-deploying-cf/pull/181) to the docs to describe where the `ssh_proxy` is located. I'll close the issue.
