### ISSUE TITLE
Issue with bosh-s3cli vs IAM profile vs govcloud

### ISSUE THREAD

**Issue by aleliaert** [cloudfoundry/cf-deployment#581]
### What is this issue about?

We're trying to get our current CF recipe into AWS region us-gov-west-1 and ran into a snag with IAM profiles.  When bosh is creating CF VMs and the VMs are reaching out to the director blobstore (in govcloud S3) we get:

```
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records
```

It appears that bosh-s3cli (named bosh-blobstore-s3?) that comes with our vintage of stemcell has a glitch with IAM profiles and govcloud, likely due to different endpoints being needed for govcloud services.  We've seen such issues with other tools such as Terragrunt.

For troubleshooting we validated that the aws CLI could access the blobstore bucket via IAM profile, just needed S3 endpoint specified when invoked.

We also we put the latest bosh-s3cli as of yesterday (4dc50e6a981c036cec6677b412981166664e1b84) on a VM where the problem occurred, fed it the same json input file, and it appeared to succeed.  So that is encouraging.

Questions we have:
- Is bosh-s3cli (aka bosh-blobstore-s3?) coming from the stemcell?
- If so, what's a good way to see which stemcells would have a sufficiently new bosh-s3cli?  (That comes with the stemcell right?)
- Is there an open-source repo that lists stemcell change release notes and has traceability back to things like bosh-s3cli?  (I do see release notes on pivnet)
- Are there any good guides on handling open-source CF stemcell vs CF version compatibility?  We know that testing is on us to some degree for open-source, but looking for guidance on good practices generally are

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

- bosh-deployment tag v1.0.0
- cf-deployment v1.3.1  (why I'm here)
- CF stemcells 3468.20 and 3468.54

### Please provide output that helps describe the issue:

```
Task 130 | 16:57:56 | Updating instance consul: consul/66f9605b-552a-4571-984e-62c9e323fac8 (0) (canary) (00:00:02)
                    L Error: Action Failed get_task: Task b070786e-3130-4569-4ead-38fbae4c1e89 result: Preparing apply spec: Preparing package confab: Fetching package blob: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json get 17d70e71-9286-4689-817c-f28d24e8585e /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get792930942', stdout: '', stderr: '2018/08/01 16:57:57 performing operation get: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
	status code: 403, request id: BFE92F7446135832, host id: WJUyH0wksi5QEgASKcWlYz/r/lixXLBJeCj55lgvs2AclEBc7tR1b0H6i+b2+R5nzvFllEwZBjA=
': exit status 1
```

### What IaaS is this issue occurring on?

AWS region us-gov-west-1

### Is there anything else unique or special about your setup?

The gov-itude may be relatively special.

**Comment by aleliaert** [comment]
Update - we gave cf-deployment v2.7.0 a whirl with 3586.26 stemcell.  Good news and bad news (for us):

Bad news is that we're getting a different error at nearly the same spot.  The input file to bosh-s3cli (bosh-blobstore-s3) contains only "null".  Error observed is:
```
Task 181 | 17:54:16 | Updating instance consul: consul/d707d0a9-2b8f-4bf3-b166-b62d50dd511c (0) (canary) (00:00:01)
                    L Error: Action Failed get_task: Task ede7d167-26bd-4f8a-5477-871b8a3c91c9 result: Preparing apply spec: Preparing package confab: Fetching package blob: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json get c838333c-7a91-44cd-9936-d56ef6866ad3 /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get017641595', stdout: '', stderr: '2018/08/03 17:54:15 bucket_name must be set
```

But the good news: if give bosh-blobstore-s3 a valid json file (as we had with cf-deployment v1.3.1) the S3 access succeeds.  That proves that the latest stemcell gets around our IAM govcloud issue.

Any leads?  Might we need a bosh director newer than 266.4 (as used with tagged and latest master of bosh-deployment)?

Thanks!

**Comment by aleliaert** [comment]
@ishustava - Thanks for the help!

> How did you deploy your bosh director? Are you using bosh-deployment repo?

We are using `bosh-deployment` to create the YML manifest for the director.  Have tried v1.0.0, v1.1.0, and master as of last week (`0cab850a`) and today (`db872958`).

> Looks like you are using s3 as your blobstore for the director? Are you using this ops file from bosh-deployment: https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml?

Yes we are specifying S3 as the director blobstore source.  For security/availability we're hoping to use S3 with IAM profile access for all state throughout our bosh/cf stack.  We hadn't been using the aws/s3-blobstore yet, but we rolled our own  ops file that looks very similar but sets `credentials_source: env_or_profile` and omits the key ids/secrets.

> I'm not sure what you mean by "give bosh-blobstore-s3 a valid json file". How are you providing that json file and for which command?

We're referring to the file `/var/vcap/bosh/etc/blobstore-s3.json` which is provided as an argument to `bosh-s3cli`, as shown in the errors coming out of our bosh deploy of cf.

With an older stemcell and `cf-deployment` (as specified in the first post) we were getting that file with seemingly valid JSON inside, but then `bosh-s3cli` had an apparent IAM profile issue.  We saved off the contents of that file for troubleshooting...  And so when we saw that file contain `null` with newer stemcell/cf (second post), it seemed like a good experiment to plop in the previous json content and at least see if the newer stemcell's `bosh-s3cli` would get past the IAM issue.  It did.

**Hmmm what to try next...**

- We just compared our home-grown ops file against the latest [https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml (which changed on August 3) and there were subtle differences - we didn't have an `options` layer or `bucket_name` under `agent/env/bosh/blobstores`.  We tried making ours match in this regard (but still with `credentials_source: env_or_profile` and no key ids/secrets) and still the same error with the null json file.  Interestingly our ops file with older syntax did appear to work in commercial AWS, maybe the settings can be specified in several ways or the director changed and expects the fields in different places?

- Will try [https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/s3-blobstore.yml) directly and feed it a key id/secret to see what happens.

- Any leads on where to look for clues on the `/var/vcap/bosh/etc/blobstore-s3.json` being null?  Logs of things handling the data, or places where it's stored upstream?  Might do a dive into bosh director logs later today but any tips would be appreciated. :)

**Comment by aleliaert** [comment]
**solved**

Lessons learned:
- The newer stemcell got us the newer `bosh-s3cli` which works with IAM and AWS govcloud regions
- Including the `options` layer under `agent/env/blobstores` got around the second issue of null json file fed to `bosh-s3cli` on latest stemcell
- Bonus lesson - learned that we had to delete our VMs/deployment before expecting blobstore-related config changes to take effect

**Comment by ishustava** [comment]
@aleliaert,

Alternative solution to the bonus lesson - you can run `bosh deploy --recreate`, and it should propagate bosh agent changes, instead of deleting the deployment or VMs.
