### ISSUE TITLE
CF-deployment + TCP routing and DNS part

### ISSUE THREAD

**Issue by techie20122018** [cloudfoundry/cf-deployment#584]
I am able to deploy cloud foundry from https://github.com/cloudfoundry/cf-deployment/ . I set system domain as  example.com . I am confused at DNS part and enabling TCP routing part .

how to proceed on this ?

**Comment by ishustava** [comment]
Hey @techie20122018,

It all depends on your infrastructure. Have you seen [these docs](https://docs.cloudfoundry.org/adminguide/enabling-tcp-routing.html#pre-deploy)? Specifically, step #2 talks about setting up DNS needed for TCP Routing.

**Comment by techie20122018** [comment]
After the deployment of cf , it has created many VMs,I am seeing two router vms and two tcp router VM's , As per the document does the domain name need to load balance between two of the tcp router VM's?

**Comment by ishustava** [comment]
It'll be useful to know answers to these: 
- How did you set up your infrastructure? Did you use [bbl](https://github.com/cloudfoundry/bosh-bootloader)?
- Which IaaS are you using?

Usually we use a subdomain of the system domain as our TCP domain, i.e something like this: `tcp.<SYSTEM_DOMAIN>`. But it looks like you don't have system domain set up yet (you said above that you're using example.com).

You can also refer to [these docs](https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md#pave-your-iaas-and-get-a-bosh-director) on how to setup your infrastructure, load balancers, DNS etc to work with cf-deployment.

**Comment by techie20122018** [comment]
I am using vsphere . I used bosh director for doing cf-deployment . i dint configure the LB or DNS so far . 
do i need to create a LB for example.com with tcp router IP as the backend ?

**Comment by ishustava** [comment]
You would have to purchase a DNS name (and I believe you [cannot buy example.com](https://en.wikipedia.org/wiki/Example.com).

I'm not too familiar with vsphere and don't know how to setup load balancers there. 

Another option is to add public IPs to the router and tcp-router VMs, and then setup round robin DNS.

**Comment by heyjcollins** [comment]
Since there's been no response on this issue since August, I'm going to close it. If you'd like to see it re-opened, please comment on the issue and reopen.
