### ISSUE TITLE
TCP routing on Vpshere envionment

### ISSUE THREAD

**Issue by techie20122018** [cloudfoundry/cf-deployment#585]
Any idea on how to do TCP routing on Vsphere environment for cloud foundry?

**Comment by heyjcollins** [comment]
Hey @techie20122018 - apologies for the delay here. We don't deploy CF to vSphere in our CI so I can only point you to documentation which you've likely already reviewed.
- [https://docs.cloudfoundry.org/adminguide/enabling-tcp-routing.html](https://docs.cloudfoundry.org/adminguide/enabling-tcp-routing.html)
- [https://dzone.com/articles/tcp-routing-comes-to-cloud-foundry](https://dzone.com/articles/tcp-routing-comes-to-cloud-foundry)

If you're still having problems making TCP routing work, I'd suggest you reach out for help on the [#cf-deployment](https://cloudfoundry.slack.com/messages/C2U7KA7M4) channel of CloudFoundry Slack.

I'm going to close this issue with this comment and hope you're able to resolve your issue.
