### ISSUE TITLE
Application Deployment in cloudfoundry 

### ISSUE THREAD

**Issue by wilfredwilly** [cloudfoundry/cf-deployment#596]
Application Deployment in cloudfoundry

Currently  i want to deploy a docker image on the cloud-foundry with 2GB of disk space but cloud foundry allows me to deploy an application with lesser than 2GB of disk space

Please let me know the configuration changes to be done

ERROR
=====
cf push testing_disk -p Java-HelloWorld-Sample-1.0.war -k 3G
Pushing app testing_disk to org techm_dev / space dev as admin...
Getting app info...
Creating app with these attributes...
+ name:         testing_disk
  path:         /root/Java-HelloWorld-Sample-1.0.war
+ disk quota:   3G
  routes:
+   testingdisk.app-cloudfoundry.com

Creating app testing_disk...
The app is invalid: disk_quota too much disk requested (requested 3072 MB - must be less than 2048 MB)
FAILED

**Comment by heyjcollins** [comment]
Hi @wilfredwilly - 
You may need to increase the quota for your org (or space) and retry.
`cf set-quota` - can be used to set quota for a specific org in your CF.

If your interested, you can get all the quota related `cf` cli commands:
```cf -h -a | grep quota```

If this resolves your issue, please close it out.

Thanks much!

**Comment by heyjcollins** [comment]
Since there's been no response on this issue since August, I'm going to close it. If you'd like to see it re-opened, please comment on the issue and reopen.

**Comment by ngdeepak** [comment]
Hi, Thanks for the previous response. I ran into similar issue. Provided resolution using cf set-quota does not resolve the issue as quota can not consider  handle disk space. Please let me know how an administrator can increase the disk size quota (not memory) for a given space? Appreciate the help

**Comment by wilfredwilly** [comment]
Hi Deepak,

It is an intermittent issue when your environment with older framework.
I installation the entire environment  with higher release(bosh & cloud foundry ) and issue got resolved.
