### ISSUE TITLE
Help needed on cf api target on bosh-lite via bbl

### ISSUE THREAD

**Issue by ketakig12** [cloudfoundry/cf-deployment#597]
I am trying to deploy adn use CF on bosh-lite using bosh-bootloader using documentation [Deploying Cloud Foundry against bosh-lite using bosh-bootloader (aka bbl)](https://github.com/cloudfoundry/cf-deployment/blob/master/iaas-support/bosh-lite/README.md) on GCP.
I have successfully deployed CF with the commands provided in the document and I can see in CF deployment via bosh that all the vms are in running state.

Now, I am having trouble with cf target and login. Can you please help on how I can target CF API and login?

**Comment by heyjcollins** [comment]
Hi @ketakig12 - 
Thanks for reaching out.
1. Can you provide the actual bosh deploy command you ran to deploy cf.
1. Can you also provide the error responses your getting for cf target and cf auth commands.

Lastly, I want to thank you for pointing out an oversight in our documentation (inadvertently). As of cf-deployment 3.0, you need to upload a runtime-config before you execute the bosh deploy. This step was not added to [the instructions you linked to](https://github.com/cloudfoundry/cf-deployment/blob/master/iaas-support/bosh-lite/README.md) in your issue description. I'm going to update those now. 

Thank you for bringing this up!

Josh

**Comment by ketakig12** [comment]
Hi Josh,

Thanks for your response and pointing out the extra step needed (though even I missed to run that step before deploying CF).

1. Can you provide the actual bosh deploy command you ran to deploy cf ->
Ran below command from local machine / laptop, with targeted bosh-lite director.
```
$ bosh \
-d cf \
deploy \
cf-deployment/cf-deployment.yml \
-o cf-deployment/operations/bosh-lite.yml \
-v system_domain=$SYSTEM_DOMAIN
```

2. Can you also provide the error responses your getting for cf target and cf auth commands ->
Running below command from local machine / laptop
```
$ cf api https://api.<SYSTEM_DOMAIN> --skip-ssl-validation
Setting api endpoint to https://api.<SYSTEM_DOMAIN>...
Request error: Get https://api.<SYSTEM_DOMAIN>/v2/info: dial tcp: lookup api.<SYSTEM_DOMAIN>: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED
```
Do I need to setup this SYSTEM_DOMAIN before/after deploying CF on bosh-lite? If so, can you please point me to the documentation which will help me with this?

Thanks,
Ketaki

**Comment by staylor14** [comment]
Hey @ketakig12,

It's not clear to me what value you're using in the case of `cf api`.  In your `bosh deploy` step, you're using the environment variable's value with `$`.  Is `<SYSTEM_DOMAIN>` just shorthand for `api.$SYSTEM_DOMAIN`?

If that's just shorthand, and you are passing a valid domain in, can you please try pinging it?  I'm wondering if the ip address matches what you're expecting.  If not, you probably need to update your DNS.

Regards,
--Steve

**Comment by staylor14** [comment]
@ketakig12 I'm sorry I didn't see your response before!

Yes, we can make more explicit the requirement that you can resolve the domain name that you choose when attempting to connect to it via the Internet.

If you just want to play with it without creating an actual domain, you can modify your local hosts file.

Thanks for the feedback!
--Steve

**Comment by heyjcollins** [comment]
@ketakig12,

We've updated the documentation for bosh-lite so it includes the runtime config DNS step.
It will go live in the next release of cf-d.

Thanks for bringing this to our attention!

Josh
