### ISSUE TITLE
sha1 for releases referenced by URL missing in generated manifest

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/cf-deployment#6]
I'm getting `Expected SHA1 when specifying remote URL for release 'etcd'` - what might I be doing wrong?

Here is what my `config.json` looks like:

```
{
  "cf": "integration-latest",
  "etcd": "integration-latest",
  "stemcell": "integration-latest",
  "stubs": ["<redacted>"]
}
```

and the content of `blessed_versions.json` actually has those sha1 values:

```
{
  "releases": [
    {
      "name": "cf",
      "commit": "2eb1e78ae64b4454ff8cd392c79bef25574ffb4c"
    },
    {
      "name": "etcd",
      "version": "18",
      "sha1": "222e26f1f38a23f4355ec2517683fdc7c70704aa",
      "url": "https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=18"
    },
    {
      "name": "consul",
      "version": "6",
      "sha1": "b9774d0f38235336c2ffb07f762de8177ab9a172",
      "url": "https://bosh.io/d/github.com/cloudfoundry-incubator/consul-release?v=6"
    }
  ],
  "stemcells": {
    "aws": {
      "type": "bosh-aws-xen-hvm-ubuntu-trusty-go_agent",
      "version": "3126",
      "url": "https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3126",
      "sha1": "c57c5294a33331d75747bf7593ec8fb822fdd497"
    }
  }
}
```

After manually adding the `sha1: 222e26f1f38a23f4355ec2517683fdc7c70704aa` for etcd release 18 to the `releases` section of the manifest, the deployment got past that check.

This probably happens because [`./tools/prepare_deployments`](https://github.com/cloudfoundry/cf-deployment/blob/master/tools/prepare-deployments#L327-L346) doesn't have the `sha1:` field?

**Comment by Amit-PivotalLabs** [comment]
That's a legit bug.  Our next two stories in this track are to have acceptance tests for this tooling.  We weren't able to implement the acceptance tests sooner because the changes to BOSH to use URL and SHA1 for releases in the manifest were still in PR review.  Thanks for catching this, I've prioritized the fix.

**Comment by rosenhouse** [comment]
Thanks for bringing this up, and for your PR.  We're working a fix through our CI pipeline, will update this issue once it lands on `master`

**Comment by robdimsdale** [comment]
We had this work in flight so we fixed this in [this commit](https://github.com/cloudfoundry/cf-deployment/commit/f0b21dd05fb92955a79a35aba91a371cab2f10cc)

This commit has made it to master, so we're closing this issue and your PR.

Cheers!
@rosenhouse & Rob
