### ISSUE TITLE
SignatureAlgorithm mismatch for SHA256 when cf uaa integrated with ADFS using SAML

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/cf-deployment#605]
Successfully integrated ADFS with CF UAA using SAML. It works fine for SHA1 signature alorithm.
On ADFS machine algorithm is changed to SHA256 using below link:
https://docs.microsoft.com/en-us/azure/active-directory/active-directory-federation-sha256-guidance
When using SignatureAlgorithm SHA256 in cf-deployment it's getting deployed successfully, but the SP (cf manifest) metadata still contains SHA1 instead of SHA256. 
Unable to login into CF and when checking for logs in EventViewer for ADFS, it throws an error for algorithm mis match.
Refered below url for changes in cf manifest:
https://bosh.io/jobs/uaa?source=github.com/cloudfoundry/uaa-release&version=59#p%3dlogin.saml.signatureAlgorithm  
How can we change in CF (SP metadata)?

Downloaded the SP metadata using below command:
$https://login.YOUR-SYSTEM-DOMAIN/saml/metadata

used cf-deployment v1.36.0 and deployed on Azure public cloud using bosh 2.0

Deployment_command:
bosh -e env_name -d cf deploy cf-deployment/cf-deployment.yml -o custom_ops/haproxy-ha-deploy.yml -o cf-deployment/operations/use-azure-storage-blobstore.yml -o custom_ops/use-shield.yml -o custom_ops/multi_cell.yml -o custom_ops/add-adfs.yml -l ../dev_env.yml

Added a new ops file for adfs integration with cf uaa using https://bosh.io/jobs/uaa?source=github.com/cloudfoundry/uaa-release&version=59 (service_provider section) .

Below is the screenshot of the error:
![algorithm_mis_match](https://user-images.githubusercontent.com/25821409/44831731-77f3fe00-ac45-11e8-9657-41f9ae3f1a86.PNG)
![error_while_logging_in](https://user-images.githubusercontent.com/25821409/44832037-c35adc00-ac46-11e8-9380-618b011c4063.PNG)

Can someone help me on this?

**Comment by ishustava** [comment]
Hey @lordcf,

> When using SignatureAlgorithm SHA256 in cf-deployment it's getting deployed successfully
How are you setting algorithm in your cf-deployment? Via an ops file?

> the SP (cf manifest) metadata still contains SHA1 instead of SHA256
This suggests to me that you probably haven't set the property correctly. Off the top of my head you can write the following ops file to set the `signatureAlgorithm` property:
```
- type: replace
   path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/signatureAlgorithm?
   value: "SHA256"
```

**Comment by lordcf** [comment]
Hi @ishustava,

Thank you for your reply & solution.
Also the solution that you provided has worked for me.
Yes you were right, there was a mistake in setting property for signatureAlgorithm.
I was able to change the signatureAlgorithm from SHA1 to SHA256.
