### ISSUE TITLE
BOSH Lite docs for GCP should include DNS configuration steps

### ISSUE THREAD

**Issue by tjvman** [cloudfoundry/cf-deployment#627]
### What is this issue about?

Documentation for how to get a CF running in BOSH Lite on GCP seems incomplete.
We encountered this issue when trying to deploy a CF to a GCP BOSH Lite by following the instructions linked in [the bosh-lite README](https://github.com/cloudfoundry/cf-deployment/blob/29d4094673449520dec53d5d6ef1bc69a7faed12/iaas-support/bosh-lite/README.md).

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

HEAD of master, so https://github.com/cloudfoundry/cf-deployment/commit/0e698ff16171626ab5d2a2f569aa30ead70f7809 as of 9/24/18

### Please include the `bosh deploy...` command, including all the operations files:

```
bosh -d cf deploy ./cf-manifest-no-vars.yml --vars-store creds.yml
```

(I've omitted the ops files because I can't track down the `bosh interpolate` that we ran, but I don't believe this is a deploy issue)

### Please provide output that helps describe the issue:
Trying to resolve `api.mydomain.cf.com`:

```
$ dig api.mydomain.cf.com
; <<>> DiG 9.11.3-1ubuntu1.2-Ubuntu <<>> api.mydomain.cf.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 44678
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;api.mydomain.cf.com	IN	A

;; Query time: 27 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Sep 24 10:12:18 PDT 2018
;; MSG SIZE  rcvd: 48
```

### What IaaS is this issue occurring on?

GCP

### Is there anything else unique or special about your setup?

Not that I'm aware of.

### Tag your pair, your PM, and/or team!
@cloudfoundry/cf-cli

**Comment by cdutra** [comment]
The story has been accepted. I'm closing this issue, feel free to reopen if necessary. Thanks
