### ISSUE TITLE
Specifying system domain for CF deployment

### ISSUE THREAD

**Issue by avoxm** [cloudfoundry/cf-deployment#639]
### What is this issue about?

In documentation it suggests to use bosh lite to run on GCP. 
And at the end here is the suggested command to deploy cf

```bosh \
-d cf \
deploy \
cf-deployment/cf-deployment.yml \
-o cf-deployment/operations/bosh-lite.yml \
-v system_domain=<SYSTEM_DOMAIN>
```

Now since I do not have the VM running cf on it how I can configure Cloud DNS to point to a VM with a static IP ?

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

**Latest** 

### Please include the `bosh deploy...` command, including all the operations files:

```bosh \
-d cf \
deploy \
cf-deployment/cf-deployment.yml \
-o cf-deployment/operations/bosh-lite.yml \
-v system_domain=<SYSTEM_DOMAIN>
```

### What IaaS is this issue occurring on?

GCP

### Is there anything else unique or special about your setup?

Nothing special. It is exactly the way it is specified in documentation.

**Comment by Changdrew** [comment]
hi @avoxm, we have an ops file to configure that called [set-router-static-ips.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/set-router-static-ips.yml) which you can run by using something like this:
```sh
-d cf \
deploy \
cf-deployment/cf-deployment.yml \
-o cf-deployment/operations/bosh-lite.yml \
-o cf-deployment/operations/set-router-static-ips.yml \
-v system_domain=<SYSTEM_DOMAIN>
```

**Comment by heyjcollins** [comment]
Hey @avoxm,

I'm cleaning up issues submitted in the past and see we've responded. I'm hoping this solves your issue and I'm going to close this issue.
Feel free to reopen it if you require further assistance or come visit us on the [cloudfoundry, cf-deployment](https://cloudfoundry.slack.com/messages/C2U7KA7M4) slack channel for more real-time support.
