### ISSUE TITLE
vcloud / oracle / alicloud bosh,cf-deployment, app push Is the cloud supported?

### ISSUE THREAD

**Issue by leedonghyean** [cloudfoundry/cf-deployment#641]
Hi, 

I need to ask you something.

vcloud / oracle / alicloud bosh,cf-deployment, app push Is the cloud supported?

If a guide exists ?

Best,
LEE

**Comment by heyjcollins** [comment]
Hi @leedonghyean,

CF Deployment is cloud-agnostic.
There are folks who run it in vSphere (which I think you're referring to here?).
We have some ops files for specific IaaS's in our operations directory.
See [the README there](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/README.md) for more information.

I'm going to close this issue and invite you to reach out to us on the [cf-deployment channel](https://cloudfoundry.slack.com/messages/C2U7KA7M4) on cloudfoundry slack
