### ISSUE TITLE
Failure deploying cf on to bosh - AWS

### ISSUE THREAD

**Issue by xavier007009** [cloudfoundry/cf-deployment#648]
I have received the below error while deploying the cf https://github.com/cloudfoundry/cf-deployment.git

Command used - 
bosh -e vbox -d cf deploy cf-deployment/cf-deployment.yml -o cf-deployment/operations/bosh-lite.yml -o cf-deployment/operations/use-compiled-releases.yml --vars-st                                                                               ore deployment-vars.yml -v system_domain=34.239.203.121.sslip.io

manifest from the git repo - cf-deployment.yml

Task 68 | 16:17:59 | Preparing deployment: Preparing deployment (00:00:04)
Task 68 | 16:18:09 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 68 | 16:18:09 | Updating instance diego-api: diego-api/37b56829-4885-41b8-b0c0-622f434cb94e (0) (canary)

 (00:20:41)
                   **L Error: 'diego-api/37b56829-4885-41b8-b0c0-622f434cb94e (0)' is not running after update. Review logs for failed jobs: bbs, silk-controller, locket
Task 68 | 16:38:50 | Error: 'diego-api/37b56829-4885-41b8-b0c0-622f434cb94e (0)' is not running after update. Review logs for failed jobs: bbs, silk-controller, locket**

Task 68 Started  Thu Oct 25 16:17:59 UTC 2018

**Comment by devakar** [comment]
I am also facing the same issue while deploying on BOSH-Lite.
Any development regarding the issue.

**Comment by xavier007009** [comment]
@devakar Yes this was resolved and the issue seem to be with the local dns.
Make sure you run the command . I might have messed up with the dns. Redoing the whole setup again worked , but this issue was related to DNS
bosh update-runtime-config bosh-deployment/runtime-configs/dns.yml --name dns
https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md
