### ISSUE TITLE
Inconsistent Job Names

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/cf-deployment#65]
We have noticed that the jobs in CF are either using underscores or hyphens. We should decide to use one or the other consistently.

For example, we have [diego-bbs](https://github.com/cloudfoundry/cf-deployment/blob/02d5ae5d8b3ef2ac928914be501ae1fe9ee4a03b/cf-deployment.yml#L299) and [cc_clock](https://github.com/cloudfoundry/cf-deployment/blob/02d5ae5d8b3ef2ac928914be501ae1fe9ee4a03b/cf-deployment.yml#L958).

/cc @apoydence

**Comment by dsabeti** [comment]
Hey @enocom. Yeah I agree completely. I prefer hyphens for instance group names, but most jobs (from releases) and variables in the manifest use underscores. Would it be too confusing to have one pattern for instance group names (what you see when you run `bosh vms` or `bosh instances`), and another for job template names and internal variables?

**Comment by enocom** [comment]
If you were to call out the naming convention in the README and make sure there weren't any deviations, I think a pattern for instance groups and jobs would work. It might even help to distinguish the two.

**Comment by dsabeti** [comment]
This story was accepted so I'm closing the story.
