### ISSUE TITLE
capi-release failing to compile on cf-deployment v6.0.0

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/cf-deployment#663]
### What is this issue about?

Follow up of the conversations in:
 - https://cloudfoundry.slack.com/archives/C07C04W4Q/p1541776178160100
 - https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1541777628114700

We are having trouble with the official bosh releases of capi-release v1.71.0 and v1.72.0, deploying on cf-deployment v6.0.0 with Xenial images on AWS.

We get an error compiling the `cloud_controller_ng`: `var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': libyaml-0.so.2: cannot open shared object file: No such file or directory - /var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/x86_64-linux/psych.so (LoadError)`

See detailed output below.

But it works fine when:
 - Rebuilding the source release by cloning the repo and using `bosh create-release`
 - Including `operations/use-compiled-releases.yml`

### Rebuilding our own release

We rebuilt the the release from my own computer, without changes, and works fine on our  environment  :thinking_face: I only did downloaded the capi-release git repo and rebuild  it locally, without changes

```
git clone https://github.com/cloudfoundry/capi-release
cd capi-release
git checkout 1.71.0
git submodule init
git submodule sync
git submodule update
bosh create-release --force --tarball  dev_releases/capi-release.tgz 
shasum dev_releases/capi-release.tgz
```

The release info of my own version is:
```
- type: replace
  path: /releases/name=capi
  value:
    name: "capi"
    version: "1.71.0+dev.2"
    url: "https://github.com/keymon/capi-release/releases/download/1.71.0/capi-release.tgz"
    sha1: "e89785b89b29cb0195bdc0ecc9fe21f4227305dc"   
```

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v6.0.0 here

### Please provide output that helps describe the issue:

```
Task 4511 | 14:39:08 | Compiling packages: cloud_controller_ng/5c55b46581319e456f2af360f7db235d04ebff6cc9b8a2d621fc0b72dab461cc (00:01:47)
                     L Error: Action Failed get_task: Task 4bfe16f1-3227-413c-7083-02a00f7c598d result: Compiling package cloud_controller_ng: Running packaging script: Running packaging script: Command exited with 1; Stdout: installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler (1.16.4) is older than the version that created the lockfile (1.17.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
, Stderr: + cp -a cloud_controller_ng packaging /var/vcap/packages/cloud_controller_ng
+ cd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
+ mariadb_dir=/var/vcap/packages/mariadb_connector_c
+ libpq_dir=/var/vcap/packages/libpq
+ bundle_cmd=/var/vcap/packages/ruby-2.4/bin/bundle
+ /var/vcap/packages/ruby-2.4/bin/bundle config build.pg --with-pg-lib=/var/vcap/packages/libpq/lib --with-pg-include=/var/vcap/packages/libpq/include
+ /var/vcap/packages/ruby-2.4/bin/bundle config build.mysql2 --with-mysql-config=/var/vcap/packages/mariadb_connector_c/bin/mariadb_config
+ /var/vcap/packages/ruby-2.4/bin/bundle install --local --deployment --without development test
/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': libyaml-0.so.2: cannot open shared object file: No such file or directory - /var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/x86_64-linux/psych.so (LoadError)
	from /var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
	from /var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
```

### What IaaS is this issue occurring on?

AWS, I do not think it is releveant.

### Is there anything else unique or special about your setup?

Not using precompiled releases. 

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by keymon** [comment]
I think this was a one off problem from a badly compiled release.

We are using: 
 - A shared compile cache in a S3 bucket shared across our dev environments.
 - Reuse compile VMs.

It seems that the ruby package got compiled incorrectly. I have the theory that it could be due reuse the compile VM. That package got cached in our S3 cache.

After that, all deployments were failing because the bad package in the cache.

I deleted the cached packages for ruby, and the deployment started to work.

I close the issue now, but this means that there is a issue on how bosh compiles instances, probably with reuse compile VMs.

**Comment by heyjcollins** [comment]
Thanks @keymon - did you bring this issue to the BOSH team?

**Comment by keymon** [comment]
Actually, I think what I said before is not right. I think a valid package was being cached by bosh itself, so it didn't try to recompile. 

So it fails for any new environment, regardless if I delete the cache or not (actually,  right now, there is no cached version for ruby2.4) :(

**Comment by dpb587-pivotal** [comment]
@keymon the compilation package cache adds a unique twist to this issue since it makes it more difficult to track down where/how initial packages were built to identify the environment/debugs around it.

I took a quick look at the tarball you built for v1.71.0 in your fork. It looks like it may have been built from a different commit than upstream 1.71.0, so it may not have been an exactly equivalent test.

When using the compilation package cache, bosh will make a local copy, so even after deleting from the cache, if BOSH already downloaded it to the local director, it will continue being used.

I think the capi/cf teams use the source releases to compile the releases themselves, so I'm not sure what scenarios would cause it to work differently in their pipelines vs local environments.

We don't generally recommend the compilation package cache since it has some limitations and security considerations. I don't recall hearing about this sort of thing before, but it might have some yet-to-be-discovered edge cases. We don't actively test the feature in our environments.

Can you recap, more specifically, how we might be able to reproduce this? Have you seen this with any other releases?

**Comment by keymon** [comment]
I have been trying to reproduce this after delete the cached blob and the blobs in bosh, but I was not able to do so. 

So I guess it was a one-off issue in our side, but I do not know why. It is true that this in our case a shared binary cache bucket. It could be that some environment somehow generated a bad ruby package and then it got shared across all dev environments due the shared.

Given I am unable to reproduce, nobody else complained about this issue and you do not consider it is an issue in the distributed tarballs, I am happy to close this.

**Comment by bandesz** [comment]
We encountered this error again when upgrading cf-deployment to 6.10.0 which contains capi-release 1.74.0. @keymon where did you delete the cache?
