### ISSUE TITLE
Deploy cf with bosh-lite on virtualbox, deployed succeed but all of instances' status is 'unresponsive agent' and I can not find any vms by "vboxmanage list vms"

### ISSUE THREAD

**Issue by Maning8** [cloudfoundry/cf-deployment#681]
### What is this issue about?

Deploy cf with bosh-lite on VirtualBox, deployed succeed but all of the instances' status is 'unresponsive agent' and I can not find any vms by "vboxmanage list vms"

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v6.4.0

#### Create-env
bosh create-env bosh.yml \
  --state ./state.json \
  -o virtualbox/cpi.yml \
  -o virtualbox/outbound-network.yml \
  -o bosh-lite.yml \
  -o bosh-lite-runc.yml \
  -o uaa.yml \
  -o credhub.yml \
  -o jumpbox-user.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 

#### deploy cf
bosh -e vbox -d cf deploy cf-deployment.yml \
  -o operations/bosh-lite.yml \
  --vars-store deployment-vars.yml \
  -v system_domain=bosh-lite.com

#### deploy succeed but all of VMs are unresponsive agent
`ubuntu@cloudfoundry01:~$ bosh -e vbox vms
Using environment '192.168.50.6' as client 'admin'

Task 85. Done

Deployment 'cf'

Instance                                                  Process State       AZ  IPs           VM CID                                VM Type  Active
api/6d8b0e71-097a-46e6-9a3d-285cef47c42e                  unresponsive agent  z1  10.244.0.134  063aacbc-2481-450e-6de3-17a99db30fc6  -        true
cc-worker/8e1ce263-640d-44d6-8291-9b436270d812            unresponsive agent  z1  10.244.0.135  46537b55-1956-43c4-4d5c-1df9b9feb9aa  -        true
credhub/94d32388-09f5-45b2-884e-f0b357a22021              unresponsive agent  z1  10.244.0.141  5b045e1f-1889-4dd3-58e6-f19ca4da7dab  -        true
diego-cell/36b98135-d477-4e05-8ac1-dbd86dc082b2           unresponsive agent  z1  10.244.0.139  dbb8be1c-2671-4142-73ec-833a91498ba6  -        true
doppler/c7ddd114-bb6e-4f42-921c-7fc9655a07fd              unresponsive agent  z1  10.244.0.138  3cb55034-011c-4ec4-451a-70fd201306cb  minimal  true
log-api/f0c33247-0aa1-4b94-8775-5df183d18749              unresponsive agent  z1  10.244.0.140  6d8f3599-8ffd-4a21-76d1-b6578f8fa8f6  minimal  true
router/943bdc08-c577-4703-a779-c2daed1a2d83               unresponsive agent  z1  10.244.0.34   c585a420-9e41-4143-70bd-f2be90430eed  -        true
scheduler/75cb3ee8-2503-4d88-bb15-6b8b98d8bf93            unresponsive agent  z1  10.244.0.137  86c92490-e80d-4bd4-7ddd-876a8d18f259  -        true
singleton-blobstore/ef5f9463-7dd5-4a0c-8466-d84fa2097404  unresponsive agent  z1  10.244.0.133  99a99913-908c-4f42-48f5-06e36845be4b  -        true
tcp-router/6f82b3d1-f867-4ff3-b4cd-adb54144f01e           unresponsive agent  z1  10.244.0.136  95ad144e-f113-45cf-61e3-189c0919f70c  -        true

10 vms

Succeeded`

#### List vms with vboxmanage command
`ubuntu@cloudfoundry01:~$ vboxmanage list vms
"sc-74e62a06-1d9a-459d-491d-f2f11ba3f7bf" {137cb4c4-62c2-4fa5-9337-098128aec4de}
"vm-75de98dd-518d-43a7-7744-ba8c806759a7" {75de98dd-518d-43a7-7744-ba8c806759a7}
ubuntu@cloudfoundry01:~$ vboxmanage list runningvms
"vm-75de98dd-518d-43a7-7744-ba8c806759a7" {75de98dd-518d-43a7-7744-ba8c806759a7}`

### What IaaS is this issue occurring on?

VirtualBox 5.2.22r126460

**Comment by Maning8** [comment]
I just deleted my bosh lite director and recreated the env, and then I encountered this question:
`L Error: Config Server failed to generate value for '/Bosh Lite Director/cf/blobstore_admin_users_password' with type 'password'. HTTP Code '400', Error: 'Credential names may only include alpha, numeric, hyphen, underscore, and forward-slash characters. Please update and retry your request.'`

**Comment by ishustava** [comment]
Hey @Maning8 ,

It looks like you are using the `outbound-network.yml` ops file but not providing [`outbound_network_name` variable](https://github.com/cloudfoundry/bosh-deployment/blob/afbd52c8a8077b8a499d05fe1d9b8812a37220c7/virtualbox/outbound-network.yml#L8). You could follow [these instructions](https://bosh.io/docs/bosh-lite/) to get a bosh lite director. Specifically, step 4 has an example command with all needed variables provided.

As for the second issue, Config server (CredHub) doesn't allow spaces in the name of a variable and it uses BOSH director's name as part of the name. In your case, you'd need to change the name of the director from "Bosh Lite Director" to something without spaces.

Hope that helps,
Iryna & @vitreuz 
CF Release Integration team

**Comment by Maning8** [comment]
@ishustava Sure, Sincerely thanks for your feedback. For the first issue, it's my typo for missing the outbound network variable. for the second issue, I change director name to "bosh-lite". I have recreated env with below commands.
bosh create-env bosh.yml \
--state ./state.json \
-o virtualbox/cpi.yml \
-o virtualbox/outbound-network.yml \
-o bosh-lite.yml \
-o bosh-lite-runc.yml \
-o uaa.yml \
-o credhub.yml \
-o jumpbox-user.yml \
--vars-store ./creds.yml \
-v director_name="bosh-lite" \
-v internal_ip=192.168.50.6 \
-v internal_gw=192.168.50.1 \
-v internal_cidr=192.168.50.0/24
-v outbound_network_name=NatNetwork

#### After this, I deployed cf-deployment. Now all VMs' status are running. got below error:
Task 106 | 06:16:54 | Updating instance nats: nats/fd2949bd-9a5c-4bb0-8405-12d95aec70cb (0) (canary) (00:01:55)
Task 106 | 06:16:54 | Updating instance database: database/a93cc713-24a9-4086-bedf-c5a9840e0d77 (0) (canary) (00:08:36)
Task 106 | 06:25:30 | Updating instance diego-api: diego-api/1c1b5cb9-fb30-4885-bd28-28080c05379d (0) (canary) (00:03:00)
Task 106 | 06:28:31 | Updating instance uaa: uaa/8acb45cd-039c-40d1-8d42-9ea04c57bf68 (0) (canary) (00:59:53)
                   L Error: Action Failed get_task: Task 9cc74522-6b1a-434e-6f31-a5b0505b3c14 result: 1 of 2 post-start scripts failed. Failed Jobs: uaa. Successful Jobs: bosh-dns.
Task 106 | 07:28:25 | Error: Action Failed get_task: Task 9cc74522-6b1a-434e-6f31-a5b0505b3c14 result: 1 of 2 post-start scripts failed. Failed Jobs: uaa. Successful Jobs: bosh-dns.

#### Here is VMs status:
Instance                                                  Process State  AZ  IPs           VM CID                                VM Type  Active
adapter/3bfd9808-d43c-4b10-a61b-d973c91a2ad3              running        z1  10.244.0.129  6b584c98-3398-4b6a-6f20-18dfc3f0a915  minimal  true
api/d92bdbdd-966f-4af2-bfb5-42071924c445                  running        z1  10.244.0.134  a31c3888-c8f4-4940-600e-4c3838f81bc7  -        true
cc-worker/addd2080-9500-495b-8096-211f62d21598            running        z1  10.244.0.135  bcdda010-a447-4682-68ac-c6e4f5563081  -        true
credhub/d10f98b9-dd73-4cf2-bd82-3c50d1f12879              running        z1  10.244.0.141  8b3383ec-9e3f-4c6a-578a-2de210bf896c  minimal  true
database/a93cc713-24a9-4086-bedf-c5a9840e0d77             running        z1  10.244.0.130  01337e3b-af74-43fc-7f7a-5facaa23db0d  small    true
diego-api/1c1b5cb9-fb30-4885-bd28-28080c05379d            running        z1  10.244.0.131  ea8f65e0-7d5b-4534-79a9-464887c7d8d4  small    true
diego-cell/2a1bfa5d-8b7b-4b2c-a2b5-2b0fb26cdc27           running        z1  10.244.0.139  19332606-a44c-4a4c-67c6-9f8f3939d798  -        true
doppler/ea0a2fa7-8e52-4282-a3df-a025d85f214b              running        z1  10.244.0.138  6a8e24d8-8b3d-4039-5df0-692f0441e4b4  -        true
log-api/96a84b7d-97da-4d2e-9a7a-aa8c2137d56a              running        z1  10.244.0.140  83039d61-f75d-4ce2-7aca-7d4eb76a9793  minimal  true
nats/fd2949bd-9a5c-4bb0-8405-12d95aec70cb                 running        z1  10.244.0.128  b0c76f83-99fe-41bf-7be0-23b80735f26d  minimal  true
router/d6b91efe-00c3-41db-94f9-250fdbbbde8f               running        z1  10.244.0.34   0d46b96a-5f9f-4bd2-7ce1-30ff9cf2f150  -        true
scheduler/ae398dda-5bb2-4736-aa2e-a8ff3a0a88fb            running        z1  10.244.0.137  7e96af9d-a290-4630-442c-2314a06b2d91  -        true
singleton-blobstore/9990d85e-5b2c-4de0-a9e5-d9004b4e4cfe  running        z1  10.244.0.133  e944cc59-593a-4e1b-663d-daecb8e228c8  small    true
tcp-router/2bce23a1-7e88-43cb-af60-3a52c6d8849f           running        z1  10.244.0.136  2444bda0-2fff-448e-5514-5157555bef95  -        true
uaa/8acb45cd-039c-40d1-8d42-9ea04c57bf68                  running        z1  10.244.0.132  d7977e63-3f90-41d0-7ab2-6771905dd670  minimal  true

#### jobs on uaa
uaa/8acb45cd-039c-40d1-8d42-9ea04c57bf68:~# monit summary
The Monit daemon 5.2.5 uptime: 18h 29m

Process 'uaa'                       running
Process 'route_registrar'           running
Process 'statsd_injector'           running
Process 'loggregator_agent'         running
Process 'loggr-expvar-forwarder'    running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
System 'system_localhost'           running

#### I queried some logs from uaa:
cat /var/vcap/sys/log/uaa/post-start.stderr.log
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused

#### For the VMs that "VM Type" is "-", only one jobs named "system_localhost" is running:
System 'system_localhost'           running

@ishustava Can you please help to take look this situation? thank you very much.

**Comment by ishustava** [comment]
It looks like `uaa` failed to start up. 

Do you see any errors that look like Java stacktraces in `/var/vap/sys/log/uaa/uaa.log`? You could search for the latest occurrence of `ERROR` log entry in that log file.

**Comment by Maning8** [comment]
@ishustava 
#### Here was the `error` I found in uaa.log 
[2018-12-18 07:44:39.453] uaa - 1 [main] ....  WARN --- DefaultFilterChainValidator: Possible error: Filters at position 8 and 9 are both instances of org.springframework.security.web.context.SecurityContextPersistenceFilter
[2018-12-18 07:44:39.466] uaa - 1 [main] ....  INFO --- DefaultFilterChainValidator: Checking whether login URL '/login' is accessible with your configuration
[2018-12-18 07:45:24.720] uaa - 1 [main] ....  INFO --- FrameworkEndpointHandlerMapping: Mapped "{[/oauth/confirm_access]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.security.oauth2.provider.endpoint.WhitelabelApprovalEndpoint.getAccessConfirmation(java.util.Map<java.lang.String, java.lang.Object>,javax.servlet.http.HttpServletRequest) throws java.lang.Exception
[2018-12-18 07:45:24.729] uaa - 1 [main] ....  INFO --- FrameworkEndpointHandlerMapping: Mapped "{[/oauth/authorize]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.security.oauth2.provider.endpoint.AuthorizationEndpoint.authorize(java.util.Map<java.lang.String, java.lang.Object>,java.util.Map<java.lang.String, java.lang.String>,org.springframework.web.bind.support.SessionStatus,java.security.Principal)
[2018-12-18 07:45:24.732] uaa - 1 [main] ....  INFO --- FrameworkEndpointHandlerMapping: Mapped "{[/oauth/authorize],methods=[POST],params=[user_oauth_approval]}" onto public org.springframework.web.servlet.View org.springframework.security.oauth2.provider.endpoint.AuthorizationEndpoint.approveOrDeny(java.util.Map<java.lang.String, java.lang.String>,java.util.Map<java.lang.String, ?>,org.springframework.web.bind.support.SessionStatus,java.security.Principal)
[2018-12-18 07:45:24.742] uaa - 1 [main] ....  INFO --- FrameworkEndpointHandlerMapping: Mapped "{[/oauth/token],methods=[GET]}" onto public org.springframework.http.ResponseEntity<org.springframework.security.oauth2.common.OAuth2AccessToken> org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.getAccessToken(java.security.Principal,java.util.Map<java.lang.String, java.lang.String>) throws org.springframework.web.HttpRequestMethodNotSupportedException
[2018-12-18 07:45:24.744] uaa - 1 [main] ....  INFO --- FrameworkEndpointHandlerMapping: Mapped "{[/oauth/token],methods=[POST]}" onto public org.springframework.http.ResponseEntity<org.springframework.security.oauth2.common.OAuth2AccessToken> org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(java.security.Principal,java.util.Map<java.lang.String, java.lang.String>) throws org.springframework.web.HttpRequestMethodNotSupportedException
[2018-12-18 07:45:24.760] uaa - 1 [main] ....  INFO --- FrameworkEndpointHandlerMapping: Mapped "{[/oauth/token/**],methods=[GET]}" onto public org.springframework.http.ResponseEntity<org.springframework.security.oauth2.common.OAuth2AccessToken> org.cloudfoundry.identity.uaa.oauth.token.UaaTokenEndpoint.doDelegateGet(java.security.Principal,java.util.Map<java.lang.String, java.lang.String>) throws org.springframework.web.HttpRequestMethodNotSupportedException
[2018-12-18 07:45:24.762] uaa - 1 [main] ....  INFO --- FrameworkEndpointHandlerMapping: Mapped "{[/oauth/token/**],methods=[POST]}" onto public org.springframework.http.ResponseEntity<org.springframework.security.oauth2.common.OAuth2AccessToken> org.cloudfoundry.identity.uaa.oauth.token.UaaTokenEndpoint.doDelegatePost(java.security.Principal,java.util.Map<java.lang.String, java.lang.String>,javax.servlet.http.HttpServletRequest) throws org.springframework.web.HttpRequestMethodNotSupportedException

#### And Is others VMs abnormal were because of uaa's error?

**Comment by ishustava** [comment]
I'm not seeing any error logs, they are all `INFO` level. You want to look for logs with level `ERROR`. 
The logline should contain `.... ERROR ---`.

For the other VMs, it's ok that they are only running `system_localhost`. That is because the deployment failed at updating the `uaa` VM, and BOSH never had a chance to update other VMs.

**Comment by Maning8** [comment]
@ishustava  There were no ERROR level log in /var/vcap/sys/log/uaa.log. Any advice for further investigation? ^_^

**Comment by ishustava** [comment]
I see. It'd be good to double check if the uaa process is running on the VM:
1. check if the port is open by running `lsof -i :8080` on the uaa VM
1. `ps aux | grep uaa` and check if there are any uaa processes running. It should look something like this:
```
# ps aux | grep uaa
root      3054  0.0  0.0  12944   964 pts/0    S+   21:52   0:00 grep --color=auto uaa
vcap      8975  0.0  0.0  19744  3392 ?        S<s  Dec14   0:00 /bin/bash /var/vcap/jobs/uaa/bin/uaa
vcap      9007  0.3  8.6 3329768 709384 ?      S<l  Dec14  25:56 /var/vcap/packages/uaa/jdk/bin/java -Djava.util.logging.config.file=/var/vcap/data/uaa/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -DPID=1 -Dnetworkaddress.cache.ttl=0 -Djavax.net.ssl.trustStore=/var/vcap/jobs/uaa/config/cacerts -Djavax.net.ssl.trustStoreType=JKS -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Xmx768m -XX:MaxMetaspaceSize=256m -classpath /var/vcap/data/uaa/tomcat/bin/bootstrap.jar:/var/vcap/data/uaa/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/var/vcap/data/uaa/tomcat -Dcatalina.home=/var/vcap/data/uaa/tomcat -Djava.io.tmpdir=/var/vcap/data/uaa/tomcat/temp org.apache.catalina.startup.Bootstrap start
```

One other thing that might be useful is to check whether or not the process status reported by `monit` flips between `running` and `not monitored`. You could do so by running `watch monit summary` on the VM for a few minutes.

If none of the above worked for you, I'd try to redeploy and see if the error is reproducible.

Hope that helps,
Iryna & @Changdrew 
CF Release Integration team

**Comment by Maning8** [comment]
@ishustava I check the port and process status
#### Port was listening 
uaa/8acb45cd-039c-40d1-8d42-9ea04c57bf68:/var/vcap/sys/log/route_registrar# lsof -i :8080
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    12437 vcap   50u  IPv4 820569      0t0  TCP *:http-alt (LISTEN)

#### process was existed
uaa/8acb45cd-039c-40d1-8d42-9ea04c57bf68:/var/vcap/sys/log/route_registrar# ps aux | grep uaa
vcap       12399  0.0  0.0  19624  3032 ?        S<s  Dec18   0:00 /bin/bash /var/vcap/jobs/uaa/bin/uaa
vcap       12437  2.8  9.6 3343156 389812 ?      S<l  Dec18  72:39 /var/vcap/packages/uaa/jdk/bin/java -Djava.util.logging.config.file=/var/vcap/data/uaa/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -DPID=1 -Dnetworkaddress.cache.ttl=0 -Djavax.net.ssl.trustStore=/var/vcap/jobs/uaa/config/cacerts -Djavax.net.ssl.trustStoreType=JKS -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Xmx768m -XX:MaxMetaspaceSize=256m -Dignore.endorsed.dirs= -classpath /var/vcap/data/uaa/tomcat/bin/bootstrap.jar:/var/vcap/data/uaa/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/var/vcap/data/uaa/tomcat -Dcatalina.home=/var/vcap/data/uaa/tomcat -Djava.io.tmpdir=/var/vcap/data/uaa/tomcat/temp org.apache.catalina.startup.Bootstrap start

#### uaa status is running. I used "watch -n1 monit summary" observed for 5 minutes and it was always running.
uaa/8acb45cd-039c-40d1-8d42-9ea04c57bf68:/var/vcap/sys/log/route_registrar# watch -n1 monit summary
Every 1.0s: monit summary                                                                                                                                                                                             Thu Dec 20 01:36:22 2018

The Monit daemon 5.2.5 uptime: 1d 18h 18m

Process 'uaa'                       running
Process 'route_registrar'           running
Process 'statsd_injector'           running
Process 'loggregator_agent'         running
Process 'loggr-expvar-forwarder'    running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
System 'system_localhost'           running

@ishustava I will try to redeploy. by the way, I have a question about remaing disk requirements. Is there need a 100G+ disk capacity remaing before deploying cf-deployment?  Disk on my machine was only 100G, after I deployed bosh-lite the disk remaining is about 80G. Is this will cause some unexpected issue?

**Comment by forexamplelyr** [comment]
@ishustava hi！Then I increased the size of my diskc to 150G
when i deploy cf，i meet the issue：
Task 191 | 14:22:09 | Compiling packages: util-linux/6310f68e8294c980de62481bced2fc915f449e3a2cc2d13a7a2a49c4a612d825 (00:33:16)
Task 191 | 14:22:10 | Compiling packages: file_server/be9b94de40a859edb9bb9859f4ab869b21347519
 (00:03:16)
                    L Error: Action Failed get_task: Task with id 5e9185cd-7060-4729-4a9f-2a9ee4472a4f could not be found
Task 191 | 14:27:01 | Compiling packages: auctioneer/69a1050832879e8c477a2a63c57fc5ce3e6993fe (00:29:38)
Task 191 | 14:30:48 | Compiling packages: routing-api/d2cec651ce5287068b1b11959579af17c4248fde59f4aff4e43fb6097c94b633 (00:23:36)
Task 191 | 14:31:05 | Compiling packages: ssh_proxy/779e429a52abaf0a9ca1fabd04eb8570aee8e121 (00:25:53)


Task 191 | 14:46:29 | Compiling packages: healthcheck/57004bfd97bd8fa59e2920744bc1c4a39af381a8 (00:27:51)
Task 191 | 14:55:47 | Compiling packages: diego-sshd/cb7bc74d3e357d48f2ee309b3c3ff35e8a6a95b5 (00:42:35)
Task 191 | 14:55:55 | Error: Action Failed get_task: Task with id 5e9185cd-7060-4729-4a9f-2a9ee4472a4f could not be found

Task 191 Started  Sat Dec 22 13:29:56 UTC 2018
Task 191 Finished Sat Dec 22 14:55:55 UTC 2018
Task 191 Duration 01:25:59
Task 191 error

Updating deployment:
  Expected task '191' to succeed but state is 'error'
Error: Action Failed get_task: Task with id 5e9185cd-7060-4729-4a9f-2a9ee4472a4f could not be found
is there sometihing wrong with it？

**Comment by Maning8** [comment]
Now I used a machine that has 8 cores CPUs, 20G MEM, 150G disk to deploy the cf-deployment. 
Note that this machine is a VMware based machine, I installed virtualbox on it for deploying cf-deployment wit bosh-lite. Is there possible the director vm was not powered? Is there anything wrong of Virtualization nesting? I have never do this before? can somebody give some advices? thanks
I deployed successfully on my Mac, but on this machine still got this error:

> Task 110 | 23:48:28 | Creating missing vms: api/2ae696ee-7bf1-4126-ae4b-71e251229ca0 (0)
> Task 110 | 23:52:22 | Creating missing vms: adapter/35140252-fda2-4a1c-b9b1-5c6f5eda05f5 (0) (00:03:54)
>                    L Error: Action Failed get_task: Task 49d3ad18-3dbe-4868-6dfe-daa79b1fcbd2 result: Updating certificates with retries
> Task 110 | 23:52:25 | Creating missing vms: database/55673135-8f53-4300-8d76-1a8a10e63166 (0) (00:03:57)
>                    L Error: Action Failed get_task: Task 92f8afc2-726e-4b97-4c58-a67227461520 result: Updating certificates with retries
> Task 110 | 23:52:25 | Creating missing vms: nats/69478b32-e7ae-4245-8482-4ad8e0fe6f41 (0) (00:03:57)
>                    L Error: Action Failed get_task: Task 07a8c1a8-b16c-4074-78be-0756458c38f5 result: Updating certificates with retries
> Task 110 | 23:52:25 | Creating missing vms: router/69e37a70-a77a-443c-a9cd-5fd0ec3e2b7d (0) (00:03:57)
>                    L Error: Action Failed get_task: Task e54c800f-5428-4fe6-5e28-1ac88c2b1c28 result: Updating certificates with retries
> Task 110 | 23:52:34 | Creating missing vms: uaa/b82e3715-ab62-4afd-8d6b-48657e0dad9d (0) (00:04:06)
>                    L Error: Action Failed get_task: Task 190d4451-864f-49f1-7c3f-c87682d1fed3 result: Updating certificates with retries
> Task 110 | 23:52:35 | Creating missing vms: cc-worker/9f44bfbc-0e03-4091-a98f-09fb107952e2 (0) (00:04:07)
>                    L Error: Action Failed get_task: Task 1f83491a-ffe4-433e-7a6c-dd0458b320da result: Updating certificates with retries
> Task 110 | 23:52:37 | Creating missing vms: diego-api/4a2bbd6d-a1ae-4f51-a65c-a0c664bd3626 (0) (00:04:09)
>                    L Error: Action Failed get_task: Task d71278a1-ab9d-4f07-4d31-efc11b782575 result: Updating certificates with retries
> Task 110 | 23:53:03 | Creating missing vms: credhub/70ac07c2-21b1-4500-8886-986bf3e84154 (0) (00:04:35)
> Task 110 | 23:53:09 | Creating missing vms: tcp-router/73eb3d7a-ad6e-48cc-932f-d29aacaad607 (0) (00:04:41)
> Task 110 | 23:53:09 | Creating missing vms: doppler/be867097-23cf-4460-9df2-cae87aa7bbc6 (0) (00:04:41)
> Task 110 | 23:53:12 | Creating missing vms: singleton-blobstore/6613cbad-7213-4c01-a3ee-ecd7900b2703 (0) (00:04:44)
> Task 110 | 23:53:20 | Creating missing vms: log-api/c05d2aef-eb5a-4c98-9789-be194b350ec2 (0) (00:04:52)
> Task 110 | 23:53:23 | Creating missing vms: diego-cell/15ead383-7018-4e97-a43a-b22cd39c251b (0) (00:04:55)
> Task 110 | 23:53:24 | Creating missing vms: scheduler/42ab4abc-9f3e-4927-801a-3859d4e1c430 (0) (00:04:56)
> Task 110 | 23:53:26 | Creating missing vms: api/2ae696ee-7bf1-4126-ae4b-71e251229ca0 (0) (00:04:58)
> Task 110 | 23:53:26 | Error: Action Failed get_task: Task 49d3ad18-3dbe-4868-6dfe-daa79b1fcbd2 result: Updating certificates with retries
> 
> Task 110 Started  Fri Dec 28 16:50:06 UTC 2018
> Task 110 Finished Fri Dec 28 23:53:26 UTC 2018
> Task 110 Duration 07:03:20
> Task 110 error
> 
> Capturing task '110' output:
>   Expected task '110' to succeed but state is 'error'
> 
> Exit code 1
>

**Comment by vitreuz** [comment]
Hi @Maning8, apologies for the long response time.

May I ask what version of bosh you are running? It's possible this may be an older version of the bosh director or that the machine may not have enough power to deploy. This [thread](https://github.com/cloudfoundry/bosh-lite/issues/429) might provide a bit more information.

You could also gather more information from the director by using `bosh task 110 --debug`. This should have error lines that start out with `E, ...`.

**Comment by heyjcollins** [comment]
Since there's been no response on this issue for a couple weeks I'm going to go ahead and close it.
Please comment and reopen if you'd like to continue the discussion. Thanks!
