### ISSUE TITLE
ssh_proxy job running in scheduler instance

### ISSUE THREAD

**Issue by rokejung** [cloudfoundry/cf-deployment#691]
In cf-deployment.yml, the ssh_proxy job is unde scheduler instance. It looks like this was done temporarily in https://github.com/cloudfoundry/cf-deployment/commit/cce5982f9e627b35ac1992547e3109f565672a5a#diff-88433d2a56659f588140499388bca4bd. And then later the job was moved back to router instance in https://github.com/cloudfoundry/cf-deployment/commit/961405be993a5d4cf9b84f9eadbe9bf35edcc218#diff-88433d2a56659f588140499388bca4bd. The problem is that if the bosh-lite ops file is not applied, SSH to app containers is broken and I get Error opening SSH connection: dial tcp xx.xx.xx.xx:2222: connect: connection refused

**Comment by vitreuz** [comment]
Hey, as a first question are you using the `cf ssh` command to get to the application? If so, we would need to know what ops files are being used. Our current configurations test that ssh works with deployed applications.

For any future issues, please use the provided issue template. It provides us with information that is helpful to help you debug this issue.

**Comment by hfrenzel** [comment]
We got nearly the same issue. cf-deployment v7.0.0 is deployed with help of concourse on openstack IaaS. Performing `cf ssh APP` is not possible: `Error opening SSH connection: dial tcp 1.2.3.4:2222: getsockopt: connection refused`. Debugging this, shows the listening port `2222` on the scheduler instances, but not on the router instances, where the DNS record of `((system_domain))` points to.

**Comment by Changdrew** [comment]
Could you please provide how you setup your infrastructure and bosh director and also which ops files you used to deploy cf?
This will provide us with better steps to reproduce this error. This seems likely a networking issue.

**Comment by rokejung** [comment]
Hi. We use these ops files.

vsphere/cpi.yml
vsphere/resource-pool.yml
uaa.yml
/credhub.yml
bbr.yml
misc/config-server.yml

I think the problem is that the ssh_proxy job was moved from router to scheduler in cf-deployment.yml
https://github.com/cloudfoundry/cf-deployment/commit/cce5982f9e627b35ac1992547e3109f565672a5a#diff-88433d2a56659f588140499388bca4bd. If we do not apply bosh-lite.yml ops file, the ssh_proxy job stays in scheduler instance.

**Comment by vitreuz** [comment]
Hi @rokejung!

We can't move the `ssh_proxy` job to the router instance group because the reference topology as of today recommends 3 load balancers (router, ssh and tcp). This would cause the current topology for certain IaaSes to break since you wouldn't be able to attach multiple load balancers of same type in the same VM through bosh.

We have some other follow up questions.
Are you using Load Balancers (e.g. NSX-T) or HAProxy?
What do you get from `app_ssh_endpoint` when running `cf curl /v2/info`? And what do you get when you `dig` the ssh endpoint?
It seems your ssh endpoint is not properly pointing to the scheduler vm or you can't talk to the scheduler vm.

Thanks,
cc @cdutra

**Comment by rokejung** [comment]
I am not using Load Balancers or HAProxy.
`cf curl /v2/info` returns `"app_ssh_endpoint": "ssh.local.mydomain.net:2222"`. Output of `dig ssh.local.mydomain.net:2222` is

; <<>> DiG 9.10.3-P4-Ubuntu <<>> ssh.local.mydomain.net:2222
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 13953
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ssh.local.mydomain.net:2222.	IN	A

;; AUTHORITY SECTION:
.			6781	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2019020800 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 9.42.106.2#53(9.42.106.2)
;; WHEN: Fri Feb 08 20:36:10 UTC 2019
;; MSG SIZE  rcvd: 130

**Comment by cdutra** [comment]
@rokejung It seems your cf installation isn't properly configured given your `app_ssh_endpoint` isn't returning a location of your ssh proxy server. You need to make sure your DNS entry for `ssh.your-env.domain` points to your scheduler vm, or lb or haproxy seating in front of your scheduler vms.

cc @vitreuz

**Comment by rokejung** [comment]
@cdutra Should I configure my DNS outside of CF configuration to point `ssh.local.mydomain.net` to the IP of the scheduler VM (I don't have LB or HAProxy)?

**Comment by cdutra** [comment]
@rokejung Yes, CF configuration doesn't setup DNS for you.
