### ISSUE TITLE
Dead loggregator route

### ISSUE THREAD

**Issue by poy** [cloudfoundry/cf-deployment#693]
The [loggregator route](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1623-L1627
) is routes to port 8080, which is not bound to on the log-api VM:

I checked it with:
```
log-api/c25293f3-c794-45ef-a56a-1b086d272117:~# lsof -P -i :8080 -sTCP:LISTEN
log-api/c25293f3-c794-45ef-a56a-1b086d272117:~# echo $?
1
```

That route is legacy and clearly has not been in use for a while.

This is related to #187

**Comment by heyjcollins** [comment]
Thanks @poy,

We'll clean that up.

**Comment by cdutra** [comment]
Story has been accepted, I'm closing this issue. Let us know if this issue persists and feel free to reopen if necessary. Thanks!
