### ISSUE TITLE
use-compiled-releases works on cf-d 6.0 but not on 7.0

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/cf-deployment#695]
### What is this issue about?

I'm deploying cf-deployment to bosh-lite on virtualbox and compilation was timing out so i wanted to skip compilation using use-compiled-releases but it did not appear to take effect until I reverted to cf deployment 6.0

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

It still does the compilation on 7.0 erroneously but works fine on 6.0

### Please include the `bosh deploy...` command, including all the operations files:

```bosh -n  -e 192.168.50.6 -d cf deploy cf-deployment.yml  -o operations/bosh-lite.yml   -o operations/use-compiled-releases.yml  -o operations/scale-to-one-az.yml -v system_domain=bosh-lite.com```

### Please provide output that helps describe the issue:
it still compiles all the packages and times out, example: 
```
Task 50 | 13:31:34 | Compiling packages: pxc/dd36ac93b0b4673b953ae7ddeb9be98fcdc6634161f7e16a32e3e77501577d59
```

### What IaaS is this issue occurring on?

Virtualbox

### Is there anything else unique or special about your setup?

no, just using cf-deployment according to deployment instructions

**Comment by cdutra** [comment]
Hi @scottschulthess, cf-deployment 7.0.0 uses the following compiled release for [pxc](https://storage.googleapis.com/cf-deployment-compiled-releases/pxc-0.14.0-ubuntu-xenial-170.19-20190114-191519-497515962.tgz). When I download and expand it I see a compiled release:
```
$ tar -xvf ~/Downloads/pxc-0.14.0-ubuntu-xenial-170.19-20190114-191519-497515962.tgz
x ./release.MF
x ./jobs/
x ./jobs/smoke-tests.tgz
x ./jobs/proxy.tgz
x ./jobs/bootstrap.tgz
x ./jobs/gra-log-purger.tgz
x ./jobs/smoke-tests-user.tgz
x ./jobs/galera-agent.tgz
x ./jobs/cluster-health-logger.tgz
x ./jobs/pxc-mysql.tgz
x ./compiled_packages/
x ./compiled_packages/pxc.tgz
x ./compiled_packages/smoke-tests.tgz
x ./compiled_packages/galera-init.tgz
x ./compiled_packages/proxy.tgz
x ./compiled_packages/bootstrap.tgz
x ./compiled_packages/migrate-to-pxc.tgz
x ./compiled_packages/socat.tgz
x ./compiled_packages/percona-xtrabackup.tgz
x ./compiled_packages/pxc-gra-log-purger.tgz
x ./compiled_packages/golang-1.9-linux.tgz
x ./compiled_packages/libgalera.tgz
x ./compiled_packages/pxc-utils.tgz
x ./compiled_packages/pxc-cluster-health-logger.tgz
x ./compiled_packages/galera-agent.tgz
x ./compiled_packages/auto-tune-mysql.tgz
x ./compiled_packages/python-2.7.tgz
```
I tried to reproduce but it doesn't show that is compiling pxc for me. The only packages that need to be compiled are `golang-1-linux` and `bosh-dns`.

I ran the following command:
```
bosh -d cf deploy ~/workspace/cf-deployment/cf-deployment.yml -o ~/workspace/cf-deployment/operations/experimental/fast-deploy-with-downtime-and-danger.yml -o ~/workspace/cf-deployment/operations/bosh-lite.yml -o ~/workspace/cf-deployment/operations/use-compiled-releases.yml -v system_domain=bosh-lite.com -o bosh-lite-local.yml
```
where `bosh-lite-local.yml`:
```
- type: remove
  path: /instance_groups/name=api/vm_extensions

- type: remove
  path: /instance_groups/name=diego-cell/vm_extensions

- type: remove
  path: /instance_groups/name=router/vm_extensions

- type: remove
  path: /instance_groups/name=tcp-router/vm_extensions
```

**Comment by scottschulthess** [comment]
Thanks @cdutra, it was very consistent when I was trying it, but perhaps it will remain a mystery.   :( Thank you for trying!
