### ISSUE TITLE
Running out of ephemeral disk on GCP

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-deployment#70]
We're seeing a confusing error message on GCP when trying to update certain jobs:

```
Response exceeded maximum allowed length
```

After [talking](https://cloudfoundry.slack.com/archives/bosh/p1487290717006803) with the BOSH team, the likely culprit is our VM running out of ephemeral disk when trying to untar some stuff. Running `df -h` on our `cc_clock` VM shows a tiny 1GB ephemeral partition: `/dev/sda3       1.1G  741M  235M  76% /var/vcap/data`. On GCP, if you ask for a 5GB root disk, as `bbl` does for the `5GB_ephemeral_disk` vm_extension, bosh will take about 3-4GB of the root disk for the agent and whatnot, and carve an ephemeral partition (`/var/vcap/data`) out of whatever remains.

Can y'all bump the `5GB_ephemeral_disk` root disk size to avoid this issue?

**Comment by dsabeti** [comment]
@ljfranklin How often do you see this problem? I'm not sure that we've seen this problem in our GCP pipelines. Also, is this in a fresh deploy or rolling/upgrade deploy?

@anEXPer, have you seen this problem in our builds before?

**Comment by ljfranklin** [comment]
@dsabeti only saw it once so far and it was during a rolling deploy. I'd imagine others would see it on jobs with very chatty logs or in our case a rolling deploy with large packages to untar. A 1GB ephemeral partition is bound to run out of space at some point if large packages need upgraded.

**Comment by dsabeti** [comment]
@ljfranklin Our GCP does a fresh deploy every time (it deletes the existing deployment first), so it's possible that we'd never see this problem. I'll prioritize this story to bump up to 10GB.

**Comment by dsabeti** [comment]
Hey @ljfranklin. `master` now contains `10GB_ephemeral_disk` for everything that has ephemeral disk attached.

**Comment by ljfranklin** [comment]
@dsabeti we're still seeing this issue in CI as the `operations/gcp.yml` ops file still overrides everything to 5GB. Do we even need that ops file or can it be removed?

**Comment by dsabeti** [comment]
Yup, it looks we should get rid of those extra vm_extensions in that ops file.

**Comment by dsabeti** [comment]
Here's the story to follow: https://www.pivotaltracker.com/story/show/136972395

**Comment by dsabeti** [comment]
All of the stories associated with this have been accepted, so I'm going to close this issue.
