### ISSUE TITLE
log-cache's egress_port should be port

### ISSUE THREAD

**Issue by poy** [cloudfoundry/cf-deployment#700]
cf-deployment.yml uses a property name (`egress_port`) that was changed a [while ago](
https://github.com/cloudfoundry/log-cache-release/commit/4b8f4821957fafabcd831990a473139e73090579) to `port`:
https://github.com/cloudfoundry/cf-deployment/blob/95468a56829ccea1a5f527a0b27d734c42401542/cf-deployment.yml#L1315

**Comment by heyjcollins** [comment]
Thanks for bringing this to our attention.
I've pulled this into our backlog.
We'll update cf-d accordingly soon.

**Comment by cdutra** [comment]
Hi @poy , thank you for letting us know. Changes made [here](https://github.com/cloudfoundry/cf-deployment/commit/3ef3816da1c43c4073deea0e0750295dbb8d9bc8).
