### ISSUE TITLE
Doppler Is Not Reachable 

### ISSUE THREAD

**Issue by aryanet** [cloudfoundry/cf-deployment#704]
### What is this issue about?

I have deployed and re-deployed 2 new foundations using bbl 7.0.0 and cf-deployment 7.1.0. The new NLB responsible for routing traffic to *.<system_domain> in AWS IaaS is listening on port 80, 443, and 4443. I deployed my services and when I wanted to troubleshoot by fetching the logs, the doppler endpoint is not reachable. I checked the AWS NLB and the gorouter instance healthcheck on port 4443 was tailing. I also validated this myself by using telnet to confirm the gorouter is not listening on port 4443. I further checked the host by running netstat -tlupn and I got the following output which shows gorouter is not listening on 4443:

router/159c019f-eb2b-4506-b3f2-6a1462af4939:~# netstat -tlupn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16351/gorouter
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      16351/gorouter
tcp        0      0 169.254.0.2:53          0.0.0.0:*               LISTEN      16087/bosh-dns
tcp        0      0 0.0.0.0:8853            0.0.0.0:*               LISTEN      16044/bosh-dns-heal
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      813/sshd
tcp        0      0 127.0.0.1:53080         0.0.0.0:*               LISTEN      16087/bosh-dns
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      16351/gorouter
tcp        0      0 127.0.0.1:35905         0.0.0.0:*               LISTEN      16351/gorouter
tcp        0      0 127.0.0.1:3458          0.0.0.0:*               LISTEN      16226/loggregator-a
tcp        0      0 127.0.0.1:2822          0.0.0.0:*               LISTEN      16156/monit
tcp        0      0 127.0.0.1:14824         0.0.0.0:*               LISTEN      16226/loggregator-a
tcp        0      0 127.0.0.1:2825          0.0.0.0:*               LISTEN      729/bosh-agent
tcp        0      0 127.0.0.1:17002         0.0.0.0:*               LISTEN      16351/gorouter
udp        0      0 127.0.0.1:3457          0.0.0.0:*                           16226/loggregator-a
udp        0      0 0.0.0.0:48528           0.0.0.0:*                           16351/gorouter
udp        0      0 169.254.0.2:53          0.0.0.0:*                           16087/bosh-dns
udp        0      0 0.0.0.0:68              0.0.0.0:*                           854/dhclient
udp        0      0 127.0.0.1:323           0.0.0.0:*                           1432/chronyd

Therefore, the doppber endpoint is not reachable. As a result:

cf logs <app> --recent
cf logs <app>

commands are failing in my deployments. 

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v7.1.0 here]

### Please include the `bosh deploy...` command, including all the operations files:

I copied the cf-deployment.yml manifest to cf-deployment-staging.yml to only make a change to include my domain's valid certificate and private key to be deployed to gorouter. Then ran this command:

bosh deploy -d cf /Users/arya/Code/cf-deployment/cf-deployment-staging.yml -l ./staging.yml -v system_domain=<redacted>.com -o /Users/arya/Code/cf-deployment/operations/use-compiled-releases.yml -o /Users/arya/Code/cf-deployment/operations/use-external-dbs.yml -o /Users/arya/Code/cf-deployment/operations/aws.yml -o /Users/arya/Code/cf-deployment/operations/use-external-blobstore.yml -o /Users/arya/Code/cf-deployment/operations/use-s3-blobstore.yml

### Please provide output that helps describe the issue:

ITs-MacBook-Pro:cf-deployment arya$ cf logs customer-platform --recent
Retrieving logs for app customer-platform in org <myorg> / space platform as <admin_user>...

Error dialing trafficcontroller server: Get https://doppler.<system_domain>:4443/apps/6b45fbf9-31c6-46d3-8cdf-ae4be6368f80/recentlogs: dial tcp 52.43.11.118:4443: connect: connection refused.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller endpoint is wss://doppler.<system_domain>:4443).
FAILED

### What IaaS is this issue occurring on?

AWS IaaS

### Is there anything else unique or special about your setup?

Just deployed valid certificates to gorouter by modifying the cf-deployment.yml manifest. 

### Tag your pair, your PM, and/or team!
@aryanet
@heyjcollins

**Comment by MasslessParticle** [comment]
With regard to Loggregator, all you need to do for AWS  in cf-d is use the following ops file: https://github.com/cloudfoundry/cf-deployment/blob/16897e006dcae39e50b94734dc060be9ed54c934/operations/aws.yml

Loggregator registers a route for the trafficcontroller. CAPI is responsible for tacking on 443 or 4443 depending on what the LB wants.

It is consistent that the NLB with failing health checks for gorouter on port 4443 would cause this issue.

**Comment by heyjcollins** [comment]
Thanks for responding @MasslessParticle.
If you look at the original issue submitted by @aryanet. The bosh deploy already included `operations/aws.yml`

**Comment by heyjcollins** [comment]
As per [this slack thread](https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1548420584095000), `operations/aws.yml` is not required unless your deployment is fronted by "classic" AWS ELBs.
BBB v.7.0.0+ sets up Network Load Balancers and the workaround included in the aws.yml ops file isn't required. --- going to close this issue. Please comment and reopen if you want to continue the dialogue or continue to experience this issue after deploying **without** `operations/aws.yml`.

**Comment by cortega-lh** [comment]
Is there a way to set the default ports without reinstalling cf? I used `operations/aws.yml` file with `bbl 7.3.0` 💣 💥

**Comment by jtuchscherer** [comment]
@cortega-lh I would just copy that [opsfile you mentioned](https://github.com/cloudfoundry/cf-deployment/blob/16897e006dcae39e50b94734dc060be9ed54c934/operations/aws.yml) and change the values to the ports you need for your installation and then run `bosh deploy` again.

**Comment by cortega-lh** [comment]
Actually, I just ran again the command for installing cloudfoundry (excluding the flag for including the `operations/aws.yml` file), and bosh automatically detected and updated the changes. It was easier than I expected and it was pretty quick.
