### ISSUE TITLE
skip_cert_verify is set to true for ccng, cc-worker, but not cc-clock

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cf-deployment#713]
### What is this issue about?

#diego reported an error that app freshness was not getting bumped after a tcp-route was mapped to an app. The exception complained about an invalid cert.

_In your own words, describe the issue._
_What steps/actions led to the issue?_

See above

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v7.3.0 (and other older recent versions)

### Please include the `bosh deploy...` command, including all the operations files:

We jumped into the middle of a deployed bosh-lite.

### Please provide output that helps describe the issue:

Not available

We'll submit a PR that sets the default `skip_cert_verify` to true for the scheduler.

### What IaaS is this issue occurring on?

N/a

### Is there anything else unique or special about your setup?

N/A

### Tag your pair, your PM, and/or team!

@nrxus @ericpromislow

**Comment by ericpromislow** [comment]
See PR https://github.com/cloudfoundry/cf-deployment/pull/714/files

**Comment by Changdrew** [comment]
@ericpromislow We'll be looking at the PR in the next few days. Cheers!
