### ISSUE TITLE
unresponsive agent on cf-deployment instances after bosh vm recreation

### ISSUE THREAD

**Issue by aryanet** [cloudfoundry/cf-deployment#717]
### What is this issue about?

Bosh VM got replaced on AWS IaaS as part of Stemcell upgrade. Majority of cf-deployment VMs reporting "unresponsive agent". 

This is reproducible using the following steps:
Create bbl environment with bbl 7.0.0 and AWS IaaS.
Create a cf-deployment with cf-deployment 6.10.0.

Recreate bosh VM with bbl by either upping its instance type in cloudconfig or change its stemcel. Basically do something to replace bosh vm instance. 

Once bosh VM instance is up, if you do bosh vms, the cf-deployment instances will show "unresponsive agent". 

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment 6.10.0 here]

### Please include the `bosh deploy...` command, including all the operations files:

bosh deploy -d cf /Users/arya/Code/cf-deployment/cf-deployment-staging.yml -l ./staging.yml -v system_domain=cf-staging.pax.com -o /Users/arya/Code/cf-deployment/operations/scale-to-one-az.yml -o /Users/arya/Code/cf-deployment/operations/use-compiled-releases.yml -o /Users/arya/Code/cf-deployment/operations/use-external-dbs.yml -o /Users/arya/Code/cf-deployment/operations/use-external-blobstore.yml -o /Users/arya/Code/cf-deployment/operations/use-s3-blobstore.yml -o /Users/arya/Code/cf-deployment/operations/enable-service-discovery.yml -o /Users/arya/Code/prometheus-boshrelease/manifests/operators/cf/add-prometheus-uaa-clients.yml -o /Users/arya/Code/prometheus-boshrelease/manifests/operators/cf/add-grafana-uaa-clients.yml

### Please provide output that helps describe the issue:
This includes the bbl command I ran with its result that changed the bosh vm as well as the output of bosh vms command:

# bbl-up
step: terraform init
step: terraform apply
^[[O^[[Istep: creating jumpbox
Deployment manifest: '/Users/arya/Workspace/bosh-bootloader-deployments/staging/jumpbox-deployment/jumpbox.yml'
Deployment state: '/Users/arya/Workspace/bosh-bootloader-deployments/staging/vars/jumpbox-state.json'

Started validating
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:00)
No deployment, stemcell or release changes. Skipping deploy.

Succeeded
step: created jumpbox
step: creating bosh director
Deployment manifest: '/Users/arya/Workspace/bosh-bootloader-deployments/staging/bosh-deployment/bosh.yml'
Deployment state: '/Users/arya/Workspace/bosh-bootloader-deployments/staging/vars/bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:00)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'uaa'... Skipped [Found in local cache] (00:00:00)
  Validating release 'uaa'... Finished (00:00:00)
  Downloading release 'credhub'... Skipped [Found in local cache] (00:00:00)
  Validating release 'credhub'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:02)

Started installing CPI
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:00:00)
  Compiling package 'bosh_aws_cpi/4792924bfe01171a768d7bcfa0b0544f1042393c'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Finished (00:00:01)
  Installing job 'aws_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:02)

Uploading stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/170.9'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM 'i-098fd926df4f27fc8'... Finished (00:00:00)
  Draining jobs on instance 'unknown/0'... Finished (00:00:02)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Unmounting disk 'vol-0efb8575d84c7988e'... Finished (00:00:04)
  Deleting VM 'i-098fd926df4f27fc8'...^[[O^[[I^[[O Finished (00:00:34)
  Creating VM for instance 'bosh/0' from stemcell 'ami-0ab60f8a2a08df12d'...^[[I Finished (00:00:40)
  Waiting for the agent on VM 'i-01bca4e0d069ee2d1' to be ready... Finished (00:00:19)
  Attaching disk 'vol-0efb8575d84c7988e' to VM 'i-01bca4e0d069ee2d1'...^[[O^[[I^[[O Finished (00:00:16)
  Rendering job templates... Finished (00:00:21)
  Compiling package 'ruby-2.4-r5/726cbb2214e138b576700db6a30698edb2b994e2'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'mysql/898f50dde093c366a644964ccb308a5281c226de'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'libpq/ac4ff59910567a4d96e4cf09a7cebe176db240c4'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'bpm-runc/c0b41921c5063378870a7c8867c6dc1aa84e7d85'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'golang/27413c6b5a88ea20a24a9eed74d4b090b7b88331'... Skipped [Package already compiled] (00:00:05)
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:01:51)
  Compiling package 'openjdk_1.8.0/4d45452ce6bd79122873640ac63cae4d9b419ed4'... Skipped [Package already compiled] (00:00:03)
  Compiling package 'golang-1.9-linux/8d6c67abda8684ce454f0bc74050a213456573ff'... Skipped [Package already compiled] (00:00:07)
  Compiling package 'nginx/bbaf345ea78b97afced22fdba03150e42b1db64e'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'registry/60dd8339d5c03242d8c9edcd1dd7a88c59d16220'... Skipped [Package already compiled] (00:00:01)
  Compiling package 'uaa_utils/90097ea98715a560867052a2ff0916ec3460aabb'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'gonats/d1f7b20816a82d5c9422c1dc2ff7e4541e6fd1b8'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'verify_multidigest/8fc5d654cebad7725c34bb08b3f60b912db7094a'... Skipped [Package already compiled] (00:00:00)
  Compiling package 's3cli/02b3531d93b38c9b744d5a15c4f7902a0cc30070'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'lunaclient/b922e045db5246ec742f0c4d1496844942d6167a'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'health_monitor/ed289ef53d20047ea4d98b1370a19ba560bcc9ae'... Skipped [Package already compiled] (00:00:01)
  Compiling package 'davcli/f8a86e0b88dd22cb03dec04e42bdca86b07f79c3'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'bosh-gcscli/fce60f2d82653ea7e08c768f077c9c4a738d0c39'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'director/6ad6429eb6f93199af86b500619a32eea2f5e584'... Skipped [Package already compiled] (00:00:02)
  Compiling package 'bpm/d139b63561eaa3893976416be9668dea539bf17d'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'uaa/6e13a5edd2a3cceb79d181bcac64771ea95fcccd'... Skipped [Package already compiled] (00:00:10)
  Compiling package 'bosh_aws_cpi/4792924bfe01171a768d7bcfa0b0544f1042393c'... Finished (00:00:02)
  Compiling package 'credhub/62f912abb406d6d9b49393be629713fd407328c7'... Skipped [Package already compiled] (00:00:05)
  Compiling package 'configurator/d19e331ac9c867c132d19426007802f86070526a'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'postgres-9.4/e3f2a66d5fb8984e8e70ebc148f098c657595f9c'... Skipped [Package already compiled] (00:00:00)
  Updating instance 'bosh/0'... Finished (00:01:03)
  Waiting for instance 'bosh/0' to be running...^[[O Finished (00:01:37)
  Running the post-start scripts 'bosh/0'... Finished (00:00:03)
Finished deploying (00:07:56)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Succeeded
step: created bosh director
step: generating cloud config
step: applying cloud config
step: applying runtime config
ITs-MacBook-Pro:staging arya$ bosh vms
Using environment 'https://10.1.0.6:25555' as client 'admin'

Task 2775
Task 2776
Task 2775 done

Task 2776 done

Deployment 'cf'

Instance                                         Process State       AZ  IPs         VM CID               VM Type        Active
adapter/ba0a7771-8aa2-4a99-a8e2-044c18cc3d26     unresponsive agent  z1  10.1.16.5   i-0b506b9f6d2dacf33  minimal        true
api/a6d70fd8-fbfa-417e-8594-0025f0538a18         unresponsive agent  z1  10.1.16.8   i-0533df5409670474e  small          true
cc-worker/69320333-949d-491e-a2aa-5ee9c3fd5571   unresponsive agent  z1  10.1.16.9   i-0b4e447f0b7466dd8  minimal        true
credhub/5e2e97dc-6796-47fc-8661-00a81ee102e0     unresponsive agent  z1  10.1.16.16  i-04d90dfc02803c973  minimal        true
diego-api/8e7e02d6-9daf-4df4-aa4b-b4a85dfee6cb   unresponsive agent  z1  10.1.16.6   i-05c0f7198b81270dd  small          true
diego-cell/bd9221a5-2cef-4c4e-bfc7-62ee747780e7  unresponsive agent  z1  10.1.16.14  i-0a7cbc6104dea295f  small-highmem  true
doppler/cae68e5d-c712-462f-abcb-3f2365a7df70     unresponsive agent  z1  10.1.16.13  i-05366899ab80736ac  minimal        true
log-api/dcf2ee1f-8cd7-4764-ab76-75586ff7895f     unresponsive agent  z1  10.1.16.15  i-05a8f2e0cccb557ee  minimal        true
nats/3b7899d7-574c-4d8a-8634-4f3821d31c9f        unresponsive agent  z1  10.1.16.4   i-046bda36a978c80ec  minimal        true
router/b308f980-5487-4be4-9d7f-809f90d55df9      unresponsive agent  z1  10.1.16.10  i-09c590e1366ff7180  minimal        true
scheduler/5d624f91-7242-4a76-a0da-ea32d7549ef1   unresponsive agent  z1  10.1.16.12  i-068859e3f2e890e1a  minimal        true
tcp-router/3d65129b-f26f-4d5c-acdc-b82e1676b753  running             z1  10.1.16.11  i-004ce425efa72612c  minimal        true
uaa/1c88f169-93ad-440c-9f66-054184dc7925         unresponsive agent  z1  10.1.16.7   i-05a9919451677b478  minimal        true

13 vms

Deployment 'prometheus'

Instance                                           Process State  AZ  IPs         VM CID               VM Type  Active
alertmanager/1559ed59-cb9f-4fe6-8bb5-4ed0d120af7c  running        z1  10.1.16.17  i-0a2b85f219bee5c37  default  true
database/6889dc3b-3fb7-473f-9d5f-16fe4f8607fd      running        z1  10.1.16.19  i-058561add6a02a22b  default  true
firehose/0caa5691-19a4-459a-83e5-aeb06f8ebba0      running        z1  10.1.16.22  i-02887b67ba6576902  default  true
grafana/4a8bf613-2622-4eaa-8beb-0d99462b0e60       running        z1  10.1.16.20  i-08d24eac98794713c  default  true
nginx/e384c2a9-672d-4a10-adcd-b6a397a31dbf         running        z1  10.1.16.21  i-0928855a663ba985a  default  true
prometheus2/34360e02-84fd-42fd-a7c8-111b8d3cf50c   running        z1  10.1.16.18  i-0ad4b29a0177ea5e3  default  true

6 vms

Succeeded

### What IaaS is this issue occurring on?

AWS

### Is there anything else unique or special about your setup?

I discussed this with @jhiemer on slack. The only way to fix it was to restart instances from AWS console:

https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1549303613589900

### Tag your pair, your PM, and/or team!
@heyjcollins

**Comment by ab-pivot** [comment]
We're closing this issue, this seems more related to the bosh team.
Please resubmit it in https://github.com/cloudfoundry/bosh/issues
