### ISSUE TITLE
cf login instructions when  credhub is used

### ISSUE THREAD

**Issue by Ykisialiou** [cloudfoundry/cf-deployment#725]
### What is this issue about?

Probably, the docs should cover the steps, necessary to login to Cloud Foundry after the installation completed (it least for `bbl` powered installation). The one can possibly find difficult to connect to credhub, get cf credentials from there, and finally connect to the fresh installation. It looks like a set of necessary credhub command ( e.g. `credhub api https://10.0.0.6:8844`, `credhub login`, `credhub get -n /bosh-bbl-env-%envname%/cf/cf_admin_password`) will make the life a bit easier. And even for nonbbl setup it will help to find the next steps for research.   

[cf-deployment v3.0.0+ here] (where credhub is used)

**Comment by Syerram** [comment]
@Ykisialiou You can create a PR directly in cf docs with the recommendations. Closing this for now. Feel free to reopen if you encounter an issue with opening PR with cf docs.
