### ISSUE TITLE
Split Release bumps and Stemcell bumps into separate tables

### ISSUE THREAD

**Issue by coreyti** [cloudfoundry/cf-deployment#739]
### What is this issue about?

When viewing the release notes for a given cf-deployment release, we would like to see the Release and Stemcell version changes as separate tables.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v7.7.0](https://github.com/cloudfoundry/cf-deployment/releases/v7.7.0)

### Please include the `bosh deploy...` command, including all the operations files:

N/A

### Please provide output that helps describe the issue:

N/A

### What IaaS is this issue occurring on?

N/A

### Is there anything else unique or special about your setup?

Our team collects interesting highlights from the cf-deployment release notes and release notes from BOSH releases, and formats those for internal deployment notification emails. We like to see the release upgrades distinct from stemcells. Being able to simply copy-and-paste from the cf-deployment release notes would be great.

### Tag your pair, your PM, and/or team!

@dirkjot

**Comment by cdutra** [comment]
Hi @coreyti, thanks for bringing this up. I agree, it would look much better if there were separate.
I'd even go further and maybe suggest a xteam pair to see how you consume and maybe even find a format (yaml) to publish a file that can be machine friendly.

Thanks!

**Comment by Syerram** [comment]
@coreyti We are in the process of automating minor releases of new stemcell bumps. These releases will only contain stemcell bumps and you can copy/paste the release note as-is into your internal notifications.

Follow the story here => https://www.pivotaltracker.com/story/show/166421899
