### ISSUE TITLE
unable to set cf api after updating cf v237 to v241

### ISSUE THREAD

**Issue by PiNh00fD** [cloudfoundry/cf-deployment#74]
Hi,

After I migrated cf from version 237 to 241, I'm unable to set api , I get Error performing request: Get https://api.training.cf.redacted.com/v2/info: EOF. this is the first time I'm posting an issue, so I have no idea what information to provide.
ubuntu@cf-ams-training:~$ cf -v
cf version 6.22.1+6b7af9c-2016-09-24

ubuntu@cf-ams-training:~$ uname -a
Linux cf-ams-training 3.13.0-108-generic #155-Ubuntu SMP Wed Jan 11 16:58:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@cf-ams-training:~$ bosh releases
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'trainee' on 'my-bosh'

+----------------------------+----------------+-------------+
| Name                       | Versions       | Commit Hash |
+----------------------------+----------------+-------------+
| cf                         | 237            | 87f11091+   |
|                            | 241*           | 638c22f9+   |
|                            | 244            | e2198e12+   |
| cflinuxfs2-rootfs          | 1.15.0*        | d4408672+   |
|                            | 1.33.0         | 15e18f58+   |
| diego                      | 0.1476.0*      | 23caa9d3    |
|                            | 0.1486.0       | e47f7e29    |
| etcd                       | 55             | 45730f57+   |
|                            | 59*            | c2bd33fc+   |
|                            | 70             | d97246d2+   |
| garden-linux               | 0.338.0*       | 38e53b4a    |
|                            | 0.342.0        | b03a9abc    |
| logsearch                  | 203.0.0*       | f85490fb+   |
| logsearch-for-cloudfoundry | 200.0.0+dev.1* | 170bbb31    |
| postgres                   | 1.0.3          | 71dfd61b+   |
+----------------------------+----------------+-------------+

ubuntu@cf-ams-training:~$ bosh deployments
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'trainee' on 'my-bosh'

+------------------------------+------------------------------------------+----------------------------------------------------+--------------+
| Name                         | Release(s)                               | Stemcell(s)                                        | Cloud Config |
+------------------------------+------------------------------------------+----------------------------------------------------+--------------+
| logsearch                    | logsearch-for-cloudfoundry/200.0.0+dev.1 | bosh-openstack-kvm-ubuntu-trusty-go_agent-raw/3215 | none         |
|                              | logsearch/203.0.0                        |                                                    |              |
+------------------------------+------------------------------------------+----------------------------------------------------+--------------+
| openstack-training-AMS       | cf/241                                   | bosh-openstack-kvm-ubuntu-trusty-go_agent-raw/3215 | none         |
|                              | etcd/59                                  |                                                    |              |
+------------------------------+------------------------------------------+----------------------------------------------------+--------------+
| openstack-training-AMS-diego | cf/241                                   | bosh-openstack-kvm-ubuntu-trusty-go_agent-raw/3215 | none         |
|                              | cflinuxfs2-rootfs/1.15.0                 |                                                    |              |
|                              | diego/0.1476.0                           |                                                    |              |
|                              | etcd/59                                  |                                                    |              |
|                              | garden-linux/0.338.0                     |                                                    |              |
+------------------------------+------------------------------------------+----------------------------------------------------+--------------+

**Comment by dsabeti** [comment]
Hi @PiNh00fD. Let me first try to get some more information to help you troubleshoot:
1. How are your load balancers and proxies configured? Are you running `cf api` from behind a proxy/VPN? What kind of load balancer are you using for your deployment -- IaaS-specific, HAProxy, etc?
2. What's the output if you use `curl -v`:
  ```
  curl -v https://api.training.cf.redacted.com/v2/info
  ```

**Comment by PiNh00fD** [comment]
Hi David,
Thanks for your swift response. I'm not in the position
to awnser your question right now. I come back to you as soon as
possible.
�
�
> Hi @PiNh00fD. Let me first
try to get some more information to help you

> troubleshoot:

> 1. How are your load balancers and proxies configured? Are you
running `cf

> api` from behind a proxy/VPN? What kind of load balancer are you
using for

**Comment by PiNh00fD** [comment]
Hi David,
Here's some information you asked for:
I'm not
using VPN, as far as I know I'm behind a proxy, but only to the
"ouside world"�
When I look at consul agent logging
(stdout) on several VM's I see:
�{"timestamp":"1487663383.864370108","source":"confab","message":"confab.agent-client.verify-joined.members.request.failed","log_level":2,"data":{"error":"Get
http://127.0.0.1:8500/v1/agent/members: dial tcp 127.0.0.1:8500:
getsockopt: connection refused","wan":false}}
Also in
consul agennt stderr logs: 2017/02/22 16:23:07 [ERR] agent.client: Failed
to decode response header: EOF�

	In the postgres logs on the postgres VM I see:

	�

	
		2017-02-23 07:36:54.528 GMT: ERROR: �relation
"schema_migrations" already exists
	
		2017-02-23 07:36:54.528 GMT: STATEMENT: �CREATE TABLE
"schema_migrations" ("filename" text PRIMARY
KEY)


	�

Some extra information:
I followed the Update procedure
from�https://docs.google.com/document/d/1ZzWzp3H6H3t1ikk6Fl-8x1LX2a_0dHPJ5MMLEwY0inI/edit
And
now I'm at step 8. Also tried to roleback to cf v237, but that fails
aswell.
ubuntu@cf-training:~$ curl -v
https://api.training.cf.redacted.com/v2/info
* Hostname was NOT
found in DNS cache
*�� Trying ***.**.***.***...
*
Connected to proxy-server.net (***.**.***.***) port 8080 (#0)
*
Establish HTTP proxy tunnel to api.training.cf.redacted.com:443
>
CONNECT api.training.cf.redacted.com:443 HTTP/1.1
> Host:
api.training.cf.redacted.com:443
> User-Agent:
curl/7.35.0
> Proxy-Connection:
Keep-Alive
>�
< HTTP/1.1 200 Connection
established
< Via: 1.1 REDACTED
< Connection:
Keep-Alive
< Proxy-Connection:
Keep-Alive
<�
* Proxy replied OK to CONNECT
request
* successfully set certificate verify
locations:
*�� CAfile: none
� CApath:
/etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
*
SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT
(11):
* SSLv3, TLS handshake, Server key exchange (12):
*
SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake,
Client key exchange (16):
* SSLv3, TLS change cipher, Client hello
(1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS
change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished
(20):
* SSL connection using ECDHE-RSA-REDACTED-GCM-REDACTED
*
Server certificate:
*�������
subject: C=NL; postalCode=**** GP; ST=reda-cted; L=Somewhere;
street=Someroad 66; O=Some company N.V.; OU=Department;
CN=*.training.cf.redacted.com
*��
�����start date: 2016-09-27 00:00:00
GMT
*������� expire date:
2018-09-27 23:59:59 GMT
*�������
subjectAltName: api.training.cf.redacted.com
matched
*������� issuer:
C=Country; ST=Greater City; L=City; O=COMODO CA Limited; CN=COMODO RSA
Organization Validation Secure Server
CA
*������� SSL certificate
verify ok.
> GET /v2/info HTTP/1.1
> User-Agent:
curl/7.35.0
> Host: api.training.cf.Redacted.com
>
Accept: */*
>�
* Connection #0 to host
proxy-server.net left intact
If you need more info, please let me
know. I'm quite a newbie on cf and
bosh.
�
�
> Hi @PiNh00fD. Let me first try
to get some more information to help you

> troubleshoot:

> 1. How are your load balancers and proxies configured? Are you
running `cf

> api` from behind a proxy/VPN? What kind of load balancer are you
using for

**Comment by dsabeti** [comment]
Hey @PiNh00fD.

Two things:
1. I only just realized that this github issue was made on the wrong repo. I should have asked you to open this on the [cf-release repo](https://github.com/cloudfoundry/cf-release/issues) instead.
2. Something about the way you're posting these results is causing it to be nearly impossible to read. I think using an email client could be part of the problem. When you open this issue in cf-release, could you please try to use the github interfaced so that we don't end up with a bunch of unknown characters and odd formatting?

Thanks!
David

**Comment by PiNh00fD** [comment]
Case can be closed. removed everything and started all over again.
