### ISSUE TITLE
push docker image onto cloudfoundry giving permission error through jenkins

### ISSUE THREAD

**Issue by navin205** [cloudfoundry/cf-deployment#748]
### What is this issue about?

We are able to push the docker image through CLI command, but unable to push through jenkins we get the below error

**org.cloudfoundry.client.v2.ClientV2Exception: CF-AppResourcesFileModeInvalid(160003): The resource file mode is invalid: File mode '444' with path '.git/objects/pack/pack-9ba7fa533ab3f17ba43ac9b193f96da519c38884.pack' is invalid. Minimum file mode is '0600'**

please suggest

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment is the latest

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

running the cf push through jenkins

### Please provide output that helps describe the issue:

org.cloudfoundry.client.v2.ClientV2Exception: CF-AppResourcesFileModeInvalid(160003): The resource file mode is invalid: File mode '444' with path '.git/objects/pack/pack-9ba7fa533ab3f17ba43ac9b193f96da519c38884.pack' is invalid. Minimum file mode is '0600'

### What IaaS is this issue occurring on?

AWS

### Is there anything else unique or special about your setup?

NA

### Tag your pair, your PM, and/or team!

amita487293@gmail.com

**Comment by navin205** [comment]
Hi guys, any update please on the above request plz

**Comment by cdutra** [comment]
Hi @navin205, thanks for reaching our to us.
It seems like this issue is similar to this: https://github.com/cloudfoundry/cli/issues/1096, more precisely this comment seems helpful: https://github.com/cloudfoundry/cli/issues/1096#issuecomment-287736208

I'll close this issue since is seems to be a travis related issue. Feel free to reopen if the problem persists.

Thanks!
