### ISSUE TITLE
consul cert empty on bosh lite

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/cf-deployment#75]
On `master` at `ebcd1cb` (and `develop` at SHA: `48eeb42`). One instance of the consul job gives the following issues:

bosh deploy output (note, we killed it otherwise it would hang forever)
```
16:43:17 | Creating missing vms: log-api/b5bf17b2-01a0-4d7f-9649-df81d6a3e190 (0) (00:00:50)
16:43:17 | Creating missing vms: diego-cell/af10dfe4-0e16-4fb8-bcdc-77ea207fdf44 (0) (00:00:50)
16:43:17 | Updating instance consul: consul/4e847ae8-f6e8-4e37-b192-2a63fd374e61 (0) (canary)
```

consul error output:
```
/:~# tail -f /var/vcap/sys/log/consul_agent/consul_agent.stderr.log
2017/02/21 16:50:28 [ERR] agent.client: Failed to decode response header: EOF
error during start: timeout exceeded: "rpc error: failed to get conn: remote error: tls: bad certificate"
2017/02/21 16:51:20 [ERR] agent.client: Failed to decode response header: EOF
2017/02/21 16:51:20 [ERR] agent.client: Failed to decode response header: EOF
```

Looking at the directory:
```
/:~# cd /var/vcap/jobs/consul_agent/config/certs/
/:/var/vcap/jobs/consul_agent/config/certs# ls -al
total 28
drwxr-xr-x 2 vcap vcap 4096 Feb 21 16:47 .
drwxr-xr-x 3 vcap vcap 4096 Feb 21 16:51 ..
-rw-r----- 1 vcap vcap    1 Feb 21 16:47 agent.crt
-rw-r----- 1 vcap vcap    1 Feb 21 16:47 agent.key
-rw-r----- 1 vcap vcap 1144 Feb 21 16:47 ca.crt
-rw-r----- 1 vcap vcap 1189 Feb 21 16:47 server.crt
-rw-r----- 1 vcap vcap 1676 Feb 21 16:47 server.key
```

**Comment by jaresty** [comment]
Hi @robdimsdale,

We believe that this issue is due to the version of the bosh CLI you are using.  As of [the merging of this PR](https://github.com/cloudfoundry/cf-deployment/pull/53) the variable definition syntax for the bosh CLI changed, which means that older versions of the CLI will generate invalid certificates.  Please update your CLI and try again.  Let us know how it goes before closing this issue.

Thanks!
Josh && @mingxiao

**Comment by robdimsdale** [comment]
Thanks @jaresty 

I haven't tested the new CLI yet but I've heard from others that it fixes the problem, so I'm going to close this issue.

Thanks for digging into this and for the suggested solution

**Comment by genevievelesperance** [comment]
Hi @jaresty,

We updated our bosh CLI to the latest to have that PR but are coming up with the same error as Rob. Do you have any other suggestions for this issue?

**Comment by jaresty** [comment]
Hey @genevievelesperance,

Do you have an existing vars-store, by any chance?  You would need to make sure that you remove it to regenerate the variables _if_ the vars-store was generated with the older CLI.  I've seen a problem like this on our machines when we generated the vars-store using the old CLI and then deployed the same vars-store with a newer CLI.

Let me know if my explanation is not clear -- 

Josh

**Comment by genevievelesperance** [comment]
Explanation is clear! I believe we did wipe the vars-store before trying to deploy with the latest CLI. We will try this again to be sure.

**Comment by genevievelesperance** [comment]
Yes, this worked. Thanks!
