### ISSUE TITLE
Request: add apt-buildpack to list of buildpacks installed

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cf-deployment#765]
### What is this issue about?

The apt-buildpack can be very useful for additional production dependencies; or temporarily bringing in dependencies for debugging. It is a buildpack maintained by the core buildpack team. But it is not included by cf-deployment yet.

Could we include it too?

**Comment by Syerram** [comment]
Buildpack team has no production support for apt-buildpack. Quote from buildpack team,

```
it does not work for many packages, it’s a hack for convenience sake
``` 

Closing the issue.
