### ISSUE TITLE
"silk-controller" job on "diego-api" instance group can't send metrics

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cf-deployment#769]
### What is this issue about?

In cf-deployment v8.1.0, the "silk-controller" job running on the "diego-api" instance group doesn't emit metrics any more. By default, it sends metrics to port 3457, see https://github.com/cloudfoundry/silk-release/blob/8c9901347707def5d9f675c594732a8cf0a36b94/jobs/silk-controller/spec#L74. There is however no metric sink listening on that port. Adding the "loggr-udp-forwarder" job to the "diego-api" instance group would solve the problem, or the "silk-controller" job needs a different configuration.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v8.1.0]

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

We have a complex process to generate the CF manifest which can't be described here. The issue should be reproducible with the instructions provided on https://github.com/cloudfoundry/cf-deployment/blob/master/texts/deployment-guide.md#step-8-deploy-cf.

### Please provide output that helps describe the issue:
No output, must missing metrics.

### What IaaS is this issue occurring on?
IaaS independent.

**Comment by davewalter** [comment]
Hi @jochenehret,

Thanks for bringing this up. This was an issue introduced in `v7.11` when the `deploy-forwarder-agent.yml` ops-file was inlined into the base cf-deployment.yml manifest. We have discussed the change with the loggregator team and confirmed that we need to add the `loggr-udp-forwarder` job to the `diego-api` instance. We will address this in an upcoming release.

Regards,
@vitreuz and Dave

**Comment by MasslessParticle** [comment]
Hi @jochenehret,

It's also possible to emit v2 envelopes directly to the forwarder agent and avoid incurring the v1 -> v2 conversion that the `loggr-udp-forwarder` does.

**Comment by davewalter** [comment]
This has been fixed here: https://github.com/cloudfoundry/cf-deployment/commit/57c15bb909140ff1398b56113f632e6fa5511786

**Comment by jochenehret** [comment]
Thanks for the quick fix!
