### ISSUE TITLE
Running 'cf api https://api.<domain>' returns 401

### ISSUE THREAD

**Issue by tnweiss** [cloudfoundry/cf-deployment#772]
### What is this issue about?

After succesfully deploying cloud foundry I try to target the api endpoint by running 

```
cf api https://api.<DOMAIN>
```

Which results in the following

```
Setting api endpoint to https://api.<DOMAIN>...
Error unmarshalling the following into a cloud controller error: 401 Unauthorized

FAILED
```

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

* Cloud Foundry - https://github.com/cloudfoundry/cf-deployment/tree/v8.1.0
* Bosh CLI - https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-5.5.0-linux-amd64
* Bosh - https://github.com/cloudfoundry/bosh-deployment commit 55fb0c22a15005a4e3f6cc0e3c1f397d44fc2bd9 (most recent) 

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

bosh -n -e ${BOSH_ENV} -d ${CF_ENV} deploy ${CF_DEPLOYMENT_DIR}/cf-deployment.yml \
  --vars-store ${DEPLOYMENT_DIR}/secrets.yml \
  -l ${DEPLOYMENT_DIR}/varsfiles/env-cloud.yml \
  -l ${DEPLOYMENT_DIR}/varsfiles/external-db-cloud.yml \
  -o ${CF_DEPLOYMENT_DIR}/operations/rename-network-and-deployment.yml \
  -o ${CF_DEPLOYMENT_DIR}/operations/use-external-dbs.yml \
  -o ${CF_DEPLOYMENT_DIR}/operations/use-external-blobstore.yml \
  -o ${CF_DEPLOYMENT_DIR}/operations/use-s3-blobstore.yml \
  -o ${CF_DEPLOYMENT_DIR}/operations/override-app-domains.yml \
  -o ${CF_DEPLOYMENT_DIR}/operations/configure-default-router-group.yml \
  -o ${CF_DEPLOYMENT_DIR}/operations/aws.yml

where CF_DEPLOYMENT_DIR is the directory i cloned https://github.com/cloudfoundry/cf-deployment to and DEPLOYMENT_DIR is a directory with my vars files.

### Please provide output that helps describe the issue:

The only error I am seeing has been posted above. 

### What IaaS is this issue occurring on?

AWS

### Is there anything else unique or special about your setup?

Before succesfuly deploying cloud foundry i uploaded a varsfile to the bosh director by running the following.

```
bosh-cloud update-runtime-config ${BOSH_DEPLOYMENT_DIR}/runtime-configs/dns.yml --vars-store ${DEPLOYMENT_DIR}/secrets.yml --name dns
```

### Tag your pair, your PM, and/or team!

N/A

**Comment by tnweiss** [comment]
Is it strange that my credhub database has no entries in it? There are 11 tables but no data in any of the tables. Should my secrets.yml passwords and certs be stored here?

**Comment by cdutra** [comment]
Hi @tnweiss,

When you specify `--vars-store` during `update-runtime-config` you're telling the director to not [these credentials](https://github.com/cloudfoundry/bosh-deployment/blob/76759bfbded58024bed4b459bfc9f4848070f524/runtime-configs/dns.yml#L53-L91) on CredHub instead using a local yaml file.
Try running:
```
bosh-cloud update-runtime-config ${BOSH_DEPLOYMENT_DIR}/runtime-configs/dns.yml -name dns
```
and redeploying your cf deployment. This way bosh director will story the credentials on CredHub and the deployment will use them from the CredHub.
Make sure to clean up [those entries](https://github.com/cloudfoundry/bosh-deployment/blob/76759bfbded58024bed4b459bfc9f4848070f524/runtime-configs/dns.yml#L53-L91) in your `secrets.yml` file.

**Comment by davewalter** [comment]
Hi @tnweiss,

Is this still an issue you need help with?

Regards,
Dave and @Changdrew
