### ISSUE TITLE
Value metrics from tps_watcher and garden-linux are missing due to lack of UDP forwarder

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/cf-deployment#775]
### What is this issue about?

In a recent change the Loggregator Agent is configured to not listen on UDP port 3457 and instead the loggr-udp-forwarder job was added to the instances that have jobs that still use UDP.  In the current config that is the api, router, and tcp-router instances.  Just to be sure I searched the config on all other instances and found these two that are still configured to use UDP:

https://github.com/cloudfoundry/garden-runc-release/blob/master/jobs/garden/spec#L214
https://github.com/cloudfoundry/capi-release/blob/master/jobs/tps/spec#L36

I verified using the Firehose nozzle plugin that any metrics for "garden-linux" and "tps_watcher" are missing.  I then added the loggr-udp-forwarder job to the scheduler and cell instances and the metrics immediately re-appeared.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v9.0.0

### Please provide output that helps describe the issue:

Example metrics that are missing without the UDP forwarder on the scheduler and cell instances:

    origin:"tps_watcher" eventType:ValueMetric timestamp:1558470181941181946 deployment:"" 
    job:"" index:"" ip:"" tags:<key:"source_id" value:"tps_watcher" >
    valueMetric:<name:"memoryStats.lastGCPauseTimeNS" value:26490 unit:"count" >
    origin:"garden-linux" eventType:ValueMetric timestamp:1558470182855344260 deployment:"" 
    job:"" index:"" ip:"" tags:<key:"source_id" value:"garden-linux" >
    valueMetric:<name:"numCPUS" value:4 unit:"count" >

**Comment by davewalter** [comment]
Hi @amhuber,

Thanks for bringing this to our attention. The missing `loggr-udp-forwarder` jobs have been added here: https://github.com/cloudfoundry/cf-deployment/commit/6a3a0fce500b18995a5ea4acb19b3e8a0c5faa14

Once the change makes it through our CI pipelines, it will be available in `release-candidate` and will be included in the next release.

Thanks,
Dave and @Changdrew
