### ISSUE TITLE
Missing metric tags in cf-deployment v9.0.0

### ISSUE THREAD

**Issue by jmprice** [cloudfoundry/cf-deployment#776]
### What is this issue about?
This is just a notice for anyone consuming job metrics like those who use the prometheus-boshrelease (https://github.com/bosh-prometheus/prometheus-boshrelease)

cf-deployment v9.0.0 which contains Loggregator Agent v3.9 with default deployment options to disable UDP listener on the loggregator agent (https://github.com/cloudfoundry/cf-deployment/blob/v9.0.0/cf-deployment.yml#L23-L24) is missing the DEPLOYMENT, JOB, INDEX, and IP tags for any metric still emitted via UDP.

The instances which contain jobs still using UDP are: api, router, and tcp-router, cell, and scheduler

It looks like this has been addressed in a later release of the Loggrator Agent but hasn't been pulled into the cf-deployment yet: cloudfoundry/loggregator-agent-release@031c110

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v9.0.0

**Comment by davewalter** [comment]
Hi @jmprice,

Thanks for the PSA. The work required to bump forward to v3.11 is scheduled for v10, which should be announced for review shortly.

We're going ahead and close this issue since we have a plan to move forward. Feel free to reach either here or in Slack if you have any questions.

Regards,
Dave and @Changdrew

**Comment by benjaminguttmann-avtq** [comment]
@davewalter : Seems like there was some issue with the release notes for cf deployment [v8.0.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v8.0.0). I can see that the commit with the bump to v3.11 was reverted but nevertheless the version update for loggregator-agent v3.9 to v3.11 is mentioned in the release notes.

**Comment by davewalter** [comment]
Thanks for pointing that out @benjaminguttmann-avtq. I'll mention it to @Syerram so he can update the release notes appropriately.
