### ISSUE TITLE
issue with cf login , getting 503 error

### ISSUE THREAD

**Issue by OElGebaly** [cloudfoundry/cf-deployment#777]
### What is this issue about?

 i have deployed CF on AWS, but once i try to run "cf login" i get the following error

REQUEST: [2019-05-22T14:57:24+02:00]
GET /v2/info HTTP/1.1
Host: api.******
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.44.1+c3b20bfbe.2019-05-08 / linux
RESPONSE: [2019-05-22T14:57:25+02:00]
HTTP/1.1 503 Service Unavailable
Connection: close
Content-Length: 24
Content-Type: text/plain; charset=utf-8
Date: Wed, 22 May 2019 12:57:25 GMT
X-Cf-Routererror: endpoint_failure
X-Content-Type-Options: nosniff
503 Service Unavailable
FAILED
Server error, status code: 503, error code: 0, message:

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?
cf version 6.44.1+c3b20bfbe.2019-05-08

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

bosh -e bosh-hexad -d cf deploy cf-deployment/cf-deployment.yml \
--vars-store env-repository/deployment-vars.yml \
-v system_domain=************ \
-o cf-deployment/operations/use-latest-stemcell.yml \
-o cf-deployment/operations/scale-to-one-az.yml \
-o cf-deployment/operations/aws.yml \
-o cf-deployment/operations/use-haproxy.yml
### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

### What IaaS is this issue occurring on?

AWS

### Is there anything else unique or special about your setup?

curl -k https://api.******
503 Service Unavailable

i did ssh into router machine and executed the following command and got the results as follows

curl -k https://10.0.16.10:9024/v2/info
{"name":"","build":"","support":"","version":0,"description":"","authorization_endpoint":"https://login.******","token_endpoint":"https://uaa.******","min_cli_version":null,"min_recommended_cli_version":null,"app_ssh_endpoint":"ssh.******:2222","app_ssh_host_key_fingerprint":"86:35:cf:9a:a6:7c:05:7c:58:e5:72:87:d5:f0:05:36","app_ssh_oauth_client":"ssh-proxy","doppler_logging_endpoint":"wss://doppler.******:4443","api_version":"2.135.0","osbapi_version":"2.14","routing_endpoint":"https://api.******/routing"}router/6f62dd75-ae69-4830-a0e8-759dda249b6d:/var/vcap/sys/log/gorouter#

monit summary
The Monit daemon 5.2.5 uptime: 2h 22m

Process 'gorouter'                  running
Process 'loggr-udp-forwarder'       running
Process 'loggregator_agent'         running
Process 'loggr-expvar-forwarder'    running
Process 'loggr-forwarder-agent'     running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
System 'system_localhost'           running

monit summary
The Monit daemon 5.2.5 uptime: 2h 25m

Process 'cloud_controller_ng'       running
Process 'cloud_controller_worker_local_1' running
Process 'cloud_controller_worker_local_2' running
Process 'nginx_cc'                  running
Process 'route_registrar'           running
Process 'statsd_injector'           running
Process 'file_server'               running
Process 'routing-api'               running
Process 'policy-server'             running
Process 'policy-server-internal'    running
Process 'cc_uploader'               running
Process 'loggr-udp-forwarder'       running
Process 'loggregator_agent'         running
Process 'loggr-expvar-forwarder'    running
Process 'loggr-forwarder-agent'     running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
System 'system_localhost'           running

**Comment by davewalter** [comment]
Hi @OElGebaly,

Have you looked at the CC and UAA logs to see if either show any errors? You could also try running with CF_TRACE=true to see exactly where the error is coming from.

Which version of cf-deployment are you running?

Regards,
Dave and @Changdrew

**Comment by OElGebaly** [comment]
@davewalter 

CF_TRACE=trace.log cf login -a https://api.******* --skip-ssl-validation -v
API endpoint: https://api.*******

REQUEST: [2019-06-14T15:01:09+02:00]
GET /v2/info HTTP/1.1
Host: api.*******
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.45.0+5f9ff16f9.2019-06-03 / linux


RESPONSE: [2019-06-14T15:01:12+02:00]
HTTP/1.1 503 Service Unavailable
Connection: close
Content-Length: 24
Content-Type: text/plain; charset=utf-8
Date: Fri, 14 Jun 2019 13:01:12 GMT
X-Cf-Routererror: endpoint_failure
X-Content-Type-Options: nosniff

503 Service Unavailable

FAILED
Server error, status code: 503, error code: 0, message:

***************************************************************
Which version of cf-deployment are you running?

i use the latest deployment manifest
manifest_version: v9.3.0

**Comment by OElGebaly** [comment]
logs from the router 

api.******* - [2019-06-14T13:43:22.109+0000] "GET /v2/info HTTP/1.1" 503 0 24 "-" "go-cli 6.45.0+5f9ff16f9.2019-06-03 / linux" "2.205.38.3:8442" "10.0.16.10:9024" x_forwarded_for:"2.205.38.3" x_forwarded_proto:"https" vcap_request_id:"a45814e6-ea6a-4d82-7f29-18c3c1c8e4f9" response_time:0.005354809 app_id:"-" app_index:"-" x_b3_traceid:"ef64e9a0df33b33b" x_b3_spanid:"ef64e9a0df33b33b" x_b3_parentspanid:"-" b3:"ef64e9a0df33b33b-ef64e9a0df33b33b"

no logs found on uaa or cc-worker

**Comment by acosta11** [comment]
Hi @OElGebaly,

Nothing in these particular logs seem to directly indicate a cf-deployment issue. To better understand which component may be the source of the 503, could we get a paste of the output from running `bosh is`?

Thanks,
Andrew and @Changdrew

**Comment by davewalter** [comment]
Hi @OElGebaly,

Do you still need help with this issue? One thought we had was that it might be related to your infrastructure setup. How did you create the environment? Are there load balancers in front of the HAproxys, or do the latter have public IP addresses?

Regards,
Dave and @acosta11

**Comment by OElGebaly** [comment]
@acosta11 

bosh is
Using environment 'https://10.0.0.6:25555' as client 'admin'

Task 36. Done

Deployment 'cf'

Instance                                                     Process State  AZ  IPs
adapter/4efe3236-d15e-4920-9e96-5e11d1d71578                 running        z1  10.0.16.5
api/933eee64-9a01-4870-abb6-de65fa65cc41                     running        z1  10.0.16.10
cc-worker/6894e0f9-4b30-43de-8c05-1d7530d679c8               running        z1  10.0.16.11
credhub/34aca465-5df1-42a8-b04f-d31e0c33540a                 running        z1  10.0.16.18
database/7b8cbed4-4342-4f15-b05e-9de8e00631e0                running        z1  10.0.16.6
diego-api/3a786f7a-f12b-4064-8b16-fe9ba11b3e47               running        z1  10.0.16.7
diego-cell/ef879bc6-ffcc-49b2-9daa-256b135cfa2e              running        z1  10.0.16.16
doppler/51ec7ea1-3410-488e-ac57-6f6c1d19b6af                 running        z1  10.0.16.15
log-api/5154d08f-7115-4bf1-bea0-d325e472d9a8                 running        z1  10.0.16.17
nats/9e05b03c-cdeb-44b0-9598-2ac607f5aab6                    running        z1  10.0.16.4
rotate-cc-database-key/09d8bc5d-aeef-4fcb-b347-27ecb0d34150  -              z1  -
router/4f85d641-8fea-4c69-b9ea-60549bd56ec7                  running        z1  10.0.16.13
scheduler/9d287cb0-f168-4a2e-8dde-dcf2d5b7da21               running        z1  10.0.16.12
singleton-blobstore/ff06d5de-9a92-4b6a-870e-1fbba8a79dbc     running        z1  10.0.16.9
smoke-tests/206fc1cf-9fea-4eca-8e12-ef64fbdea9f7             -              z1  -
tcp-router/78038e48-28d4-439d-8391-347bfbc39472              running        z1  10.0.16.14
uaa/9c68dc86-fab6-4806-b34a-c3afcd28b869                     running        z1  10.0.16.8

**Comment by OElGebaly** [comment]
@davewalter 

i deployed bosh director using this Cloud Foundry documentation

https://docs.cloudfoundry.org/deploying/common/aws.html

and deployed CF via this guide on Cloud Foundry documentation

https://docs.cloudfoundry.org/deploying/cf-deployment/deploy-cf.html

**Comment by OElGebaly** [comment]
@davewalter i am already using AWS load balancers  and they all have public IPs

**Comment by OElGebaly** [comment]
i am posting again the cf login command with the error response

cf login -a https://API-END-Point --skip-ssl-validation -v
API endpoint: https://*********

REQUEST: [2019-07-04T13:27:29+02:00]
GET /v2/info HTTP/1.1
Host: *****************
Accept: application/json
Content-Type: application/json
User-Agent: go-cli 6.45.0+5f9ff16f9.2019-06-03 / linux


RESPONSE: [2019-07-04T13:27:29+02:00]
HTTP/1.1 503 Service Unavailable
Connection: close
Content-Length: 24
Content-Type: text/plain; charset=utf-8
Date: Thu, 04 Jul 2019 11:27:29 GMT
X-Cf-Routererror: endpoint_failure
X-Content-Type-Options: nosniff

503 Service Unavailable

FAILED
Server error, status code: 503, error code: 0, message:

**Comment by davewalter** [comment]
Hi @OElGebaly,

We just noticed that the log entry you referenced above from the router indicated that it returned the `503` response. Did you check the cloud_controller logs on the api instance to see if any errors were being recorded there? There might also be more information in other router logs. I'm not sure which one contained the entry you posted.

Regards,
Dave and @Changdrew

**Comment by OElGebaly** [comment]
@davewalter 
thanks for your reply, the only log entries i could find is on the router VM please find them below 
, nothing recorded at api cloud controller node


[2019-07-10T09:25:32.068+0000] "GET /v2/info HTTP/1.1" 503 0 24 "-" "go-cli 6.45.0+5f9ff16f9.2019-06-03 / linux" "178.5.109.206:31952" "10.0.16.10:9024" x_forwarded_for:"178.5.109.206" x_forwarded_proto:"http" vcap_request_id:"511040e9-38ce-4c90-78d3-ec8a0cc8ec06" response_time:0.005228248 app_id:"-" app_index:"-" x_b3_traceid:"d589eaed65e6d902" x_b3_spanid:"d589eaed65e6d902" x_b3_parentspanid:"-" b3:"d589eaed65e6d902-d589eaed65e6d902"

**Comment by davewalter** [comment]
Hi @OElGebaly,

At this point, I would reach out to the Networking team in Slack to see if they can help you figure out why the router is returning 503.

Sorry I can't be more help.

Regards,
Dave

**Comment by Syerram** [comment]
@OElGebaly Pls reach out to #networking team on cloudfoundry.slack.com. Closing this ticket for now and feel free to open it again if you have new information to share.
