### ISSUE TITLE
 Error: Job 'uaa' not found in Template table

### ISSUE THREAD

**Issue by fghorbel** [cloudfoundry/cf-deployment#778]
### What is this issue about?

I have upgraded Bosh-test instance to: 

name: "bosh"
version: "270.1.0"

name: bosh-aws-cpi
version:62

name: "bpm"
version: "1.0.4"

name: "uaa"
version: "72.0"

name: "credhub"
version: "1.9.12"

stemcell:
url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.34

The error Task 33540 | 11:31:23 | Error: Job 'uaa' not found in Template table comes from the uaa job into the cf-deployment. For some reason it doesn t work. No errors in the log files have been shown ...We should investigate

In addition Bosh-test is not stable. For some reasons the task got into the queue but it never kicked off. So, i have to restart the director everything which fixes the problem.
Here the errors that i saw from the Bosh-test logs. the problem could be related to these errors

==> /var/vcap/sys/log/director/worker_4.stdout.log <==
E, [2019-06-02T21:00:00.431372 #28089] [] ERROR -- Director: PG::ConnectionBad: PQconsumeInput() SSL error: decryption failed or bad record mac: (conn: 47239431069600) SELECT NULL

==> /var/vcap/sys/log/nats/nats.log <==
[1] 2019/06/02 23:33:52.274895 [ERR] 10.25.11.40:40438 - cid:6658 - TLS handshake error: tls: oversized record received with length 20037

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment 9.1.0]

`boshv5  -d us-east-1-10.14 deploy  cf-deployment.yml  --vars-store ../comman-vars.yml -v system_domain=$CF_SYS_DOMAIN -v apps_domain=$CF_APPS_DOMAIN -o  operations/use-external-blobstore.yml  -o operations/use-s3-blobstore.yml -o  operations/use-external-dbs.yml`

```
Task 33540 | 11:31:23 | Error: Job 'uaa' not found in Template table

Task 33540 Started  Sun Jun  2 11:31:23 UTC 2019
Task 33540 Finished Sun Jun  2 11:31:23 UTC 2019
Task 33540 Duration 00:00:00
Task 33540 error

Updating deployment:
  Expected task '33540' to succeed but state is 'error'

Exit code 1
```

### What IaaS is this issue occurring on?

[IaaS AWS]

### Is there anything else unique or special about your setup?
NO

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by davewalter** [comment]
Hi @fghorbel,

We haven't seen anything like this with cf-deployment v9.1 or later. It sounds like you probably will want to fix the issues with the director first (the BOSH team can help with that; you can reach them on [CF Slack](https://cloudfoundry.slack.com) in the `#bosh` channel) and then see if the UAA issue still exists. I am going to go ahead and close this, but feel free to re-open it if you are still having problems once your director is functional.

Regards,
Dave
