### ISSUE TITLE
Task 34 system_domain : Failed to find variable

### ISSUE THREAD

**Issue by haviana** [cloudfoundry/cf-deployment#779]
### What is this issue about?
cf-deployment initial setup

Task 34 | 15:23:28 | Error: - Failed to find variable '/VirtualBox-Director/cf/system_domain' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v9.2.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

bosh -d cf deploy cf-deployment/cf-deployment.yml
 -o cf-deployment/operations/bosh-lite.yml \
 -v system_domain=$SYSTEM_DOMAIN \
 -o cf-deployment/operations/scale-to-one-az.yml \
 -o cf-deployment/operations/use-compiled-releases.yml \
 -o ~/workspace/cf-deployment/operations/experimental/use-bosh-dns.yml \
 -o ~/workspace/cf-deployment/operations/experimental/use-bosh-dns-for-containers.yml \
 --no-redact

### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_Task 34 | 15:23:28 | Error: - Failed to find variable '/VirtualBox-Director/cf/system_domain' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does no
t exist or you do not have sufficient authorization.'

Task 34 Started  Tue Jun 11 15:23:28 UTC 2019
Task 34 Finished Tue Jun 11 15:23:28 UTC 2019
Task 34 Duration 00:00:00
Task 34 error
[CLI] 2019/06/11 16:23:28 ERROR - Updating deployment: Expected task '34' to succeed but state is 'error'

Updating deployment:
  Expected task '34' to succeed but state is 'error'

Exit code 1

### What IaaS is this issue occurring on?

bosh-lite

**Comment by benjaminguttmann-avtq** [comment]
@haviana : The error message indicates that BOSH tries to find the variable `system_domain` in credhub and cannot find it in there. So it seems like the `-v system_domain=$SYSTEM_DOMAIN` is not working. Not clear if the bosh command is a single line or multiline, but if it is multi-line keep in mind to use `\` and the end of each line and maybe check for some unnecessary space behind the `\` that might cause some issues here.

**Comment by haviana** [comment]
Thanks for the answer @benjaminguttmann-avtq. I have with the scripts that i intent to be necessary for CF and it is available in https://github.com/haviana/CloudFoundryScripts/blob/master/do-cfENV.sh.
I have also defined system_domain in my environment https://github.com/haviana/CloudFoundryScripts/blob/master/.profile.
What do you think is the reason for the system_domain is not in credbhub?

**Comment by benjaminguttmann-avtq** [comment]
@haviana : Sorry for the confusion, bosh shouldn't look for the variable in credhub as it is provided via the `-v`, you could check your manifest before by replacing `deploy` with `int` and removing the `--no-redact` at the end. In the generated manifest you might check if the system domain provided by you was replaced with the variable `((system_domain))`. Also the order it is important for bosh deploy/int, so you might move the -v to the end of the command.

**Comment by haviana** [comment]
@benjaminguttmann-avtq i have done what you said about the manifest:
 `bosh -d cf int cf-deployment-9.2.0/cf-deployment.yml
 -o cf-deployment-9.2.0/operations/bosh-lite.yml \
 -o cf-deployment-9.2.0/operations/scale-to-one-az.yml \
 -o cf-deployment-9.2.0/operations/use-compiled-releases.yml \
 -o ~/workspace/cf-deployment-9.2.0/operations/experimental/use-bosh-dns.yml \
 -o ~/workspace/cf-deployment-9.2.0/operations/experimental/use-bosh-dns-for-containers.yml \
 -v system_domain=$SYSTEM_DOMAIN
` and then done a grep for system_domain and the result was:

> api: https://api.((system_domain))
        apps_domain: ((system_domain))
      api_uri: proxy.((system_domain))
          - proxy.((system_domain))
          - proxy.((system_domain))
            redirect-uri: https://uaa.((system_domain))/login
        url: https://uaa.((system_domain))
          - uaa.((system_domain))
          - '*.uaa.((system_domain))'
          - login.((system_domain))
          - '*.login.((system_domain))'
      system_domain: ((system_domain))
          - blobstore.((system_domain))
      - ((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
      system_domain: ((system_domain))
        url: https://uaa.((system_domain))
          server_cert_domain_san: api.((system_domain))
          - api.((system_domain))
          - api.((system_domain))/networking
        system_domain: ((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
      system_domain: ((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
            public_endpoint: https://blobstore.((system_domain))
      system_domain: ((system_domain))
          server_cert_domain_san: log-cache.((system_domain))
          - log-cache.((system_domain))
          - '*.log-cache.((system_domain))'
      system_domain: ((system_domain))
          server_cert_domain_san: doppler.((system_domain))
          - doppler.((system_domain))
          - '*.doppler.((system_domain))'
          server_cert_domain_san: log-stream.((system_domain))
          - log-stream.((system_domain))
          - '*.log-stream.((system_domain))'
    - api.((system_domain))
    common_name: api.((system_domain))
    - log-cache.((system_domain))
    - '*.log-cache.((system_domain))'
    - ((system_domain))
    - '*.((system_domain))'
    - api.((system_domain))
    common_name: api.((system_domain))
    - credhub.((system_domain))
    common_name: credhub.((system_domain))
    - log-stream.((system_domain))

Why the system_domain is not been replaced by my system_domain variable which is bosh-lite.com?

Thanks in advance for your help.

**Comment by benjaminguttmann-avtq** [comment]
Is it working if you replace `$SYSTEM_DOMAIN` with `bosh-lite.com` ?

**Comment by haviana** [comment]
Thank you very much with your help i found the problem. It was on my script to create the cf environment.
Now, i hava the following and so far its working 
`#!/bin/bash

echo "Creating Performing action"
echo "system_domain: $SYSTEM_DOMAIN"
echo Performing $1
#bosh update-runtime-config bosh-deployment/runtime-configs/dns.yml --name dns
bosh \
  -d cf \
 $1 \
  cf-deployment-9.2.0/cf-deployment.yml \
  -o cf-deployment-9.2.0/operations/bosh-lite.yml \
  -o cf-deployment-9.2.0/operations/scale-to-one-az.yml \
  -o cf-deployment-9.2.0/operations/use-compiled-releases.yml \
  -v system_domain=$SYSTEM_DOMAIN
if  [ $? -eq 0 ]; then
   echo "Creation of cf successfully finished.."
else
 echo "Fail"
fi
`

**Comment by haviana** [comment]
I have a error in one line on my previous script and for that motive the line with system_domain was never executed.

**Comment by acosta11** [comment]
This issue seems to have been resolved. Please re-open this issue if you have any more questions.

Andrew and @Changdrew
