### ISSUE TITLE
How to upgrade cloud foundry from v7.2.0 to v7.11.0

### ISSUE THREAD

**Issue by ramaraoyerramsetti** [cloudfoundry/cf-deployment#785]
### What is this issue about?
Need to understand the possibility and process of cloud foundry upgrade from 7.2.0 to 7.11.0

I'm a bit new to CF deployment but quite used to handling applications on CF components.
At the moment we have a requirement to upgrade CF from 7.2 (which we have proved) to 7.11 which is the latest available to upgrade.
As of now we were doing clean deployments but here we need to know whether there's a clear approach to upgrade existing stack. In theory, I think we need to update manifest yml file with latest version and details of any component that's been changed and use bosh deployment commands to deploy.

But we are not sure what are the actual steps and commands to upgrade. It would be great if someone provides details on how to upgrade CF.

Thanks in advance.
_What steps/actions led to the issue?_
Need to upgrade from 7.2.0 to 7.11.0

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v7.2.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

[bosh deploy command here]

### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

### What IaaS is this issue occurring on?

[IaaS name(s) here]

### Is there anything else unique or special about your setup?

[Description here]

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by acosta11** [comment]
Hello Ram,

After pulling the latest minor version of the repo, upgrading your CF deployment uses the same deploy command as your current CF deployment. See [this link](https://bosh.io/docs/deploying/) for more information:


> The CLI has a single command to create and update a deployment: bosh deploy command. From 
the perspective of the Director same steps are taken to create or update a deployment.

Thanks,
Andrew

**Comment by ramaraoyerramsetti** [comment]
Thanks Andrew, we achieved the upgrade by using the latest manifest changes and using the same deploy commands.
