### ISSUE TITLE
CF ssh handshake failed

### ISSUE THREAD

**Issue by ramaraoyerramsetti** [cloudfoundry/cf-deployment#790]
### What is this issue about?
Not able to ssh to app container using "cf ssh" after enable-ssh.

We have upgrade CF from v7.2 to v7.11. 
cf ssh was working fine with v7.2 but post upgrade cf ssh giving below handshake error.

cf ssh <app>
FAILED
Error opening SSH connection: ssh: handshake failed: EOF

Do we need perform any other settings apart from upgrade to enable ssh ?

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v7.11.0

cf-cli version - 6.46.0+29d6257f1.2019-07-09

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

[bosh deploy command here]

### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

### What IaaS is this issue occurring on?

[IaaS name(s) here]

### Is there anything else unique or special about your setup?

[Description here]

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by davewalter** [comment]
Hi @ramaraoyerramsetti,

I am afraid that we don't offer support for older versions of cf-deployment. Could you please upgrade to the [latest available release](https://github.com/cloudfoundry/cf-deployment/releases) and see if that resolves the issue?

Thanks,
Dave
