### ISSUE TITLE
Not able to tail CF logs when upgrade CF from v7.2.0 to v7.11.0

### ISSUE THREAD

**Issue by ramaraoyerramsetti** [cloudfoundry/cf-deployment#795]
### What is this issue about?
Not able to tail cf logs of any app and getting the below error. This is happening when we upgraded CF from 7.2 to 7.11

cf logs <app>
Error dialing trafficcontroller server: unexpected EOF.
Please ask your Cloud Foundry Operator to check the platform configuration (trafficcontroller is wss://doppler.cf-new.hf-cdp.internal:4443).. Retrying...

Timeout trying to connect to NOAA

cf logs <app> --recent
unknown issue when making HTTP request to Loggregator
FAILED

This caused when we upgraded CF from 7.2.0 to 7.11.0
### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using? = v7.11.0

[cf-deployment v7.11.0 here]

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

Not deployed the bosh recently, just upgraded cf version from v7.2.0 to v7.11.0

### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

### What IaaS is this issue occurring on?

AWS

### Is there anything else unique or special about your setup?
We can see the request for logs reached the router component but not able to trace issue from there.

[Description here]

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by davewalter** [comment]
Hi @ramaraoyerramsetti,

I am afraid that we don't offer support for older versions of cf-deployment. Could you please upgrade to the [latest available release](https://github.com/cloudfoundry/cf-deployment/releases) and see if that resolves the issue?

Thanks,
Dave
