### ISSUE TITLE
Auto-bump datadog-firehose-nozzle-release

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/cf-deployment#797]
### What is this issue about?

[This opsfile](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/test/add-datadog-firehose-nozzle.yml) is quite useful and it would be great if the `datadog-firehose-nozzle-release` it references was automatically bumped like other releases are. Currently it is at version `68` in `cf-deployment` but the latest release version is `74`.

**Comment by sunjayBhatia** [comment]
See: https://github.com/cloudfoundry/cf-deployment/pull/804

**Comment by acosta11** [comment]
Added to the pipeline in https://github.com/cloudfoundry/cf-deployment/commit/d0ef3302cf4d96d477c0b0cd069d885754780ab4 .
