### ISSUE TITLE
`prom_scraper` in Loggregator agent 3.18 leaks file descriptors

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/cf-deployment#798]
### What is this issue about?

The `prom_scraper` job from Loggregator-agent 3.18 does not properly clean up connections and results in exhausted file descriptors on a VM.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

10.1.0

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

@chentom88 @AllenDuet

**Comment by davewalter** [comment]
Hi @MasslessParticle,

Thanks for letting us know. Our CI has already [consumed loggregator-agent v3.19](https://github.com/cloudfoundry/cf-deployment/commit/8c684602f8e335c09f31225ec81d1f689646c09c) and is currently running our standard set of tests. As soon as they pass, we will cut a new minor release of cf-deployment, which will be v10.2.0.

Regards,
Dave

**Comment by davewalter** [comment]
This was resolved when we released [v11.0.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v11.0.0) of cf-deployment, which included a bump to v3.20 of loggregator-agent.
