### ISSUE TITLE
UAA Bosh Release 73.7.0 is missing Version

### ISSUE THREAD

**Issue by FloThinksPi** [cloudfoundry/cf-deployment#799]
### What is this issue about?

The UAA-Version in CF-D 10.1.0, UAA-release 73.7.0 contains a UAA version which has no Version number (gradle files refer to version 0.0.0)

See https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1564401816020800 for slack conversation.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

CF-D 10.1.0

### Please provide output that helps describe the issue:

```
curl https://uaa.myserver.example/info

{  
   “app”:{  
      “version”:“0.0.0”
   },
   “links”:{  
      “uaa”:      “https://uaa.myserver.example”,
      “passwd”:“/forgot_password”,
      “login”:      “https://login.myserver.example”,
      “register”:“/create_account”
   },
   “zone_name”:“uaa”,
   “entityID”:“login.myserver.example”,
   “commit_id”:“04c4811",
   “idpDefinitions”:{  

   },
   “prompts”:{  
      “username”:[  
         “text”,
         “Email”
      ],
      “password”:[  
         “password”,
         “Password”
      ]
   },
   “timestamp”:   “2019-07-22T19:49:34+0000   "
}
```

Following github diff also shows that the Version in UAA got replaced by 0.0.0
[Difflink](https://github.com/cloudfoundry/uaa/compare/a8f574db5a48ecb6db80b344f0b81542238c4a7d...04c481155f7aa028134ae9a7da518acf6705adb4#diff-503f218d646c10f484fdc9d6315bf2e3L1-R1)

### What IaaS is this issue occurring on?

GCP

### Is there anything else unique or special about your setup?

Nope

### Tag your pair, your PM, and/or team!

@philippthun

**Comment by Syerram** [comment]
This is fixed in the latest v11 version.
