### ISSUE TITLE
deploy doc link broken

### ISSUE THREAD

**Issue by cdlliuy** [cloudfoundry/cf-deployment#801]
Some links in the "deploy CF" guide https://github.com/cloudfoundry/cf-deployment/blob/master/texts/deployment-guide.md  are broken, such as:

https://github.com/cloudfoundry/cf-deployment/blob/master/texts/iaas-support/bosh-lite/README.md

https://github.com/cloudfoundry/cf-deployment/blob/master/texts/iaas-support/README.md

**Comment by davewalter** [comment]
Hi @cdlliuy,

It looks like this was addressed by PR https://github.com/cloudfoundry/cf-deployment/pull/791 so I am going to go ahead and close this issue. Please feel free to reopen it if there are still broken links not fixed by the above PR.

Thanks!
Dave
