### ISSUE TITLE
Unknown MySQL Server Host 'sql-db.service.cf.internal' (

### ISSUE THREAD

**Issue by addisflava** [cloudfoundry/cf-deployment#806]
### What is this issue about?

_In your own words, describe the issue._
_What steps/actions led to the issue?_

am getting the following error in the api instance for the cloud_controller 
/var/vcap/sys/log/cloud_controller_ng/cloud_controller_ng.log 
"Encountered error: Mysql2::Error: Unknown MySQL Server Host 'sql-db.service.cf.internal' 
Blobstore is available                       
                                                                                                             
Mysql2::Error: Unknown MySQL Server Host 'sql-db.service.cf.internal' (-5)                                                                                
Checking for blobstore availability                                                                                                                       
Blobstore is available                                                                                                                                    
Mysql2::Error: Unknown MySQL Server Host 'sql-db.service.cf.internal' (-5)

am getting this error only when i add the ops file use-external-dbs.yml . other wise it works fine when its using its own database 
in  the use-external-dbs.yml  ops file and i dont see any substitution for the alias in cf-deploment.yml
    - domain: sql-db.service.cf.internal                                                                                                                
        targets:                                                                                                                                          
        - query: '*'                                                                                                                                      
          instance_group: database                                                                                                                        
          deployment: cf                                                                                                                                  
          network: default                                                                                                                                
          domain: bosh

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v10.1.Z here]

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

[bosh deploy command here]
       boshv3 -e bosh-$env  -d ${DEPLOYMENT}   deploy cf-deployment.yml  \
       -l static-vars.yml \
       -o aws.yml \
       -o use-external-dbs.yml
### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

### What IaaS is this issue occurring on?

[IaaS name(s) here]

### Is there anything else unique or special about your setup?

[Description here]

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by davewalter** [comment]
Hi @addisflava,

If you are using the `use-external-dbs.yml ` ops-file, then nothing should be attempting to use `sql-db.service.cf.internal` as it is no longer resolvable. I ran `bosh interpolate cf-deployment.yml -o operations/use-external-dbs.yml` | grep sql-db and the only entry I saw was in the `bosh-dns-aliases` addon section at the top of the manifest. Can you please check your interpolated manifest to see if there are any other references, specifically in the configuration for cloud controller?

Let us know what you find.
Dave

**Comment by addisflava** [comment]
yes the same thing here only in the domian section 

without  use-external-dbs.yml  ops file
```
→bosh interpolate  -d cf   cf-deployment.yml         -l static-vars.yml        -o aws.yml   | grep -n sql-db.service
202:      - domain: sql-db.service.cf.internal
434:            db_host: sql-db.service.cf.internal
455:        host: sql-db.service.cf.internal
478:            db_host: sql-db.service.cf.internal
637:        address: sql-db.service.cf.internal
846:        address: sql-db.service.cf.internal
974:          host: sql-db.service.cf.internal
989:        host: sql-db.service.cf.internal
1091:        address: sql-db.service.cf.internal
1213:        address: sql-db.service.cf.internal
1794:          host: sql-db.service.cf.internal
2468:    common_name: sql-db.service.cf.internal
```

with use-external-dbs.yml  ops file 
```
→bosh interpolate  -d cf   cf-deployment.yml         -l static-vars.yml        -o aws.yml   -o use-external-dbs.yml| grep -n sql-db.service
202:      - domain: sql-db.service.cf.internal
```

**Comment by davewalter** [comment]
Interesting. If you ssh onto one of the cloud-controller instances using `bosh ssh api/0` and run `sudo grep -rl sql-db.service.cf.internal /var/vcap/jobs/*`, do you see any results? For reference, on a deployment configured with an external database, I only see:
```
$ sudo grep -rl sql-db /var/vcap/jobs/*
/var/vcap/jobs/bosh-dns-aliases/dns/aliases.json
```
whereas on a deployment configured with an internal database, I see:
```
$ sudo grep -rl sql-db /var/vcap/jobs/*
/var/vcap/jobs/bosh-dns-aliases/dns/aliases.json
/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml
/var/vcap/jobs/policy-server/config/policy-server.json
/var/vcap/jobs/policy-server-internal/config/policy-server-internal.json
/var/vcap/jobs/routing-api/config/routing-api.yml
```

**Comment by addisflava** [comment]
@davewalter 

thanks i found out the reson is because i changes the deployment name and didnt use the rename-network-and-deployment.yml ops file
