### ISSUE TITLE
Minimizing VM sizes for the scale-to-one-az.yml opsfile deployment

### ISSUE THREAD

**Issue by mjj209** [cloudfoundry/cf-deployment#815]
### What is this issue about?
related to https://github.com/cloudfoundry/cf-deployment/issues/315
We would like to minimize the VM sizes for cf-deployment in a single-AZ architecture. We would like guidance on doing one of the following:
1. PR'ing to the scale-to-one-az.yml opsfile
2. PR'ing a new experimental opsfile
3. Do nothing, because there will be a better solution soon, or this would never be accepted as a PR

The CF Toolsmiths are planning to start building a lot of cf-deployment environments. We would like to make this testing cheap. We saw that it will be trivial to apply the scale-to-one-az.yml ops file, and have only singleton jobs, which reduces the count of VMs. We have experience in minimizing the VM sizes for the commercial PCF Product as described [here](https://content.pivotal.io/blog/how-to-save-a-fortune-on-cloud-infrastructure). We would like to reduce the size of several VMs, specifically on GCP.

We would plan to experiment a bit with sizes of the various VMs. My short list for minimizing sizes is:
- Diego cell -> 2 cores and 13GB of RAM
- UAA -> 1 core and 2GB RAM
- Cloud Controller -> 1 core and 4GB RAM
- Clock-global -> 1 core and 4GB RAM

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v11.0.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

We plan to use the following OpsFiles:
scale-to-one-az.yml
use-compiled-releases.yml
fast-deploy-with-downtime-and-danger.yml

### What IaaS is this issue occurring on?

We currently are only working with GCP

### Tag your pair, your PM, and/or team!
We're in the #toolsmiths channel in the Cloud Foundry Slack, or #cf-toolsmiths in the Pivotal Slack org.

**Comment by davewalter** [comment]
Hi @mjj209,

I would suggest developing this as a separate ops-file to avoid making changes to the existing `scale-to-one-az.yml` ops-file that might surprise other operators, especially if the changes are going to be different per IaaS. This way, you can work on the ops-file(s) in your own GH repo and then consider PR'ing them into cf-deployment when they are ready for others to consume. You can use the [collect-ops-files](https://github.com/cloudfoundry/cf-deployment-concourse-tasks#collect-ops-files) Concourse task to combine multiple ops-file directories together to be used in a single [bosh-deploy](https://github.com/cloudfoundry/cf-deployment-concourse-tasks#bosh-deploy) step. See [here](https://github.com/cloudfoundry/cf-deployment/blob/ededadf5ba65bbc11d7b570c094c6ec4d86ebb65/ci/pipelines/cf-deployment.yml#L478-L516) for an example.

Let us know if you need help with anything during this process.

Regards,
Dave

**Comment by mjj209** [comment]
@davewalter That sounds good, we'll plan to develop a separate ops-file in our own GH repo for the time being. Thanks for the guidance!
