### ISSUE TITLE
Is Open tracing possible during cf push ??

### ISSUE THREAD

**Issue by pyogesh2** [cloudfoundry/cf-deployment#822]
In our setup, we have the zipkin tracing enabled and we are able to trace the application from gorouter to the app and so.
However, we are interested to trace - during cf push of an application. 
Are the open tracing enabled within the cloud foundry components - cc api etc.,

**Comment by acosta11** [comment]
Hi @pyogesh2 ,

Sorry, but that functionality does not currently exist as far as we know. Zipkin supports app request tracing, which is separate from the cf internal tracing that would be relevant to the cf push command. The closest functionality is the verbose mode of the cf cli (-v flag or the env variable CF_TRACE=true) which will provide only the top level requests to the cc api.

If you're interested in further exploring zipkin tracing in particular, the '#networking' slack channel may be able to help (that's where we checked when investigating this functionality).

Thanks,
Andrew and @davewalter
