### ISSUE TITLE
cf ssh not working for v7.11.0

### ISSUE THREAD

**Issue by ramaraoyerramsetti** [cloudfoundry/cf-deployment#827]
### What is this issue about?
Post successful deployment of CF version 7.11.0, apps were deploying fine but we're not able to ssh into app and can see "Error opening SSH connection: ssh: handshake failed: EOF"

It looks the request reaching UAA server and can see the below logs as well from UAA server but not any error logs.

UAA server logs -[2019-10-01 07:52:16.878] uaa - 1 [http-nio-8080-exec-3] ....  INFO --- Audit: ClientAuthenticationSuccess ('Client authentication success'): principal=cf, origin=[remoteAddress=10.16.38.122, clientId=cf], identityZoneId=[uaa]
[2019-10-01 07:52:16.933] uaa - 1 [http-nio-8080-exec-3] ....  INFO --- Audit: TokenIssuedEvent ('["clients.read","openid","routing.router_groups.write","scim.read","cloud_controller.admin","uaa.user","routing.router_groups.read","cloud_controller.read","password.write","cloud_controller.write","network.admin","doppler.firehose","scim.write"]'): principal=ef441dce-0d35-42b5-99dd-e38e8f95d480, origin=[caller=cf, details=(remoteAddress=10.16.38.122, clientId=cf)], identityZoneId=[uaa]
_In your own words, describe the issue._
_What steps/actions led to the issue?_
while performing cf ssh <app name>

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment vX.Y.Z here]
v7.11.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

[bosh deploy command here]

### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

### What IaaS is this issue occurring on?
AWS
[IaaS name(s) here]

### Is there anything else unique or special about your setup?

[Description here]

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by davewalter** [comment]
Hi @ramaraoyerramsetti,

Unfortunately, we cannot provide support for old versions of cf-deployment. You can try upgrading to the [latest version of cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) and seeing if that resolves the problem. Alternatively, you can reach out to the Diego team (#diego) for help in [Slack](https://cloudfoundry.slack.com).

Regards,
Dave and @weymanf
