### ISSUE TITLE
use initial_deploy_az_update_strategy in favor of expirmental fast deploy opsfile

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/cf-deployment#829]
since the new release of bosh `270.6.0`
we have the ability to use [initial_deploy_az_update_strategy](https://www.pivotaltracker.com/n/projects/956238/stories/168067218)

would be nice to have instead of relying on a opsfile like [experimental/fast-deploy-with-downtime-and-danger.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/fast-deploy-with-downtime-and-danger.yml)

**Comment by davewalter** [comment]
Hi @ramonskie,

Based on the [comments](https://www.pivotaltracker.com/story/show/168067218/comments/206744306) in the tracker story, it looks like we would still need the contents of the `fast-deploy-with-downtime-and-danger.yml` ops-file to remove the `canary` requirement and increase the `max_in_flight` setting. Given that we cannot do this by default, we aren't sure what you are requesting? You could always create a new ops-file to set this if desired.

Regards,
Dave and @weymanf

**Comment by ramonskie** [comment]
ahh okay.
well than my assumption for this opsfile existence was then incorrect.
my thought was just for the speedup of the deployment.

its still a nice feature to add though. to speedup the first time deployment in general.
but maby it should be added later as this is a pretty new feature.

**Comment by davewalter** [comment]
Hi @ramonskie,

We'll check in with the BOSH team to see if there is any benefit to adding `initial_deploy_az_update_strategy` to the base cf-deployment manifest or one of the ops-files.

Thanks,
Dave

**Comment by weymanf** [comment]
After further review our base manifest will probably keep the canaries at 1 and max_in_flight at 1, which would basically mean adding this flag to the base manifest will have no affect. We can add this to a separate opsfile but it will be affectively the same as the current fast-deploy opsfile. 

We are probably not going to maintain a separate opsfile for a first deploy situation that is safer than the fast-deploy-with-downtime-and-danger.yml. Going to close this Issue.

Regards,
Weyman + Dave
