### ISSUE TITLE
compiled release URLs are not being updated before new release is cut

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/cf-deployment#847]
### What is this issue about?

Today we noted that https://github.com/cloudfoundry/cf-deployment/commit/f18498ed26697047a173ffe89e12b618b95ae553 was released as https://github.com/cloudfoundry/cf-deployment/releases/tag/v12.11.0 which listed in its release notes as bumping the version of the stemcell.

We noted that https://github.com/cloudfoundry/cf-deployment/blob/f18498ed26697047a173ffe89e12b618b95ae553/operations/use-compiled-releases.yml#L8 still refers to the old stemcell (as do all the other compiled releases).

This will nearly certainly cause deployment with that operator file to fail.

Normally this file is bumped before a new release is cut.

**Comment by pivotaljohn** [comment]
Hello @aeijdenberg, thank you for your concern.

If we're reading your question right, the good news is that that this will not actually create a problem for operators. From the [BOSH docs on compiled releases](https://bosh.io/docs/compiled-releases/):

> Compiled releases are built against a particular stemcell version. Director allows compiled releases to be installed on any minor version of the major stemcell version that the compiled release was exported against. bosh create-env command requires exact stemcell match unlike the Director.

We are also validating this in our own CI [here](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-deployment/jobs/upgrade-deploy/builds/2935). We'll presume this issue closed, but if you see other concerns, feel free to re-open.

Thanks,
@cloudfoundry/cf-release-integration
