### ISSUE TITLE
Is uaa.login.client_secret unnecessary?

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cf-deployment#85]
The job properties for the UAA in cf-deployment.yml includes a `uaa.login.client_secret` property, but that is no longer a property listed in the UAA spec, and looks to have been removed in https://github.com/cloudfoundry/uaa-release/commit/a33a1f30e3ccaad24872b67144d6e13a9e730cef

Should this be removed from the manifest, and replaces with a login client defined in `uaa.clients`? Is the login client no longer required in `uaa.clients` either?

**Comment by dsabeti** [comment]
Hey @geofffranks. Great find. Thanks for pointing this out. I'll prioritize this story.

**Comment by dsabeti** [comment]
We've made the fix and accepted the story, so I'm closing the issue.
