### ISSUE TITLE
"api" instance_group should have update.serial=true

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cf-deployment#852]
### What is this issue about?

We've updated from CF v12.3.0 to CF v12.9.0. The update contained some CC database scheme migrations. BOSH tried to update the first node from the "api" instance_group, but this failed because of database issues. Because "api" did not have "update.serial=true", BOSH continued to update the next instance_group: the "cc-worker" nodes. The "cc-workers" were then all updated and failed because they expected the new database scheme. This caused a longer downtime on the landscape. 

So we think that "update.serial" should be set to "true" for the "api" instance_group. The workers must only be updated when the database migration has completed successfully.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

Update from cf-deployment v12.3.0 to v12.9.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

We basically run "bosh -d cf deploy".

### Please provide output that helps describe the issue:

```
Task 16184818 | 13:35:36 | Updating instance bits: bits/fe8d758e-127a-4d4f-b764-4711bc7d6653 (9) (00:02:24)
Task 16184818 | 13:38:02 | Updating instance cc-worker: cc-worker/e597d744-7bd6-4228-9617-cd2b2627f2d4 (0) (canary)
Task 16184818 | 13:38:08 | Updating instance api: api/0bc6d14d-a274-4f78-ac13-e213e40a7078 (0) (canary)
Task 16184818 | 13:40:56 | Updating instance cc-worker: cc-worker/e597d744-7bd6-4228-9617-cd2b2627f2d4 (0) (canary) (00:02:54)
Task 16184818 | 13:40:56 | Updating instance cc-worker: cc-worker/5c2fb9b6-f692-47e2-a481-211234c53141 (4)
Task 16184818 | 13:42:00 | Updating instance api: api/0bc6d14d-a274-4f78-ac13-e213e40a7078 (0) (canary) (00:03:52)
                     L Error: Action Failed get_task: Task c968e90c-7f40-48d3-4d74-f8c015254bb8 result: 1 of 7 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: sysctl, bpm, bosh-dns, syslog_forwarder, cc_uploader, policy-server.
Task 16184818 | 13:43:50 | Updating instance cc-worker: cc-worker/5c2fb9b6-f692-47e2-a481-211234c53141 (4) (00:02:54)
Task 16184818 | 13:43:50 | Updating instance cc-worker: cc-worker/685e0809-fa8c-4056-8c65-a9c5140c0850 (2) (00:02:52)
Task 16184818 | 13:46:42 | Updating instance cc-worker: cc-worker/c3688af0-100a-480b-ab09-adea293f567f (6) (00:03:02)
Task 16184818 | 13:49:45 | Updating instance cc-worker: cc-worker/133824e3-3ad5-4bfc-b478-245b2f995cc8 (1) (00:02:58)
Task 16184818 | 13:52:43 | Updating instance cc-worker: cc-worker/413883be-9995-4356-b8d7-1357ece04ef6 (7) (00:02:56)
Task 16184818 | 13:55:39 | Updating instance cc-worker: cc-worker/f77fee59-b438-4636-97c0-88a7638da847 (3) (00:02:53)
Task 16184818 | 13:58:32 | Updating instance cc-worker: cc-worker/fcf9c593-f07e-464f-992d-ed7b35fbbbbf (5) (00:02:33)
Task 16184818 | 14:01:06 | Error: Action Failed get_task: Task c968e90c-7f40-48d3-4d74-f8c015254bb8 result: 1 of 7 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: sysctl, bpm, bosh-dns, syslog_forwarder, cc_uploader, policy-server.

Task 16184818 Started  Thu Dec  5 11:10:28 UTC 2019
Task 16184818 Finished Thu Dec  5 14:01:06 UTC 2019
Task 16184818 Duration 02:50:38
Task 16184818 error
Updating deployment:
  Expected task '16184818' to succeed but state is 'error'

Exit code 1
```

### What IaaS is this issue occurring on?

AWS (but the issue is IaaS independent)

### Is there anything else unique or special about your setup?

This issue is related to the failing database scheme migration: https://github.com/cloudfoundry/cloud_controller_ng/issues/1363

**Comment by cwlbraa** [comment]
started a thread to discuss this in #cf-deployment https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1579722394000500

**Comment by davewalter** [comment]
Hi @jochenehret,

Thanks for bringing this up. After much discussion between CAPI and ourselves, we have added the serial true flag to the api instance group here: https://github.com/cloudfoundry/cf-deployment/commit/a2a2ffa4d66a77aec013fc5b4475f4cd4a63090d

It will take a few hours to work it's way through our CI, but should be included in our next release, which is due later this week.

Thanks,
Dave and Sebastian (@vitreuz)
