### ISSUE TITLE
Convert to uaa.jwt.policy.keys from uaa.jwt.signing_key

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cf-deployment#86]
Per https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L353-L356, the `uaa.jwt.signing_key` and `uaa.jwt.verification_key` properties are deprecated. Should these templates be updated to use the new `uaa.jwt.policy.keys` and `uaa.jwt.policy.active_key_id` properties?

**Comment by dsabeti** [comment]
Hey @geofffranks. Another great catch. We actually already have a story to address this: https://www.pivotaltracker.com/story/show/134668165. 😄 

Admittedly, It's just a long ways off in our backlog. Right now, we're focusing a little more on smoothing out the UX for cf-deployment -- for example, reducing deploy time, allowing for a single-AZ/smaller footprint deploy, and a migration path from cf-release to cf-deployment. Let me know if you there's a reason you'd want this update sooner.

**Comment by geofffranks** [comment]
Nope, just didn't see it in the GH issues.
