### ISSUE TITLE
inconsistent blobstore for compiling windows packages.

### ISSUE THREAD

**Issue by aarti2309** [cloudfoundry/cf-deployment#878]
### What is this issue about?

We are facing inconsistent blobstore issue while compiling the widows packages for windows cells. when I fixed the release of windows using --fix then I got "shelling out" error. However, these errors are very random on windows packages.

CF Version 11.2.0
CF Stemcells:  bosh-aws-xen-hvm-ubuntu-xenial-go_agent/621.29 and bosh-aws-xen-hvm-windows2016-stemcell-go_agent/1709.21   /1709.20
Bosh Version 270.8.0(Stemcell bosh-aws-xen-hvm-ubuntu-xenial-go_agent/621.29 )
CPI: AWS
Compiling VM type: C5.xlarge

![inconsistence-blob](https://user-images.githubusercontent.com/24243530/80065286-7e8c6300-8557-11ea-918b-c07bb23b6922.JPG)
![shelling-out2](https://user-images.githubusercontent.com/24243530/80065295-81875380-8557-11ea-87e6-9bf6edf82bb8.JPG)

**Comment by davewalter** [comment]
Hi @aarti2309,

Sorry to hear that you are experiencing problems. This seems more like an problem with your BOSH director configuration than anything to do with cf-deployment itself, so we are going to go ahead and close this issue. We suggest reaching out to the BOSH team to see if they can assist you.

Regards,
Dave and @Birdrock
