### ISSUE TITLE
How to rotate cf certs (using credhub) with larger duration

### ISSUE THREAD

**Issue by aad** [cloudfoundry/cf-deployment#886]
### What is this issue about?

we are using credhub as secret store for cf. the original ca/certificates were generated by an older bosh-cli (which has expire duration 1 year) and we could rotate certs successfully every year.

We tried the latest bosh-cli (6.2.1) and we can generate larger duration in a fresh environment. The challenge is in existing environment. After applying the duration changes in bosh, we tried to rotate the certs and we found the duration in newly generated certs is still 1 year.

high level steps we tried
- bosh deploy with duration applied via opsfile
- force a cert rotation 
- verify new expiration date

```
- type: replace
  path: /variables/name=xxx_ca/options?/duration?
  value: ((certificate_duration))
```

I raised the same query in credhub (https://github.com/cloudfoundry-incubator/credhub/issues/128) but i think someone here might have done this successfully.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v12.34.0]

### What IaaS is this issue occurring on?

[vsphere]

**Comment by jamespollard8** [comment]
Hey @aad,

because this is specifically credhub related, asking on their repo was the right place 👍 

To ask others about potential work-arounds, you could try the [#credhub](https://cloudfoundry.slack.com/archives/C3EN0BFC0) channel in the CloudFoundry slack
