### ISSUE TITLE
13.6 Release notes omit loggregator-agent limitations

### ISSUE THREAD

**Issue by spgreenberg** [cloudfoundry/cf-deployment#893]
### What is this issue about?

I believe the release notes regarding the limitations to the loggregator-agent are missing for 13.6. It does not appear that 13.6 updates this release and therefore the limitations should still be in place.

```
Known open issues with Loggregator Agent 6.0.2
If you're impacted by any of the following issues, please skip this version:

Syslog TLS drains incorrectly setting limited ciphers. (Issue #34)
Syslog drains added new tags to log messages that were not there before. (Issue #35)
```

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

13.6.0

**Comment by davewalter** [comment]
Thanks for bringing this to our attention. We have updated the [release notes for v13.6.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.6.0) to include the known issue for loggregator-agent v6.0.2.

Dave and @ericpromislow
