### ISSUE TITLE
skip one or more cf-deployment minor releases

### ISSUE THREAD

**Issue by markusporsch** [cloudfoundry/cf-deployment#902]
### What is this issue about?

Is there a way to skip one or more cf-deployment minor releases? For example can i upgrade from version 13.10.0 directly to version 13.15.0 ? We have a large cloud installation and every roleout needs a bunch of time.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v13.15.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

`bosh -e prod`
`  -d cf deploy cf-deployment/cf-deployment.yml`
`  -o cf-deployment/operations/use-compiled-releases.yml`
`  -o custom_opsfiles/cf/scale.yml`
`  -o custom_opsfiles/cf/gorouter-timeout.yml` 
`  -o custom_opsfiles/cf/networkpolicy-disable.yml`
`  -v system_domain=XXX.XX`
`  -o cf-deployment/operations/enable-nfs-volume-service.yml`
`  -o cf-deployment/operations/enable-smb-volume-service.yml` 
`  -o cf-deployment/operations/use-trusted-ca-cert-for-apps.yml` 
`  -o cf-deployment/operations/set-router-static-ips.yml`
`  -o cf-deployment/operations/enable-service-discovery.yml`
`  -o custom_opsfiles/cf/set-scheduler-static-ips.yml`
`  -o custom_opsfiles/cf/uaa-smtp.yml`
`  -o custom_opsfiles/cf/blobstore-cleanup-enable.yml`
`  -o custom_opsfiles/cf/resize-blobstore-disk.yml`
`  -o custom_opsfiles/cf/scale-database-cluster.yml` 
`  -o cf-deployment/operations/backup-and-restore/enable-backup-restore.yml`
`  -o custom_opsfiles/cf/memory-capacity.yml`
`  -v router_static_ips=[XX.XXX.XXX.XX,….]`
`  -v scheduler_static_ips=[XX.XXX.XXX.XX,….]`
`  -l trusted-certs.vars.yml`

### What IaaS is this issue occurring on?

VMware vSphere (6.7.0)

### Tag your pair, your PM, and/or team!
/cc @ukleeberger, @TimonB

**Comment by davewalter** [comment]
Hi @markusporsch,

Upgrading across multiple minor releases of cf-deployment should be possible. You should be able to simply check out the `v13.15.0` tag of cf-deployment and run your normal `bosh deploy` command.

Although this will increase the size of each upgrade (and therefore the time the upgrade takes), we try to do a good job of cutting releases fairly frequently to mitigate this. Looking at the [changeset](https://github.com/cloudfoundry/cf-deployment/compare/v13.10.0...v13.15.0) between those two releases, I don't see anything that gives me cause for concern, but that obviously depends on the ops-files you are using in your deployment.

Hope this helps,
Dave

**Comment by markusporsch** [comment]
Hi @davewalter, 

Thanks for answering our issue. That helps us a lot.

Regards, 
Markus
