### ISSUE TITLE
cf logs showing no output after upgrade to v 12.24

### ISSUE THREAD

**Issue by 1kaushik1** [cloudfoundry/cf-deployment#905]
### What is this issue about?

we recently upgraded our CF platform from v7 to v12.24. The deployment was successful, however we are not able to access cf logs, the command returns no output(same for --recent,tailing and staging. Can see this error message for the loggregator agent in the machines

`2020/09/09 12:04:26.121646 failed to connect: unable to lookup a log consumer
2020/09/09 12:04:26.121660 failed to connect: unable to lookup a log consumer`

Since all the machines and processes are in running state, we are not able to isolate the problem.
Tried doppler, log-api process restart and vm recreation. Connectivity to the doppler ips and ports (8082) is also working. Service discovery for doppler is also working fine. attached screenshots for reference.
 
![2020-09-11 14_00_49-Window](https://user-images.githubusercontent.com/25524420/92893715-8f227480-f437-11ea-8751-a46f1fbf60c0.png)

![image](https://user-images.githubusercontent.com/25524420/92894408-2e476c00-f438-11ea-9d39-4eb50c1c4f3c.png)

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v12.24

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

`bosh -e bosh -d cf deploy cf-deployment/cf-deployment.yml  -o cf-deployment/operations/use-external-blobstore.yml  -o cf-deployment/operations/backup-and-restore/enable-backup-restore.yml -o <own-ops file>/enable-component-syslog.yml -l some-environment-var-file.yml`

### Please provide output that helps describe the issue:

 cf logs spring-music --recent
Retrieving logs for app spring-music in org test / space test as admin...

root@acf-jumpbox:

### What IaaS is this issue occurring on?

Azure stack

### Is there anything else unique or special about your setup?

Setup is deployed on Azure stack

**Comment by heycait** [comment]
What version of the CF CLI are you using?

**Comment by lordcf** [comment]
@heycait , im using cf cli v - 6.52
output of cf -v :- 
cf version 6.52.0+b086fe522.2020-08-26

**Comment by 1kaushik1** [comment]
Hi @heycait , we are using cf cli version - 6.52
output of cf -v :-  cf version 6.52.0+b086fe522.2020-08-26

**Comment by heycait** [comment]
Can you see a logging endpoint in `cf curl /v2/info`?

See: https://apidocs.cloudfoundry.org/268/info/get_info.html

**Comment by 1kaushik1** [comment]
Yes, i do see a logging output 

   "doppler_logging_endpoint": "wss://doppler.sys.acf.paas.mdsp-infra.acc.mspas.atos.net:443",
   "api_version": "2.144.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.sys.acf.paas.mdsp-infra.acc.mspas.atos.net/routing", 

Also i tried cf logs --recent -v and i got the following output (the last request and response)

REQUEST: [2020-09-15T11:18:27Z]
GET /api/v1/read/3b937e98-3afa-41dd-95ac-ddd0b34f2017?descending=true&envelope_types=LOG&limit=1000&start_time=-6795364578871345152 HTTP/1.1
Host: log-cache.sys.acf.paas.mdsp-infra.acc.mspas.atos.net
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.52.0+b086fe522.2020-08-26 (go1.13.8; amd64 linux)


RESPONSE: [2020-09-15T11:18:27Z]
HTTP/1.1 200 OK
X-Vcap-Request-Id: 8a0f0599-6e49-4dc3-642c-ee56cf56818c
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1;mode=block
Content-Length: 27
Content-Type: application/json
Date: Tue, 15 Sep 2020 11:18:27 GMT
Grpc-Metadata-Content-Type: application/grpc

I dont see an error response on any of the requests. I believe the log-cache is not having any logs and the same is being returned.
Also for all the loggregator-agents in all machines, i can see the error message unable to lookup a log consumer 2020/09/09 12:04:26.121660 failed to connect: unable to lookup a log consumer. 
this is  there for all the loggregator agents i checked. So could it be that the agent is not able to forward logs ?

**Comment by 1kaushik1** [comment]
update :- On checking the system metrics, i could see 100% CPU utilization on the doppler VMs.  But this  is only on the doppler vms and not log-api machine. Could this be related to https://github.com/cloudfoundry/loggregator-release/issues/401

im planning to upgrade the bosh-dns release to 1.16 and see if that is changing anything.

**Comment by 1kaushik1** [comment]
Hi @heycait , After upgrading the bosh-dns version to 1.17.0, the doppler CPU usage subsided (earlier it was 100%) and after that we were able to see the application logs. So now the issue seems resolved.
thank you for your help :)

**Comment by jamespollard8** [comment]
Great - glad to hear that!
