### ISSUE TITLE
Update routers in serial

### ISSUE THREAD

**Issue by shashwathi** [cloudfoundry/cf-deployment#91]
Hi, 

**Issue** : Currently cf-deployment rolls are routers in parallel and it causes downtime for backends. 

**Possible fix**: To fix this issue we need to update routers in serial and roll this vm after UAA(to fetch oauth tokens for routing API). 

Routing team has CI coverage for zero downtime tests and these are intermittently failing since we moved to cf-deployment and it would be great if your team can roll out the fix.

Related PR : https://github.com/cloudfoundry/cf-deployment/pull/87

Regards
Shash

**Comment by dsabeti** [comment]
Hey @shashwathi. It sounds like we worked this out. One thing we could still use are the zero-downtime tests -- it would be great to run them in our pipeline as well.

**Comment by shashwathi** [comment]
@dsabeti : 

I am not sure whether that change worked out. We reduced the health check interval and drain period on GCP LB but we are still seeing failures on out Zero downtime tests. We have a story to investigate these failures and will update you when we find something.

>it would be great to run them in our pipeline as well

Sure. That would be great. Do you want to XTP to set this up in your pipeline ?

**Comment by dsabeti** [comment]
@shashwathi Yeah, let's plan on XTP some time soon, but feel free to update this issue with anything else that you find.

**Comment by dsabeti** [comment]
Hey @shashwathi, I realized that we never followed up on this. We've since added the changes to deploy the router in serial. Are your uptime tests passing? If so, could you point me to the tests? Eventually, we'll want to run these tests in the cf-deployment pipeline.

**Comment by shashwathi** [comment]
@dsabeti 
Thank you for following up. 

>  We've since added the changes to deploy the router in serial. Are your uptime tests passing? 

Yes, our tests are passing. Thank you for the change.

>Eventually, we'll want to run these tests in the cf-deployment pipeline.

We have zero downtime test coverage for both TCP and HTTP router (gorouter). It looks like release integration team has read access to routing team's deployments repository. So attaching the links for zero downtime tests

- https://github.com/cloudfoundry/deployments-routing/blob/master/routing-ci/deployments/routing-pipeline.yml#L278
 
Let us know if you have any trouble integrating this to your pipeline. 

Regards
Shash

**Comment by dsabeti** [comment]
Thanks @shashwathi. I just took note of those tests in our placeholder story, so we'll take a look when we get to it.
