### ISSUE TITLE
UAA update not automatically done

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/cf-deployment#913]
### What is this issue about?

Most recent cf-deployment version does not contain a recent UAA version
https://github.com/cloudfoundry/cf-deployment/blame/master/cf-deployment.yml#L2632-L2634

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

lastet

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

na

### Please provide output that helps describe the issue:

na

### What IaaS is this issue occurring on?

all

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by strehle** [comment]
@shamus FYI

**Comment by davewalter** [comment]
Hi @strehle,

Since we recently released v14.0.0 of cf-deployment that includes UAA 74.27.0. I am going to close this issue out.

Thanks for reminding us to release more often.
Dave
