### ISSUE TITLE
Remove old references to "ubuntu-trusty"

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/cf-deployment#918]
### What is this issue about?

Still some old references to "trusty" when all should be on Xenial (and soon to be bionic)

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v15.5.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

N/A

### Please provide output that helps describe the issue:

You can see a couple of references to ubuntu-trusty below ...

https://github.com/cloudfoundry/cf-deployment/blob/main/cf-deployment.yml#L58
and
https://github.com/cloudfoundry/cf-deployment/blob/main/cf-deployment.yml#L116

### What IaaS is this issue occurring on?

All

### Is there anything else unique or special about your setup?

No

**Comment by jspawar** [comment]
Good catch, thanks. Changes to remove those references have been made
