### ISSUE TITLE
Deploy cf with bosh on openstack-Rocky,Error : Action Failed get_task: Task xxx result: Updating certificates with retries

### ISSUE THREAD

**Issue by m714990877** [cloudfoundry/cf-deployment#919]
I can create five agent, but I can't seem to connect agent,Please see a few pictures below.
![捕获3](https://user-images.githubusercontent.com/45618423/105653287-625a8f80-5ef6-11eb-9dac-fdc995cdc440.JPG)

![捕获2](https://user-images.githubusercontent.com/45618423/105653961-fa0cad80-5ef7-11eb-9c24-172a3d824723.JPG)

![捕获1](https://user-images.githubusercontent.com/45618423/105654156-5f609e80-5ef8-11eb-9971-44144f36de01.JPG)

List of commands I executed：

bosh create-env bosh-deployment/bosh.yml \
    --state=bosh-state.json \
    --vars-store=director-creds.yml \
    --vars-file=vars.yml \
    -o bosh-deployment/openstack/cpi.yml \
    --var-file=private_key=bosh.pem

bosh interpolate bosh-deployment/bosh.yml \
    --vars-store=director-creds.yml \
    --vars-file=vars.yml \
    -o bosh-deployment/openstack/cpi.yml \
    --var-file=private_key=bosh.pem | tee bosh.yml

bosh -e bosh-1 update-cloud-config /root/bosh-1/cf-deployment/iaas-support/openstack/cloud-config.yml

bosh -e bosh-1 -d cf deploy cf-deployment/cf-deployment.yml \
      -o cf-deployment/operations/scale-to-one-az.yml \
      -o cf-deployment/operations/use-compiled-releases.yml \
      -o cf-deployment/operations/openstack.yml \
      -v system_domain="sys.cfop.cloud.dhc.com.cn" \
      --vars-store=/root/bosh-1/cf-deployment/creds.yml

**Comment by m714990877** [comment]
I can ssh/ping this agent

**Comment by jamespollard8** [comment]
Hey @m714990877 , thanks for opening an issue.

We don't maintain the openstack CPI so we'd recommend you head to [#openstack](https://cloudfoundry.slack.com/archives/C0SBBBJSZ) on the open-source CloudFoundry slack, and follow the instructions in the channel description to tag the relevant folks.

Because we don't work directly on the openstack CPI, I'm going to close out this issue.

Best,
James
