### ISSUE TITLE
Bump to GA bionic stemcell

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/cf-deployment#924]
### What is this issue about?

The bionic stemcell is now GA. We would like to use it by default in cf-deployment.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

N/A

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

N/A

### Please provide output that helps describe the issue:

N/A

### What IaaS is this issue occurring on?

N/A

### Is there anything else unique or special about your setup?

N/A

### Tag your pair, your PM, and/or team!
@acosta11 @paulcwarren

**Comment by ravi4mendix** [comment]
Hi @davewalter , do you have any update when this will be merged and made available in CF?

**Comment by angelachin** [comment]
Hi

Making and merging a PR for this is blocked on ensuring we have testing for cf-deployment in the community concourse. The existing RelInt concourse is planned to be converted to a private LTS xenial testing pipeline this month, which is why we cannot rely on it.

The current plan is to move pipelines for cf-deployment to the community concourse once it is ready. We plan to partner with the engineers working on that concourse to assist in the migration. Here's a link to the [Github project that is tracking the bionic stemcell work](https://github.com/orgs/cloudfoundry/projects/4).

In the meantime, you can use the opsfile to try out Bionic support in cf-deployment!

Cheers,
@angelachin

**Comment by mephmanx** [comment]
Any update on this?  Would like to use at least bionic, if not focal..

**Comment by slcardinal** [comment]
> Any update on this? Would like to use at least bionic, if not focal..

My team is also very interested in the status of this issue. Looking for any news that will help us make plans to keep our Cloud Foundry environment up to date and secure.

**Comment by mymasse** [comment]
Also highly interested in this for keeping our CF up to date and secure however somebody will need to push for this PR to be merged in nfs-volume-release: https://github.com/cloudfoundry/nfs-volume-release/pull/64

Otherwise we can't upgrade our fondations to bionic

**Comment by ramonskie** [comment]
it seems that there is currently a discussion going on about who is responsible for this repo
since the foundation is now making working groups to keep these repos supported and allive
see https://github.com/cloudfoundry/community/pull/139

**Comment by jochenehret** [comment]
This repo is now part of the new [App Runtime Deployments Working Group](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-deployments.md). We are planning to create a new cf-deployment release based on the "Bionic" stemcell. Backlog and timeline are just being created.

**Comment by davewalter** [comment]
I ran the [CI job](https://release-integration.ci.cf-app.com/teams/main/pipelines/update-releases/jobs/update-stemcell-and-recompile-releases/builds/226) to bump the stemcell to Bionic, which means that the default stemcell on the `develop` branch has been updated.

However, CI has highlighted a couple of issues that need to be addressed before this change can be merged to `release-candidate` and a new release created:

* The latest Bionic stemcell (1.67) has a [known issue with the Warden CPI](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1647538532157779?thread_ts=1647464686.494709&cid=C02HPPYQ2) that will hopefully be fixed in the next version.
* The latest version of [nfs-volume-release](https://github.com/cloudfoundry/nfs-volume-release) does not support Bionic stemcells. The required changes have been made on the `master` branch, so we are just waiting for a new release to be created.

I am considering reverting the bump to Bionic until both of these blockers are resolved as it is currently preventing the flow of other changes through CI.

**Comment by ramonskie** [comment]
@davewalter 
just wanted to let you know that the warden cpi issues has been fixed in 1.71

**Comment by davewalter** [comment]
The new stemcell is now available. Unfortunately, I would have to revert a lot of commits to undo the current bump so I am just going to let the new stemcell flow in to see what that fixes.

**Comment by hammondrm** [comment]
It looks like the current release of smb-volume is also not supported on Bionic. There is a [support issue](https://github.com/cloudfoundry/smb-volume-release/issues/16) for this.

**Comment by davewalter** [comment]
Thanks for the heads up. At this point, I think these are the only known blockers for getting a new release cut.

**Comment by davewalter** [comment]
All issues have been resolved. [v20.0.0](https://github.com/cloudfoundry/cf-deployment/releases/v20.0.0) includes the bump to use Bionic stemcells by default.
