### ISSUE TITLE
TLS-only NATS

### ISSUE THREAD

**Issue by 46bit** [cloudfoundry/cf-deployment#929]
### What is this issue about?

`cf-deployment` deploys a NATS cluster that is available over both plaintext and TLS. This was necessary because not all components supported TLS NATS.

Having a NATS cluster that supports both plaintext and TLS is complicated. NATS is only available on one at a time, so each NATS node is running two separate NATS agents (one for plaintext, one for TLS.) The cluster config has also been quite fragile (@ameowlia knows more about this.)

### What change do you propose?

We want `cf-deployment` to default to deploying TLS-only NATS. This would simplify the cluster, and remove one of the remaining non-TLS components (furthering #906.)

We'd provide an optional opsfile so that users can choose to run plaintext-only NATS. Users with custom components that don't yet support TLS NATS could still use plaintext NATS.

We will also finish upgrading mainstream open-source components to support TLS NATS (e.g. `service-discovery-controller` and `metric-discovery-registrar`.)

### How seriously is this work taken?

SAP want to get this done. For instance we've already [switched Gorouter to use TLS NATS](https://github.com/cloudfoundry/cf-deployment/pull/925).

**Comment by ameowlia** [comment]
Hi @46bit, 

🎉  I am so happy that you are taking on this work! Not only will this make our internal system more secure, but it will also cut the number of nodes in the NATS cluster in half, which will provide more stability.

Here is the list of NATS clients (that I know of):


| bosh job | able to be configured to use TLS | Details |
|--|--|--|
| [gorouter](https://github.com/cloudfoundry/routing-release/blob/3fcb85399df133f04b90890a29490b8e36b6dd23/jobs/gorouter/spec#L319-L321) | ✅  | subscribes for route registration messages |
| [route registrar](https://github.com/cloudfoundry/routing-release/blob/3fcb85399df133f04b90890a29490b8e36b6dd23/jobs/route_registrar/spec#L49-L51) | ✅  | publishes component routes for gorouter to consume |
| [route emitter](https://github.com/cloudfoundry/diego-release/blob/f359be839070779388f3626d7a0892630216ae43/jobs/route_emitter/spec#L59-L61) | ✅  | publishes app routes for gorouter to consume |
| [route emitter windows](https://github.com/cloudfoundry/diego-release/blob/f359be839070779388f3626d7a0892630216ae43/jobs/route_emitter_windows/spec#L49-L51) | ✅  | publishes app routes on windows cells for gorouter to consume |
| [loggr-system-metric-scraper](https://github.com/cloudfoundry/system-metrics-scraper-release/blob/521a1bb02a65f5ec3a0436d9a462325006a946a6/jobs/loggr-system-metric-scraper/spec) | 🚫  | It publishes messages about metric targets |
| [service discovery controller](https://github.com/cloudfoundry/cf-networking-release/blob/develop/jobs/service-discovery-controller/spec) | 🚫  | subscribes to internal route messages from route emitter |
| [metrics discovery registrar](https://github.com/cloudfoundry/metrics-discovery-release/blob/main/jobs/metrics-discovery-registrar/spec) | 🚫  | It publishes messages about metric targets |
| [scrape config generator](https://github.com/cloudfoundry/metrics-discovery-release/blob/01beb6f2481f6493d566c85c2dfbecd42a2292cf/jobs/scrape-config-generator/spec) | 🚫   | subscribes to information about metric targets |

I've circulated this issue internally and no one (outside of my team) has jumped out saying that they maintain something that uses NATS, so _hopefully_ this is a complete list.

**Comment by 46bit** [comment]
@ameowlia Thanks for the list! Here's some first impressions.

I'm working on giving TLS NATS support to `service-discovery-controller`.

`loggr-system-metric-scraper` isn't shipped in default `cf-deployment`. It wasn't used by GOV.UK PaaS and isn't used by SAP BTP. I wonder if we can make using it conditional on plaintext NATS?

`metrics-discovery-registrar` seems to support TLS NATS since https://github.com/cloudfoundry/metrics-discovery-release/commit/e8636c218e05c4bc43e8837a899355eb55a3293e.

`scrape-config-generator` seems to support TLS NATS since https://github.com/cloudfoundry/metrics-discovery-release/commit/af2bfcabfc308d6477fad9032c9a3f728a2c94d0.

**Comment by 46bit** [comment]
@ameowlia Good news! Both `metrics-discovery-registrar` and `scrape-config-generator` seem to already be using mTLS for NATS in `cf-deployment`.

I've checked `metrics-discovery-registrar` in a running environment. Oddly I can't find `scrape-config-generator` used anywhere but I'm fairly sure its config would make it use TLS NATS as well.

**Comment by 46bit** [comment]
I had hoped we'd ship TLS NATS by default, but provide an opsfile to revert to plaintext NATS if anyone needed to. Unfortunately that is not possible.

`metrics-discovery-registrar` and `scrape-config-generator` are both hardcoded to want TLS NATS. For instance see how https://github.com/cloudfoundry/metrics-discovery-release/blob/7964ba900fe89f301d67f398a7ed4a46f5c33572/src/cmd/discovery-registrar/main.go#L42-L84 will crash if it doesn't have mTLS details for NATS.

**Comment by ameowlia** [comment]
Thanks for the update @46bit !

> metrics-discovery-registrar seems to support TLS NATS since cloudfoundry/metrics-discovery-release@e8636c2.
scrape-config-generator seems to support TLS NATS since cloudfoundry/metrics-discovery-release@af2bfca.

🤦‍♀️  - yup, you are right. I was looking only for the "tls.enabled" property, but these don't have it because they ALWAYS use TLS. I fixed my table to reflect this.

> loggr-system-metric-scraper isn't shipped in default cf-deployment. It wasn't used by GOV.UK PaaS and isn't used by SAP BTP.

I will try to get some background info on this to see where it is used.

> I'm working on giving TLS NATS support to service-discovery-controller.
🎉  Yay! This work is closer to being done then I thought.

**Comment by 46bit** [comment]
@ameowlia I've discovered that `loggr-system-metric-scraper` already uses TLS NATS: https://github.com/cloudfoundry/system-metrics-scraper-release/commit/0c0dfacb2901fca4cc8c2948d33ebb8b2d9c37d8. Could you double-check? 😄

**Comment by davewalter** [comment]
@ameowlia @46bit I just cut [v17.0.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v17.0.0) that removes the plaintext NATs job so I think we can close this issue?

**Comment by 46bit** [comment]
@davewalter agreed! thanks to you, @ameowlia et al for getting this shipped :)
