### ISSUE TITLE
Some internal routes are temporarily (5 to 10 minutes) unavailable when bosh deploy is running

### ISSUE THREAD

**Issue by TimonB** [cloudfoundry/cf-deployment#945]
### What is this issue about?

When we run bosh deploy some internal routes (seems that not all routes are affected) become unavailable for 5 to 10 minutes. 
In this time the java applications are complaining about “…with root cause java.net.UnknownHostException: someapp.apps.internal“
The affected apps are scaled to more than one instance (so one instance should always be available). We have not noticed any problems with the public routes in this time.

This occurred the first time when we switched from v16.24.0 to v16.25.0 (currently we are running v17.0.0) but the problem also occurs when we run “bosh deploy” with some config changes.

In our Grafana we can see that the “Rate Register Messages Received per second” drops when the problem occurs:

<img width="799" alt="cf" src="https://user-images.githubusercontent.com/11681839/144206853-e927fba6-6ec2-4a8d-8e5e-e14d1effde7d.png">

Do you have any idea which components can cause the problems?
Do you need some logfiles?

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

cf-deployment v17.0.0

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):
```

bosh -e production \
   -d cf deploy cf-deployment/cf-deployment.yml \
   -o cf-deployment/operations/use-compiled-releases.yml \
   -o custom_opsfiles/cf/scale-to-our-needs.yml \
   -o custom_opsfiles/cf/gorouter-timeout.yml \
   -o custom_opsfiles/cf/networkpolicy-disable.yml \
   -v system_domain=mycompany.com \
   -o cf-deployment/operations/enable-nfs-volume-service.yml \
   -o cf-deployment/operations/enable-smb-volume-service.yml \
   -o cf-deployment/operations/use-trusted-ca-cert-for-apps.yml \
   -o cf-deployment/operations/set-router-static-ips.yml \
   -o cf-deployment/operations/enable-service-discovery.yml \
   -o custom_opsfiles/cf/set-scheduler-static-ips.yml \
   -o custom_opsfiles/cf/uaa-smtp.yml \
   -o custom_opsfiles/cf/blobstore-cleanup-enable.yml \
   -o custom_opsfiles/cf/use-external-blobstore.yml \
   -o custom_opsfiles/cf/use-s3-blobstore.yml \
   -o custom_opsfiles/cf/scale-database-cluster.yml \
   -o cf-deployment/operations/backup-and-restore/enable-backup-restore.yml \
   -o custom_opsfiles/cf/memory-capacity.yml \
   -v router_static_ips=[10.176.213.50,10.176.213.51,10.176.213.52,10.176.213.53,10.176.213.54,10.176.213.55,10.176.213.56,10.176.213.57] \
   -v scheduler_static_ips=[10.176.213.65,10.176.213.66] \
   -v app_package_directory_key=cf-packages-prod \
   -v resource_directory_key=cf-resources-prod \
   -v buildpack_directory_key=cf-buildpacks-prod \
   -v droplet_directory_key=cf-droplets-prod \
   -l trusted-certs.vars.yml
```

### What IaaS is this issue occurring on?

VMWare vSphere

**Comment by markusporsch** [comment]
Hi Jochen, thank you for your answer. We have 8 api, 6 cc-worker, 2 diego-api, 2 nats, 8 router, and 2 scheduler instances.

**Comment by ctlong** [comment]
@TimonB @markusporsch is this still a problem that you all are facing in more recent versions of cf-deployment?

**Comment by markusporsch** [comment]
@ctlong the problem only occurred with version v17.0.0 and hasn't recurred since.

**Comment by ctlong** [comment]
I'm going to close this issue then. Please feel free to open it up again if required :).
