### ISSUE TITLE
not able to push app to cloud foundry

### ISSUE THREAD

**Issue by sidnepal2048** [cloudfoundry/cf-deployment#947]
![cloudfoundry](https://user-images.githubusercontent.com/28677723/146841062-2f75f248-b88d-449b-92a0-ae71ace4845a.PNG)

This app was deployed successfully with java 17 but getting error with java 15. Can someone let me know what I missed here?

**Comment by davewalter** [comment]
Closing as a duplicate of https://github.com/cloudfoundry/java-buildpack/issues/925
