### ISSUE TITLE
cf upgrade issue : Property 'nats.user' expects a hash, but received 'String'

### ISSUE THREAD

**Issue by riddhichheda** [cloudfoundry/cf-deployment#948]
cf upgrade

I am trying to upgrade the CF from v12.24.0 to v15.7.0. While doing so I am getting error related to nats. 
I have a separate pxc deployment which is currently at v0.22.0

 bosh -e staging -d staging-cf deploy cf-deployment/cf-deployment.yml -o cf-deployment/operations/aws.yml -o custom-ops/modify-network-and-ip.yml -o cf-deployment/operations/override-app-domains.yml -o cf-deployment/operations/set-bbs-active-key.yml -o cf-deployment/operations/community/change-metron-agent-deployment.yml -o custom-ops/modify-dns-aliases.yml -o cf-deployment/operations/use-external-dbs.yml  -o cf-deployment/operations/use-external-blobstore.yml -o cf-deployment/operations/use-s3-blobstore.yml  -o custom-ops/modify-azs.yml -o custom-ops/add-vcap-password.yml -o custom-ops/add-org-quota-defination.yml -o custom-ops/add-password-policy.yml -o custom-ops/remove-tcp-router.yml -o custom-ops/add-fog-connections.yml -o custom-ops/add-additional-routers.yml -o custom-ops/add-cf-exporter.yml -o cf-deployment/operations/community/change-metron-agent-deployment.yml -o staging/env-ops/add-QA-routers.yml -o staging/env-ops/scale-to-one-az.yml -o custom-ops/add-custom-buildpack.yml -o custom-ops/modify-manifest.yml -o custom-ops/modify-variables-valid-duration.yml -o custom-ops/add-vts-support-certs.yml -o custom-ops/add-additional-memory.yml -o custom-ops/remove-router-backends.yml -o staging/env-ops/disable-routing-api.yml -o staging/env-ops/modify-default-and-mtls-router.yml -l staging/staging_env.yml

" L Error: Property 'nats.user' expects a hash, but received 'String'"
![image](https://user-images.githubusercontent.com/48857408/146989141-2ceff783-d6c2-4911-b9bb-1f8c6e9d1354.png)

AWS is the IaaS used.

Can you please let me know why I am facing this issue and how can I resolve it?
Do I have to jump to some other versions before going forward to upgrade it to the latest release of v17.1.0?

Thank you.

**Comment by davewalter** [comment]
Hi @riddhichheda,

Have you tried running `bosh interpolate` to help identify where the problem is? One change related to NATS that was made in [v13.5.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.5.0) was to add a `nats-tls` job to the nats instance group. If you have an ops-file that is modifying the NATS configuration, this might be causing you problems.

Hope this helps,
Dave

**Comment by riddhichheda** [comment]
Hi Dave, Thanks for the response.
I interpolated the manifest before deploying and no issues were there with that. Also I am not using any ops file for changing NATS configuration. Can this be because of bosh-dns? or bosh itself? The bosh version which I have is 270.5.0 and the bosh-dns version is 1.12.0. But other deployments which I have on the bosh had no issues in upgrading related to nats.

**Comment by metron2** [comment]
This error means you have a string value for something that should be a map

**Comment by ctlong** [comment]
Hi @riddhichheda, is this still an issue?
