### ISSUE TITLE
Too much stuff in bosh-lite ops file?

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/cf-deployment#96]
I'm trying to deploy Spark (modifying [this example](https://github.com/kubernetes/kubernetes/tree/master/examples/spark)) on CF, and think I'll need to leverage container-to-container networking.  The simplest way for me to do this is to deploy CF on BOSH-Lite and leverage [this `cf-networking-release` ops file](https://github.com/cloudfoundry-incubator/cf-networking-release/blob/develop/manifest-generation/opsfiles/cf-networking.yml).  That ops file assumes there's a MySQL database, but the bosh-lite ops file in this repo replaces MySQL with Postgres.

Is the bosh-lite ops file doing too much?  I understand wanting to give bosh-lite users a simple experience, but it seems like swapping out MySQL for Postgres should be its own thing, and asking bosh-lite users to compose a small handful of building blocks isn't that bad (and is encouraged).

/cc @cloudfoundry/cf-container-networking @cppforlife @wendorf @drich10

**Comment by mcwumbly** [comment]
There's an [(unreviewed) PR for cf-networking](https://github.com/cloudfoundry-incubator/cf-networking-release/pull/5) that includes a bosh-lite ops-file, which also swaps out MySQL for Postgres.

A quick look indicates that may be one of the only differences between that and our standard opsfile (though I haven't looked too closely at it yet).

So, yeah, at first glance, I think separating those two concerns might make things easier to compose and more clear where the differences are.

**Comment by dsabeti** [comment]
@Amit-PivotalLabs, this isn't the first time we've come up against this issue. I was hoping to have more "workflow" ops files, but they become difficult to compose. I'm thinking of revamping a lot of these ops files to be very small, and instead have docs that explain the different workflows. 

For example, we might replace the bosh-lite ops files with three:
- "IaaS" changes necessary for bosh-lite
- Scale down to one instance of each instance_group
- replace mysql with postgres
And then in a doc, explain that deploying to bosh-lite requires `bosh deploy ... -o bosh-lite.yml -o scale-to-single-instance.yml -o use-postgres.yml`.

This wouldn't complete solve the problem, but at least users could opt out of the `use-postgres.yml` and use your ops file for adding cf-networking. We're still collecting information so we can try to solve this.

**Comment by Amit-PivotalLabs** [comment]
Sounds good @dsabeti, especially pulling out a separate `use-postgres.yml` would be really nice.

**Comment by ljfranklin** [comment]
+1 on using smaller ops files. At retro, several CAPI team members mentioned getting tripped up when trying to get a bosh-lite with mysql. We have a custom [bosh-lite-mysql.yml](https://github.com/cloudfoundry/capi-ci/blob/51fb01bd21bbb2134a8874095f96eac706963160/cf-deployment-operations/bosh-lite-mysql.yml) ops file, but it's not obvious whether this ops file should be used in place of or in addition to the main `bosh-lite.yml` file or whether the ordering of these ops files matters.

**Comment by cdutra** [comment]
The story has been accepted. Feel free to reopen the issue if it's still valid. Thanks
