### ISSUE TITLE
Update smoke tests to use cf CLI v8

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/cf-deployment#969]
### What is this issue about?

v8 is the latest stable cf CLI release and we should use it in smoke tests.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

N/A

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

N/A

### Please provide output that helps describe the issue:

N/A

### What IaaS is this issue occurring on?

N/A

### Is there anything else unique or special about your setup?

N/A

### Tag your pair, your PM, and/or team!

N/A

**Comment by davewalter** [comment]
This work has been done. See https://github.com/cloudfoundry/cf-smoke-tests-release/commit/adb3ff439f4727eb4697f8b113b0f6327f1abdaf and https://github.com/cloudfoundry/cf-deployment/commit/0d5713081ecfaba5f578680f160fd3fc19513be2.
