### ISSUE TITLE
Empty cf log and stats server temporarily unavailable with cf push.

### ISSUE THREAD

**Issue by soroshidg** [cloudfoundry/cf-deployment#971]
### What is this issue about?

While deploying any app it is throwing "Stats server temporarily unavailable." and cf app logs are not getting displayed. 

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v18.0.0]

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

bosh -d <cf-deployment-name> deploy manifest.yml

### Please provide output that helps describe the issue:

_It's helpful to include snippets of the error response or logs output_

```
cf a
Getting apps in org cloud-foundry / space demo as admin...

Stats server temporarily unavailable.
Stats server temporarily unavailable.
Stats server temporarily unavailable.

name                     requested state   processes           routes
cf-example-staticfile    started           web:1/1             cf-example-staticfile-cheerful-squirrel-pw.as-g6.cf.comcast.net
cf-sample-app-go         started           web:1/1             cf-sample-app-go.as-g6.cf.comcast.net
cf-sample-app-nodejs     started           web:1/1             cf-sample-app-nodejs.as-g6.cf.comcast.net
```
also, logs are not displaying - ```cf logs spring-music
Retrieving logs for app spring-music in org cloud-foundry / space demo as admin...
```


### What IaaS is this issue occurring on?

vsphere

### Is there anything else unique or special about your setup?

no. Same setup worked fine with cf-deployment v17.1.0

### Tag your pair, your PM, and/or team!

**Comment by ctlong** [comment]
The error "Stats server temporarily unavailable." seems to indicate that CAPI is not able to communicate correctly with Log Cache to retrieve app stats and app logs.

CF v18.0.0 split out [Log Cache from the Doppler VMs](https://github.com/cloudfoundry/cf-deployment/pull/949), which may require some special considerations when deploying.

Can you use the [Log Cache cf CLI plugin](https://github.com/cloudfoundry/log-cache-cli) to validate that your Log Cache is receiving traffic correctly? `cf log-meta` should include lines about any apps that are emitting logs, and `cf tail APP_NAME` should directly connect to Log Cache to stream logs for an app.

**Comment by soroshidg** [comment]
Thanks @ctlong  It seems this issue is because of the open CAPI release issue - https://github.com/cloudfoundry/capi-release/issues/224 which is still open.

**Comment by ctlong** [comment]
There was a workaround for that issue included in CF-D v18: [set `cc.logcache.host` to `log-cache.service.cf.internal`](https://github.com/cloudfoundry/cf-deployment/blob/v18.0.0/cf-deployment.yml#L964).

If you're overriding that property then I would suggest setting it back to `log-cache.service.cf.internal`.

**Comment by soroshidg** [comment]
With both v18 and v19 we did not override that and it's `log-cache.service.cf.internal` only for cc.logcache.host,  still no metrics and log and stats server errors during `cf p`  or `cf a`.

**Comment by ctlong** [comment]
> Can you use the [Log Cache cf CLI plugin](https://github.com/cloudfoundry/log-cache-cli) to validate that your Log Cache is receiving traffic correctly? `cf log-meta` should include lines about any apps that are emitting logs, and `cf tail APP_NAME` should directly connect to Log Cache to stream logs for an app.

❓ Is your Log Cache receiving traffic?

❓ In what ways does your manifest differ from the default `cf-deployment.yml` in CF-D v18/19?
