### ISSUE TITLE
Error: Instance group 'nats' must specify availability zone that matches availability zones of network 'default'

### ISSUE THREAD

**Issue by vrdosapati** [cloudfoundry/cf-deployment#973]
Getting Error: Instance group 'nats' must specify availability zone that matches availability zones of network 'default'
While cf deploying in aws using bosh 
Can some one help

**Comment by vrdosapati** [comment]
Here is the cloud config 


azs:
- name: z1
  cloud_properties: {availability_zone: us-east-1b}


vm_types:
- name: default
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk: {size: 3000, type: gp3}
- name: large
  cloud_properties:
    instance_type: m3.large
    ephemeral_disk: {size: 30000, type: gp3}

instance_groups:
- name: nats
  cloud_properties: {availability_zone: us-east-1b}
  instances: 2
  vm_type: default
  persistent_disk: 10_240
  resource_pool: medium_z1
  networks:
  - name: default

disk_types:
- name: default
  disk_size: 3000
  cloud_properties: {type: gp3}
- name: large
  disk_size: 50_000
  cloud_properties: {type: gp3}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.197.209.0/24
    gateway: 10.197.209.1
    az: z1
    static: [10.197.209.62]
    dns: [10.197.209.2]
    cloud_properties: {subnet: subnet-062c92d2534e342b0}
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: default

**Comment by jochenehret** [comment]
The "nats" instance group should specify an availability zone, see https://bosh.io/docs/manifest-v2/#instance-groups. I don't think that "cloud_properties" is required.

**Comment by ctlong** [comment]
@vrdosapati did that resolve your issue?
