### ISSUE TITLE
How and where can we add the proxy on the platform on Bosh and CF, so that the entire platform and the apps also can access internet

### ISSUE THREAD

**Issue by sirishareddiroutu** [cloudfoundry/cf-deployment#976]
Hi team,

Currently, we have a Cloud Foundry platform setup on VMWare vSphere that has no proxy setting enabled at the platform level but it can access the internet by another proxy setup like (Force point proxy) at the infrastructure level. We are now switching the proxy therefore we want to enable the platform to use the new proxy to get internet access. The new proxy requires authentication.

We have updated the env vars (cf set-running-environment-variable-group '{"http_proxy": "http://Userid:password@ipaddress:port", "https_proxy":"http://Userid:password@ipaddress:port" }'

cf set-staging-environment-variable-group '{"http_proxy": "http://Userid:password@ipaddress:port", "https_proxy":"http://Userid:password@ipaddress:port" }')

After adding the global variables, and pushing the app we do not see any traffic sourcing from Diego cell approaching to any buildpacks through this new proxy.

When we use these global env vars from which platform VM/component does the internet traffic initiates through this new proxy?
and the proxy requires authentication therefore we added a username and password.

Let us know if any other way is possible to add the authentication for proxy with this env vars.

Or if possible can we modify the bosh deployment of CF or the bosh itself to use the proxy for the platform? Where else do we have to set up the proxy for the platform so that it can use it on the bosh level? How the bosh deployed deployments of CF- all the VMs of CF and Diego can use the proxy?

How the entire platform and all its components at the CF level can access the internet through this new proxy?

**Comment by jimconner** [comment]
Setting the proxy env vars will only be helpful if the app code running in the containers supports using them. For java apps passing proxy settings with a `-Dhttp.proxyHost=` settings seems to be the norm. Python apps need to be passing a proxy setting to the requests library etc...  

The place I work was in the same situation before we changed over to a transparent proxy meaning that we don't have to do this anymore.

Not a solution, but hopefully that helps explain one of the possible reasons why your apps might not be talking out.

**Comment by sirishareddiroutu** [comment]
Hi Jim,

Thanks for the information.

Can you please let me know what has to be done for other types of applications like nodejs, go, dotnet, ruby, and apps having docker container images?
What type of proxy solution needs to be implemented for those apps?

**Comment by ctlong** [comment]
Closing as stale
