### ISSUE TITLE
21.7 Release notes should point out that v2 secgroups don't work any more.

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/cf-deployment#987]
### What is this issue about?

Hey, we have been testing CF-dep internally and found out that https://github.com/cloudfoundry/cf-networking-release/releases/tag/v3.10.0 contains a "breaking" change. When you use a cf cli <7 aka the v2 api to create or update a security group, the asg-syncer of CF_networking will ignore that (until another secgroup is changed via v3 api). Only when using the v3 api or cli v7+ it will propagate this group to apps.
If a rule was set with v2 it does not matter if you restart, restage or create a new app, the rule will be ignored. (until you create, bind or delete another sec group with cli v7). I think it would be a good idea to inform people that there could be impact.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v21.7.0]

### Please provide output that helps describe the issue:

From output side cf cli6 and 7 show the same groups (as we talk to the same cc here) but the policy server has a separate set that it syncs once a v3 api secgroup change is performed. 

### What IaaS is this issue occurring on?

aws

### Is there anything else unique or special about your setup?

Nothing really from the other 20 we have, its just our release testing so 2 cf-d versions ahead of the rest.

### Tag your pair, your PM, and/or team!
@benjaminguttmann-avtq

**Comment by ctlong** [comment]
I updated the [release notes](https://github.com/cloudfoundry/cf-deployment/releases/tag/v21.7.0) just now.
